common/force-app/main/default/objects/Image_Info__c/Image_Info__c.object-meta.xml
<CustomObject>
    <label>Image Info</label>
    <nameField>
        <displayFormat>IMG-{0000}</displayFormat>
        <label>Image Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Image infos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Image_Info__c/fields/Image_Public_URL__c.field-meta.xml
<CustomField>
    <fullName>Image_Public_URL__c</fullName>
    <label>Image Public URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Image_Info__c/fields/Image_Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Image_Unique_Name__c</fullName>
    <label>Image Unique Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

common/force-app/main/default/classes/ImageInfoControllerTest.cls
@isTest
public class ImageInfoControllerTest {
@isTest
    public static void testimaginfo(){
        List<Image_Info__c> infoList=new List<Image_Info__c>();
        Image_Info__c img1=new Image_Info__c(Image_Unique_Name__c='Test1',Image_Public_URL__C='https://google.com/myimage1');
         Image_Info__c img2=new Image_Info__c(Image_Unique_Name__c='Test2',Image_Public_URL__C='https://google.com/myimage2');
        infoList.add(img1);
         infoList.add(img2);
        insert  infoList;
        ImageInfoController infoctrl=new ImageInfoController();
       System.assert(infoctrl.imageNameURLMap.containsKey('Test1'));
    }
}