common/force-app/main/default/objects/Image_Info__c/Image_Info__c.object-meta.xml
<CustomObject>
    <label>Image Info</label>
    <nameField>
        <displayFormat>IMG-{0000}</displayFormat>
        <label>Image Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Image infos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Image_Info__c/fields/Image_Public_URL__c.field-meta.xml
<CustomField>
    <fullName>Image_Public_URL__c</fullName>
    <label>Image Public URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Image_Info__c/fields/Image_Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Image_Unique_Name__c</fullName>
    <label>Image Unique Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

common/force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <label>Investment</label>
    <nameField>
        <displayFormat>IN-{00000000}</displayFormat>
        <label>Investment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Investment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investments</relationshipLabel>
    <relationshipName>Investments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Current_Value__c.field-meta.xml
<CustomField>
    <fullName>Current_Value__c</fullName>
    <formula>&quot;$&quot;
+
IF(LEN(TEXT(MFLOOR(Opportunity_Product__r.ListPrice)))&gt;3,
    IF(LEN(TEXT(MFLOOR(Opportunity_Product__r.ListPrice)))&gt;6,
        LEFT(TEXT(MFLOOR(Opportunity_Product__r.ListPrice)),LEN(TEXT(MFLOOR(Opportunity_Product__r.ListPrice)))-6)+&quot;,&quot;+LEFT(RIGHT(TEXT(MFLOOR(Opportunity_Product__r.ListPrice)),6),3)+&quot;,&quot;+RIGHT(TEXT(MFLOOR(Opportunity_Product__r.ListPrice)),3),
        LEFT(TEXT(MFLOOR(Opportunity_Product__r.ListPrice)),LEN(TEXT(MFLOOR(Opportunity_Product__r.ListPrice)))-3)+&quot;,&quot;+RIGHT(TEXT(MFLOOR(Opportunity_Product__r.ListPrice)),3)),
TEXT(MFLOOR(Opportunity_Product__r.ListPrice)))
+
IF(MOD(Opportunity_Product__r.ListPrice , 1) = 0,&apos;.00&apos;,TEXT(MOD(Opportunity_Product__r.ListPrice , 1)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Value</label>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Is_Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Is_Person_Account__c</fullName>
    <formula>Account__r.IsPersonAccount</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Person Account</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Process_Fund_Disbursement__c.field-meta.xml
<CustomField>
    <fullName>Process_Fund_Disbursement__c</fullName>
    <defaultValue>false</defaultValue>
    <description>this field will be utilised when the partial/full fund is disbursed.</description>
    <inlineHelpText>checking the box will effect the portfolio summary on investor portal</inlineHelpText>
    <label>Process Fund Disbursement</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Investment_Stages</valueSetName>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/News_List_Page__c.object-meta.xml
<CustomObject>
    <label>News List Page</label>
    <nameField>
        <displayFormat>LP-{00000}</displayFormat>
        <label>ListPage Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>News List Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/News_List_Page__c/fields/CategoryBanner_Img_Url__c.field-meta.xml
<CustomField>
    <fullName>CategoryBanner_Img_Url__c</fullName>
    <description>Category Image Banner image URL</description>
    <label>CategoryBanner_Img_Url</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Likes_Number__c.field-meta.xml
<CustomField>
    <fullName>Likes_Number__c</fullName>
    <label>Likes Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Navigation_url__c.field-meta.xml
<CustomField>
    <fullName>Navigation_url__c</fullName>
    <label>Navigation url</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/News_Category__c.field-meta.xml
<CustomField>
    <fullName>News_Category__c</fullName>
    <label>News Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/News_Descriptions__c.field-meta.xml
<CustomField>
    <fullName>News_Descriptions__c</fullName>
    <label>News Descriptions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/News_Label__c.field-meta.xml
<CustomField>
    <fullName>News_Label__c</fullName>
    <label>News Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Newsbg_Url__c.field-meta.xml
<CustomField>
    <fullName>Newsbg_Url__c</fullName>
    <label>Newsbg Url</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Publish_On_Community_Site__c.field-meta.xml
<CustomField>
    <fullName>Publish_On_Community_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean flag to decide if this blog should be visible or not.</description>
    <inlineHelpText>Boolean flag to decide if this blog should be visible or not.</inlineHelpText>
    <label>Publish On Community Site</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/src_url__c.field-meta.xml
<CustomField>
    <fullName>src_url__c</fullName>
    <description>Source URL</description>
    <label>src url</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Tagged_category__c.field-meta.xml
<CustomField>
    <fullName>Tagged_category__c</fullName>
    <description>This is the URL for tagged category on the top corner</description>
    <inlineHelpText>This is the URL for tagged category on the top corner</inlineHelpText>
    <label>Tagged category</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/OpportunityLineItem/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Button_Text__c.field-meta.xml
<CustomField>
    <fullName>Button_Text__c</fullName>
    <label>Button Text</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Deal_Page_Link__c.field-meta.xml
<CustomField>
    <fullName>Deal_Page_Link__c</fullName>
    <label>Deal Page Link</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/FAQ_s__c.field-meta.xml
<CustomField>
    <fullName>FAQ_s__c</fullName>
    <label>FAQ&apos;s</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Fully_Funded__c.field-meta.xml
<CustomField>
    <fullName>Fully_Funded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fully Funded</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/IM_PDS__c.field-meta.xml
<CustomField>
    <fullName>IM_PDS__c</fullName>
    <description>Link to approved/Final document only</description>
    <label>IM/PDS</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Offer_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Offer_Close_Date__c</fullName>
    <inlineHelpText>The target date for capital raise to be complete</inlineHelpText>
    <label>Offer Close Date</label>
    <type>DateTime</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Offer_Launch_Date__c.field-meta.xml
<CustomField>
    <fullName>Offer_Launch_Date__c</fullName>
    <description>The date that Capital Raising launched the offer to market</description>
    <label>Offer Launch Date</label>
    <type>DateTime</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Private_Deal__c.field-meta.xml
<CustomField>
    <fullName>Private_Deal__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box for private deals that are not to be publicly published on the community site but are visible by invite to the URL.</inlineHelpText>
    <label>Private Deal</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Publish_on_Community_Site__c.field-meta.xml
<CustomField>
    <fullName>Publish_on_Community_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publish on Community Site</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Return_Type__c.field-meta.xml
<CustomField>
    <fullName>Return_Type__c</fullName>
    <label>Return Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Per Annum</fullName>
            </value>
            <value>
                <fullName>Fixed Return</fullName>
            </value>
            <value>
                <fullName>Variable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Sector_Personas__c.field-meta.xml
<CustomField>
    <fullName>Sector_Personas__c</fullName>
    <description>The personas that this product is suitable for</description>
    <label>Sector/Personas</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Just Launchers</fullName>
            </value>
            <value>
                <fullName>Sharp Shooters</fullName>
            </value>
            <value>
                <fullName>Prosperity Builders</fullName>
            </value>
            <value>
                <fullName>Grand Designers</fullName>
            </value>
            <value>
                <fullName>Wholesale/Sophisticated Investors</fullName>
            </value>
            <value>
                <fullName>Retail Investors</fullName>
            </value>
            <value>
                <fullName>Property Investors</fullName>
            </value>
            <value>
                <fullName>ARE Auckland Real Estate Management - property and Asset managers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ventures - Pre-Seed</fullName>
            </value>
            <value>
                <fullName>Ventures - Seed</fullName>
            </value>
            <value>
                <fullName>Ventures - Series A</fullName>
            </value>
            <value>
                <fullName>Ventures - Series B</fullName>
            </value>
            <value>
                <fullName>Ventures - Series C</fullName>
            </value>
            <value>
                <fullName>Ventures - Bridging Round</fullName>
            </value>
            <value>
                <fullName>Ventures - Pre-IPO</fullName>
            </value>
            <value>
                <fullName>Ventures - IPO</fullName>
            </value>
            <value>
                <fullName>Property - Equity</fullName>
            </value>
            <value>
                <fullName>Property - Preference Equity</fullName>
            </value>
            <value>
                <fullName>Property - Debt</fullName>
            </value>
            <value>
                <fullName>Fund - Multi Stage as per IM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Tile_Banner__c.field-meta.xml
<CustomField>
    <fullName>Tile_Banner__c</fullName>
    <label>Tile Banner</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Tile_Heading__c.field-meta.xml
<CustomField>
    <fullName>Tile_Heading__c</fullName>
    <label>Tile Heading</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Tile_Offer_Type__c.field-meta.xml
<CustomField>
    <fullName>Tile_Offer_Type__c</fullName>
    <label>Tile Offer Type</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Trust_Deed_Link__c.field-meta.xml
<CustomField>
    <fullName>Trust_Deed_Link__c</fullName>
    <label>Trust Deed Link</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VC Product</fullName>
            </value>
            <value>
                <fullName>Property Product</fullName>
            </value>
            <value>
                <fullName>CSF Product</fullName>
            </value>
            <value>
                <fullName>CSF Nominee</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>PSP Product</fullName>
            </value>
            <value>
                <fullName>Retail IPO</fullName>
            </value>
            <value>
                <fullName>Retail MIS</fullName>
            </value>
            <value>
                <fullName>Vest</fullName>
            </value>
            <value>
                <fullName>CIF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/globalValueSets/Investment_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Why Appt Set Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Decision Appt Set Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Closing Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Application Received</fullName>
    </customValue>
    <customValue>
        <fullName>Receipt Issued</fullName>
    </customValue>
    <customValue>
        <fullName>Closed Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Closed Won</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
        <isActive>false</isActive>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>Closing</fullName>
        <isActive>false</isActive>
        <label>Closing</label>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
        <isActive>false</isActive>
        <label>Active</label>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
        <isActive>false</isActive>
        <label>Pending</label>
    </customValue>
    <description>Stages of an Investment</description>
    <masterLabel>Investment Stages</masterLabel>
</GlobalValueSet>

common/force-app/main/default/classes/ProductControllerTest.cls
@isTest
public with sharing class ProductControllerTest {
    @TestSetup
    public static void creatData(){
         List<News_List_Page__c> nlps = new List<News_List_Page__c>();
        for(Integer i=0;i<10;i++){
		 News_List_Page__c nlp = new News_List_Page__c();
        
        nlp.News_Label__c = 'News Label Test '+i+1;
        nlp.Tagged_category__c = 'Tagged Catg1';
        nlp.Date__c = system.today();
        nlp.News_Category__c = 'News Catg1';
        nlp.News_Descriptions__c = 'test desc';
        nlp.Likes_Number__c = 0;
        nlp.Newsbg_Url__c = 'https://www.venturecrowd.com.au';
        nlp.src_url__c = 'https://www.venturecrowd.com.au';
        nlp.Navigation_url__c = 'https://www.venturecrowd.com.au'; 
        nlp.CategoryBanner_Img_Url__c = 'https://www.venturecrowd.com.au';
            
            nlps.add(nlp);
        }
        
        insert nlps;
        createtestproduct();
        createnewsBlogs();
       
    }
    @isTest
    public static void productTestMethod(){
        product2 prod = new product2();
        prod.Name = 'Test Prod';
        prod.IM_PDS__c = 'https://test.salesforce.com';
        prod.DisplayUrl = 'https://www.venturecrowd.com.au';
        prod.Deal_Page_Link__c = 'https://www.venturecrowd.com.au';
        prod.Trust_Deed_Link__c = 'https://www.venturecrowd.com.au';
        prod.Sector_Personas__c = 'Just Launchers';
        prod.ProductCode = 'AURT';
        prod.FAQ_s__c = 'Test FAQ';
        prod.Fully_Funded__c = true;
        prod.Return_Type__c = 'Per Annum';
        prod.Tile_Banner__c = 'https://www.venturecrowd.com.au';
        prod.Tile_Heading__c = 'Test heading';
        prod.Tile_Offer_Type__c = 'Investment';
        prod.Button_Text__c = 'View Offer';
        prod.IsActive = true;
        prod.Private_Deal__c = false;
        prod.Publish_on_Community_Site__c = TRUE;
        prod.Offer_Launch_Date__c = system.now();
        prod.Offer_Close_Date__c = system.now();
        
        Database.SaveResult prodINs = database.insert(prod,false);
        System.assertEquals(True, prodINs.isSuccess());

        ProductController pc = new ProductController();
        ProductController.getInvestProds();
        ProductController.getRelProds(new List<Id> {prod.Id});
    }

    @isTest
    public static void newsBlogTestMethod(){
        News_List_Page__c nlp = new News_List_Page__c();
        nlp.News_Label__c = 'News Label1';
        nlp.Tagged_category__c = 'Tagged Catg1';
        nlp.Date__c = system.today();
        nlp.News_Category__c = 'News Catg1';
        nlp.News_Descriptions__c = 'test desc';
        nlp.Likes_Number__c = 2;
        nlp.Newsbg_Url__c = 'https://www.venturecrowd.com.au';
        nlp.src_url__c = 'https://www.venturecrowd.com.au';
        nlp.Navigation_url__c = 'https://www.venturecrowd.com.au'; 
        Database.SaveResult newsINs = database.insert(nlp,false);
        System.assertEquals(True, newsINs.isSuccess());   

        ProductController pc = new ProductController();
    }
    @isTest
    public static void testnewslike(){
        List<News_List_Page__c> pages=[Select Id from News_List_Page__c where News_Label__c like 'News Label Test %'];
       ProductController pc = new ProductController();
        pc.currentblogrecId=pages[0].Id;
        pc.likeblog();
        News_List_Page__c currpage=[Select Id,Likes_Number__c from News_List_Page__c where Id=:pages[0].Id Limit 1];
        System.assertEquals(1, currpage.Likes_Number__c);
        
    }
    
   @isTest
    public static void testimaginfo(){
        List<Image_Info__c> infoList=new List<Image_Info__c>();
        Image_Info__c img1=new Image_Info__c(Image_Unique_Name__c='Test1',Image_Public_URL__C='https://google.com/myimage1');
         Image_Info__c img2=new Image_Info__c(Image_Unique_Name__c='Test2',Image_Public_URL__C='https://google.com/myimage2');
        infoList.add(img1);
         infoList.add(img2);
        insert  infoList;
        ProductController infoctrl=new ProductController();
       System.assert(infoctrl.imageNameURLMap.containsKey('Test1'));
    }
    
    @isTest
    public static void getProducttest(){
        ProductController.getProducts(false, 'Property Product');
        ProductController.getProducts(true, null);
    }
     @isTest
    public static void getNewsBlogtest(){
       List<News_List_Page__c> newsblogs= ProductController.getNewsBlogs();
		System.assert(newsblogs.size()>0);
    }
    
   @isTest
    public static void getNBForNewsConByCat(){
        News_List_Page__c nlp = new News_List_Page__c(Date__c=System.today(), News_Label__c='Test');
        nlp.News_Category__c = 'Test';
        
        insert nlp;
       List<News_List_Page__c> lstPC =  ProductController.getNewsBlogsForNewsContainerByCategory(10, 0, 'Test');
       ProductController.getNewsBlogsForNewsContainer( 2, 2);
       ProductController.getNewsBlogsByCategory('Test');
        System.assertEquals(1, lstPC.size());
        
    }
    public static void createtestproduct(){
         List<product2> productlist=new  List<product2>();
        for(Integer i=0;i<10;i++){
            product2 prod = new product2();
        prod.Name = 'Test Prod '+i+1;
        prod.IM_PDS__c = 'https://test.salesforce.com';
        prod.DisplayUrl = 'https://www.venturecrowd.com.au';
        prod.Deal_Page_Link__c = 'https://www.venturecrowd.com.au';
        prod.Trust_Deed_Link__c = 'https://www.venturecrowd.com.au';
        prod.Sector_Personas__c = 'Just Launchers';
        prod.ProductCode = 'AURT';
        prod.FAQ_s__c = 'Test FAQ';
        prod.Fully_Funded__c = true;
        prod.Return_Type__c = 'Per Annum';
        prod.Tile_Banner__c = 'https://www.venturecrowd.com.au';
        prod.Tile_Heading__c = 'Test heading';
        prod.Tile_Offer_Type__c = 'Investment';
        prod.Button_Text__c = 'View Offer';
        prod.IsActive = true;
        prod.Private_Deal__c = false;
        prod.Publish_on_Community_Site__c = TRUE;
        prod.Offer_Launch_Date__c = system.now();
        prod.Offer_Close_Date__c = system.now();
            productlist.add(prod);
        }
        
        insert productlist;
        ProductController.isRetailProd(productlist[0].Id);
    }
    public static void createnewsBlogs(){
        List<News_List_Page__c> newslist=new List<News_List_Page__c>();
        for(Integer i=0;i<10;i++){
            
             News_List_Page__c nlp = new News_List_Page__c();
        nlp.News_Label__c = 'News Label '+i+1;
        nlp.Tagged_category__c = 'Tagged Catg1';
        nlp.Date__c = system.today();
        nlp.News_Category__c = 'News Catg1';
        nlp.News_Descriptions__c = 'test desc';
        nlp.Likes_Number__c = 2;
        nlp.Newsbg_Url__c = 'https://www.venturecrowd.com.au';
        nlp.src_url__c = 'https://www.venturecrowd.com.au';
        nlp.Navigation_url__c = 'https://www.venturecrowd.com.au'; 
        newslist.add(nlp);
        }
        insert newslist;
    }
    @IsTest
    static void getInvestProds_Test(){    
        ProductController.investmentsRecords(' WHERE Stage__c = \'Closed Won\' AND Is_Person_Account__c = TRUE AND Process_Fund_Disbursement__c = FALSE','Current Investments - Personal');
        ProductController.investmentsRecords(' WHERE Stage__c = \'Closed Won\' AND Is_Person_Account__c = FALSE AND Process_Fund_Disbursement__c = FALSE ','Current Investments - Entities');
        ProductController.investmentsRecords('  WHERE (Stage__c = \'Application Received\'  OR Stage__c = \'Receipt Issued\' )AND Process_Fund_Disbursement__c = FALSE','Pending Investments');
        ProductController.investmentsRecords(' WHERE Stage__c = \'Closed Won\' AND Process_Fund_Disbursement__c = TRUE ','Previous Investments');
        InvestControllerTest.testCreateOpportunityMethod();
        Investment__c inv = [SELECT Id,Current_Value__c,Account__r.BPAY_CRN__c,Account__r.BPAY_Biller_Code__c,Investment_Product_Image_FORMULA__c,Opportunity_Product__r.Current_Investment_Value__c,Opportunity_Product__r.TotalPrice,Opportunity_Product__r.ListPrice,Opportunity_Product__r.Investment_Contribution_Fee__c,Opportunity_Product__r.Product2.Portal_Display_Name__c,Opportunity_Product__r.Product2.Portal_Short_Description__c,Opportunity_Product__r.Product2.Type__c,Opportunity_Product__r.Product2.Sector__c,Opportunity_Product__r.Product2.stage__c,Investment_Product_Type__c,Investment_Date__c,Investment_Amount__c,Investment_Opp_ID__c,Funds_Received__c,Purchased_Shares__c, Account__r.Name FROM Investment__c];
        new ProductController.invRecordWrapper(inv,'Current Investments - Personal');
        //new ProductController.invRecordWrapper(inv,'Pending Investments');
    }
    @IsTest
    static void getFiles_Test(){
        InvestControllerTest.testCreateOpportunityMethod();
        Investment__c invest = [SELECT Id FROM Investment__c LIMIT 1];
        //Create files
        ContentVersion testFile = new ContentVersion (
        Title = 'FY23 Tax Statement Amended',
		PathOnClient = 'FY23 Tax Statement Amended.txt',
        VersionData = Blob.valueOf('Test'),
        IsMajorVersion = true
          
        );
        insert testFile;
        testFile = [SELECT  ContentDocumentId FROM  ContentVersion WHERE Id = :testFile.Id];
        ContentDocumentLink testLink = new ContentDocumentLink(
        ContentDocumentId = testFile.ContentDocumentId,
        LinkedEntityId = invest.Id,
        ShareType = 'V'
        
        );
        insert testLink;
        ProductController.fetchFiles(invest.Id);

    }
}