common/force-app/main/default/objects/Interest_Dividend_Disbursement__c/Interest_Dividend_Disbursement__c.object-meta.xml
<CustomObject>
    <label>Interest Dividend Disbursement</label>
    <nameField>
        <displayFormat>IID-{00000}</displayFormat>
        <label>Interest Dividend Disbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest Dividend Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Interest_Dividend_Disbursement__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Interest Dividend Disbursements</relationshipLabel>
    <relationshipName>Interest_Dividend_Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Interest_Dividend_Transaction_Log__c/Interest_Dividend_Transaction_Log__c.object-meta.xml
<CustomObject>
    <label>Interest Dividend Transaction Log</label>
    <nameField>
        <displayFormat>IDTL-{0000}</displayFormat>
        <label>Interest Dividend Transaction Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest Dividend Transaction Log</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Interest_Dividend_Transaction_Log__c/fields/Days_included_in_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Days_included_in_Calculation__c</fullName>
    <label>Days included in Calculation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/Interest_Dividend_Transaction_Log__c/fields/Interest__c.field-meta.xml
<CustomField>
    <fullName>Interest__c</fullName>
    <label>Interest</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Interest_Dividend_Transaction_Log__c/fields/Interest_Dividend_Disbursement__c.field-meta.xml
<CustomField>
    <fullName>Interest_Dividend_Disbursement__c</fullName>
    <label>Interest Dividend Disbursement</label>
    <referenceTo>Interest_Dividend_Disbursement__c</referenceTo>
    <relationshipLabel>Interest Dividend Transaction Log</relationshipLabel>
    <relationshipName>Interest_Dividend_Transaction_Log</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/Interest_Dividend_Transaction_Log__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Interest Dividend Transaction Log</relationshipLabel>
    <relationshipName>Interest_Dividend_Transaction_Log</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/Interest_Dividend_Transaction_Log_Detail__c/Interest_Dividend_Transaction_Log_Detail__c.object-meta.xml
<CustomObject>
    <label>Interest Dividend Transaction Log Detail</label>
    <nameField>
        <displayFormat>IDTD-{0000}</displayFormat>
        <label>Interest Dividend Transaction Log Detail</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest Dividend Transaction Log Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Interest_Dividend_Transaction_Log_Detail__c/fields/Interest_Dividend_Transaction_Log__c.field-meta.xml
<CustomField>
    <fullName>Interest_Dividend_Transaction_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interest Dividend Transaction Log</label>
    <referenceTo>Interest_Dividend_Transaction_Log__c</referenceTo>
    <relationshipLabel>Interest Dividend Transaction Log Detail</relationshipLabel>
    <relationshipName>Interest_Dividend_Transaction_Log_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Interest_Dividend_Transaction_Log_Detail__c/fields/Investment_Value__c.field-meta.xml
<CustomField>
    <fullName>Investment_Value__c</fullName>
    <label>Investment Value</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Interest_Dividend_Transaction_Log_Detail__c/fields/Number_of_Days__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Days__c</fullName>
    <label>Number of Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/Interest_Dividend_Transaction_Log_Detail__c/fields/Returns_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Returns_Percentage__c</fullName>
    <label>Returns Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Invested_Product_ADMIN_FIELD__c.field-meta.xml
<CustomField>
    <fullName>Invested_Product_ADMIN_FIELD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please disregard this field. Admin field Only!</inlineHelpText>
    <label>Invested Product_ADMIN FIELD</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Old_Redemption_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Old_Redemption_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Old Redemption Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Unit_Cert_Issued__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cert_Issued__c</fullName>
    <label>Unit Cert Issued</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Unit_Certificate_Amount__c.field-meta.xml
<CustomField>
    <fullName>Unit_Certificate_Amount__c</fullName>
    <inlineHelpText>The amount issued on the unit certificate. This is the amount invested less any contribution fees.</inlineHelpText>
    <label>Original Unit Certificate Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Pricebook_Entry_Log__c/Pricebook_Entry_Log__c.object-meta.xml
<CustomObject>
    <label>Pricebook Entry Log</label>
    <nameField>
        <displayFormat>PEL-{00000}</displayFormat>
        <label>Pricebook Entry Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricebook Entry Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Pricebook_Entry_Log__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Pricebook_Entry_Log__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Pricebook Entry Logs</relationshipLabel>
    <relationshipName>Pricebook_Entry_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Fixed_Returns__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Returns__c</fullName>
    <label>Fixed Returns</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Forecast_Returns__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Returns__c</fullName>
    <label>Forecast Returns</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Monthly_Distributions__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Distributions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Monthly Distributions</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Return_Type__c.field-meta.xml
<CustomField>
    <fullName>Return_Type__c</fullName>
    <label>Return Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Per Annum</fullName>
            </value>
            <value>
                <fullName>Fixed Return</fullName>
            </value>
            <value>
                <fullName>Variable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/ROI_Log__c/ROI_Log__c.object-meta.xml
<CustomObject>
    <label>ROI Log</label>
    <nameField>
        <displayFormat>ROI-{0000}</displayFormat>
        <label>ROI Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ROI Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/ROI_Log__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>ROI Log</relationshipLabel>
    <relationshipName>ROI_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/ROI_Log__c/fields/Returns_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Returns_Percentage__c</fullName>
    <label>Returns Percentage</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/ROI_Log__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

common/force-app/main/default/classes/interestDividendDisbursementCntrl.cls
public without sharing class interestDividendDisbursementCntrl {
    @AuraEnabled
    public static List<selOptions> availableProdOptns(){
        Map<Id,string> prodIdVsName = new Map<Id,string>();
        List<selOptions> retopnslst = new List<selOptions>();
        for(Product2 p : [SELECT Id,Name,(SELECT Id,Name FROM Opportunities__r WHERE StageName ='Closed Won') FROM Product2]){
            if(!p.Opportunities__r.isEmpty())
            retopnslst.add(new selOptions(p.Name,p.Id));
        }
        return retopnslst;
    }
    @AuraEnabled
    public static retwrapper getProdsetails(Id prodID){
        Product2 prod = [SELECT Id,Name,Return_Type__c,Fixed_Returns__c, Forecast_Returns__c,Monthly_Distributions__c,CreatedDate,(SELECT Id,Name,Active__c,End_Date__c,Start_Date__c,List_Price__c FROM Pricebook_Entry_Logs__r ORDER BY Name DESC),(SELECT Id,UnitPrice FROM PricebookEntries WHERE IsActive = true),(SELECT Id,Active__c,Start_Date__c,End_Date__c,Name,Returns_Percentage__c FROM ROI_Log__r ORDER BY Name DESC) FROM Product2 WHERE Id =:prodID];
        retwrapper retwrap = new retwrapper();
        retwrap.prod = prod;
        List<Opportunity> opplst = [SELECT Id,Name,Unit_Certificate_Amount__c,Unit_Cert_Issued__c,Invested_Product_ADMIN_FIELD__c,Invested_Product_ADMIN_FIELD__r.Fixed_Returns__c,(SELECT Id,Name,End_Date__c FROM Interest_Dividend_Transaction_Log__r ORDER BY createddate desc LIMIT 1),(SELECT Id,Quantity,UnitPrice FROM OpportunityLineItems) FROM opportunity WHERE StageName ='Closed Won' AND Invested_Product_ADMIN_FIELD__c = :prodID LIMIT 200];
        retwrap.prod = prod;
        retwrap.opplst = opplst;
        return retwrap;
    }

    public class selOptions{
        @AuraEnabled public string label;
        @AuraEnabled public string value;
        public selOptions(string label,string value){
            this.label = label;
            this.value = value;
        }
    }
    public class retwrapper{
        @AuraEnabled public Product2 prod;
        @AuraEnabled public List<Opportunity> opplst;
    }
    @AuraEnabled
    public static void createFunddisuirsment(Id prodId, string endate, string jsonstr){
        List<localwrapper1> wraplst = (List<localwrapper1>) JSON.deserialize(jsonstr,List<localwrapper1>.class);
        Interest_Dividend_Disbursement__c disbursemnet = new Interest_Dividend_Disbursement__c();
        disbursemnet.End_Date__c = dateformatter(endate);
        disbursemnet.Product__c = prodId;
        insert disbursemnet;
        Map<Id,Id> oppIdVSlogId = new Map<Id,Id>();
        list<Interest_Dividend_Transaction_Log__c> loglst = new list<Interest_Dividend_Transaction_Log__c>();
        for(localwrapper1 wrap : wraplst){
            Interest_Dividend_Transaction_Log__c log = new Interest_Dividend_Transaction_Log__c();
            log.Days_included_in_Calculation__c = wrap.dayscnt;
            log.Opportunity__c = wrap.oppId;
            log.Interest__c = wrap.totalint;
            log.Interest_Dividend_Disbursement__c = disbursemnet.Id;
            log.End_Date__c = dateformatter(wrap.enddate);
            log.Start_Date__c = dateformatter(wrap.startdate);
            loglst.add(log);
        }
        insert loglst;
        List<Interest_Dividend_Transaction_Log_Detail__c> detaillst = new list<Interest_Dividend_Transaction_Log_Detail__c>();
        for(Interest_Dividend_Transaction_Log__c log : loglst){
            oppIdVSlogId.put(log.Opportunity__c,log.Id);
        }
        for(localwrapper1 wrap1 : wraplst){
            for(localwrapper2 wrap2 : wrap1.children){
                Interest_Dividend_Transaction_Log_Detail__c detail = new Interest_Dividend_Transaction_Log_Detail__c();
                detail.Interest_Dividend_Transaction_Log__c = oppIdVSlogId.get(wrap2.opporId);
                detail.End_Date__c = dateformatter(wrap2.enddate);
                detail.Start_Date__c = dateformatter(wrap2.startdate);
                detail.Interest__c = wrap2.totalint;
                detail.Investment_Value__c = wrap2.totalworth;
                detail.Number_of_Days__c = wrap2.dayscnt;
                detail.Returns_Percentage__c = wrap2.returnspercentage;
                detaillst.add(detail);
            }
        }
        insert detaillst;
    }
    public static Date dateformatter(string dat){
        List<String> datlst = dat.split('-');
        return Date.newInstance(Integer.valueof(datlst[2]),Integer.valueof(datlst[1]),Integer.valueof(datlst[0]));
    }
    public class localwrapper1{
        @AuraEnabled public Integer dayscnt;
        @AuraEnabled public decimal totalint;
        @AuraEnabled public Id oppId;
        @AuraEnabled public string startdate;
        @AuraEnabled public string enddate;
        @AuraEnabled public List<localwrapper2> children;
    }
    public class localwrapper2{
        @AuraEnabled public string startdate;
        @AuraEnabled public string enddate;
        @AuraEnabled public decimal totalworth;
        @AuraEnabled public Integer dayscnt;
        @AuraEnabled public decimal totalint;
        @AuraEnabled public decimal returnspercentage;
        @AuraEnabled public Id opporId;
    }
    @AuraEnabled
    public static Map<string,object>  getProddetails(Id ProdId){
        Map<string,object> retobj = new Map<string,object>();
        Product2 prod = [SELECT Id,Name,(SELECT Id,UnitPrice FROM PricebookEntries WHERE IsActive = true) FROM Product2 WHERE Id = :ProdId];
        retobj.put('prodName',prod.Name);
        retobj.put('currentprice',prod.PricebookEntries[0].UnitPrice);
        return retobj;
    }
    @AuraEnabled
    public static void updatePriceBookEntry(Id ProdId,Decimal newListprice){
        Product2 prod = [SELECT Id,Name,createdDate,(SELECT Id,UnitPrice FROM PricebookEntries WHERE IsActive = true),(SELECT Id,Name,Active__c,End_Date__c,Start_Date__c FROM Pricebook_Entry_Logs__r ORDER BY Name DESC) FROM Product2 WHERE Id = :ProdId];
        PricebookEntry pe = new PricebookEntry(Id = prod.PricebookEntries[0].Id);
        pe.UnitPrice = newListprice;
        update pe;
        List<Pricebook_Entry_Log__c> pelst = new List<Pricebook_Entry_Log__c>();
        if(prod.Pricebook_Entry_Logs__r.isEmpty()){
            Pricebook_Entry_Log__c pe1 = new Pricebook_Entry_Log__c();
            pe1.Active__c = false;
            pe1.Start_Date__c = prod.createdDate;
            pe1.End_Date__c = system.NOW();
            pe1.Product__c = prod.Id;
            pe1.List_Price__c = prod.PricebookEntries[0].UnitPrice;
            pelst.add(pe1);
            Pricebook_Entry_Log__c pe2 = new Pricebook_Entry_Log__c();
            pe2.Active__c = true;
            pe2.Start_Date__c = system.NOW();
            pe2.Product__c = prod.Id;
            pe2.List_Price__c = newListprice;
            pelst.add(pe2);
        }else{
            Pricebook_Entry_Log__c pe1 = new Pricebook_Entry_Log__c(Id=prod.Pricebook_Entry_Logs__r[0].Id);
            pe1.Active__c = false;
            pe1.End_Date__c = system.NOW();
            pelst.add(pe1);
            Pricebook_Entry_Log__c pe2 = new Pricebook_Entry_Log__c();
            pe2.Active__c = true;
            pe2.Start_Date__c = system.NOW();
            pe2.Product__c = prod.Id;
            pe2.List_Price__c = newListprice;
            pelst.add(pe2);
        }
        upsert pelst;
    }
}