common/force-app/main/default/objects/Raise__c/Raise__c.object-meta.xml
<CustomObject>
    <description>The raise object accountable for keeping track of a Founder&apos;s raise process.</description>
    <label>Raise</label>
    <nameField>
        <label>Raise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Raise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Raise__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field represents an account lookup relationship.</description>
    <inlineHelpText>Select an account to associate with this record.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Raise</relationshipLabel>
    <relationshipName>Raise</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field represents a master-detail relationship with the Company object.</description>
    <inlineHelpText>Select the company to which this record belongs.</inlineHelpText>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Raise (Company)</relationshipLabel>
    <relationshipName>Company</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_ABN__c.field-meta.xml
<CustomField>
    <fullName>Form_ABN__c</fullName>
    <description>This field stores the Australian Business Number (ABN).</description>
    <inlineHelpText>Enter the Australian Business Number (ABN) for this company.</inlineHelpText>
    <label>ABN</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_ACN__c.field-meta.xml
<CustomField>
    <fullName>Form_ACN__c</fullName>
    <description>This field stores the Australian Company Number (ACN).</description>
    <inlineHelpText>Enter the Australian Company Number (ACN) for this company.</inlineHelpText>
    <label>ACN</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Business_model__c.field-meta.xml
<CustomField>
    <fullName>Form_Business_model__c</fullName>
    <description>This field contains a long text description of the business model.</description>
    <inlineHelpText>Provide a detailed description of the business model.</inlineHelpText>
    <label>Business model</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Business_strategy__c.field-meta.xml
<CustomField>
    <fullName>Form_Business_strategy__c</fullName>
    <description>This field contains a long text description of the business strategy.</description>
    <inlineHelpText>Provide a detailed description of the business strategy.</inlineHelpText>
    <label>Business strategy</label>
    <length>1400</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Company_Legal_Trading_Name__c.field-meta.xml
<CustomField>
    <fullName>Form_Company_Legal_Trading_Name__c</fullName>
    <description>This field stores the full legal trading name of the company.</description>
    <inlineHelpText>Enter the full legal trading name of the company.</inlineHelpText>
    <label>Company&apos;s full legal trading name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Company_Overview__c.field-meta.xml
<CustomField>
    <fullName>Form_Company_Overview__c</fullName>
    <description>This field provides an overview of the company.</description>
    <inlineHelpText>Give a detailed overview of your company’s mission, vision, and operations.</inlineHelpText>
    <label>Who are we</label>
    <length>1400</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Company_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Form_Company_Street_Address__c</fullName>
    <description>This field is the Company Street address</description>
    <label>Company Street Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Debt_funding_and_other_funding__c.field-meta.xml
<CustomField>
    <fullName>Form_Debt_funding_and_other_funding__c</fullName>
    <description>This field provides information about debt funding and other funding sources.</description>
    <inlineHelpText>Include details about the company&apos;s debt funding and other financial sources.</inlineHelpText>
    <label>Debt funding and other funding</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Details_of_previous_CSF_offers__c.field-meta.xml
<CustomField>
    <fullName>Form_Details_of_previous_CSF_offers__c</fullName>
    <description>Details of previous CSF Offers</description>
    <label>Details of previous CSF offers</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Financial_information_summary__c.field-meta.xml
<CustomField>
    <fullName>Form_Financial_information_summary__c</fullName>
    <description>This field summarizes the financial information of the company.</description>
    <inlineHelpText>Summarize the key financial information of your company.</inlineHelpText>
    <label>Financial information summary</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Investment_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Form_Investment_Product_Type__c</fullName>
    <description>This field specifies the type of investment product offered by the company.</description>
    <inlineHelpText>Specify the type of investment product your company offers.</inlineHelpText>
    <label>Investment Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinary Shares</fullName>
                <default>true</default>
                <label>Ordinary Shares</label>
            </value>
            <value>
                <fullName>Preference Shares</fullName>
            </value>
            <value>
                <fullName>Convertible Note</fullName>
            </value>
            <value>
                <fullName>Promissory Note</fullName>
            </value>
            <value>
                <fullName>SAFE Note</fullName>
            </value>
            <value>
                <fullName>Units in a MIS</fullName>
            </value>
            <value>
                <fullName>Secured Loan</fullName>
            </value>
            <value>
                <fullName>Interests in a Limited Partnership</fullName>
            </value>
            <value>
                <fullName>Shares</fullName>
                <isActive>false</isActive>
                <label>Shares</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Legal_or_disciplinary_action__c.field-meta.xml
<CustomField>
    <fullName>Form_Legal_or_disciplinary_action__c</fullName>
    <description>This field provides information about any legal or disciplinary actions involving the company.</description>
    <inlineHelpText>Include details about any legal or disciplinary actions involving your company.</inlineHelpText>
    <label>Legal or disciplinary action</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Maximum_target__c.field-meta.xml
<CustomField>
    <fullName>Form_Maximum_target__c</fullName>
    <description>This field indicates the maximum funding target for the company.</description>
    <inlineHelpText>Specify the maximum amount of funding your company is aiming to raise.</inlineHelpText>
    <label>Maximum target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Minimum_Investment_amount__c.field-meta.xml
<CustomField>
    <fullName>Form_Minimum_Investment_amount__c</fullName>
    <description>This field indicates the minimum investment amount required.</description>
    <inlineHelpText>Specify the minimum amount that can be invested in your company.</inlineHelpText>
    <label>Minimum Investment amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Minimum_target__c.field-meta.xml
<CustomField>
    <fullName>Form_Minimum_target__c</fullName>
    <description>This field indicates the minimum funding target for the company.</description>
    <inlineHelpText>Specify the minimum amount of funding your company needs to raise.</inlineHelpText>
    <label>Minimum target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Number_of_shares_on_issue__c.field-meta.xml
<CustomField>
    <fullName>Form_Number_of_shares_on_issue__c</fullName>
    <description>This field indicates the total number of shares currently issued by the company.</description>
    <inlineHelpText>Specify the total number of shares currently issued by your company.</inlineHelpText>
    <label>Number of shares on issue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Offer_close_date__c.field-meta.xml
<CustomField>
    <fullName>Form_Offer_close_date__c</fullName>
    <description>This field specifies the closing date for the current offer.</description>
    <inlineHelpText>Provide the closing date for the current offer.</inlineHelpText>
    <label>Offer close date</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Offer_launch_date__c.field-meta.xml
<CustomField>
    <fullName>Form_Offer_launch_date__c</fullName>
    <description>This field specifies the launch date for the current offer.</description>
    <inlineHelpText>Provide the launch date for the current offer.</inlineHelpText>
    <label>Offer launch date</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Organisation_structure__c.field-meta.xml
<CustomField>
    <fullName>Form_Organisation_structure__c</fullName>
    <description>This field describes the organizational structure of the company.</description>
    <inlineHelpText>Detail the organizational structure of your company.</inlineHelpText>
    <label>Organisation structure</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Planned_use_of_funds__c.field-meta.xml
<CustomField>
    <fullName>Form_Planned_use_of_funds__c</fullName>
    <description>This field outlines the planned use of the funds raised.</description>
    <inlineHelpText>Describe how the funds raised will be used.</inlineHelpText>
    <label>Planned use of funds</label>
    <length>1200</length>
    <type>Html</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Proprietary_company__c.field-meta.xml
<CustomField>
    <fullName>Form_Proprietary_company__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates whether the company is a proprietary company.</description>
    <inlineHelpText>Check this box if your company is a proprietary company.</inlineHelpText>
    <label>Proprietary company</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Public_company__c.field-meta.xml
<CustomField>
    <fullName>Form_Public_company__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates whether the company is a public company.</description>
    <inlineHelpText>Check this box if your company is a public company.</inlineHelpText>
    <label>Public company</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Registered_Aus__c.field-meta.xml
<CustomField>
    <fullName>Form_Registered_Aus__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates whether the company is registered in Australia.</description>
    <inlineHelpText>Check this box if your company is registered in Australia.</inlineHelpText>
    <label>Is your company registered in Australia</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Rights_associated_with_shares__c.field-meta.xml
<CustomField>
    <fullName>Form_Rights_associated_with_shares__c</fullName>
    <description>This field outlines the rights associated with the shares.</description>
    <inlineHelpText>Detail the rights that are associated with the shares being offered.</inlineHelpText>
    <label>Rights associated with shares</label>
    <length>1400</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Risks_facing_the_business__c.field-meta.xml
<CustomField>
    <fullName>Form_Risks_facing_the_business__c</fullName>
    <description>This field outlines the risks facing the business.</description>
    <inlineHelpText>Describe the key risks that your business is currently facing.</inlineHelpText>
    <label>Risks facing the business</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Target_amount__c.field-meta.xml
<CustomField>
    <fullName>Form_Target_amount__c</fullName>
    <description>This field indicates the target amount for the raise.</description>
    <inlineHelpText>Specify the total target amount your company aims to raise.</inlineHelpText>
    <label>Target amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Valuation__c.field-meta.xml
<CustomField>
    <fullName>Form_Valuation__c</fullName>
    <description>This field indicates the company’s valuation.</description>
    <inlineHelpText>Specify the current valuation of your company.</inlineHelpText>
    <label>Valuation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/classes/TestRaisePDFGenerator.cls
@isTest
public class TestRaisePDFGenerator {

    @isTest
    static void testGenerateAndSaveRaisePDF() {
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;

        Account testCompany = new Account(Name = 'Test Company');
        insert testCompany;

        Raise__c raiseRecord = new Raise__c(
            Name = 'Test Raise',
            Account__c = testAccount.Id,
            Company__c = testCompany.Id,
            Form_Company_Legal_Trading_Name__c = 'Test Legal Name',
            Form_Registered_Aus__c = true,
            Form_ABN__c = '123456789',
            Form_ACN__c = '987654321',
            Form_Company_Street_Address__c = '123 Test Street',
            Form_Company_Overview__c = 'Test Overview',
            Form_Business_strategy__c = 'Test Strategy',
            Form_Business_model__c = 'Test Model',
            Form_Organisation_structure__c = 'Test Structure',
            Form_Proprietary_company__c = true,
            Form_Public_company__c = false,
            Form_Financial_information_summary__c = 'Test Summary',
            Form_Debt_funding_and_other_funding__c = 'Test Funding',
            Form_Legal_or_disciplinary_action__c = 'None',
            Form_Risks_facing_the_business__c = 'Test Risks',
            Form_Planned_use_of_funds__c = 'Test use of funds',
            Form_Offer_launch_date__c = Date.today(),
            Form_Offer_close_date__c = Date.today().addDays(30),
            Form_Investment_Product_Type__c = 'ordinary shares',
            Form_Valuation__c = 1000000.00,
            Form_Number_of_shares_on_issue__c = 1000,
            Form_Rights_associated_with_shares__c = 'Test Rights',
            Form_Details_of_previous_CSF_offers__c = 'None',
            Form_Target_amount__c = 100000.00,
            Form_Minimum_target__c = 50000.00,
            Form_Maximum_target__c = 150000.00,
            Form_Minimum_Investment_amount__c = 1000.00,
            Form_Risk_warning__c = 'Test Warning',
            Form_Cooling_off_rights__c = 'Test Rights',
            Form_Glossary__c = 'Test Glossary'
        );
        insert raiseRecord;

        Raise_Team_and_Advisors__c teamRecord = new Raise_Team_and_Advisors__c(
            Role__c = 'Advisor',
            Name__c = 'Test Advisor',
            Related_Raise__c = raiseRecord.Id
        );
        insert teamRecord;

        RaisePDFGenerator.PDFGenerationRequest request = new RaisePDFGenerator.PDFGenerationRequest();
        request.raiseId = raiseRecord.Id;
        request.targetRecordId = raiseRecord.Id;

        Test.startTest();
        TestRaisePDFGeneratorMock mock = new TestRaisePDFGeneratorMock();
        mock.generateAndSaveRaisePDFInternal(new List<RaisePDFGenerator.PDFGenerationRequest>{ request });
        Test.stopTest();

        ContentVersion cv = [
            SELECT Id, Title 
            FROM ContentVersion 
            WHERE Title = :('Offer Document_' + raiseRecord.Name + '.pdf') 
            LIMIT 1
        ];
        System.assertNotEquals(null, cv, 'PDF ContentVersion should be created');

        ContentDocumentLink cdl = [
            SELECT Id, LinkedEntityId 
            FROM ContentDocumentLink 
            WHERE LinkedEntityId = :raiseRecord.Id 
            LIMIT 1
        ];
        System.assertNotEquals(null, cdl, 'ContentDocumentLink should be created');
    }

    @isTest
    static void testGenerateAndSaveRaisePDF_MissingIDs() {
        RaisePDFGenerator.PDFGenerationRequest invalidRequest = new RaisePDFGenerator.PDFGenerationRequest();
        invalidRequest.raiseId = null;
        invalidRequest.targetRecordId = null;

        Test.startTest();
        RaisePDFGenerator.generateAndSaveRaisePDF(new List<RaisePDFGenerator.PDFGenerationRequest>{ invalidRequest });
        Test.stopTest();

        Integer cvCount = [SELECT COUNT() FROM ContentVersion];
        System.assertEquals(0, cvCount, 'No ContentVersion should be created with missing IDs.');
    }

@isTest
static void testGetPDFBlob_ExceptionScenario() {
    Account testAccount = new Account(Name = 'Test Exception Account');
    insert testAccount;

    Raise__c raiseRecord = new Raise__c(Name = 'Test Raise Exception', Account__c = testAccount.Id);
    insert raiseRecord;

    RaisePDFGenerator.PDFGenerationRequest request = new RaisePDFGenerator.PDFGenerationRequest();
    request.raiseId = raiseRecord.Id;
    request.targetRecordId = raiseRecord.Id;

    TestRaisePDFGeneratorFailMock mock = new TestRaisePDFGeneratorFailMock();

    Test.startTest();
    try {
        mock.generateAndSaveRaisePDFInternal(new List<RaisePDFGenerator.PDFGenerationRequest>{ request });
    } catch (Exception e) {
        System.debug('Caught (but not asserting on) exception: ' + e.getMessage());
    }
    Test.stopTest();
}
}