common/force-app/main/default/objects/Raise__c/Raise__c.object-meta.xml
<CustomObject>
    <description>The raise object accountable for keeping track of a Founder&apos;s raise process.</description>
    <label>Raise</label>
    <nameField>
        <label>Raise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Raise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Raise__c/fields/Form_ABN__c.field-meta.xml
<CustomField>
    <fullName>Form_ABN__c</fullName>
    <description>This field stores the Australian Business Number (ABN).</description>
    <inlineHelpText>Enter the Australian Business Number (ABN) for this company.</inlineHelpText>
    <label>ABN</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_ACN__c.field-meta.xml
<CustomField>
    <fullName>Form_ACN__c</fullName>
    <description>This field stores the Australian Company Number (ACN).</description>
    <inlineHelpText>Enter the Australian Company Number (ACN) for this company.</inlineHelpText>
    <label>ACN</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Business_model__c.field-meta.xml
<CustomField>
    <fullName>Form_Business_model__c</fullName>
    <description>This field contains a long text description of the business model.</description>
    <inlineHelpText>Provide a detailed description of the business model.</inlineHelpText>
    <label>Business model</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Business_strategy__c.field-meta.xml
<CustomField>
    <fullName>Form_Business_strategy__c</fullName>
    <description>This field contains a long text description of the business strategy.</description>
    <inlineHelpText>Provide a detailed description of the business strategy.</inlineHelpText>
    <label>Business strategy</label>
    <length>1400</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Company_Legal_Trading_Name__c.field-meta.xml
<CustomField>
    <fullName>Form_Company_Legal_Trading_Name__c</fullName>
    <description>This field stores the full legal trading name of the company.</description>
    <inlineHelpText>Enter the full legal trading name of the company.</inlineHelpText>
    <label>Company&apos;s full legal trading name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Company_Overview__c.field-meta.xml
<CustomField>
    <fullName>Form_Company_Overview__c</fullName>
    <description>This field provides an overview of the company.</description>
    <inlineHelpText>Give a detailed overview of your company’s mission, vision, and operations.</inlineHelpText>
    <label>Who are we</label>
    <length>1400</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Company_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Form_Company_Street_Address__c</fullName>
    <description>This field is the Company Street address</description>
    <label>Company Street Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Cooling_off_rights__c.field-meta.xml
<CustomField>
    <fullName>Form_Cooling_off_rights__c</fullName>
    <description>This field describes the cooling-off rights.</description>
    <inlineHelpText>Describe the rights for cooling-off period provided to the customers.</inlineHelpText>
    <label>Cooling-off rights</label>
    <length>1400</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Debt_funding_and_other_funding__c.field-meta.xml
<CustomField>
    <fullName>Form_Debt_funding_and_other_funding__c</fullName>
    <description>This field provides information about debt funding and other funding sources.</description>
    <inlineHelpText>Include details about the company&apos;s debt funding and other financial sources.</inlineHelpText>
    <label>Debt funding and other funding</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Details_of_previous_CSF_offers__c.field-meta.xml
<CustomField>
    <fullName>Form_Details_of_previous_CSF_offers__c</fullName>
    <description>Details of previous CSF Offers</description>
    <label>Details of previous CSF offers</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Financial_information_summary__c.field-meta.xml
<CustomField>
    <fullName>Form_Financial_information_summary__c</fullName>
    <description>This field summarizes the financial information of the company.</description>
    <inlineHelpText>Summarize the key financial information of your company.</inlineHelpText>
    <label>Financial information summary</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Investment_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Form_Investment_Product_Type__c</fullName>
    <description>This field specifies the type of investment product offered by the company.</description>
    <inlineHelpText>Specify the type of investment product your company offers.</inlineHelpText>
    <label>Investment Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinary Shares</fullName>
                <default>true</default>
                <label>Ordinary Shares</label>
            </value>
            <value>
                <fullName>Preference Shares</fullName>
            </value>
            <value>
                <fullName>Convertible Note</fullName>
            </value>
            <value>
                <fullName>Promissory Note</fullName>
            </value>
            <value>
                <fullName>SAFE Note</fullName>
            </value>
            <value>
                <fullName>Units in a MIS</fullName>
            </value>
            <value>
                <fullName>Secured Loan</fullName>
            </value>
            <value>
                <fullName>Interests in a Limited Partnership</fullName>
            </value>
            <value>
                <fullName>Shares</fullName>
                <isActive>false</isActive>
                <label>Shares</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Legal_or_disciplinary_action__c.field-meta.xml
<CustomField>
    <fullName>Form_Legal_or_disciplinary_action__c</fullName>
    <description>This field provides information about any legal or disciplinary actions involving the company.</description>
    <inlineHelpText>Include details about any legal or disciplinary actions involving your company.</inlineHelpText>
    <label>Legal or disciplinary action</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Maximum_target__c.field-meta.xml
<CustomField>
    <fullName>Form_Maximum_target__c</fullName>
    <description>This field indicates the maximum funding target for the company.</description>
    <inlineHelpText>Specify the maximum amount of funding your company is aiming to raise.</inlineHelpText>
    <label>Maximum target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Minimum_Investment_amount__c.field-meta.xml
<CustomField>
    <fullName>Form_Minimum_Investment_amount__c</fullName>
    <description>This field indicates the minimum investment amount required.</description>
    <inlineHelpText>Specify the minimum amount that can be invested in your company.</inlineHelpText>
    <label>Minimum Investment amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Minimum_target__c.field-meta.xml
<CustomField>
    <fullName>Form_Minimum_target__c</fullName>
    <description>This field indicates the minimum funding target for the company.</description>
    <inlineHelpText>Specify the minimum amount of funding your company needs to raise.</inlineHelpText>
    <label>Minimum target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Number_of_shares_on_issue__c.field-meta.xml
<CustomField>
    <fullName>Form_Number_of_shares_on_issue__c</fullName>
    <description>This field indicates the total number of shares currently issued by the company.</description>
    <inlineHelpText>Specify the total number of shares currently issued by your company.</inlineHelpText>
    <label>Number of shares on issue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Offer_close_date__c.field-meta.xml
<CustomField>
    <fullName>Form_Offer_close_date__c</fullName>
    <description>This field specifies the closing date for the current offer.</description>
    <inlineHelpText>Provide the closing date for the current offer.</inlineHelpText>
    <label>Offer close date</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Offer_launch_date__c.field-meta.xml
<CustomField>
    <fullName>Form_Offer_launch_date__c</fullName>
    <description>This field specifies the launch date for the current offer.</description>
    <inlineHelpText>Provide the launch date for the current offer.</inlineHelpText>
    <label>Offer launch date</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Organisation_structure__c.field-meta.xml
<CustomField>
    <fullName>Form_Organisation_structure__c</fullName>
    <description>This field describes the organizational structure of the company.</description>
    <inlineHelpText>Detail the organizational structure of your company.</inlineHelpText>
    <label>Organisation structure</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Planned_use_of_funds__c.field-meta.xml
<CustomField>
    <fullName>Form_Planned_use_of_funds__c</fullName>
    <description>This field outlines the planned use of the funds raised.</description>
    <inlineHelpText>Describe how the funds raised will be used.</inlineHelpText>
    <label>Planned use of funds</label>
    <length>1200</length>
    <type>Html</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Proprietary_company__c.field-meta.xml
<CustomField>
    <fullName>Form_Proprietary_company__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates whether the company is a proprietary company.</description>
    <inlineHelpText>Check this box if your company is a proprietary company.</inlineHelpText>
    <label>Proprietary company</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Public_company__c.field-meta.xml
<CustomField>
    <fullName>Form_Public_company__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates whether the company is a public company.</description>
    <inlineHelpText>Check this box if your company is a public company.</inlineHelpText>
    <label>Public company</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Registered_Aus__c.field-meta.xml
<CustomField>
    <fullName>Form_Registered_Aus__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates whether the company is registered in Australia.</description>
    <inlineHelpText>Check this box if your company is registered in Australia.</inlineHelpText>
    <label>Is your company registered in Australia</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Rights_associated_with_shares__c.field-meta.xml
<CustomField>
    <fullName>Form_Rights_associated_with_shares__c</fullName>
    <description>This field outlines the rights associated with the shares.</description>
    <inlineHelpText>Detail the rights that are associated with the shares being offered.</inlineHelpText>
    <label>Rights associated with shares</label>
    <length>1400</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Risk_warning__c.field-meta.xml
<CustomField>
    <fullName>Form_Risk_warning__c</fullName>
    <description>This field contains a risk warning related to the investment.</description>
    <inlineHelpText>Provide a risk warning to inform potential investors of the risks involved.</inlineHelpText>
    <label>Risk warning</label>
    <length>1400</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Risks_facing_the_business__c.field-meta.xml
<CustomField>
    <fullName>Form_Risks_facing_the_business__c</fullName>
    <description>This field outlines the risks facing the business.</description>
    <inlineHelpText>Describe the key risks that your business is currently facing.</inlineHelpText>
    <label>Risks facing the business</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Share_price__c.field-meta.xml
<CustomField>
    <fullName>Form_Share_price__c</fullName>
    <description>This field indicates the price per share.</description>
    <formula>IF(Share_Price__c &gt; 0, 
   Share_Price__c, 
   Form_Valuation__c / Form_Number_of_shares_on_issue__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Specify the price per share for the current offering.</inlineHelpText>
    <label>Share price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Target_amount__c.field-meta.xml
<CustomField>
    <fullName>Form_Target_amount__c</fullName>
    <description>This field indicates the target amount for the raise.</description>
    <inlineHelpText>Specify the total target amount your company aims to raise.</inlineHelpText>
    <label>Target amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Valuation__c.field-meta.xml
<CustomField>
    <fullName>Form_Valuation__c</fullName>
    <description>This field indicates the company’s valuation.</description>
    <inlineHelpText>Specify the current valuation of your company.</inlineHelpText>
    <label>Valuation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/classes/RaisePDFController.cls
// File: RaisePDFController.cls
public with sharing class RaisePDFController {
    public String HTMLContent { get; private set; }

    public RaisePDFController() {
        String raiseId = ApexPages.currentPage().getParameters().get('raiseId');
        if (String.isBlank(raiseId)) {
            throw new AuraHandledException('Missing Raise ID.');
        }

        // Fetch the Raise record and related Team and Advisors
        Raise__c raiseRecord = [
            SELECT Name, 
                Form_Company_Legal_Trading_Name__c,
                Form_Registered_Aus__c,
                Form_ABN__c,
                Form_ACN__c,
                Form_Company_Street_Address__c,
                Form_Company_Overview__c,
                Form_Business_strategy__c,
                Form_Business_model__c,
                Form_Organisation_structure__c,
                Form_Proprietary_company__c, 
                Form_Public_company__c, 
                Form_Financial_information_summary__c,
                Form_Debt_funding_and_other_funding__c,
                Form_Legal_or_disciplinary_action__c,
                Form_Risks_facing_the_business__c,
                Form_Planned_use_of_funds__c,
                Form_Offer_launch_date__c,
                Form_Offer_close_date__c,
                Form_Investment_Product_Type__c,
                Form_Valuation__c,
                Form_Number_of_shares_on_issue__c,
                Form_Share_price__c,
                Form_Rights_associated_with_shares__c,
                Form_Details_of_previous_CSF_offers__c,
                Form_Target_amount__c,
                Form_Minimum_target__c,
                Form_Maximum_target__c,
                Form_Minimum_Investment_amount__c,
                Form_Risk_warning__c,
                Form_Cooling_off_rights__c,
                Form_Glossary__c
            FROM Raise__c 
            WHERE Id = :raiseId 
            LIMIT 1
        ];

        List<Raise_Team_and_Advisors__c> teamRecords = [
            SELECT Role__c, Name 
            FROM Raise_Team_and_Advisors__c 
            WHERE Related_Raise__c = :raiseId
        ];

        // Generate HTML content
        HTMLContent = generateHtmlContent(raiseRecord, teamRecords);
    }

    /**
     * Generates the HTML content for the PDF based on the Raise record and related Team records.
     *
     * @param raiseRecord The Raise__c record.
     * @param teamRecords The list of related Raise_Team_and_Advisors__c records.
     * @return A string containing the HTML content.
     */
    private String generateHtmlContent(Raise__c raiseRecord, List<Raise_Team_and_Advisors__c> teamRecords) {
        String htmlContent = '<h1>' + escapeHtml(raiseRecord.Name) + ' Offer Document</h1>';
        htmlContent += '<table>';

        htmlContent += generateTableRow('Company\'s Full Legal Trading Name:', raiseRecord.Form_Company_Legal_Trading_Name__c);
        htmlContent += generateTableRow('Is Your Company Registered in Australia:', String.valueOf(raiseRecord.Form_Registered_Aus__c));
        htmlContent += generateTableRow('ABN:', raiseRecord.Form_ABN__c);
        htmlContent += generateTableRow('ACN:', raiseRecord.Form_ACN__c);
        htmlContent += generateTableRow('Company Street Address:', raiseRecord.Form_Company_Street_Address__c);
        htmlContent += generateTableRow('Who Are We:', raiseRecord.Form_Company_Overview__c);
        htmlContent += generateTableRow('Business Strategy:', raiseRecord.Form_Business_strategy__c);
        htmlContent += generateTableRow('Business Model:', raiseRecord.Form_Business_model__c);
        htmlContent += generateTableRow('Organisation Structure:', raiseRecord.Form_Organisation_structure__c);
        htmlContent += generateTableRow('Proprietary Company:', String.valueOf(raiseRecord.Form_Proprietary_company__c));
        htmlContent += generateTableRow('Public Company:', String.valueOf(raiseRecord.Form_Public_company__c));
        htmlContent += generateTableRow('Financial Information Summary:', raiseRecord.Form_Financial_information_summary__c);
        htmlContent += generateTableRow('Debt Funding and Other Funding:', raiseRecord.Form_Debt_funding_and_other_funding__c);
        htmlContent += generateTableRow('Legal or Disciplinary Action:', raiseRecord.Form_Legal_or_disciplinary_action__c);
        htmlContent += generateTableRow('Risks Facing the Business:', raiseRecord.Form_Risks_facing_the_business__c);
        htmlContent += generateTableRow('Planned Use of Funds:', raiseRecord.Form_Planned_use_of_funds__c);
        htmlContent += generateTableRow('Offer Launch Date:', String.valueOf(raiseRecord.Form_Offer_launch_date__c));
        htmlContent += generateTableRow('Offer Close Date:', String.valueOf(raiseRecord.Form_Offer_close_date__c));
        htmlContent += generateTableRow('Investment Product Type:', raiseRecord.Form_Investment_Product_Type__c);
        htmlContent += generateTableRow('Valuation:', String.valueOf(raiseRecord.Form_Valuation__c));
        htmlContent += generateTableRow('Number of Shares on Issue:', String.valueOf(raiseRecord.Form_Number_of_shares_on_issue__c));
        htmlContent += generateTableRow('Share Price:', String.valueOf(raiseRecord.Form_Share_price__c));
        htmlContent += generateTableRow('Rights Associated with Shares:', raiseRecord.Form_Rights_associated_with_shares__c);
        htmlContent += generateTableRow('Details of Previous CSF Offers:', raiseRecord.Form_Details_of_previous_CSF_offers__c);
        htmlContent += generateTableRow('Target Amount:', String.valueOf(raiseRecord.Form_Target_amount__c));
        htmlContent += generateTableRow('Minimum Target:', String.valueOf(raiseRecord.Form_Minimum_target__c));
        htmlContent += generateTableRow('Maximum Target:', String.valueOf(raiseRecord.Form_Maximum_target__c));
        htmlContent += generateTableRow('Minimum Investment Amount:', String.valueOf(raiseRecord.Form_Minimum_Investment_amount__c));
        htmlContent += generateTableRow('Risk Warning:', raiseRecord.Form_Risk_warning__c);
        htmlContent += generateTableRow('Cooling-off Rights:', String.valueOf(raiseRecord.Form_Cooling_off_rights__c));
        htmlContent += generateTableRow('Glossary:', raiseRecord.Form_Glossary__c);

        // Add Team and Advisors Section
        htmlContent += '<tr><th colspan="2">Team and Advisors</th></tr>';
        for (Raise_Team_and_Advisors__c teamRecord : teamRecords) {
            htmlContent += generateTableRow(escapeHtml(teamRecord.Role__c) + ':', escapeHtml(teamRecord.Name));
        }

        htmlContent += '</table>';
        return htmlContent;
    }

    /**
     * Generates an HTML table row with two columns: label and value.
     *
     * @param label The label for the row.
     * @param value The value for the row.
     * @return A string containing the HTML table row.
     */
    private String generateTableRow(String label, String value) {
        if (value != null && !String.isEmpty(value)) {
            return '<tr><td><strong>' + escapeHtml(label) + '</strong></td><td>' + escapeHtml(value) + '</td></tr>';
        }
        return '';
    }

    /**
     * Escapes HTML special characters to prevent rendering issues.
     *
     * @param input The input string to escape.
     * @return The escaped string.
     */
    private String escapeHtml(String input) {
        if (input == null) return '';
        return input.escapeHtml4();
    }

}