common/force-app/main/default/objects/Opportunity/fields/Closed_Won_Stages__c.field-meta.xml
<CustomField>
    <fullName>Closed_Won_Stages__c</fullName>
    <label>Closed Won Stages</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Partially Redeemed</fullName>
            </value>
            <value>
                <fullName>Fully Redeemed</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Rollover</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Current_Holdings__c.field-meta.xml
<CustomField>
    <fullName>Current_Holdings__c</fullName>
    <label>Current Holdings</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Current_Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Current_Total_Price__c</fullName>
    <label>Current Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Original_invested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Original_invested_Amount__c</fullName>
    <label>Original invested Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Original_invested_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Original_invested_Quantity__c</fullName>
    <label>Original invested Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Total_Redeemed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Redeemed_Amount__c</fullName>
    <label>Total Redeemed Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Total_Redeemed_Units__c.field-meta.xml
<CustomField>
    <fullName>Total_Redeemed_Units__c</fullName>
    <label>Total Redeemed Units</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/OpportunityLineItem/fields/Current_Investment_Value__c.field-meta.xml
<CustomField>
    <fullName>Current_Investment_Value__c</fullName>
    <formula>ListPrice  *   Original_Invested_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Investment Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/OpportunityLineItem/fields/Original_Invested_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Original_Invested_Quantity__c</fullName>
    <label>Current Holdings</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/OpportunityLineItem/fields/Original_Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Original_Sales_Price__c</fullName>
    <label>Current Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Redemption_Transaction_Log__c/Redemption_Transaction_Log__c.object-meta.xml
<CustomObject>
    <label>Redemption Transaction Log</label>
    <nameField>
        <displayFormat>RTL-{000000}</displayFormat>
        <label>Redemption Transaction Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Redemption Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Redemption_Transaction_Log__c/fields/Current_Invested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Invested_Amount__c</fullName>
    <label>Current Invested Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Redemption_Transaction_Log__c/fields/Current_Invested_Holding__c.field-meta.xml
<CustomField>
    <fullName>Current_Invested_Holding__c</fullName>
    <label>Current Invested Holding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/Redemption_Transaction_Log__c/fields/Date_of_Application__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Application__c</fullName>
    <label>Date of Application</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Redemption_Transaction_Log__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Redemption Transaction Logs</relationshipLabel>
    <relationshipName>Redemption_Transaction_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Redemption_Transaction_Log__c/fields/Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Redemption Transaction Logs</relationshipLabel>
    <relationshipName>Redemption_Transaction_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Redemption_Transaction_Log__c/fields/Original_invested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Original_invested_Amount__c</fullName>
    <label>Original Invested Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Redemption_Transaction_Log__c/fields/Original_invested_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Original_invested_Quantity__c</fullName>
    <label>Original Invested Holding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/Redemption_Transaction_Log__c/fields/Redeemed_Holding__c.field-meta.xml
<CustomField>
    <fullName>Redeemed_Holding__c</fullName>
    <label>Redeemed Holding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/Redemption_Transaction_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/classes/redeemProcessController.cls
public with sharing class redeemProcessController {
    @AuraEnabled
    public static void transactionLogs(String opportunityId,string opportunityProdId,Decimal amount,Decimal quantity,Date appliedDate) {
        try{
        List<Opportunity> oppList = new List<Opportunity>();
        Opportunity oppObj;
        List<OpportunityLineItem> oppLineItemList = new List<OpportunityLineItem>();
        OpportunityLineItem oppLineItemObj;
        oppList = [Select Id,Total_Redeemed_Amount__c,Total_Redeemed_Units__c,Original_invested_Quantity__c,
        Original_invested_Amount__c from opportunity where Id=:opportunityId];
        if(oppList.size()>0){
            oppObj = oppList[0];
        }

        oppLineItemList = [Select Id,TotalPrice,Quantity,Original_Sales_Price__c, Original_Invested_Quantity__c,Current_Investment_Value__c
                   from opportunityLineItem where Id=:opportunityProdId];
        if(oppLineItemList.size()>0){
            oppLineItemObj = oppLineItemList[0];
            oppLineItemObj.Original_Invested_Quantity__c = oppLineItemObj.Original_Invested_Quantity__c>0? oppLineItemObj.Original_Invested_Quantity__c-quantity:oppLineItemObj.Original_Invested_Quantity__c;
            oppLineItemObj.Original_Sales_Price__c = oppLineItemObj.Original_Sales_Price__c>0? oppLineItemObj.Current_Investment_Value__c-amount:oppLineItemObj.Original_Sales_Price__c;
            update oppLineItemObj;
            
            oppObj.Total_Redeemed_Amount__c = oppObj.Total_Redeemed_Amount__c!=null ? oppObj.Total_Redeemed_Amount__c + amount:amount;
            oppObj.Total_Redeemed_Units__c = oppObj.Total_Redeemed_Units__c!=null ? oppObj.Total_Redeemed_Units__c + Quantity:Quantity;
            oppObj.Original_invested_Quantity__c = oppObj.Original_invested_Quantity__c!=null ? oppObj.Original_invested_Quantity__c :oppLineItemObj.Quantity;
            oppObj.Original_invested_Amount__c = oppObj.Original_invested_Amount__c!=null ? oppObj.Original_invested_Amount__c :oppLineItemObj.TotalPrice;
            oppObj.StageName = 'Closed Won';
            oppObj.Current_Total_Price__c = oppLineItemObj.Original_Sales_Price__c;
            oppObj.Current_Holdings__c = oppLineItemObj.Original_Invested_Quantity__c;
            oppObj.Closed_Won_Stages__c = 0 == oppLineItemObj.Original_Sales_Price__c ? 'Fully Redeemed' : 'Partially Redeemed';
            update oppObj;

            Redemption_Transaction_Log__c logObj = new Redemption_Transaction_Log__c();
            logObj.Opportunity__c = oppObj.Id;
            logObj.Redeemed_Amount__c = amount;
            logObj.Redeemed_Holding__c = quantity;
            logObj.Date_of_Application__c = appliedDate;
            logObj.Original_Invested_Quantity__c = oppLineItemObj.Quantity;
            logObj.Original_invested_Amount__c = oppLineItemObj.TotalPrice;
            logObj.Current_Invested_Amount__c = oppLineItemObj.Original_Sales_Price__c;
            logObj.Current_Invested_Holding__c = oppLineItemObj.Original_Invested_Quantity__c;    
            logObj.Status__c = 'Processed';
            logObj.Opportunity_Product__c = oppLineItemObj.Id;
            Insert logObj;
        }
    }catch(exception ex){
        throw new AuraHandledException(ex.getMessage());
    }
    }

}