common/force-app/main/default/objects/Product2/fields/Banner_Date_Validation__c.field-meta.xml
<CustomField>
    <fullName>Banner_Date_Validation__c</fullName>
    <description>We are going to use this field to sync up the raiseBanners in the website</description>
    <formula>NOW() &lt; Offer_Close_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>We are going to use this field to sync up the raiseBanners in the website</inlineHelpText>
    <label>Banner Date Validation</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Deal_Description__c.field-meta.xml
<CustomField>
    <fullName>Deal_Description__c</fullName>
    <label>Deal Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Deal_Page_Link__c.field-meta.xml
<CustomField>
    <fullName>Deal_Page_Link__c</fullName>
    <label>Deal Page Link</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Distribution_Type__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Type__c</fullName>
    <label>Distribution Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>yielding__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interest Paid</fullName>
            </value>
            <value>
                <fullName>Accruing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Fully_Funded__c.field-meta.xml
<CustomField>
    <fullName>Fully_Funded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fully Funded</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Portal_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Portal_Display_Name__c</fullName>
    <label>Portal Display Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Private_Deal__c.field-meta.xml
<CustomField>
    <fullName>Private_Deal__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box for private deals that are not to be publicly published on the community site but are visible by invite to the URL.</inlineHelpText>
    <label>Private Deal</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Publish_on_Community_Site__c.field-meta.xml
<CustomField>
    <fullName>Publish_on_Community_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publish on Community Site</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Raise__c.field-meta.xml
<CustomField>
    <fullName>Raise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Raise</label>
    <referenceTo>Raise__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <inlineHelpText>The sector that this product operates in</inlineHelpText>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture and Farming</fullName>
            </value>
            <value>
                <fullName>Art and Design</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Banking and Finance</fullName>
            </value>
            <value>
                <fullName>Construction and Real Estate</fullName>
            </value>
            <value>
                <fullName>Defense and Aerospace</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Energy and Utilities</fullName>
            </value>
            <value>
                <fullName>Entertainment and Media</fullName>
            </value>
            <value>
                <fullName>Environmental and Waste Management</fullName>
            </value>
            <value>
                <fullName>Food and Beverage</fullName>
            </value>
            <value>
                <fullName>Healthcare and Pharmaceuticals</fullName>
            </value>
            <value>
                <fullName>Hospitality and Tourism</fullName>
            </value>
            <value>
                <fullName>Human Resources</fullName>
            </value>
            <value>
                <fullName>Information Technology (IT)</fullName>
            </value>
            <value>
                <fullName>Legal Services</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Marketing and Advertising</fullName>
            </value>
            <value>
                <fullName>Nonprofit</fullName>
            </value>
            <value>
                <fullName>Retail and E-commerce</fullName>
            </value>
            <value>
                <fullName>Retail Banking</fullName>
            </value>
            <value>
                <fullName>Security Services</fullName>
            </value>
            <value>
                <fullName>Social Services</fullName>
            </value>
            <value>
                <fullName>Sport and Fitness</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
            <value>
                <fullName>Transportation, Logistics and Mobility</fullName>
            </value>
            <value>
                <fullName>WealthTech</fullName>
                <isActive>false</isActive>
                <label>WealthTech</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ventures - Pre-Seed</fullName>
            </value>
            <value>
                <fullName>Ventures - Seed</fullName>
            </value>
            <value>
                <fullName>Ventures - Series A</fullName>
            </value>
            <value>
                <fullName>Ventures - Series B</fullName>
            </value>
            <value>
                <fullName>Ventures - Series C</fullName>
            </value>
            <value>
                <fullName>Ventures - Bridging Round</fullName>
            </value>
            <value>
                <fullName>Ventures - Pre-IPO</fullName>
            </value>
            <value>
                <fullName>Ventures - IPO</fullName>
            </value>
            <value>
                <fullName>Property - Equity</fullName>
            </value>
            <value>
                <fullName>Property - Preference Equity</fullName>
            </value>
            <value>
                <fullName>Property - Debt</fullName>
            </value>
            <value>
                <fullName>Fund - Multi Stage as per IM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Tile_Banner__c.field-meta.xml
<CustomField>
    <fullName>Tile_Banner__c</fullName>
    <label>Tile Banner</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Tile_Heading__c.field-meta.xml
<CustomField>
    <fullName>Tile_Heading__c</fullName>
    <label>Tile Heading</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Tile_Offer_Type__c.field-meta.xml
<CustomField>
    <fullName>Tile_Offer_Type__c</fullName>
    <label>Tile Offer Type</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VC Product</fullName>
            </value>
            <value>
                <fullName>Property Product</fullName>
            </value>
            <value>
                <fullName>CSF Product</fullName>
            </value>
            <value>
                <fullName>CSF Nominee</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>PSP Product</fullName>
            </value>
            <value>
                <fullName>Retail IPO</fullName>
            </value>
            <value>
                <fullName>Retail MIS</fullName>
            </value>
            <value>
                <fullName>Vest</fullName>
            </value>
            <value>
                <fullName>CIF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Product2/fields/yielding__c.field-meta.xml
<CustomField>
    <fullName>yielding__c</fullName>
    <inlineHelpText>Select the view that is most appropriate for the type of product</inlineHelpText>
    <label>Yielding</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Capitalised</fullName>
            </value>
            <value>
                <fullName>Compounding</fullName>
            </value>
            <value>
                <fullName>Distributions owing</fullName>
            </value>
            <value>
                <fullName>No distributions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Raise__c/Raise__c.object-meta.xml
<CustomObject>
    <description>The raise object accountable for keeping track of a Founder&apos;s raise process.</description>
    <label>Raise</label>
    <nameField>
        <label>Raise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Raise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Raise__c/fields/Publish_on_Community_Site__c.field-meta.xml
<CustomField>
    <fullName>Publish_on_Community_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will be automatically checked once the Tile Banner field is populated and the Status is set to &quot;Live in VC Website&quot;</description>
    <inlineHelpText>This field will be automatically checked once the Tile Banner field is populated and the Status is set to &quot;Live in VC Website&quot;</inlineHelpText>
    <label>Publish on Community Site</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Tile_Banner__c.field-meta.xml
<CustomField>
    <fullName>Tile_Banner__c</fullName>
    <description>This tile banner will be used to be displayed in the Website.
This tile banner URL will also be synched up with the Product Tile Banner Field.</description>
    <inlineHelpText>This tile banner will be used to be displayed in the Website, please create and update the URL in this field for the Tile Banner.</inlineHelpText>
    <label>Tile Banner</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/classes/Product_V2_Factory.cls
public class Product_V2_Factory implements IProduct_V2_Factory {
    
    /**
     * Retrieves a list of product records that are marked for publishing on the community site.
     *
     * @return List<Product2> - A list of Product2 records.
     * @throws AuraHandledException if no products are found or if an error occurs during retrieval.
     */
    public List<Product2> getProductOfferInformation() {
        try {
            // Query to retrieve the relevant product records
            List<Product2> productsRecord = [
                SELECT Portal_Display_Name__c, Tile_Heading__c, Deal_Description__c, Tile_Offer_Type__c, Tile_Banner__c, 
                Family, Deal_Page_Link__c, Raise__c FROM Product2 

                WHERE Publish_on_Community_Site__c = True AND IsActive = True AND Private_Deal__c = False AND Banner_Date_Validation__c = True
                ORDER BY CreatedDate DESC 
            ];
    
            // Check if the query returned any records
            if (productsRecord.isEmpty()) {
                // Log a message indicating no records were found
                Logger.logMessage('ProductApp', 'Product_V2_Factory', 'getProductOfferInformation', 'No product records found');
                
                // Throw an exception indicating no products are available
                throw new AuraHandledException('No products found for publication on the community site.');
            } else {
                // Log a success message indicating records were retrieved
                Logger.logMessage('ProductApp', 'Product_V2_Factory', 'getProductOfferInformation', 'Successfully retrieved product records.');
                
                // Return the list of product records
                return productsRecord;
            }
        } catch (Exception e) {
            // Log an error message with details of the exception
            Logger.logError('ProductApp', 'Product_V2_Factory', 'getProductOfferInformation', null, null, null, null, e, 'Failed to retrieve product records.');
            
            // Throw an AuraHandledException with the original exception message for the caller to handle
            throw new AuraHandledException('An error occurred while retrieving product records: ' + e.getMessage());   
        }
    }

    public Product2 getProductInformation(Id productId) {
        try {
            // Query to retrieve the relevant product records
            Product2 productsRecord = [SELECT Name, Stage__c, Sector__c, DisplayUrl,Portal_Display_Name__c, yielding__c, Distribution_Type__c, Family FROM Product2 WHERE Id =: productId LIMIT 1];
            return productsRecord;
        } catch (Exception e) {
            // Log an error message with details of the exception
            Logger.logError('ProductApp', 'Product_V2_Factory', 'getProductOfferInformation', null, null, null, null, e, 'Failed to retrieve product records.' + productId);
            
            // Throw an AuraHandledException with the original exception message for the caller to handle
            throw new AuraHandledException('An error occurred while retrieving product records: ' + e.getMessage());   
        }

    }
    
    public List<Product2> getProductByType(String productTypeName, String productRTName){
        
        String query = 'SELECT Id, Name, Portal_Display_Name__c, ProductCode FROM Product2 WHERE Publish_on_Community_Site__c = True AND IsActive = True AND Fully_Funded__c = FALSE AND Private_Deal__c = False';
        
        if(!String.isEmpty(productTypeName)){

            query += ' AND Type__c = :productTypeName';
        }

        try{
            if(!String.isEmpty(productRTName)){
                String productRT = Schema.SObjectType.Product2.getRecordTypeInfosByName().get(productRTName).getRecordTypeId();
                if(!String.isEmpty(productRT)){
                    query += ' AND RecordTypeId = :productRT';
                }
            }
        }catch(Exception e){
            System.debug('Error retrieiving Record Type');
        }
        

        List<sObject> returnList = Database.query(query);

        return returnList;
    }
    

    public PricebookEntry getProductPriceBook(Id productId) {
        PricebookEntry priceBookRecord = [SELECT UnitPrice, Name FROM PricebookEntry WHERE Product2Id =:productId];
        return priceBookRecord;
    }

}