common/force-app/main/default/objects/Product2/fields/Button_Text__c.field-meta.xml
<CustomField>
    <fullName>Button_Text__c</fullName>
    <label>Button Text</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Deal_Page_Link__c.field-meta.xml
<CustomField>
    <fullName>Deal_Page_Link__c</fullName>
    <label>Deal Page Link</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/FAQ_s__c.field-meta.xml
<CustomField>
    <fullName>FAQ_s__c</fullName>
    <label>FAQ&apos;s</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Fully_Funded__c.field-meta.xml
<CustomField>
    <fullName>Fully_Funded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fully Funded</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/IM_PDS__c.field-meta.xml
<CustomField>
    <fullName>IM_PDS__c</fullName>
    <description>Link to approved/Final document only</description>
    <label>IM/PDS</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Offer_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Offer_Close_Date__c</fullName>
    <inlineHelpText>The target date for capital raise to be complete</inlineHelpText>
    <label>Offer Close Date</label>
    <type>DateTime</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Offer_Launch_Date__c.field-meta.xml
<CustomField>
    <fullName>Offer_Launch_Date__c</fullName>
    <description>The date that Capital Raising launched the offer to market</description>
    <label>Offer Launch Date</label>
    <type>DateTime</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Private_Deal__c.field-meta.xml
<CustomField>
    <fullName>Private_Deal__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box for private deals that are not to be publicly published on the community site but are visible by invite to the URL.</inlineHelpText>
    <label>Private Deal</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Publish_on_Community_Site__c.field-meta.xml
<CustomField>
    <fullName>Publish_on_Community_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publish on Community Site</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Return_Type__c.field-meta.xml
<CustomField>
    <fullName>Return_Type__c</fullName>
    <label>Return Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Per Annum</fullName>
            </value>
            <value>
                <fullName>Fixed Return</fullName>
            </value>
            <value>
                <fullName>Variable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Sector_Personas__c.field-meta.xml
<CustomField>
    <fullName>Sector_Personas__c</fullName>
    <description>The personas that this product is suitable for</description>
    <label>Sector/Personas</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Just Launchers</fullName>
            </value>
            <value>
                <fullName>Sharp Shooters</fullName>
            </value>
            <value>
                <fullName>Prosperity Builders</fullName>
            </value>
            <value>
                <fullName>Grand Designers</fullName>
            </value>
            <value>
                <fullName>Wholesale/Sophisticated Investors</fullName>
            </value>
            <value>
                <fullName>Retail Investors</fullName>
            </value>
            <value>
                <fullName>Property Investors</fullName>
            </value>
            <value>
                <fullName>ARE Auckland Real Estate Management - property and Asset managers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Tile_Banner__c.field-meta.xml
<CustomField>
    <fullName>Tile_Banner__c</fullName>
    <label>Tile Banner</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Tile_Heading__c.field-meta.xml
<CustomField>
    <fullName>Tile_Heading__c</fullName>
    <label>Tile Heading</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Tile_Offer_Type__c.field-meta.xml
<CustomField>
    <fullName>Tile_Offer_Type__c</fullName>
    <label>Tile Offer Type</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Trust_Deed_Link__c.field-meta.xml
<CustomField>
    <fullName>Trust_Deed_Link__c</fullName>
    <label>Trust Deed Link</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/classes/SuggestedInvestmentControllerTest.cls
@isTest
public class SuggestedInvestmentControllerTest {
    @isTest
    public static void testGetRecentInvestments(){
        product2 prod = new product2();
        prod.Name = 'Test Prod';
        prod.IM_PDS__c = 'https://test.salesforce.com';
        prod.DisplayUrl = 'https://www.venturecrowd.com.au';
        prod.Deal_Page_Link__c = 'https://www.venturecrowd.com.au';
        prod.Trust_Deed_Link__c = 'https://www.venturecrowd.com.au';
        prod.Sector_Personas__c = 'Just Launchers';
        prod.ProductCode = 'AURT';
        prod.FAQ_s__c = 'Test FAQ';
        prod.Fully_Funded__c = true;
        prod.Return_Type__c = 'Per Annum';
        prod.Tile_Banner__c = 'https://www.venturecrowd.com.au';
        prod.Tile_Heading__c = 'Test heading';
        prod.Tile_Offer_Type__c = 'Investment';
        prod.Button_Text__c = 'View Offer';
        prod.IsActive = true;
        prod.Private_Deal__c = false;
        prod.Publish_on_Community_Site__c = TRUE;
        prod.Offer_Launch_Date__c = system.now();
        prod.Offer_Close_Date__c = system.now();
        database.insert(prod,false);
        //Database.SaveResult prodINs = 
        //System.assertEquals(True, prodINs.isSuccess());
            Test.startTest();
            	String suggestedInvetsment = SuggestedInvestmentController.getRecentInvestments();
        		system.assertEquals(suggestedInvetsment != null,true);
            Test.stopTest();
    }

}