common/force-app/main/default/objects/Product2/fields/Deal_Description__c.field-meta.xml
<CustomField>
    <fullName>Deal_Description__c</fullName>
    <label>Deal Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Minimum_Investment__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Investment__c</fullName>
    <label>Minimum Investment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Offer_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Offer_Close_Date__c</fullName>
    <inlineHelpText>The target date for capital raise to be complete</inlineHelpText>
    <label>Offer Close Date</label>
    <type>DateTime</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Offer_Launch_Date__c.field-meta.xml
<CustomField>
    <fullName>Offer_Launch_Date__c</fullName>
    <description>The date that Capital Raising launched the offer to market</description>
    <label>Offer Launch Date</label>
    <type>DateTime</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Portal_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Portal_Display_Name__c</fullName>
    <label>Portal Display Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ventures - Pre-Seed</fullName>
            </value>
            <value>
                <fullName>Ventures - Seed</fullName>
            </value>
            <value>
                <fullName>Ventures - Series A</fullName>
            </value>
            <value>
                <fullName>Ventures - Series B</fullName>
            </value>
            <value>
                <fullName>Ventures - Series C</fullName>
            </value>
            <value>
                <fullName>Ventures - Bridging Round</fullName>
            </value>
            <value>
                <fullName>Ventures - Pre-IPO</fullName>
            </value>
            <value>
                <fullName>Ventures - IPO</fullName>
            </value>
            <value>
                <fullName>Property - Equity</fullName>
            </value>
            <value>
                <fullName>Property - Preference Equity</fullName>
            </value>
            <value>
                <fullName>Property - Debt</fullName>
            </value>
            <value>
                <fullName>Fund - Multi Stage as per IM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Target_Amount__c.field-meta.xml
<CustomField>
    <fullName>Target_Amount__c</fullName>
    <label>Target Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Temp_Total_Opp_Amount__c.field-meta.xml
<CustomField>
    <fullName>Temp_Total_Opp_Amount__c</fullName>
    <label>Temp Total Opp Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/classes/tempProductService.cls
public without sharing class tempProductService {
    public String getProductDetails(String productId){
        try{
            tempProductFactory factory = New tempProductFactory();
            Product2 productRecord = factory.getProductDetails(productId);
            if(productRecord != null){            
                productData productData = new productData();
                productData.id = productRecord.Id;
                productData.launchDate = productRecord.Offer_Launch_Date__c;
                productData.amountRaised = productRecord.Temp_Total_Opp_Amount__c;
                productData.offerCloseDate = productRecord.Offer_Close_Date__c;
                productData.companyName = productRecord.Portal_Display_Name__c;
                productData.companyOneLiner = productRecord.Deal_Description__c;
                productData.stage = productRecord.Stage__c;
                productData.minInvestAmount = productRecord.Minimum_Investment__c;
                productData.targetAmt = productRecord.Target_Amount__c;

                Logger.logMessage('ProductApp', 'tempProductService', 'getProductDetails', 'Successfully retrieved product details for productId: ' + productId);
                return JSON.serialize(productData);
            }else {
                throw new AuraHandledException('No product record found for the given ID.');
            }
        }catch(Exception e){
            Logger.logError('ProductApp', 'tempProductService', 'getProductDetails', productId, null, null, null, e, 'Failed to get product details for productId: ' + productId);
            throw new AuraHandledException('An unexpected error occurred: ' + e.getMessage());

        }
    }

    public class productData{
        String Id;
        Datetime launchDate;
        Decimal amountRaised;
        Datetime offerCloseDate;
        String companyOneLiner;
        String companyName;
        String stage;
        Decimal targetAmt;
        Decimal minInvestAmount;
    }
}