common/force-app/main/default/objects/Product2/fields/Deal_Description__c.field-meta.xml
<CustomField>
    <fullName>Deal_Description__c</fullName>
    <label>Deal Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Minimum_Investment__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Investment__c</fullName>
    <label>Minimum Investment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Offer_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Offer_Close_Date__c</fullName>
    <inlineHelpText>The target date for capital raise to be complete</inlineHelpText>
    <label>Offer Close Date</label>
    <type>DateTime</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Offer_Launch_Date__c.field-meta.xml
<CustomField>
    <fullName>Offer_Launch_Date__c</fullName>
    <description>The date that Capital Raising launched the offer to market</description>
    <label>Offer Launch Date</label>
    <type>DateTime</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Portal_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Portal_Display_Name__c</fullName>
    <label>Portal Display Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ventures - Pre-Seed</fullName>
            </value>
            <value>
                <fullName>Ventures - Seed</fullName>
            </value>
            <value>
                <fullName>Ventures - Series A</fullName>
            </value>
            <value>
                <fullName>Ventures - Series B</fullName>
            </value>
            <value>
                <fullName>Ventures - Series C</fullName>
            </value>
            <value>
                <fullName>Ventures - Bridging Round</fullName>
            </value>
            <value>
                <fullName>Ventures - Pre-IPO</fullName>
            </value>
            <value>
                <fullName>Ventures - IPO</fullName>
            </value>
            <value>
                <fullName>Property - Equity</fullName>
            </value>
            <value>
                <fullName>Property - Preference Equity</fullName>
            </value>
            <value>
                <fullName>Property - Debt</fullName>
            </value>
            <value>
                <fullName>Fund - Multi Stage as per IM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Target_Amount__c.field-meta.xml
<CustomField>
    <fullName>Target_Amount__c</fullName>
    <label>Target Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Temp_Total_Opp_Amount__c.field-meta.xml
<CustomField>
    <fullName>Temp_Total_Opp_Amount__c</fullName>
    <label>Temp Total Opp Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/classes/tempProductFactory.cls
public class tempProductFactory {
    public Product2 getProductDetails(Id productId) {
        try {
            Product2 productRecord = [SELECT Id, Offer_Launch_Date__c, Temp_Total_Opp_Amount__c, Target_Amount__c,
            Offer_Close_Date__c, Portal_Display_Name__c, Stage__c, Minimum_Investment__c,Deal_Description__c
            FROM Product2
            WHERE Id = :productId];
    
            if (productRecord != null) {
                Logger.logMessage('ProductApp', 'tempProductFactory', 'getProductDetails', 'Successfully retrieved full product record for productId: ' + productId);
                return productRecord;
            } else {
                Logger.logMessage('ProductApp', 'tempProductFactory', 'getProductDetails', 'No raise record found for productId: ' + productId);
                throw new AuraHandledException('No product record found for product: ' + productId);
            }
        } catch (Exception e) {
            Logger.logError('ProductApp', 'tempProductFactory', 'getProductDetails', productId, null, null, null, e, 'Failed to get full raise record for raiseId: ' + productId);
            throw new AuraHandledException(e.getMessage());   
        }
    }
}