common/force-app/main/default/objects/Product2/fields/Fixed_Returns__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Returns__c</fullName>
    <label>Fixed Returns</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

common/force-app/main/default/objects/ROI_Log__c/ROI_Log__c.object-meta.xml
<CustomObject>
    <label>ROI Log</label>
    <nameField>
        <displayFormat>ROI-{0000}</displayFormat>
        <label>ROI Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ROI Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/ROI_Log__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>ROI Log</relationshipLabel>
    <relationshipName>ROI_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/ROI_Log__c/fields/Returns_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Returns_Percentage__c</fullName>
    <label>Returns Percentage</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/ROI_Log__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

common/force-app/main/default/classes/prodTriggerHandler.cls
public without sharing class prodTriggerHandler {
    public static void handleROIlogs(){
        Map<Id,Decimal> prodIdVSfixedreturndmap = new Map<Id,Decimal>();
        for(Product2 p : (List<Product2>)Trigger.new){
            if((Trigger.old == NULL && p.Fixed_Returns__c <> NULL) || (Trigger.old <> NULL && isfieldchanged(Trigger.oldmap.get(p.Id),p,'Fixed_Returns__c'))){
                prodIdVSfixedreturndmap.put(p.Id,p.Fixed_Returns__c);
            }
        }
        List<ROI_Log__c> loglst = new List<ROI_Log__c>();
        for(Product2 p : [SELECT Id,Fixed_Returns__c, (SELECT Id,Active__c,Start_Date__c,End_Date__c,Name FROM ROI_Log__r ORDER BY Name DESC) FROM Product2 WHERE ID IN :prodIdVSfixedreturndmap.keyset()]){
            if(p.ROI_Log__r.isEmpty()){
                ROI_Log__c log1 = new ROI_Log__c();
                log1.Start_Date__c = System.Now();
                log1.Active__c = true;
                log1.Product__c = p.Id;
                log1.Returns_Percentage__c = p.Fixed_Returns__c;
                loglst.add(log1);
            }else{
                ROI_Log__c log2 = p.ROI_Log__r[0];
                log2.Active__c = false;
                log2.End_Date__c = System.Now();
                loglst.add(log2);

                ROI_Log__c log1 = new ROI_Log__c();
                log1.Start_Date__c = System.Now();
                log1.Active__c = true;
                log1.Product__c = p.Id;
                log1.Returns_Percentage__c = p.Fixed_Returns__c;
                loglst.add(log1);
            }
        }
        upsert loglst;
    }
    public static Boolean isfieldchanged(Sobject oldrecord, Sobject newrecord, string field){
        return oldrecord.get(field) <> newrecord.get(field);
    }
}