common/force-app/main/default/objects/Site_Nav_Bar__c/Site_Nav_Bar__c.object-meta.xml
<CustomObject>
    <label>Site Nav Bar</label>
    <nameField>
        <displayFormat>SNV-{0000}</displayFormat>
        <label>Site Nav Bar Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Nav Bar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Site_Nav_Bar__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <label>Display Name</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Site_Nav_Bar__c/fields/Display_Order__c.field-meta.xml
<CustomField>
    <fullName>Display_Order__c</fullName>
    <label>Display Order</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/Site_Nav_Bar__c/fields/Display_URL__c.field-meta.xml
<CustomField>
    <fullName>Display_URL__c</fullName>
    <label>Display URL</label>
    <length>225</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Site_Nav_Bar__c/fields/Sub_Header__c.field-meta.xml
<CustomField>
    <fullName>Sub_Header__c</fullName>
    <label>Sub-Header</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INVEST</fullName>
            </value>
            <value>
                <fullName>VENTURES</fullName>
            </value>
            <value>
                <fullName>LEARN</fullName>
            </value>
            <value>
                <fullName>RAISE</fullName>
            </value>
            <value>
                <fullName>PROPERTY</fullName>
            </value>
            <value>
                <fullName>ABOUT</fullName>
            </value>
            <value>
                <fullName>NEWS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Site_Nav_Bar__c/fields/Valid_From__c.field-meta.xml
<CustomField>
    <fullName>Valid_From__c</fullName>
    <label>Valid From</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

common/force-app/main/default/objects/Site_Nav_Bar__c/fields/Valid_To__c.field-meta.xml
<CustomField>
    <fullName>Valid_To__c</fullName>
    <label>Valid To</label>
    <type>DateTime</type>
</CustomField>

common/force-app/main/default/classes/CommunityUserDetailControllerTest.cls
@isTest
public class CommunityUserDetailControllerTest {
    
    @isTest
    public static void testGetCurrentUser(){
        Test.startTest();
        CommunityUserDetailController.getCurrentUser();
        Test.stopTest();
        System.assert( CommunityUserDetailController.getCurrentUser() != null);
    }
    
    @isTest
    public static void testGetheaders(){
        Site_Nav_Bar__c testSNV = new Site_Nav_Bar__c();
        testSNV.Sub_Header__c = 'VENTURES';
        testSNV.Display_Order__c = 1;
        testSNV.Display_Name__c = 'Test Display Name';
        testSNV.Display_URL__c = 'testClass.comapex';
        testSNV.Valid_From__c = System.now();
        testSNV.Valid_To__c = System.now() + 1;
        
        INSERT testSNV;
        
        Test.startTest();
        CommunityUserDetailController.getheaders();
        Test.stopTest();
        
        Site_Nav_Bar__c assertSNV = [SELECT Id, Sub_Header__c FROM Site_Nav_Bar__c WHERE Sub_Header__c = 'VENTURES'];
        System.assert(assertSNV != NULL);
        
    }
}