common/force-app/main/default/objects/Site_Nav_Bar__c/Site_Nav_Bar__c.object-meta.xml
<CustomObject>
    <label>Site Nav Bar</label>
    <nameField>
        <displayFormat>SNV-{0000}</displayFormat>
        <label>Site Nav Bar Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Nav Bar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Site_Nav_Bar__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF( ISNULL(Valid_To__c ) , (Valid_From__c &lt;=  NOW()), (Valid_From__c &lt;=  NOW()) &amp;&amp; ( Valid_To__c &gt;= NOW()))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Site_Nav_Bar__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <label>Display Name</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Site_Nav_Bar__c/fields/Display_Order__c.field-meta.xml
<CustomField>
    <fullName>Display_Order__c</fullName>
    <label>Display Order</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/Site_Nav_Bar__c/fields/Display_URL__c.field-meta.xml
<CustomField>
    <fullName>Display_URL__c</fullName>
    <label>Display URL</label>
    <length>225</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Site_Nav_Bar__c/fields/Sub_Header__c.field-meta.xml
<CustomField>
    <fullName>Sub_Header__c</fullName>
    <label>Sub-Header</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INVEST</fullName>
            </value>
            <value>
                <fullName>VENTURES</fullName>
            </value>
            <value>
                <fullName>LEARN</fullName>
            </value>
            <value>
                <fullName>RAISE</fullName>
            </value>
            <value>
                <fullName>PROPERTY</fullName>
            </value>
            <value>
                <fullName>ABOUT</fullName>
            </value>
            <value>
                <fullName>NEWS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/classes/CommunityUserDetailController.cls
public without sharing class CommunityUserDetailController {
	// *******************   Community user detail *************** 
	@AuraEnabled(cacheable=true)
	public static List<User> getCurrentUser(){
        List<User> users=new List<User>();
        if(UserInfo.getUserType()!='Guest'){
            users=  [SELECT Id, Name, profile.Name,SmallPhotourl,FullPhotoUrl FROM User WHERE Id =: Userinfo.getUserId()];   
        }
        return users;
	
   }
   @AuraEnabled
   public static Map<string,List<navheader>> getheaders(){
        Map<string,List<navheader>> retMap = new Map<string,List<navheader>>();
        for(Site_Nav_Bar__c snv : [SELECT Id, Sub_Header__c,  Display_Order__c, Display_Name__c, Display_URL__c, Active__c FROM Site_Nav_Bar__c WHERE Active__c = TRUE ORDER BY Sub_Header__c,Display_Order__c ASC]){
            if(!retMap.keyset().contains(snv.Sub_Header__c))
            retMap.put(snv.Sub_Header__c, new List<navheader>());
            retMap.get(snv.Sub_Header__c).add(new navheader(snv));
        }
        return retMap;
   }
   public class navheader{
       @AuraEnabled public string displayName {get;set;}
       @AuraEnabled public string displayUrl {get;set;}
       public navheader(Site_Nav_Bar__c sitenavbar){
           if(Site.getSiteType() == 'ChatterNetworkPicasso'){
                displayName = sitenavbar.Display_Name__c;
        		displayUrl = sitenavbar.Display_URL__c;
            }else{
                displayName = sitenavbar.Display_Name__c;
        		displayUrl = System.Label.Community_URL + sitenavbar.Display_URL__c;
            }
        
       }
   }
}