common/force-app/main/default/objects/Site_Nav_Bar__c/Site_Nav_Bar__c.object-meta.xml
<CustomObject>
    <label>Site Nav Bar</label>
    <nameField>
        <displayFormat>SNV-{0000}</displayFormat>
        <label>Site Nav Bar Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Nav Bar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Site_Nav_Bar__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF( ISNULL(Valid_To__c ) , (Valid_From__c &lt;=  NOW()), (Valid_From__c &lt;=  NOW()) &amp;&amp; ( Valid_To__c &gt;= NOW()))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Site_Nav_Bar__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <label>Display Name</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Site_Nav_Bar__c/fields/Display_Order__c.field-meta.xml
<CustomField>
    <fullName>Display_Order__c</fullName>
    <label>Display Order</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/Site_Nav_Bar__c/fields/Display_URL__c.field-meta.xml
<CustomField>
    <fullName>Display_URL__c</fullName>
    <label>Display URL</label>
    <length>225</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Site_Nav_Bar__c/fields/Sub_Header__c.field-meta.xml
<CustomField>
    <fullName>Sub_Header__c</fullName>
    <label>Sub-Header</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INVEST</fullName>
            </value>
            <value>
                <fullName>VENTURES</fullName>
            </value>
            <value>
                <fullName>LEARN</fullName>
            </value>
            <value>
                <fullName>RAISE</fullName>
            </value>
            <value>
                <fullName>PROPERTY</fullName>
            </value>
            <value>
                <fullName>ABOUT</fullName>
            </value>
            <value>
                <fullName>NEWS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Site_Nav_Bar__c/fields/Valid_From__c.field-meta.xml
<CustomField>
    <fullName>Valid_From__c</fullName>
    <label>Valid From</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

common/force-app/main/default/classes/VC_CF_MenuCOntrollerTest.cls
@isTest
public class VC_CF_MenuCOntrollerTest {
	@isTest
    public static void testnavigate(){
        VC_CF_MenuCOntroller ctrl=new VC_CF_MenuCOntroller();
        PageReference pageRef = Page.VC_CF_Home;
        Test.setCurrentPage(pageRef);
        Apexpages.currentPage().getParameters().put('navigateurl',System.Label.Investor_Community_URL+'/vc-cf-home/vc-cf-invest');
        PageReference newpage=  ctrl.navigateToPage();
        System.assertEquals(System.Label.Investor_Community_URL+'/vc-cf-home/vc-cf-invest', newpage.getUrl());        
    }
    @isTest
    public static void navbarTest(){
        Site_Nav_Bar__c s = new Site_Nav_Bar__c();
        s.Display_Name__c = 'test';
        s.Display_URL__c = 'test';
        s.Sub_Header__c = 'INVEST';
        s.Valid_From__c = system.now().adddays(-1);
        s.Display_Order__c = 1;
        insert s;
        system.debug([SELECT Id, Sub_Header__c,  Display_Order__c, Display_Name__c, Display_URL__c, Active__c FROM Site_Nav_Bar__c WHERE Active__c = TRUE ORDER BY Sub_Header__c,Display_Order__c ASC]);
        VC_CF_MenuCOntroller ctrl=new VC_CF_MenuCOntroller();
    }
}