common/force-app/main/default/objects/Lead/fields/Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason__c</fullName>
    <label>Lost Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Another real estate agent</fullName>
            </value>
            <value>
                <fullName>Awaiting other Development Results</fullName>
            </value>
            <value>
                <fullName>Bought another property</fullName>
            </value>
            <value>
                <fullName>Buyer&apos;s agent</fullName>
            </value>
            <value>
                <fullName>Can&apos;t decide</fullName>
            </value>
            <value>
                <fullName>Cancelled Before Appointment</fullName>
            </value>
            <value>
                <fullName>Claims they never clicked</fullName>
            </value>
            <value>
                <fullName>Claim they did not book</fullName>
            </value>
            <value>
                <fullName>CM-Dasp-Advisor</fullName>
            </value>
            <value>
                <fullName>CM-Dasp-Didn&apos;t like the project</fullName>
            </value>
            <value>
                <fullName>CM-Dasp-No Trust - does not understand the model</fullName>
            </value>
            <value>
                <fullName>CM-Dasp-Other</fullName>
            </value>
            <value>
                <fullName>CM-Dasp-Personal reasons.</fullName>
            </value>
            <value>
                <fullName>CM-Wasp-Location based</fullName>
            </value>
            <value>
                <fullName>CM-Wasp-No Trust - does not understand the model</fullName>
            </value>
            <value>
                <fullName>CM-Wasp-time waster</fullName>
            </value>
            <value>
                <fullName>CM-wasp-Timing not quite right -but still interested.</fullName>
            </value>
            <value>
                <fullName>Couldn&apos;t get finance</fullName>
            </value>
            <value>
                <fullName>Dasp Lost Tags</fullName>
            </value>
            <value>
                <fullName>Does Not Qualify</fullName>
            </value>
            <value>
                <fullName>Don&apos;t have enough in SMSF</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Founder looking to raise capital</fullName>
            </value>
            <value>
                <fullName>Invested Elsewhere</fullName>
            </value>
            <value>
                <fullName>Just looking</fullName>
            </value>
            <value>
                <fullName>Lots too small</fullName>
            </value>
            <value>
                <fullName>Multiple Offer on Lot</fullName>
            </value>
            <value>
                <fullName>Multiple opportunities</fullName>
            </value>
            <value>
                <fullName>No Deposit</fullName>
            </value>
            <value>
                <fullName>No funds</fullName>
            </value>
            <value>
                <fullName>No Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Lead/fields/Products_Interested_In__c.field-meta.xml
<CustomField>
    <fullName>Products_Interested_In__c</fullName>
    <label>Products Interested In</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First_Mortgage</fullName>
                <label>First Mortgage</label>
            </value>
            <value>
                <fullName>Investing</fullName>
            </value>
            <value>
                <fullName>Listing a Property</fullName>
            </value>
            <value>
                <fullName>Private Syndicate Platform (PSP)</fullName>
            </value>
            <value>
                <fullName>Property Equity</fullName>
            </value>
            <value>
                <fullName>Property Sales</fullName>
            </value>
            <value>
                <fullName>Raising Capital</fullName>
            </value>
            <value>
                <fullName>Startups</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>GP</fullName>
                <isActive>false</isActive>
                <label>GP</label>
            </value>
            <value>
                <fullName>H</fullName>
                <isActive>false</isActive>
                <label>H</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Lead/recordTypes/VC.recordType-meta.xml
<RecordType>
    <fullName>VC</fullName>
    <active>true</active>
    <businessProcess>VC</businessProcess>
    <label>VC</label>
</RecordType>

common/force-app/main/default/objects/Lead/recordTypes/VCPP.recordType-meta.xml
<RecordType>
    <fullName>VCPP</fullName>
    <active>true</active>
    <businessProcess>VC</businessProcess>
    <label>VCPP</label>
</RecordType>

common/force-app/main/default/classes/LeadTriggerHandlerTest.cls
@isTest
public class LeadTriggerHandlerTest 
{
    static testMethod void deleteLeadTestMethod3() 
    {
        List<lead> leadList = new List<lead>();
        Lead leadObj = new Lead();
        leadObj.lastname = 'Test1lname';
        leadObj.email = 'testemail1@yopmail.com';
        leadObj.MobilePhone = '6786789876';
        leadObj.Status = 'New';
        leadObj.Products_Interested_In__c = 'Investing';
        leadObj.LeadSource = 'Partner';
        leadObj.Loss_Reason__c = 'No Trust';
        leadObj.Is_Duplicate__c = True;

        leadList.add(leadObj);
		insert leadList;        

        update leadlist;
        Test.startTest();
        LeadTriggerHandler.deleteLead(leadList);
        LeadTriggerHandler.deleteLead2(leadList);
        LeadTriggerHandler.deleteLead3(leadList);
        LeadTriggerHandler.roundRobinOnOpportunity(leadList, leadList);
        
        Test.stopTest();
    }
    static testMethod void leadReEnquiryTestMethod1() 
    {
        Account acc = new Account();
        acc.lastname = 'Test1lname';
        acc.RecordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('VC Person Account').getRecordTypeId();

        acc.Phone = '6786789876';
        //insert acc;
        
        Contact con = new Contact();
        con.LastName  = 'Test1lname';
        con.MobilePhone = '6786789876';
        con.email = 'testemail1@yopmail.com1';
        insert con;

        List<lead> leadList = new List<lead>();
        Lead leadObj = new Lead();
        leadObj.lastname = 'Test1lname';
        leadObj.email = 'testemail1@yopmail.com';
        leadObj.MobilePhone = '6786789876';
        leadObj.Status = 'New';
        leadObj.Products_Interested_In__c = 'Investing';
        leadObj.LeadSource = 'Partner';
        leadObj.Loss_Reason__c = 'No Trust';

        leadList.add(leadObj);
		insert leadList;        

        Test.startTest();
        // LeadTriggerHandler.leadReEnquiry(leadList);
        //LeadTriggerHandler.roundRobinOnOpportunity(newleadList, oldleadList);
        Test.stopTest();
    }
    static testMethod void leadReEnquiryTestMethod2() 
    {
        Account acc = new Account();
        acc.lastname = 'Test1lname';
        acc.Phone = '6786789876';
        acc.RecordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('VC Person Account').getRecordTypeId();
//        insert acc;
        
        Contact con = new Contact();
        con.LastName  = 'Test1lname';
        con.MobilePhone = '6786789876';
        con.email = 'testemail1@yopmail.com1';
        insert con;

        List<lead> leadList = new List<lead>();
        Lead leadObj = new Lead();
        leadObj.lastname = 'Test1lname';
        leadObj.email = 'testemail1@yopmail.com';
        leadObj.MobilePhone = '6786789876';
        leadObj.Status = 'New';
        leadObj.Products_Interested_In__c = 'Investing';
        leadObj.LeadSource = 'Partner';
        leadObj.Loss_Reason__c = 'No Trust';

        leadList.add(leadObj);
		insert leadList;        

        Test.startTest();
        // LeadTriggerHandler.leadReEnquiry(leadList);
        Test.stopTest();
    }
    static testMethod void beforetrigger(){
        Id VCPPRecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('VCPP').getRecordTypeId();
        Lead leadObj = new Lead();
        leadObj.lastname = 'Test1lnameufgufguhjfgj';
        leadObj.email = 'testemail1@yohgughugyhupmail.com';
        leadObj.MobilePhone = '6786789876';
        leadObj.Status = 'New';
        leadObj.Products_Interested_In__c = 'Investing';
        leadObj.LeadSource = 'Partner';
        leadObj.Loss_Reason__c = 'No Trust';
        leadObj.RecordTypeId = VCPPRecordTypeId;
        insert leadObj;
    }
    
}