common/force-app/main/default/objects/Lead/fields/Web_Source__c.field-meta.xml
<CustomField>
    <fullName>Web_Source__c</fullName>
    <label>Web Source</label>
    <type>TextArea</type>
</CustomField>

common/force-app/main/default/objects/Lead/recordTypes/VC.recordType-meta.xml
<RecordType>
    <fullName>VC</fullName>
    <active>true</active>
    <businessProcess>VC</businessProcess>
    <label>VC</label>
</RecordType>

common/force-app/main/default/objects/Opportunity/fields/Email_ID__c.field-meta.xml
<CustomField>
    <fullName>Email_ID__c</fullName>
    <description>this email id is passed from Symphony</description>
    <inlineHelpText>ADMIN FIELD. Passed from Symphony App</inlineHelpText>
    <label>Email ID</label>
    <type>Email</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/recordTypes/VC.recordType-meta.xml
<RecordType>
    <fullName>VC</fullName>
    <active>true</active>
    <businessProcess>VC</businessProcess>
    <label>VC</label>
</RecordType>

common/force-app/main/default/classes/TestConvertLeadHandler.cls
@isTest
public class TestConvertLeadHandler {
    Static testMethod void convertLeadTest()
    {	
        Account acct = new Account();
        acct.lastname = 'Testlname';
        acct.Phone = '123456789';
        acct.PersonEmail = 'Test@test.com';
        acct.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('VC Person Account').getRecordTypeId();
        insert acct;
        
        Lead leadObj = new Lead();
        leadObj.lastname = 'Testlname';
        leadObj.email = 'Test@test.com';
        leadObj.MobilePhone = '123456789';
        leadObj.Status = 'New';
        leadObj.LeadSource = 'VC Website Organic';
        leadObj.Web_Source__c ='ZEGA-CSF';
		insert leadObj;    
        
        List<Opportunity> oppList = new List<Opportunity>();
        Opportunity oppObj = new Opportunity();
        oppObj.name = 'Test1lname';
        oppObj.AccountId = acct.Id;
        oppObj.stageName = 'Application Received';
        oppObj.Web_Source__c = 'ZEGA-CSF';
        oppObj.LeadSource = 'VC Website Organic';
        oppObj.Email_ID__c = 'test@value.com';
        date dt = System.today();
        dt = dt.addDays(5);
		oppObj.CloseDate = dt;        
        oppList.add(oppObj);
        insert oppList; 
        
        test.startTest();
        ConvertLeadHandler.convertLead(oppList);
        test.stopTest();

    }
}