common/force-app/main/default/objects/EOI__c/EOI__c.object-meta.xml
<CustomObject>
    <description>This object will be used by Founders, this was part of the MVP project.</description>
    <label>EOI</label>
    <nameField>
        <label>EOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOI&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/EOI__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>This will link to the Ventures Company Account that is related to the EOI</description>
    <inlineHelpText>This field links to the Ventures Company Account that is related to this EOI</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EOI&apos;s</relationshipLabel>
    <relationshipName>EOI_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Company_Stage__c.field-meta.xml
<CustomField>
    <fullName>Company_Stage__c</fullName>
    <label>Company Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Seed</fullName>
            </value>
            <value>
                <fullName>Seed</fullName>
            </value>
            <value>
                <fullName>Series A</fullName>
            </value>
            <value>
                <fullName>Series B +</fullName>
            </value>
            <value>
                <fullName>Pre-IPO</fullName>
            </value>
            <value>
                <fullName>IPO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Company_Website_Link__c.field-meta.xml
<CustomField>
    <fullName>Company_Website_Link__c</fullName>
    <description>Formula field that brings the Account Website and sets it up as a Hyperlink</description>
    <formula>HYPERLINK(Account__r.Website, Account__r.Website)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Formula field that shows the Account Website.</inlineHelpText>
    <label>Company Website Link</label>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Differentiation__c.field-meta.xml
<CustomField>
    <fullName>Differentiation__c</fullName>
    <label>Differentiation</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/EOI_Progress__c.field-meta.xml
<CustomField>
    <fullName>EOI_Progress__c</fullName>
    <description>Formula to evaluate Progress % of the EOI</description>
    <formula>IF( Target_Raise_Amount__c &gt; 0,
MIN(( Value_of_investment_interest__c / Target_Raise_Amount__c ), 1),
0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Formula to evaluate Progress % of the EOI</inlineHelpText>
    <label>EOI Progress</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/EOI_Published_Date__c.field-meta.xml
<CustomField>
    <fullName>EOI_Published_Date__c</fullName>
    <label>EOI Published Date</label>
    <type>DateTime</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/EOI_Subtitle__c.field-meta.xml
<CustomField>
    <fullName>EOI_Subtitle__c</fullName>
    <description>EOI subtitle for the top of the EOI Preview Page</description>
    <inlineHelpText>EOI subtitle for the top of the EOI Preview Page</inlineHelpText>
    <label>EOI Subtitle</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/EOI_Title__c.field-meta.xml
<CustomField>
    <fullName>EOI_Title__c</fullName>
    <description>EOI Title</description>
    <label>EOI Title</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Facebook_link__c.field-meta.xml
<CustomField>
    <fullName>Facebook_link__c</fullName>
    <label>Facebook link</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Growth_plan__c.field-meta.xml
<CustomField>
    <fullName>Growth_plan__c</fullName>
    <description>Field name to be used in Experience Cloud for MVP. Also used by Apex Class MyEOIController, CRUD EOI, Visualforce page for Preview.</description>
    <inlineHelpText>Field name to be used in Experience Cloud for MVP. Also used by Apex Class MyEOIController, CRUD EOI, Visualforce page for Preview.</inlineHelpText>
    <label>Growth plan</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Instagram_link__c.field-meta.xml
<CustomField>
    <fullName>Instagram_link__c</fullName>
    <label>Instagram link</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Intellectual_Property__c.field-meta.xml
<CustomField>
    <fullName>Intellectual_Property__c</fullName>
    <description>Field name to be used in Experience Cloud for MVP. Also used by Apex Class MyEOIController, CRUD EOI, Visualforce page for Preview.</description>
    <inlineHelpText>Field name to be used in Experience Cloud for MVP. Also used by Apex Class MyEOIController, CRUD EOI, Visualforce page for Preview.</inlineHelpText>
    <label>Intellectual Property</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Leads_expressed_interest__c.field-meta.xml
<CustomField>
    <fullName>Leads_expressed_interest__c</fullName>
    <inlineHelpText>Number of Leads that have expressed interest. This is calculated after a new lead is added or deleted.</inlineHelpText>
    <label>Leads expressed interest</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Linkedin_link__c.field-meta.xml
<CustomField>
    <fullName>Linkedin_link__c</fullName>
    <label>Linkedin link</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Minimum_Investment_amount__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Investment_amount__c</fullName>
    <description>The minimum investment amount that an investor is allowed to express interest in</description>
    <inlineHelpText>The minimum investment amount that an is allowed to express interest in</inlineHelpText>
    <label>Minimum Investment amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Offer_Overview__c.field-meta.xml
<CustomField>
    <fullName>Offer_Overview__c</fullName>
    <description>Offer Overview field, based on the figma file from the MVP of Feb 2024</description>
    <inlineHelpText>Please provide a one-liner about the offer.</inlineHelpText>
    <label>Company Overview</label>
    <length>700</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/One_liner_about_business__c.field-meta.xml
<CustomField>
    <fullName>One_liner_about_business__c</fullName>
    <label>One liner about business</label>
    <type>TextArea</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Problem_or_opportunity__c.field-meta.xml
<CustomField>
    <fullName>Problem_or_opportunity__c</fullName>
    <description>Field name to be used in Experience Cloud for MVP. Also used by Apex Class MyEOIController, CRUD EOI, Visualforce page for Preview.</description>
    <inlineHelpText>Field name to be used in Experience Cloud for MVP. Also used by Apex Class MyEOIController, CRUD EOI, Visualforce page for Preview.</inlineHelpText>
    <label>Problem or opportunity</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Progress__c.field-meta.xml
<CustomField>
    <fullName>Progress__c</fullName>
    <description>Text area - Details the progress of the Company</description>
    <inlineHelpText>Detail Progress of the company.</inlineHelpText>
    <label>Progress</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Raise_Contact_email__c.field-meta.xml
<CustomField>
    <fullName>Raise_Contact_email__c</fullName>
    <label>Raise Contact email</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <description>Field name to be used in Experience Cloud for MVP. Also used by Apex Class MyEOIController, CRUD EOI, Visualforce page for Preview.</description>
    <inlineHelpText>Field name to be used in Experience Cloud for MVP. Also used by Apex Class MyEOIController, CRUD EOI, Visualforce page for Preview.</inlineHelpText>
    <label>Solution</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Target_Raise_Amount__c.field-meta.xml
<CustomField>
    <fullName>Target_Raise_Amount__c</fullName>
    <label>Target Raise Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Total_addressable_market__c.field-meta.xml
<CustomField>
    <fullName>Total_addressable_market__c</fullName>
    <description>Field name to be used in Experience Cloud for MVP. Also used by Apex Class MyEOIController, CRUD EOI, Visualforce page for Preview.</description>
    <inlineHelpText>Field name to be used in Experience Cloud for MVP. Also used by Apex Class MyEOIController, CRUD EOI, Visualforce page for Preview.</inlineHelpText>
    <label>Total addressable market</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Twitter_X_link__c.field-meta.xml
<CustomField>
    <fullName>Twitter_X_link__c</fullName>
    <label>Twitter/X link</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/URL_Files_Img__c.field-meta.xml
<CustomField>
    <fullName>URL_Files_Img__c</fullName>
    <description>This field stores a JSON file after a user click save on edit EOI. The Apex controller updating this is ContentDownloadURL</description>
    <inlineHelpText>This field stores a JSON file after a user click save on edit EOI. The Apex controller updating this is ContentDownloadURL</inlineHelpText>
    <label>URL_Files_Img</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Value_of_investment_interest__c.field-meta.xml
<CustomField>
    <fullName>Value_of_investment_interest__c</fullName>
    <label>Value of investment interest</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Website_Link__c.field-meta.xml
<CustomField>
    <fullName>Website_Link__c</fullName>
    <label>Website Link</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Youtube_link__c.field-meta.xml
<CustomField>
    <fullName>Youtube_link__c</fullName>
    <label>Youtube link</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Youtube_Video_Link__c.field-meta.xml
<CustomField>
    <fullName>Youtube_Video_Link__c</fullName>
    <description>This field is optional if the user would like to display a video in the EOI live deal</description>
    <inlineHelpText>Paste the YouTube URL video link</inlineHelpText>
    <label>Youtube Video Link</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/EOI_Media_Links__c/EOI_Media_Links__c.object-meta.xml
<CustomObject>
    <description>This are the media links that will be related to the EOI records</description>
    <label>EOI Media Links</label>
    <nameField>
        <label>EOI Media Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOI Media Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/EOI_Media_Links__c/fields/EOI__c.field-meta.xml
<CustomField>
    <fullName>EOI__c</fullName>
    <label>Related EOI</label>
    <referenceTo>EOI__c</referenceTo>
    <relationshipLabel>EOI Media Links</relationshipLabel>
    <relationshipName>EOI_Media_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/Lead/fields/Investment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Investment_Amount__c</fullName>
    <description>The field is out of use now. The currency type Investment amount field is in use instead.</description>
    <inlineHelpText>Provide an indication of the investment amount you are considering.</inlineHelpText>
    <label>Investment Amount</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>$250 to $500</fullName>
            </value>
            <value>
                <fullName>$500 to $1,000</fullName>
            </value>
            <value>
                <fullName>$1,000 to $2,000</fullName>
            </value>
            <value>
                <fullName>$2,000 to $5,000</fullName>
            </value>
            <value>
                <fullName>$1,000 to $3,000</fullName>
            </value>
            <value>
                <fullName>$3,000 to $5,000</fullName>
            </value>
            <value>
                <fullName>$5,000 to $8,000</fullName>
            </value>
            <value>
                <fullName>$8,000 to $10,000</fullName>
            </value>
            <value>
                <fullName>$10,000 to $20,000</fullName>
            </value>
            <value>
                <fullName>$20,000 to $50,000</fullName>
            </value>
            <value>
                <fullName>$50,000 to $100,000</fullName>
            </value>
            <value>
                <fullName>$100,000 to $200,000</fullName>
            </value>
            <value>
                <fullName>$200,000+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/classes/MyEOIController.cls
/*********************************************************************************************************************************************
Author		 :	 Prakash Borade
Description	 :   This class is specifically created to manage EOI.
History      :   -
Test Class   :   MyEOIControllerTest.cls
Uses         :   Till the date 6/Feb/2024 this class is used by following LWC- ManageEOI, EOI_Preview, CreateUpdateEOi, AddEditAdvisor, AddEditLeadInvestor, AddEditMediaLinks, AddEditWiderTeam
----------------------------------------------------------------------------------------------------------------------------------------------
Version      Date                 Author               Details
1            01/01/2024           Prakash Borade       Initial Development
**********************************************************************************************************************************************/
public without sharing class MyEOIController {
    /*
        updateEoi - Method is used updated eoi record
    */
    @AuraEnabled
    public static string updateEoi(Map<string, object> datamap, Id eoiId) {
        try {
            EOI__c eoi = new EOI__c();
            eoi.Id = eoiId;
            for (string s : datamap.keyset()) {
                eoi.put(s, datamap.get(s));
            }
            update eoi;
            return 'Success';
        } catch (exception e) {
            return e.getMessage();
        }
    }

    // Base method to get EOI details (Used in LWC - ManageEoi, EOI_Preview, CreateUpdateEoi), this method also return Documents(Supporting images , logo and banner) linked with EOI.
    // KEN PREVUP-53 added the Minimum_Investment_amount__c field to the method
    @AuraEnabled(cacheable=true)
    public static EOI__c getEoiDetails(Id eoiId) {
        try {
            EOI__c eoiRecord = [
                SELECT Account__r.Name,Account__r.Id, Id, Name,Minimum_Investment_amount__c, EOI_Title__c, One_liner_about_business__c, Offer_Overview__c, Problem_or_opportunity__c, Youtube_Video_Link__c, EOI_Subtitle__c, Solution__c, Differentiation__c, Intellectual_Property__c, Total_addressable_market__c, Progress__c, Growth_plan__c, EOI_Published_Date__c, URL_Files_Img__c, Instagram_link__c, Youtube_link__c, Facebook_link__c, Linkedin_link__c, Twitter_X_link__c, Company_Website_Link__c, Website_link__c, Company_Stage__c, Target_Raise_Amount__c, Raise_Contact_email__c, Leads_Expressed_Interest__c, Value_of_investment_interest__c, EOI_Progress__c, End_Date__c, Published_EOI_URL__c, EOI_Status__c, Planned_used_of_funds__c, (SELECT ContentDocument.Title, ContentDocument.LatestPublishedVersion.VersionDataUrl FROM ContentDocumentLinks),
                Is_Fund__c ,Fund_Structure__c, Investment_Strategy__c, Tax_Concessions__c, Portfolio_Size__c, Investment_Objective__c, Investment_Period__c, Fund_Term__c, First_Close_Amount__c
                FROM EOI__c
                WHERE Id = :eoiId
            ];
            return eoiRecord;
        } catch (Exception ex) {
            // throw error on bad request
            throw new AuraHandledException('An error occurred in geting EOI details. Please contact your administrator.');
        }
    }

    /*
        addUpdateTeamMember - used to add/update team member in EOI - founder , advisor etc.
    */
    @AuraEnabled
    public static string addUpdateTeamMember(Map<string, object> datamap) {
        try {
            // we get team member data from lwc in datamap and if Id is present then we update the existing record else we create a new record for team member.
            EOI_team_and_advisors__c teamMember = new EOI_team_and_advisors__c();
            for (string s : datamap.keyset()) {
                teamMember.put(s, datamap.get(s));
            }
            upsert teamMember;
            return 'Success';
        } catch (exception e) {
            return e.getMessage();
        }
    }

    /*
        getTeamMembers - used to fetch all team members list.
    */
    @AuraEnabled(cacheable=true)
    public static List<EOI_team_and_advisors__c> getTeamMembers(String category, Id eoiId) {
        try {
            List<EOI_team_and_advisors__c> lstTeamMember = [SELECT Id, Name, Category__c, Member_Role__c, Founder_Picture__c, Team_Member_Description__c, Team_Related_EOI__c, Team_member_Linkedin__c, Order__c FROM EOI_team_and_advisors__c WHERE Category__c = :category AND Team_Related_EOI__c = :eoiId];

            if (!lstTeamMember.isEmpty() && lstTeamMember.size() > 0) {
                // return list of all team member record
                return lstTeamMember;
            } else {
                // return null when no team member
                return null;
            }
        } catch (Exception ex) {
            throw new AuraHandledException('An error occurred in getTeamMember. Please contact your administrator.');
        }
    }

    /*
        addUpdateLeadInvestor - create update entry on EOI_Lead_Investor__c object.
    */
    @AuraEnabled
    public static string addUpdateLeadInvestor(Map<string, object> datamap) {
        try {
            EOI_Lead_Investor__c leadInvestor = new EOI_Lead_Investor__c();
            for (string s : datamap.keyset()) {
                leadInvestor.put(s, datamap.get(s));
            }
            upsert leadInvestor;
            return 'Success';
        } catch (exception e) {
            return e.getMessage();
        }
    }

    /*
        getLeadInvestor - get list of all availabel EOI_Lead_Investor__c.
    */
    @AuraEnabled(cacheable=true)
    public static List<EOI_Lead_Investor__c> getLeadInvestor(Id eoiId) {
        try {
            List<EOI_Lead_Investor__c> lstLeadInvestor = [SELECT Id, Name, Lead_Investor_Amount__c, Related_EOI__c, Lead_Investor_Bio__c FROM EOI_Lead_Investor__c WHERE Related_EOI__c = :eoiId];

            if (!lstLeadInvestor.isEmpty() && lstLeadInvestor.size() > 0) {
                return lstLeadInvestor;
            } else {
                // return null on no lead investor
                return null;
            }
        } catch (Exception ex) {
            throw new AuraHandledException('An error occurred in getLeadInvestor. Please contact your administrator.');
        }
    }

    /*
        addUpdateMediaLinks - create/update record of EOI_Media_Links__c.
    */
    @AuraEnabled
    public static string addUpdateMediaLinks(Map<string, object> datamap) {
        try {
            EOI_Media_Links__c mediaLink = new EOI_Media_Links__c();
            for (string s : datamap.keyset()) {
                mediaLink.put(s, datamap.get(s));
            }
            upsert mediaLink;
            return 'Success';
        } catch (exception e) {
            return e.getMessage();
        }
    }

    /*
        getMediaLinks - get list of all EOI_Media_Links__c.
        UPDATED ON 12/11/2024 to include Min Investment amt
    */
    @AuraEnabled(cacheable=true)
    public static List<EOI_Media_Links__c> getMediaLinks(Id eoiId) {
        try {
            List<EOI_Media_Links__c> lstMediaLinks = [SELECT Id, Name, Media_URL__c, EOI__c FROM EOI_Media_Links__c WHERE EOI__c = :eoiId];

            if (!lstMediaLinks.isEmpty() && lstMediaLinks.size() > 0) {
                return lstMediaLinks;
            } else {
                // return null if no media links found
                return null;
            }
        } catch (Exception ex) {
            throw new AuraHandledException('An error occurred in getMediaLinks. Please contact your administrator.');
        }
    }

    // Here getting leads related to EOI, showing this on EOI management page
    @AuraEnabled
    public static List<Lead> getInterestesLeads(Id eoiId) {
        return [SELECT Name, Email, MobilePhone, Investment_Range__c, Investment_Amount__c,Status, CreatedDate, Investment_Amount_Currency__c, Min_Investment__c FROM Lead WHERE Related_EOI__c = :eoiId];
    }

}