common/force-app/main/default/objects/EOI__c/EOI__c.object-meta.xml
<CustomObject>
    <description>This object will be used by Founders, this was part of the MVP project.</description>
    <label>EOI</label>
    <nameField>
        <label>EOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOI&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/EOI__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>This will link to the Ventures Company Account that is related to the EOI</description>
    <inlineHelpText>This field links to the Ventures Company Account that is related to this EOI</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EOI&apos;s</relationshipLabel>
    <relationshipName>EOI_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/EOI_Published_Date__c.field-meta.xml
<CustomField>
    <fullName>EOI_Published_Date__c</fullName>
    <label>EOI Published Date</label>
    <type>DateTime</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/EOI_Status__c.field-meta.xml
<CustomField>
    <fullName>EOI_Status__c</fullName>
    <description>This is the Status (Progress) for the EOI record.</description>
    <label>EOI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Published</fullName>
                <default>true</default>
                <label>Not Published</label>
            </value>
            <value>
                <fullName>Submitted to be Published</fullName>
            </value>
            <value>
                <fullName>Publishing</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Published_EOI_URL__c.field-meta.xml
<CustomField>
    <fullName>Published_EOI_URL__c</fullName>
    <label>Published EOI URL</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/URL_Files_Img__c.field-meta.xml
<CustomField>
    <fullName>URL_Files_Img__c</fullName>
    <description>This field stores a JSON file after a user click save on edit EOI. The Apex controller updating this is ContentDownloadURL</description>
    <inlineHelpText>This field stores a JSON file after a user click save on edit EOI. The Apex controller updating this is ContentDownloadURL</inlineHelpText>
    <label>URL_Files_Img</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/Raise__c.object-meta.xml
<CustomObject>
    <description>The raise object accountable for keeping track of a Founder&apos;s raise process.</description>
    <label>Raise</label>
    <nameField>
        <label>Raise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Raise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Raise__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field represents an account lookup relationship.</description>
    <inlineHelpText>Select an account to associate with this record.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Raise</relationshipLabel>
    <relationshipName>Raise</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field represents a master-detail relationship with the Company object.</description>
    <inlineHelpText>Select the company to which this record belongs.</inlineHelpText>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Raise (Company)</relationshipLabel>
    <relationshipName>Company</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Course_unlocked__c.field-meta.xml
<CustomField>
    <fullName>Course_unlocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox indicates whether the course has been unlocked for the user.</description>
    <inlineHelpText>Check this box if the user has unlocked access to the course.</inlineHelpText>
    <label>Course unlocked</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/EOI__c.field-meta.xml
<CustomField>
    <fullName>EOI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field represents a lookup relationship with the EOI object.</description>
    <inlineHelpText>Select an Expression of Interest (EOI) associated with this record.</inlineHelpText>
    <label>EOI</label>
    <referenceTo>EOI__c</referenceTo>
    <relationshipLabel>Raise</relationshipLabel>
    <relationshipName>Raise</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Investment_type__c.field-meta.xml
<CustomField>
    <fullName>Form_Investment_type__c</fullName>
    <description>This field indicates the type of investment being made.</description>
    <inlineHelpText>Indicate the type of investment: Retail or Wholesale.</inlineHelpText>
    <label>Investment type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Retail</fullName>
                <default>true</default>
                <label>Retail</label>
            </value>
            <value>
                <fullName>Wholesale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Offer_close_date__c.field-meta.xml
<CustomField>
    <fullName>Form_Offer_close_date__c</fullName>
    <description>This field specifies the closing date for the current offer.</description>
    <inlineHelpText>Provide the closing date for the current offer.</inlineHelpText>
    <label>Offer close date</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Offer_launch_date__c.field-meta.xml
<CustomField>
    <fullName>Form_Offer_launch_date__c</fullName>
    <description>This field specifies the launch date for the current offer.</description>
    <inlineHelpText>Provide the launch date for the current offer.</inlineHelpText>
    <label>Offer launch date</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Learning_completed__c.field-meta.xml
<CustomField>
    <fullName>Learning_completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates whether the learning has been completed.</description>
    <inlineHelpText>Check this box if the learning has been completed.</inlineHelpText>
    <label>Learning completed</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field indicates the status of the record.</description>
    <inlineHelpText>Select the current status of this record.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for review</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Waiting for payment</fullName>
            </value>
            <value>
                <fullName>Waiting to complete learning course</fullName>
            </value>
            <value>
                <fullName>Pending final approval</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live on VC Website</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/classes/CompaniesService.cls
/**
 * This is the service layer class associated with the Raise process. 
 * All of the business logic relevant to Raise will remain in this class.
*/
public without sharing class CompaniesService {
    /**
     * Check if a Raise record exists for a Business account.
     * @param companyId The Id of the Business Account.
     * @return Boolean to indicate if the raise exists.
     * @throws AuraHandledException
     */ 
    public Boolean raiseExists(String companyId){
        try{
            CompaniesFactory factory = New CompaniesFactory();
            Boolean result = factory.checkRaiseExists(companyId);
            Logger.logMessage('CompaniesApp', 'CompaniesService', 'raiseExists', 'Checked existence of raise record for companyId: ' + companyId);
            return result;
        }catch (Exception e){
            Logger.logError('CompaniesApp', 'CompaniesService', 'raiseExists', companyId, null, null, null, e, 'Failed to check if raise exists for companyId: ' + companyId);
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * Check if a EOI Record exists for a Business account.
     * @param companyId The Id of the Business Account.
     * @return Boolean to indicate if the raise exists.
     * @throws AuraHandledException
     */ 
    public Boolean eoiExists(String companyId){
        try{
            CompaniesFactory factory = New CompaniesFactory();
            Boolean result = factory.checkEoiExists(companyId);
            Logger.logMessage('CompaniesApp', 'CompaniesService', 'eoiExists', 'Checked existence of raise record for companyId: ' + companyId);
            return result;
        }catch (Exception e){
            Logger.logError('CompaniesApp', 'CompaniesService', 'eoiExists', companyId, null, null, null, e, 'Failed to check if raise exists for companyId: ' + companyId);
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * Get the details of a raise record given the Business Account ID
     * @param companyId The Id of the Business Account record.
     * @return JSON.serialize string representation of the raise record.
     * @throws AuraHandledException
     */ 
    public String getRaiseDetailsFromCompanyId(String companyId){
        try{
            CompaniesFactory factory = New CompaniesFactory();
            Raise__c raiseRecord = factory.getRaiseRecordCompanyId(companyId);
            if(raiseRecord != null){
                RaiseData returnData = new RaiseData();
                returnData.id = raiseRecord.Id;
                returnData.name = raiseRecord.Name;
                returnData.account = raiseRecord.Account__c;
                returnData.company = raiseRecord.Company__c;
                returnData.eoi = raiseRecord.EOI__c;
                returnData.status = raiseRecord.Status__c;
                returnData.investmentType = raiseRecord.Form_Investment_type__c;
                returnData.offerCloseDate = raiseRecord.Form_Offer_close_date__c;
                returnData.launchDate = raiseRecord.Form_Offer_launch_date__c;
                returnData.courseUnlocked = raiseRecord.Course_unlocked__c;
                returnData.learningCompleted = raiseRecord.Learning_completed__c;
                Logger.logMessage('CompaniesApp', 'CompaniesService', 'getRaiseDetailsFromCompanyId', 'Successfully retrieved raise details for companyId: ' + companyId);
                return JSON.serialize(returnData);
            }else{
                Logger.logMessage('CompaniesApp', 'CompaniesService', 'getRaiseDetailsFromCompanyId', 'This is from Service No raise record found for companyId: ' + companyId);
                throw new AuraHandledException( 'No raise record found for companyId: ' + companyId);
            }
        }catch(Exception e){
            Logger.logError('CompaniesApp', 'CompaniesService', 'getRaiseDetailsFromCompanyId', companyId, null, null, null, e, 'Failed to get raise details for companyId: ' + companyId);
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * Get the details of a EOI record given the Business Account ID
     * @param companyId The Id of the Business Account record.
     * @return JSON.serialize string representation of the eoi record.
     * @throws AuraHandledException
     */ 
    public String getEoiDetailsFromCompanyId(String companyId){
        try{
            CompaniesFactory factory = New CompaniesFactory();
            EOI__c eoiRecord = factory.getEOIDetailsFromCompanyId(companyId);
            if(eoiRecord != null){
                EoiData returnData = new EoiData();
                returnData.id = eoiRecord.Id;
                returnData.name = eoiRecord.Name;
                returnData.status = eoiRecord.EOI_Status__c;
                returnData.publishedDate = eoiRecord.EOI_Published_Date__c;
                Logger.logMessage('CompaniesApp', 'CompaniesService', 'getEoiDetailsFromCompanyId', 'Successfully retrieved eoi details for companyId: ' + companyId);
                return JSON.serialize(returnData);
            }else{
                Logger.logMessage('CompaniesApp', 'CompaniesService', 'getEoiDetailsFromCompanyId', 'EoiDetails Method No raise record found for companyId: ' + companyId);
                throw new AuraHandledException( 'No raise record found for companyId: ' + companyId);
            }
        }catch(Exception e){
            Logger.logError('CompaniesApp', 'CompaniesService', 'getEoiDetailsFromCompanyId', companyId, null, null, null, e, 'Failed to get eoi details for companyId: ' + companyId);
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * Get the details of companies associated with a given user ID.
     *
     * This method retrieves company details, including their respective EOI (Expression of Interest) 
     * and Raise records, for a specified user. It gathers necessary information from the CompaniesFactory 
     * and other related entities and returns a list of maps containing the detailed information.
     *
     * @param userId The ID of the user for whom the company details are to be fetched.
     * @return A list of maps, each representing a company with its details and associated records.
     *         Each map contains key-value pairs representing different attributes of the company 
     *         and its associated records.
     * @throws AuraHandledException If there is an error while retrieving the company details.
     */ 
    public List<Map<String,Object>> getCompaniesCardDetails(String userId) {
        try {
            // Initialize the CompaniesFactory to interact with the companies data.            
            CompaniesFactory factory = New CompaniesFactory();
            List<Account> companiesId = factory.getCompanyId(userId);
            List<Map<String,Object>> finalReturnData = new List<Map<String,Object>>();
            
            // Iterate through each company ID to fetch and compile their details.
            for (Account companyId : companiesId) {                
                Account companyRecord = factory.getCompanyDetails(companyId.Id);
                Boolean eoiExist = factory.checkEoiExists(companyId.Id);
                Boolean raiseExist = factory.checkRaiseExists(companyId.Id);
                Map<String,Object> returnData = new Map<String,Object>();

                // If an EOI record exists, retrieve and add its details to the return data.
                if (eoiExist) {
                    EOI__c eoiRecord = factory.getEoiDetailsFromCompanyId(companyId.Id);
                    returnData.put('eoiId',eoiRecord.Id);
                    returnData.put('eoiStatus', eoiRecord.EOI_Status__c);

                     // Check if EOI is live
                    if(eoiRecord.EOI_Status__c == 'Published' || eoiRecord.EOI_Status__c == 'Closed'){
                        returnData.put('eoiPublishURL', eoiRecord.Published_EOI_URL__c);
                    }


                    if (eoiRecord.URL_Files_Img__c != null) {
                        List<Object> imagesURLS = (List<Object>) JSON.deserializeUntyped(eoiRecord.URL_Files_Img__c);
                        for (Object imageObj : imagesURLS) {
                            Map<String, Object> imageMap = (Map<String, Object>) imageObj;
                            if (imageMap.get('title') == 'logo') {
                                returnData.put('companyLogoEOI', (String) imageMap.get('contentDownloadURL'));
                                break;
                            }
                        }
                    }
                    // Format the date to only return date not date and time
                    if(eoiRecord.EOI_Published_Date__c != null) {
                        Date eoiDate = eoiRecord.EOI_Published_Date__c.date();
                        returnData.put('eoiLaunchDate', eoiDate);
                    }
                    returnData.put('eoiExist', eoiExist);
                }

                // If a Raise record exists, retrieve and add its details to the return data.
                if (raiseExist) {
                    Raise__c raiseRecord = factory.getRaiseRecordCompanyId(companyId.Id);
                    List<Map<String, Object>> documentsUrls = FileUploadController.getDocumentsUrl('companyLogoId', raiseRecord.Id);
                    returnData.put('raiseId', raiseRecord.Id);
                    returnData.put('raiseStatus', raiseRecord.Status__c);
                    returnData.put('raiseEndDate', raiseRecord.Form_Offer_close_date__c);
                    returnData.put('raiseLaunchDate', raiseRecord.Form_Offer_launch_date__c);
                    returnData.put('raiseExist', raiseExist);
                    returnData.put('raiseCourseUnlocked', raiseRecord.Course_unlocked__c);
                    returnData.put('learningCompleted', raiseRecord.Learning_completed__c);
                    // Extract the publicDownloadUrl;
                    if (!documentsUrls.isEmpty() && documentsUrls[0].containsKey('publicDownloadUrl')) {
                        String publicDownloadUrl = (String) documentsUrls[0].get('publicDownloadUrl');
                        returnData.put('companyLogo', publicDownloadUrl);
                    }
                }
                returnData.put('companyId', companyRecord.Id);
                returnData.put('companyName', companyRecord.Name);
                finalReturnData.add(returnData);
            }
                Logger.logMessage('CompaniesApp', 'CompaniesService', 'getCompaniesCardDetails', 'Successfully retrieved raise details for userId: ' + userId);
                return finalReturnData;
        }catch(Exception e){
            Logger.logError('CompaniesApp', 'CompaniesService', 'getCompaniesCardDetails', userId, null, null, null, e, 'Failed to get company card details for userId: ' + userId);
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * Class structure that abstracts the EOI record structure need for my Companies Page
     */ 
    public class EoiData {
        String name;
        Id id;
        String status;
        Datetime publishedDate;
    }

    /**
     * Class structure that abstracts the Raise record structure need for my Companies Page
     */ 
	public class RaiseData{
        String name;
        String account;
        String eoi;
        String id; 
        String status;
        String company;
        String investmentType;
        Decimal minTarget;
        Decimal maxTarget;
        Decimal minInvestAmount;
        Date offerCloseDate;
        Date launchDate;
        Boolean learningCompleted;
        Boolean courseUnlocked;
    }


}