common/force-app/main/default/objects/EOI__c/EOI__c.object-meta.xml
<CustomObject>
    <description>This object will be used by Founders, this was part of the MVP project.</description>
    <label>EOI</label>
    <nameField>
        <label>EOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOI&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/EOI__c/fields/Company_Stage__c.field-meta.xml
<CustomField>
    <fullName>Company_Stage__c</fullName>
    <label>Company Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Seed</fullName>
            </value>
            <value>
                <fullName>Seed</fullName>
            </value>
            <value>
                <fullName>Series A</fullName>
            </value>
            <value>
                <fullName>Series B +</fullName>
            </value>
            <value>
                <fullName>Pre-IPO</fullName>
            </value>
            <value>
                <fullName>IPO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/EOI_Status__c.field-meta.xml
<CustomField>
    <fullName>EOI_Status__c</fullName>
    <description>This is the Status (Progress) for the EOI record.</description>
    <label>EOI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Published</fullName>
                <default>true</default>
                <label>Not Published</label>
            </value>
            <value>
                <fullName>Submitted to be Published</fullName>
            </value>
            <value>
                <fullName>Publishing</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/EOI_Title__c.field-meta.xml
<CustomField>
    <fullName>EOI_Title__c</fullName>
    <description>EOI Title</description>
    <label>EOI Title</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Minimum_Investment_amount__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Investment_amount__c</fullName>
    <description>The minimum investment amount that an investor is allowed to express interest in</description>
    <inlineHelpText>The minimum investment amount that an is allowed to express interest in</inlineHelpText>
    <label>Minimum Investment amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/One_liner_about_business__c.field-meta.xml
<CustomField>
    <fullName>One_liner_about_business__c</fullName>
    <label>One liner about business</label>
    <type>TextArea</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Publish_on_Community_Site__c.field-meta.xml
<CustomField>
    <fullName>Publish_on_Community_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox will render the card to show it on the VC website</description>
    <label>Publish on Community Site</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Published_EOI_URL__c.field-meta.xml
<CustomField>
    <fullName>Published_EOI_URL__c</fullName>
    <label>Published EOI URL</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/URL_Files_Img__c.field-meta.xml
<CustomField>
    <fullName>URL_Files_Img__c</fullName>
    <description>This field stores a JSON file after a user click save on edit EOI. The Apex controller updating this is ContentDownloadURL</description>
    <inlineHelpText>This field stores a JSON file after a user click save on edit EOI. The Apex controller updating this is ContentDownloadURL</inlineHelpText>
    <label>URL_Files_Img</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/Raise__c.object-meta.xml
<CustomObject>
    <description>The raise object accountable for keeping track of a Founder&apos;s raise process.</description>
    <label>Raise</label>
    <nameField>
        <label>Raise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Raise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Raise__c/fields/EOI__c.field-meta.xml
<CustomField>
    <fullName>EOI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field represents a lookup relationship with the EOI object.</description>
    <inlineHelpText>Select an Expression of Interest (EOI) associated with this record.</inlineHelpText>
    <label>EOI</label>
    <referenceTo>EOI__c</referenceTo>
    <relationshipLabel>Raise</relationshipLabel>
    <relationshipName>Raise</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Final_Approval__c.field-meta.xml
<CustomField>
    <fullName>Final_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This will be checked once final review and approval is completed.</inlineHelpText>
    <label>Final Approval</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Publish_on_Community_Site__c.field-meta.xml
<CustomField>
    <fullName>Publish_on_Community_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will be automatically checked once the Tile Banner field is populated and the Status is set to &quot;Live in VC Website&quot;</description>
    <inlineHelpText>This field will be automatically checked once the Tile Banner field is populated and the Status is set to &quot;Live in VC Website&quot;</inlineHelpText>
    <label>Publish on Community Site</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Published_Raise_URL__c.field-meta.xml
<CustomField>
    <fullName>Published_Raise_URL__c</fullName>
    <inlineHelpText>This field is to be filled with the Raise deal page URL</inlineHelpText>
    <label>Published Raise URL</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field indicates the status of the record.</description>
    <inlineHelpText>Select the current status of this record.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for review</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Waiting for payment</fullName>
            </value>
            <value>
                <fullName>Waiting to complete learning course</fullName>
            </value>
            <value>
                <fullName>Pending final approval</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live on VC Website</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/classes/EOI_Service.cls
public without sharing class EOI_Service {
/**
     * Retrieves EOI offer information and returns it as a serialized JSON string.
     *
     * @return String - A JSON string representing a list of EOIsData.
     * @throws AuraHandledException if no EOIs are found or if an error occurs during processing.
     */
    public String getEoiOfferInformation() {
            // Create an instance of the factory to retrieve EOI information
            EOI_Factory factory = new EOI_Factory();

            // Get the list of EOIs from the factory
            List<EOI__c> eoiRecords = factory.getEoiOfferInformation();

            // Check if the list of EOIs is empty
            if (eoiRecords.isEmpty()) {
                // Log a message indicating no EOI records were found
                Logger.logMessage('EOIApp', 'EOI_Service', 'getEoiOfferInformation', 'No EOI records found.');

                // Throw an exception indicating no EOI records were found
                throw new AuraHandledException('No EOIs found for publication on the community site.');
            } else {
                // Initialize a list to hold the EOIsData objects
                List<EoiOfferData> eoiRecordsList = new List<EoiOfferData>();

                // Loop through the EOIs and map them to the EOIsData class
                for (EOI__c eoi : eoiRecords) {
                    EoiOfferData data = new EoiOfferData();
                    data.tileHeading = eoi.EOI_Title__c;
                    data.companyOneLiner = eoi.One_liner_about_business__c;
                    data.imagesUrl = eoi.URL_Files_Img__c;
                    data.investmentType = eoi.Company_Stage__c;
                    data.dealPageLink = eoi.Published_EOI_URL__c;
                    eoiRecordsList.add(data);
                }

                // Log a success message indicating records were successfully retrieved and processed
                Logger.logMessage('EOIApp', 'EOI_Service', 'getEoiOfferInformation', 'Successfully retrieved and processed EOI records.');

                // Serialize the list of EOIsData to JSON and return it
                return JSON.serialize(eoiRecordsList);
            }
  
    }

    /**
     * Retrieves EOI offer information and returns it as a serialized JSON string for SXSW finalists.
     *
     * @return String - A JSON string representing a list of EOIsData.
     * @throws AuraHandledException if no EOIs are found or if an error occurs during processing.
     */
    public String getSXSWEoiOfferInformation(String searchTerm) {
            // Create an instance of the factory to retrieve EOI information
            EOI_Factory factory = new EOI_Factory();

            // Get the list of EOIs from the factory
            List<EOI__c> eoiRecords = factory.getEoiSXSWFinalist(searchTerm);

            // Check if the list of EOIs is empty
            if (eoiRecords.isEmpty()) {
                // Log a message indicating no EOI records were found
                Logger.logMessage('EOIApp', 'EOI_Service', 'getEoiOfferInformation', 'No EOI SXSW records found.');

                // Throw an exception indicating no EOI records were found
                throw new AuraHandledException('No SXSW EOIs found for publication on the community site.');
            } else {
                // Initialize a list to hold the EOIsData objects
                List<EoiOfferData> eoiRecordsList = new List<EoiOfferData>();

                // Loop through the EOIs and map them to the EOIsData class
                for (EOI__c eoi : eoiRecords) {
                    EoiOfferData data = new EoiOfferData();
                    data.tileHeading = eoi.EOI_Title__c;
                    data.companyOneLiner = eoi.One_liner_about_business__c;
                    data.imagesUrl = eoi.URL_Files_Img__c;
                    data.investmentType = eoi.Company_Stage__c;
                    data.dealPageLink = eoi.Published_EOI_URL__c;
                    eoiRecordsList.add(data);
                }

                // Log a success message indicating records were successfully retrieved and processed
                Logger.logMessage('EOIApp', 'EOI_Service', 'getEoiOfferInformation', 'Successfully retrieved and processed EOI SXSW records.');

                // Serialize the list of EOIsData to JSON and return it
                return JSON.serialize(eoiRecordsList);
            }
  
    }

    /**
     * Inner class representing the EOI data structure that will be serialized into JSON.
     */
    public class EoiOfferData {
        public String tileHeading;
        public String companyOneLiner;
        public String imagesUrl;
        public String investmentType;
        public String dealPageLink;
    }

    public List<EOI__c> getEoiInformation(Id eoiId) {
        EOI_Factory factory = new EOI_Factory();
        List<EOI__c> eoiRecords = factory.getEoiInformation(eoiId);
        return eoiRecords;
    }

    public Map<String,Object> getLiveRaiseFromEOI(Id eoiId) {
        EOI_Factory factory = new EOI_Factory();

        List<Raise__c> returnResults = factory.getRaiseForEOI(eoiId);

        Map<String,Object> returnValue = new Map<String,Object>();

        for(Raise__c raiseRecord : returnResults){
            
            Map<String,Object> raiseReturnMap = new Map<String,Object>();

            if(raiseRecord.Status__c == 'Live'){
                    raiseReturnMap.put('raiseId', raiseRecord.Id);
                    raiseReturnMap.put('raiseName' , raiseRecord.Name);
                    raiseReturnMap.put('raiseStatus' , raiseRecord.Status__c);
                    raiseReturnMap.put('raiseUrl' , raiseRecord.Published_Raise_URL__c);
                    raiseReturnMap.put('raiseIsApproved' , raiseRecord.Final_Approval__c);
                    raiseReturnMap.put('raiseIsPublic' , raiseRecord.Publish_on_Community_Site__c);


                    returnValue.put(raiseRecord.Id, raiseReturnMap);
            }
        
        }

        if(returnValue.isEmpty()){
            throw new AuraHandledException('No Live Raises Found for EOI: ' + eoiId);
        }

        return returnValue;
    }

    public Map<String,Object> getEOIByID(Id eoiId){

         EOI_Factory factory = new EOI_Factory();

         EOI__c eoiRecord = factory.getEOIByID(eoiId);

         Map<String,Object> returnMap  = new Map<String,Object>();

         returnMap.put('name', eoiRecord.Name);
         returnMap.put('status', eoiRecord.EOI_Status__c);
         returnMap.put('minimumInvestmentAmt', eoiRecord.Minimum_Investment_amount__c);
         

         return returnMap;
    }
}