common/force-app/main/default/objects/EOI__c/EOI__c.object-meta.xml
<CustomObject>
    <description>This object will be used by Founders, this was part of the MVP project.</description>
    <label>EOI</label>
    <nameField>
        <label>EOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOI&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/EOI__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>This will link to the Ventures Company Account that is related to the EOI</description>
    <inlineHelpText>This field links to the Ventures Company Account that is related to this EOI</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EOI&apos;s</relationshipLabel>
    <relationshipName>EOI_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/EOI_Status__c.field-meta.xml
<CustomField>
    <fullName>EOI_Status__c</fullName>
    <description>This is the Status (Progress) for the EOI record.</description>
    <label>EOI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Published</fullName>
                <default>true</default>
                <label>Not Published</label>
            </value>
            <value>
                <fullName>Submitted to be Published</fullName>
            </value>
            <value>
                <fullName>Publishing</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/EOI_Title__c.field-meta.xml
<CustomField>
    <fullName>EOI_Title__c</fullName>
    <description>EOI Title</description>
    <label>EOI Title</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Internal_Owner__c.field-meta.xml
<CustomField>
    <fullName>Internal_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Internal Owner in charge of the EOI and the Account</description>
    <inlineHelpText>Internal Owner in charge of the EOI and the Account</inlineHelpText>
    <label>Internal Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EOI_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/One_liner_about_business__c.field-meta.xml
<CustomField>
    <fullName>One_liner_about_business__c</fullName>
    <label>One liner about business</label>
    <type>TextArea</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Publish_on_Community_Site__c.field-meta.xml
<CustomField>
    <fullName>Publish_on_Community_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox will render the card to show it on the VC website</description>
    <label>Publish on Community Site</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Published_EOI_URL__c.field-meta.xml
<CustomField>
    <fullName>Published_EOI_URL__c</fullName>
    <label>Published EOI URL</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/SXSW_Finalist__c.field-meta.xml
<CustomField>
    <fullName>SXSW_Finalist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this if the EOI is an SXSW Finalist. This will enable it to be displayed on the SXSW Finalist EOI landing page</description>
    <inlineHelpText>Check this if the EOI is an SXSW Finalist. This will enable it to be displayed on the SXSW Finalist EOI landing page</inlineHelpText>
    <label>SXSW Finalist</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/URL_Files_Img__c.field-meta.xml
<CustomField>
    <fullName>URL_Files_Img__c</fullName>
    <description>This field stores a JSON file after a user click save on edit EOI. The Apex controller updating this is ContentDownloadURL</description>
    <inlineHelpText>This field stores a JSON file after a user click save on edit EOI. The Apex controller updating this is ContentDownloadURL</inlineHelpText>
    <label>URL_Files_Img</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Lead/fields/Investment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Investment_Amount__c</fullName>
    <description>The field is out of use now. The currency type Investment amount field is in use instead.</description>
    <inlineHelpText>Provide an indication of the investment amount you are considering.</inlineHelpText>
    <label>Investment Amount</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>$250 to $500</fullName>
            </value>
            <value>
                <fullName>$500 to $1,000</fullName>
            </value>
            <value>
                <fullName>$1,000 to $2,000</fullName>
            </value>
            <value>
                <fullName>$2,000 to $5,000</fullName>
            </value>
            <value>
                <fullName>$1,000 to $3,000</fullName>
            </value>
            <value>
                <fullName>$3,000 to $5,000</fullName>
            </value>
            <value>
                <fullName>$5,000 to $8,000</fullName>
            </value>
            <value>
                <fullName>$8,000 to $10,000</fullName>
            </value>
            <value>
                <fullName>$10,000 to $20,000</fullName>
            </value>
            <value>
                <fullName>$20,000 to $50,000</fullName>
            </value>
            <value>
                <fullName>$50,000 to $100,000</fullName>
            </value>
            <value>
                <fullName>$100,000 to $200,000</fullName>
            </value>
            <value>
                <fullName>$200,000+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Lead/fields/Investment_Amount_Currency__c.field-meta.xml
<CustomField>
    <fullName>Investment_Amount_Currency__c</fullName>
    <label>Investment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Lead/fields/Lead_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Sub_Status__c</fullName>
    <label>Lead Sub-Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contact Made</fullName>
            </value>
            <value>
                <fullName>No Contact Made</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Lead/fields/Related_EOI__c.field-meta.xml
<CustomField>
    <fullName>Related_EOI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related EOI</label>
    <referenceTo>EOI__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/classes/InvestmentAmountMigrationBatchTest.cls
/**
 * @description
 * Test class for InvestmentAmountMigrationBatch.
 * This class contains test methods to verify the functionality of the batch class,
 * including successful migration of Investment Amounts, handling of unknown picklist values,
 * and ensuring that the batch class runs without errors when emails are sent.
 *
 * The test class covers the following scenarios:
 * - Test migration with valid picklist values.
 * - Test handling of unknown picklist values (error condition).
 * - Test batch execution with a large number of records.
 *
 * Adjustments have been made to remove the invalid mocking of Messaging.SendEmailResult.
 * Since emails are not actually sent during test execution, we can proceed without mocking.
 *
 * Author: [Your Name]
 * Date: [Current Date]
 */
@IsTest
private class InvestmentAmountMigrationBatchTest {

    /**
     * @description
     * Test method to verify that the batch class correctly updates Lead records with valid picklist values.
     */
    @IsTest
    static void testBatchMigrationWithValidData() {
        // Set up test data

        // Create a test Account (required for EOI__c)
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;

        // Create a test EOI__c record
        EOI__c testEOI = new EOI__c(
            Name = 'Test EOI',
            Account__c = testAccount.Id,
            EOI_Status__c = 'Published',
            Publish_on_Community_Site__c = true,
            // Include any other required fields for EOI__c
            URL_Files_Img__c = 'http://example.com/image.png',
            Published_EOI_URL__c = 'http://example.com/eoi',
            One_liner_about_business__c = 'Innovative business idea',
            SXSW_Finalist__c = true,
            EOI_Title__c = 'Exciting EOI Title',
            Internal_Owner__c = UserInfo.getUserId()
        );
        insert testEOI;

        // Create Leads with valid picklist values and set Related_EOI__c to the EOI__c record ID
        List<Lead> testLeads = new List<Lead>();
        testLeads.add(new Lead(
            LastName = 'Test Lead 1',
            Company = 'Test Company',
            Investment_Amount__c = '$500 to $1,000',
            Related_EOI__c = testEOI.Id
            // Lead_Sub_Status__c = 'Contact Made' // Mandatory field
        ));
        testLeads.add(new Lead(
            LastName = 'Test Lead 2',
            Company = 'Test Company',
            Investment_Amount__c = '$10,000 to $20,000',
            Related_EOI__c = testEOI.Id
            // Lead_Sub_Status__c = 'Contact Made' // Mandatory field
        ));
        testLeads.add(new Lead(
            LastName = 'Test Lead 3',
            Company = 'Test Company',
            Investment_Amount__c = '$200,000+',
            Related_EOI__c = testEOI.Id
            // Lead_Sub_Status__c = 'Contact Made' // Mandatory field
        ));

        insert testLeads;

        // Verify that the new Investment Amount field is null before batch execution
        for (Lead lead : testLeads) {
            System.assertEquals(null, lead.Investment_Amount_Currency__c, 'New Investment Amount should be null before batch execution.');
        }

        // Start test context
        Test.startTest();

        // Instantiate and execute the batch class
        InvestmentAmountMigrationBatch batch = new InvestmentAmountMigrationBatch();
        Database.executeBatch(batch, 200); // Using batch size of 1 for simplicity

        // Stop test context to execute asynchronous batch job
        Test.stopTest();

        // Refresh the Lead records from the database
        testLeads = [SELECT Id, Investment_Amount__c, Investment_Amount_Currency__c FROM Lead WHERE Id IN :testLeads];

        // Verify that the Leads have been updated correctly
        for (Lead lead : testLeads) {
            Integer expectedAmount = InvestmentAmountMigrationBatch.amountRangeMap.get(lead.Investment_Amount__c);
            System.assertEquals(Decimal.valueOf(expectedAmount), lead.Investment_Amount_Currency__c, 'New Investment Amount should be updated correctly.');
        }
    }

    /**
     * @description
     * Test method to verify that the batch class handles unknown picklist values gracefully.
     */
    @IsTest
    static void testBatchMigrationWithInvalidData() {
        // Set up test data

        // Create a test Account (required for EOI__c)
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;

        // Create a test EOI__c record
        EOI__c testEOI = new EOI__c(
            Name = 'Test EOI',
            Account__c = testAccount.Id,
            EOI_Status__c = 'Published',
            Publish_on_Community_Site__c = true,
            // Include any other required fields for EOI__c
            URL_Files_Img__c = 'http://example.com/image.png',
            Published_EOI_URL__c = 'http://example.com/eoi',
            One_liner_about_business__c = 'Innovative business idea',
            SXSW_Finalist__c = true,
            EOI_Title__c = 'Exciting EOI Title',
            Internal_Owner__c = UserInfo.getUserId()
        );
        insert testEOI;

        // Create a Lead with an unknown picklist value
        List<Lead> testLeads = new List<Lead>();
        testLeads.add(new Lead(
            LastName = 'Test Lead 4',
            Company = 'Test Company',
            Investment_Amount__c = 'Unknown Value',
            Related_EOI__c = testEOI.Id
            // Lead_Sub_Status__c = 'Contact Made' // Mandatory field
        ));

        insert testLeads;

        // Start test context
        Test.startTest();

        // Instantiate and execute the batch class
        InvestmentAmountMigrationBatch batch = new InvestmentAmountMigrationBatch();
        Database.executeBatch(batch, 200);

        // Stop test context to execute asynchronous batch job
        Test.stopTest();

        // Refresh the Lead records from the database
        testLeads = [SELECT Id, Investment_Amount__c, Investment_Amount_Currency__c FROM Lead WHERE Id IN :testLeads];

        // Verify that the New Investment Amount is still null due to the unknown picklist value
        for (Lead lead : testLeads) {
            System.assertEquals(null, lead.Investment_Amount_Currency__c, 'New Investment Amount should remain null for unknown picklist values.');
        }
    }

    /**
     * @description
     * Test method to verify that the batch class runs without errors when processing emails.
     */
    @IsTest
    static void testBatchExecutionWithEmail() {
        // Set up test data

        // Create a test Account (required for EOI__c)
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;

        // Create a test EOI__c record
        EOI__c testEOI = new EOI__c(
            Name = 'Test EOI',
            Account__c = testAccount.Id,
            EOI_Status__c = 'Published',
            Publish_on_Community_Site__c = true,
            // Include any other required fields for EOI__c
            URL_Files_Img__c = 'http://example.com/image.png',
            Published_EOI_URL__c = 'http://example.com/eoi',
            One_liner_about_business__c = 'Innovative business idea',
            SXSW_Finalist__c = true,
            EOI_Title__c = 'Exciting EOI Title',
            Internal_Owner__c = UserInfo.getUserId()
        );
        insert testEOI;

        // Create Leads with both valid and invalid picklist values
        List<Lead> testLeads = new List<Lead>();
        testLeads.add(new Lead(
            LastName = 'Test Lead 5',
            Company = 'Test Company',
            Investment_Amount__c = '$1,000 to $2,000',
            Related_EOI__c = testEOI.Id
            // Lead_Sub_Status__c = 'Contact Made' // Mandatory field
        ));
        testLeads.add(new Lead(
            LastName = 'Test Lead 6',
            Company = 'Test Company',
            Investment_Amount__c = 'Invalid Value',
            Related_EOI__c = testEOI.Id
            // Lead_Sub_Status__c = 'Contact Made' // Mandatory field
        ));

        insert testLeads;

        // Start test context
        Test.startTest();

        // Instantiate and execute the batch class
        InvestmentAmountMigrationBatch batch = new InvestmentAmountMigrationBatch();
        Database.executeBatch(batch, 200);

        // Stop test context to execute asynchronous batch job
        Test.stopTest();

        // Since emails are not sent in test context, we ensure the batch completes without exceptions
        // We can verify that the Leads were updated appropriately

        // Refresh the Lead records from the database
        List<Lead> updatedLeads = [SELECT Id, Investment_Amount__c, Investment_Amount_Currency__c FROM Lead WHERE Id IN :testLeads];

        // Verify that the valid Lead was updated and the invalid one was not
        for (Lead lead : updatedLeads) {
            if (lead.Investment_Amount__c == '$1,000 to $2,000') {
                Integer expectedAmount = InvestmentAmountMigrationBatch.amountRangeMap.get(lead.Investment_Amount__c);
                System.assertEquals(Decimal.valueOf(expectedAmount), lead.Investment_Amount_Currency__c, 'New Investment Amount should be updated correctly.');
            } else if (lead.Investment_Amount__c == 'Invalid Value') {
                System.assertEquals(null, lead.Investment_Amount_Currency__c, 'New Investment Amount should remain null for invalid picklist values.');
            }
        }
    }

    /**
     * @description
     * Test method to simulate a large number of Lead records to test batch processing.
     */
    @IsTest
    static void testBatchWithLargeNumberOfRecords() {
        // Set up test data

        // Create a test Account (required for EOI__c)
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;

        // Create a test EOI__c record
        EOI__c testEOI = new EOI__c(
            Name = 'Test EOI',
            Account__c = testAccount.Id,
            EOI_Status__c = 'Published',
            Publish_on_Community_Site__c = true,
            // Include any other required fields for EOI__c
            URL_Files_Img__c = 'http://example.com/image.png',
            Published_EOI_URL__c = 'http://example.com/eoi',
            One_liner_about_business__c = 'Innovative business idea',
            SXSW_Finalist__c = true,
            EOI_Title__c = 'Exciting EOI Title',
            Internal_Owner__c = UserInfo.getUserId()
        );
        insert testEOI;

        List<Lead> testLeads = new List<Lead>();
        Integer numberOfLeads = 150; // More than the maxRecordsInEmail in the batch class

        // Create a large number of Leads with valid picklist values
        for (Integer i = 0; i < numberOfLeads; i++) {
            testLeads.add(new Lead(
                LastName = 'Test Lead ' + i,
                Company = 'Test Company',
                Investment_Amount__c = '$5,000 to $8,000',
                Related_EOI__c = testEOI.Id
                // Lead_Sub_Status__c = 'Contact Made' // Mandatory field
            ));
        }

        insert testLeads;

        // Start test context
        Test.startTest();

        // Instantiate and execute the batch class
        InvestmentAmountMigrationBatch batch = new InvestmentAmountMigrationBatch();
        Database.executeBatch(batch, 200); // Using a batch size of 200

        // Stop test context to execute asynchronous batch job
        Test.stopTest();

        // Verify that the Leads have been updated
        testLeads = [SELECT Id, Investment_Amount_Currency__c FROM Lead WHERE Id IN :testLeads];
        for (Lead lead : testLeads) {
            System.assertEquals(5000, lead.Investment_Amount_Currency__c, 'New Investment Amount should be updated to 5000.');
        }

        // Since emails are not sent in test context, we ensure the batch completes without exceptions
    }
}