common/force-app/main/default/objects/EOI__c/EOI__c.object-meta.xml
<CustomObject>
    <description>This object will be used by Founders, this was part of the MVP project.</description>
    <label>EOI</label>
    <nameField>
        <label>EOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOI&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/EOI__c/fields/Company_Stage__c.field-meta.xml
<CustomField>
    <fullName>Company_Stage__c</fullName>
    <label>Company Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Seed</fullName>
            </value>
            <value>
                <fullName>Seed</fullName>
            </value>
            <value>
                <fullName>Series A</fullName>
            </value>
            <value>
                <fullName>Series B +</fullName>
            </value>
            <value>
                <fullName>Pre-IPO</fullName>
            </value>
            <value>
                <fullName>IPO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/EOI_Status__c.field-meta.xml
<CustomField>
    <fullName>EOI_Status__c</fullName>
    <description>This is the Status (Progress) for the EOI record.</description>
    <label>EOI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Published</fullName>
                <default>true</default>
                <label>Not Published</label>
            </value>
            <value>
                <fullName>Submitted to be Published</fullName>
            </value>
            <value>
                <fullName>Publishing</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/EOI_Title__c.field-meta.xml
<CustomField>
    <fullName>EOI_Title__c</fullName>
    <description>EOI Title</description>
    <label>EOI Title</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Minimum_Investment_amount__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Investment_amount__c</fullName>
    <description>The minimum investment amount that an investor is allowed to express interest in</description>
    <inlineHelpText>The minimum investment amount that an is allowed to express interest in</inlineHelpText>
    <label>Minimum Investment amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/One_liner_about_business__c.field-meta.xml
<CustomField>
    <fullName>One_liner_about_business__c</fullName>
    <label>One liner about business</label>
    <type>TextArea</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Publish_on_Community_Site__c.field-meta.xml
<CustomField>
    <fullName>Publish_on_Community_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox will render the card to show it on the VC website</description>
    <label>Publish on Community Site</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Published_EOI_URL__c.field-meta.xml
<CustomField>
    <fullName>Published_EOI_URL__c</fullName>
    <label>Published EOI URL</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/SXSW_Finalist__c.field-meta.xml
<CustomField>
    <fullName>SXSW_Finalist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this if the EOI is an SXSW Finalist. This will enable it to be displayed on the SXSW Finalist EOI landing page</description>
    <inlineHelpText>Check this if the EOI is an SXSW Finalist. This will enable it to be displayed on the SXSW Finalist EOI landing page</inlineHelpText>
    <label>SXSW Finalist</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/URL_Files_Img__c.field-meta.xml
<CustomField>
    <fullName>URL_Files_Img__c</fullName>
    <description>This field stores a JSON file after a user click save on edit EOI. The Apex controller updating this is ContentDownloadURL</description>
    <inlineHelpText>This field stores a JSON file after a user click save on edit EOI. The Apex controller updating this is ContentDownloadURL</inlineHelpText>
    <label>URL_Files_Img</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/Raise__c.object-meta.xml
<CustomObject>
    <description>The raise object accountable for keeping track of a Founder&apos;s raise process.</description>
    <label>Raise</label>
    <nameField>
        <label>Raise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Raise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Raise__c/fields/EOI__c.field-meta.xml
<CustomField>
    <fullName>EOI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field represents a lookup relationship with the EOI object.</description>
    <inlineHelpText>Select an Expression of Interest (EOI) associated with this record.</inlineHelpText>
    <label>EOI</label>
    <referenceTo>EOI__c</referenceTo>
    <relationshipLabel>Raise</relationshipLabel>
    <relationshipName>Raise</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Final_Approval__c.field-meta.xml
<CustomField>
    <fullName>Final_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This will be checked once final review and approval is completed.</inlineHelpText>
    <label>Final Approval</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Publish_on_Community_Site__c.field-meta.xml
<CustomField>
    <fullName>Publish_on_Community_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will be automatically checked once the Tile Banner field is populated and the Status is set to &quot;Live in VC Website&quot;</description>
    <inlineHelpText>This field will be automatically checked once the Tile Banner field is populated and the Status is set to &quot;Live in VC Website&quot;</inlineHelpText>
    <label>Publish on Community Site</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Published_Raise_URL__c.field-meta.xml
<CustomField>
    <fullName>Published_Raise_URL__c</fullName>
    <inlineHelpText>This field is to be filled with the Raise deal page URL</inlineHelpText>
    <label>Published Raise URL</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field indicates the status of the record.</description>
    <inlineHelpText>Select the current status of this record.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for review</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Waiting for payment</fullName>
            </value>
            <value>
                <fullName>Waiting to complete learning course</fullName>
            </value>
            <value>
                <fullName>Pending final approval</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live on VC Website</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/classes/EOI_Factory.cls
public class EOI_Factory implements IEOI_Factory {
    /**
     * Retrieves a list of EOI records that are marked for publishing on the community site.
     *
     * @return List<EOI> - A list of EOI records.
     * @throws AuraHandledException if no EOIs are found or if an error occurs during retrieval.
     */
    public List<EOI__c> getEoiOfferInformation() {
        // Query to retrieve the relevant EOI records
        List<EOI__c> eoiRecords = [
            SELECT URL_Files_Img__c, Published_EOI_URL__c, One_liner_about_business__c, Company_Stage__c, EOI_Title__c FROM EOI__c 
            WHERE EOI_Status__c = 'Published' AND Publish_on_Community_Site__c = True
            ORDER BY CreatedDate DESC
            ];

        // Check if the query returned any records
        if (eoiRecords.isEmpty()) {
            // Log a message indicating no records were found
            Logger.logMessage('EOIApp', 'EOI_Factory', 'getEoiOfferInformation', 'No EOI records found');
            
            // Throw an exception indicating no EOIs are available
            throw new DmlException('No EOIs found for publication on the community site.');
        } else {
            // Log a success message indicating records were retrieved
            Logger.logMessage('EOIApp', 'EOI_Factory', 'getEoiOfferInformation', 'Successfully retrieved EOI records.');
            
            // Return the list of EOI records
            return eoiRecords;
        }
    }

    /**
     * Retrieves a list of EOI records that are marked for publishing on the community site.
     *
     * @return List<EOI> - A list of EOI records.
     * @throws AuraHandledException if no EOIs are found or if an error occurs during retrieval.
     */
    public List<EOI__c> getEoiSXSWFinalist(String searchTerm) {
        // Query to retrieve the relevant EOI records

        List<EOI__c> eoiRecords = new List<EOI__c>();

        if(!String.isBlank(searchTerm)){
            String searchKeyword = '%'+searchTerm+'%';

            eoiRecords = [
            SELECT URL_Files_Img__c, Published_EOI_URL__c, One_liner_about_business__c, Company_Stage__c, EOI_Title__c FROM EOI__c 
            WHERE EOI_Status__c = 'Published' AND Publish_on_Community_Site__c = True AND SXSW_Finalist__c = True AND Name LIKE :searchKeyword
            ORDER BY CreatedDate DESC
            ];
        }else{
            eoiRecords = [
            SELECT URL_Files_Img__c, Published_EOI_URL__c, One_liner_about_business__c, Company_Stage__c, EOI_Title__c FROM EOI__c 
            WHERE EOI_Status__c = 'Published' AND Publish_on_Community_Site__c = True AND SXSW_Finalist__c = True
            ORDER BY CreatedDate DESC
            ];
        }

        

        // Check if the query returned any records
        if (eoiRecords.isEmpty()) {
            // Log a message indicating no records were found
            Logger.logMessage('EOIApp', 'EOI_Factory', 'getEoiOfferInformation', 'No EOI records found');
            
            // Throw an exception indicating no EOIs are available
            throw new DmlException('No EOIs found for publication on the community site.');
        } else {
            // Log a success message indicating records were retrieved
            Logger.logMessage('EOIApp', 'EOI_Factory', 'getEoiOfferInformation', 'Successfully retrieved EOI records.');
            
            // Return the list of EOI records
            return eoiRecords;
        }

    }
    
    public List<EOI__c> getEoiInformation(Id eoiId) {
        List<EOI__c> eoiRecords = [SELECT URL_Files_Img__c, EOI_Title__c, EOI_Status__c FROM EOI__c WHERE Id = :eoiId];
            Logger.logMessage('EOIApp', 'EOI_Factory', 'getEoiInformation', 'No EOI record found for Id: ' + eoiId);
            return eoiRecords;
    }

    
    public List<Raise__c> getRaiseForEOI(Id eoiId){
        List<Raise__c> raisesForEOI = [SELECT Id, Name, Status__c, Published_Raise_URL__c, Final_Approval__c, Publish_on_Community_Site__c FROM Raise__c WHERE EOI__c=:eoiId];

        if(raisesForEOI.isEmpty()){
            throw new DmlException('No Raises Found for EOI ID: ' + eoiId );
        }else{
            return raisesForEOI;
        }
    }

    public EOI__c getEOIByID(Id eoiId){
        List<EOI__c> returnRecord = [SELECT Id, Name, EOI_Status__c, Minimum_Investment_amount__c FROM EOI__c WHERE Id=:eoiId];

        if(returnRecord.isEmpty()){
            throw new DmlException('No EOI Found for EOI ID: ' + eoiId );
        }else{
            return returnRecord[0];
        }
    }
}