common/force-app/main/default/objects/EOI__c/EOI__c.object-meta.xml
<CustomObject>
    <description>This object will be used by Founders, this was part of the MVP project.</description>
    <label>EOI</label>
    <nameField>
        <label>EOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOI&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Lead/fields/Are_you_located_in_Australia__c.field-meta.xml
<CustomField>
    <fullName>Are_you_located_in_Australia__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Are you located in Australia?</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Lead/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>Founder comments for this lead</description>
    <inlineHelpText>Founder comments for this lead</inlineHelpText>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Lead/fields/Investment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Investment_Amount__c</fullName>
    <description>The field is out of use now. The currency type Investment amount field is in use instead.</description>
    <inlineHelpText>Provide an indication of the investment amount you are considering.</inlineHelpText>
    <label>Investment Amount</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>$250 to $500</fullName>
            </value>
            <value>
                <fullName>$500 to $1,000</fullName>
            </value>
            <value>
                <fullName>$1,000 to $2,000</fullName>
            </value>
            <value>
                <fullName>$2,000 to $5,000</fullName>
            </value>
            <value>
                <fullName>$1,000 to $3,000</fullName>
            </value>
            <value>
                <fullName>$3,000 to $5,000</fullName>
            </value>
            <value>
                <fullName>$5,000 to $8,000</fullName>
            </value>
            <value>
                <fullName>$8,000 to $10,000</fullName>
            </value>
            <value>
                <fullName>$10,000 to $20,000</fullName>
            </value>
            <value>
                <fullName>$20,000 to $50,000</fullName>
            </value>
            <value>
                <fullName>$50,000 to $100,000</fullName>
            </value>
            <value>
                <fullName>$100,000 to $200,000</fullName>
            </value>
            <value>
                <fullName>$200,000+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Lead/fields/Investment_Amount_Currency__c.field-meta.xml
<CustomField>
    <fullName>Investment_Amount_Currency__c</fullName>
    <label>Investment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Lead/fields/Related_EOI__c.field-meta.xml
<CustomField>
    <fullName>Related_EOI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related EOI</label>
    <referenceTo>EOI__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Lead/fields/utm_campaign__c.field-meta.xml
<CustomField>
    <fullName>utm_campaign__c</fullName>
    <inlineHelpText>This field tells you if the goal is for branding or traffic.</inlineHelpText>
    <label>utm campaign</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Lead/fields/utm_content__c.field-meta.xml
<CustomField>
    <fullName>utm_content__c</fullName>
    <inlineHelpText>This field describes the exact product of the goal e.g &quot;Brand - Park Ridge&quot;</inlineHelpText>
    <label>utm content</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Lead/fields/utm_keyword__c.field-meta.xml
<CustomField>
    <fullName>utm_keyword__c</fullName>
    <inlineHelpText>This field shows that keyword was searched/clicked when the google search was made.</inlineHelpText>
    <label>utm keyword</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Lead/fields/utm_medium__c.field-meta.xml
<CustomField>
    <fullName>utm_medium__c</fullName>
    <inlineHelpText>This field tells you the type of campaign being run.</inlineHelpText>
    <label>utm medium</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Lead/fields/utm_source__c.field-meta.xml
<CustomField>
    <fullName>utm_source__c</fullName>
    <inlineHelpText>This field tells you the channel the lead has come from.</inlineHelpText>
    <label>utm source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Lead/fields/Web_Source__c.field-meta.xml
<CustomField>
    <fullName>Web_Source__c</fullName>
    <label>Web Source</label>
    <type>TextArea</type>
</CustomField>

common/force-app/main/default/objects/Lead/fields/Wholesale_Status__c.field-meta.xml
<CustomField>
    <fullName>Wholesale_Status__c</fullName>
    <inlineHelpText>This field is used when a lead fills in their Facebook form and their interpretation of whether they are wholesale or not.</inlineHelpText>
    <label>Are you a wholesale investor?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not Sure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>Founder comments</description>
    <inlineHelpText>Founder comments</inlineHelpText>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Raise__c.field-meta.xml
<CustomField>
    <fullName>Raise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Raise</label>
    <referenceTo>Raise__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/utm_campaign__c.field-meta.xml
<CustomField>
    <fullName>utm_campaign__c</fullName>
    <label>utm_campaign</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/utm_content__c.field-meta.xml
<CustomField>
    <fullName>utm_content__c</fullName>
    <label>utm_content</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/utm_medium__c.field-meta.xml
<CustomField>
    <fullName>utm_medium__c</fullName>
    <label>utm_medium</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/utm_source__c.field-meta.xml
<CustomField>
    <fullName>utm_source__c</fullName>
    <label>utm_source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/Raise__c.object-meta.xml
<CustomObject>
    <description>The raise object accountable for keeping track of a Founder&apos;s raise process.</description>
    <label>Raise</label>
    <nameField>
        <label>Raise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Raise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Raise__c/fields/EOI__c.field-meta.xml
<CustomField>
    <fullName>EOI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field represents a lookup relationship with the EOI object.</description>
    <inlineHelpText>Select an Expression of Interest (EOI) associated with this record.</inlineHelpText>
    <label>EOI</label>
    <referenceTo>EOI__c</referenceTo>
    <relationshipLabel>Raise</relationshipLabel>
    <relationshipName>Raise</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/classes/LeadFactory.cls
/**
 * LeadFactory class provides the implementation for fetching, creating, and updating Lead records.
 * It leverages dynamic SOQL and field mappings to handle these operations efficiently.
 */

public inherited sharing class LeadFactory {

    public List<Lead> getLeadById(Id leadId){
        return [SELECT FirstName,LastName, Email, MobilePhone, Comments__c, Company, Web_Source__c, LeadSource, Related_EOI__c FROM Lead WHERE Id=:leadId];
    }

    /**
     * Retrieves a paginated list of Lead records associated with a specific Raise record.
     * Constructs a dynamic SOQL query based on the provided parameters.
     *
     * @param recordId       The ID of the Raise record to filter the Leads.
     * @param pageSize       The number of records to return per page.
     * @param pageNumber     The current page number to retrieve.
     * @param sortBy         The field by which to sort the records.
     * @param sortDirection  The direction of sorting (ASC or DESC).
     * @param columnNames    The list of columns to include in the result.
     * @return               A LeadService.RecordsWrapper object containing the list of Lead records and the total record count.
     * @throws AuraHandledException If the associated EOI does not exist or if any error occurs during the query execution.
     */
    public LeadService.RecordsWrapper getRecords(Id recordId, Integer pageSize, Integer pageNumber, String sortBy, String sortDirection, List<String> columnNames){
        try{

            List<Raise__c> raiseRecord = [SELECT EOI__c FROM Raise__c WHERE Id=:recordId];


            if(!raiseRecord.isEmpty()){
                Id eoiId = raiseRecord[0].EOI__c;

                   // Construct the SOQL query dynamically based on column names
                Integer offset = (pageNumber - 1) * pageSize;

                // Manually join column names into a single string
                String fields = '';
                for (String column : columnNames) {
                    fields += column + ', ';
                }
                fields = fields.removeEnd(', ');

                String query = 'SELECT ' + fields + ' FROM Lead WHERE Related_EOI__c=:eoiId' ;

                if (sortBy != null && sortDirection != null) {
                    query += ' ORDER BY ' + sortBy + ' ' + sortDirection;
                }

                query += ' LIMIT :pageSize OFFSET :offset';

                List<sObject> records = Database.query(query);

                List<AggregateResult> totalRecords = [SELECT COUNT(Id) FROM Lead WHERE Related_EOI__c =: eoiId];

                return new LeadService.RecordsWrapper(records, totalRecords);  
            }else{
                throw new AuraHandledException('EOI does not exist for this raise');
            }
           
        }catch(Exception e){
            throw new AuraHandledException(e.getStackTraceString());
        }
      
    }

    /**
     * Creates a new Lead record with the provided field values using a predefined field mapping.
     *
     * @param fieldsToAdd    A map of field names and their respective values to create a new Lead.
     * @return               A map containing details of the created Lead record.
     */
    public Map<String,Object> createLead(Map<String,Object> fieldsToAdd){
        GenericObjectFactory factory = new GenericObjectFactory();
        BidiMap fieldMapping = new BidiMap(new Map<String,String>{
            'firstName'=>'FirstName',
            'middleNames'=>'MiddleName',
            'lastName'=>'LastName',
            // OwnerId added as part of INFSD-651 KKAM
            'OwnerId'=>'OwnerId',
            'webSource'=>'Web_Source__c',
            'email' => 'Email',
            'mobileCodeFormatted' => 'MobilePhone',
            'isWholesale' => 'Wholesale_Status__c',
            'investmentAmount' => 'Investment_Amount_Currency__c',
            'ausResident' => 'Are_you_located_in_Australia__c',
            'comments' => 'Comments__c',
            'source' => 'LeadSource',
            'company' => 'Company',
            'emailOptIn' => 'Email_Opt_In__c',
            'utm_campaign' => 'utm_campaign__c',
            'utm_content' => 'utm_content__c',
            'utm_term' => 'utm_keyword__c',
            'utm_medium' => 'utm_medium__c',
            'utm_source' => 'utm_source__c',
            'utm_keyword' => 'utm_keyword__c',
            'recordTypeId' => 'RecordTypeId',
            'relatedEOI' => 'Related_EOI__c'
        });

        Map<String,Object> returnData = factory.createRecord(
            'Lead', 
            fieldsToAdd, 
            fieldMapping
        );

        return returnData;
     
    }

    /**
     * Updates an existing Lead record with the provided field values using a predefined field mapping.
     *
     * @param recordId       The ID of the Lead record to be updated.
     * @param objectName     The name of the object being updated (usually 'Lead').
     * @param fieldsToUpdate A map of field names and their respective values to update the Lead.
     * @param fieldMap       A BidiMap containing the mapping between UI field names and Salesforce API field names.
     * @return               A map containing the result of the update operation, including unmapped fields.
     */
    public Map<String,Object> updateLead(Id recordId, String objectName, Map<String, Object> fieldsToUpdate, BidiMap fieldMap){
        Map<String,Object> returnData = new Map<String,Object>();
        // Opportunity recordToUpdate = new Opportunity();
        SObject recordToUpdate = Schema.getGlobalDescribe().get(objectName).newSObject();
        
        recordToUpdate.put('Id',recordId);

        Map<String, SObjectField> objectFieldsMap = recordToUpdate.getSObjectType().getDescribe().fields.getMap();
        Map<String, Object> unmappedFields = new Map<String,Object>();

        for(String field : fieldsToUpdate.keySet()){
            if(fieldMap.containsKey(field)){
                // get api field name
                String sObjectFieldName = fieldMap.getValue(field);

                // check if field exists in the object
                if(objectFieldsMap.containsKey(sObjectFieldName)){
                    //get the field type
                    SObjectField sObjectField = objectFieldsMap.get(sObjectFieldName);
                    // check if its a calculated field
                    if(sObjectField.getDescribe().isCalculated()){
                        unmappedFields.put(field, fieldsToUpdate.get(field));
                    }else{
                        Schema.DisplayType fieldType = sObjectField.getDescribe().getType();
                        Object fieldValue = fieldsToUpdate.get(field);

                        // convert value to field type
                        Object convertedValue = convertFieldValue(fieldType, fieldValue);

                        // put
                        recordToUpdate.put(sObjectFieldName, convertedValue);
                    }
                }else{
                    unmappedFields.put(field, fieldsToUpdate.get(field));
                }

            }else{
                unmappedFields.put(field, fieldsToUpdate.get(field));
            }
        }
        update recordToUpdate;
        returnData.put('Id', recordId);
        returnData.put('unmapped', unmappedFields);
        
        return returnData;
    }


    /**
     * Converts a field value to the appropriate type based on the field description.
     * @param fieldType The field type.
     * @param fieldValue The value to convert.
     * @return The converted value.
     */
    @TestVisible
    private Object convertFieldValue(Schema.DisplayType fieldType, Object fieldValue) {
        if (fieldValue == null) {
            return null;
        }
    
        switch on fieldType {
            when BOOLEAN {
                return Boolean.valueOf((String) fieldValue);
            }
            when DATE {
                return Date.valueOf((String) fieldValue);
            }
            when DATETIME {
                return Datetime.valueOfGmt((String) fieldValue);
            }
            when INTEGER {
                return Integer.valueOf((String) fieldValue);
            }
            when DOUBLE, CURRENCY, PERCENT {
                return Double.valueOf((String) fieldValue);
            }
            when STRING, TEXTAREA, URL, EMAIL, PHONE {
                return (String) fieldValue;
            }
            when ID {
                return (Id) fieldValue;
            }
            when REFERENCE {
                return (Id) fieldValue;
            }
            when else {
                return (String) fieldValue;
            }
        }
    }

    // get EOI Leads emails
    public List<Lead> getEOILeadsEmail(String email) {
        // Fetch Investments
        List<Lead> leadRecords = [SELECT Name, Investment_Amount_Currency__c, Investment_Amount__c,Related_EOI__c FROM Lead WHERE IsConverted = false AND Email=:email AND Related_EOI__c != null];
        
        if (!leadRecords.isEmpty()) {
            Logger.logMessage('OpportunityApp', 'OpportunitiesFactory', 'getEOILeadsEmail', 'Successfully retrieved lead records for: ' + email);
        } else {
            Logger.logMessage('OpportunityApp', 'OpportunitiesFactory', 'getEOILeadsEmail', 'No lead record found for email: ' + email);
        }
        return leadRecords;  // Return empty list instead of null
        
    }
}