common/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Course__c/fields/Course_type__c.field-meta.xml
<CustomField>
    <fullName>Course_type__c</fullName>
    <label>Course type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Any</fullName>
                <default>true</default>
                <label>Any</label>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Wholesale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Course_article__c/Course_article__c.object-meta.xml
<CustomObject>
    <description>Serves as a junction object to fulfil the many-many relationship between course and knowledge article.</description>
    <label>Course article</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Course_article__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course articles</relationshipLabel>
    <relationshipName>Course_articles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Course_article__c/fields/Knowledge__c.field-meta.xml
<CustomField>
    <fullName>Knowledge__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Knowledge</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Course articles</relationshipLabel>
    <relationshipName>Course_articles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Knowledge__kav/fields/Banner_image_URL__c.field-meta.xml
<CustomField>
    <fullName>Banner_image_URL__c</fullName>
    <description>url for the banner image</description>
    <label>Banner image URL</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Knowledge__kav/fields/Course_length__c.field-meta.xml
<CustomField>
    <fullName>Course_length__c</fullName>
    <description>Course length in hours</description>
    <inlineHelpText>Course length in hours</inlineHelpText>
    <label>Course length</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/Knowledge__kav/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the knowledge article</description>
    <inlineHelpText>Please enter a description of the knowledge article</inlineHelpText>
    <label>Description</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Knowledge__kav/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <description>Objective of the knowledge article</description>
    <inlineHelpText>Please enter the objective of the knowledge article</inlineHelpText>
    <label>Objective</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

common/force-app/main/default/objects/Learning__c/Learning__c.object-meta.xml
<CustomObject>
    <label>Learning</label>
    <nameField>
        <label>Learning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Learning__c/fields/Completed_date__c.field-meta.xml
<CustomField>
    <fullName>Completed_date__c</fullName>
    <label>Completed date</label>
    <type>DateTime</type>
</CustomField>

common/force-app/main/default/objects/Learning_course__c/Learning_course__c.object-meta.xml
<CustomObject>
    <description>Serves as a junction object to fulfil the many-many relationship between Learning and Course.</description>
    <label>Learning course</label>
    <nameField>
        <label>Learning course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Learning_course__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Learning courses</relationshipLabel>
    <relationshipName>Learning_courses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Learning_course__c/fields/Learning__c.field-meta.xml
<CustomField>
    <fullName>Learning__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Learning</label>
    <referenceTo>Learning__c</referenceTo>
    <relationshipLabel>Learning courses</relationshipLabel>
    <relationshipName>Learning_courses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Learning_progress__c/Learning_progress__c.object-meta.xml
<CustomObject>
    <label>Learning progress</label>
    <nameField>
        <label>Learning progress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning progress</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Learning_progress__c/fields/Knowledge__c.field-meta.xml
<CustomField>
    <fullName>Knowledge__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Knowledge</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Learning progress</relationshipLabel>
    <relationshipName>Learning_progress</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Learning_progress__c/fields/Learning__c.field-meta.xml
<CustomField>
    <fullName>Learning__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Learning</label>
    <referenceTo>Learning__c</referenceTo>
    <relationshipLabel>Learning progress</relationshipLabel>
    <relationshipName>Learning_progress</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/Raise__c.object-meta.xml
<CustomObject>
    <description>The raise object accountable for keeping track of a Founder&apos;s raise process.</description>
    <label>Raise</label>
    <nameField>
        <label>Raise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Raise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Raise__c/fields/Learning__c.field-meta.xml
<CustomField>
    <fullName>Learning__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The learning record associated to this raise</description>
    <inlineHelpText>Please link an existing learning record</inlineHelpText>
    <label>Learning</label>
    <referenceTo>Learning__c</referenceTo>
    <relationshipLabel>Raise</relationshipLabel>
    <relationshipName>Raise</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Learning_completed__c.field-meta.xml
<CustomField>
    <fullName>Learning_completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates whether the learning has been completed.</description>
    <inlineHelpText>Check this box if the learning has been completed.</inlineHelpText>
    <label>Learning completed</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/classes/KnowledgeFactory.cls
public class KnowledgeFactory implements IKnowledgeFactory{
    
    
    
    public Knowledge__kav getArticle(Id articleId){
        Knowledge__kav article = [SELECT Id, 
                                  Answer__c, 
                                  Banner_image_URL__c, 
                                  Description__c, 
                                  Objective__c, 
                                  Question__c, 
                                  Title, 
                                  Course_length__c ,
                                  CreatedDate,
                                  LastPublishedDate,
                                  UrlName 
                                  FROM Knowledge__kav
                                 WHERE Id=:articleId];
        return article;
    }
    
    public List<Knowledge__kav> getArticlesFromCourse(Id courseId){
            List<Knowledge__kav> returnList = new  List<Knowledge__kav>();
            
            List<Course_article__c> courseArticleLinks = [SELECT Id, Name, Course__c, Knowledge__c 
                                                          FROM Course_article__c 
                                                          WHERE Course__c=:courseId ORDER BY Name ASC];
            
            for(Course_article__c courseArticleLink : courseArticleLinks){
                Id articleId = courseArticleLink.Knowledge__c;
                Knowledge__kav article = getArticle(articleId);
                System.debug(article);
                returnList.add(article);
            }	
            
            return returnList;
    }
    
    public Course__c getCourseDetails(Id courseId){
         Course__c course = [SELECT Id, 
                             Name,
                             Description__c,
                             Course_type__c
                             FROM Course__c
                             WHERE Id=:courseId];
        return course;
    }
    
    public List<Course__c> getCoursesFromLearning(Id learningId){
            List<Course__c> returnList = new  List<Course__c>();
            // setup return structure
            List<Learning_course__c> learningCourses = [SELECT Id, Course__c, Learning__c, Name
                                                        FROM Learning_course__c
                                                        WHERE Learning__c=:learningId];
            
            for(Learning_course__c learningCourse : learningCourses){
                Id courseId = learningCourse.Course__c;
                
                Course__c course = getCourseDetails(courseId);
                returnList.add(course);
            }
            
            return returnList;
            
    }

    public List<Learning_progress__c> getLearningProgressFromLearning(Id learningId){
        try{
            List<Learning_progress__c> returnList = [SELECT Id, Name,Completed__c,Knowledge__c ,Learning__c 
            FROM Learning_progress__c 
            WHERE Learning__c=:learningId];

            return returnList;
        }catch(Exception e){
            throw e;
        }
    }

    public Learning__c completeLearningCourse(Id learningId){
        try{
            Learning__c learningRecord = [SELECT Id, Completed__c,Completed_date__c FROM Learning__c WHERE Id=:learningId ];
            learningRecord.Completed__c = true;
            learningRecord.Completed_date__c = Date.today();
            update learningRecord;



            return learningRecord;
        }catch(Exception e){
            Logger.logError('RaiseApp', 'KnowledgeFactory', 'completeLearningCourse', null, null, null, null, e, 'Failed to complete learning' + e.getMessage());
            throw e;
        }
    }


    public Raise__c completeLearningRaise(Id raiseId){
        try{
            Raise__c raiseRecord = [SELECT Id, Learning_completed__c FROM Raise__c WHERE Id=:raiseId LIMIT 1];
            raiseRecord.Learning_completed__c = true;

            update raiseRecord;

            return raiseRecord;
        }catch(Exception e){
            Logger.logError('RaiseApp', 'KnowledgeFactory', 'completeLearningRaise', null, null, null, null, e, 'Failed to complete learning' + e.getMessage());
            throw e;
        }
    }

    public Boolean updateLearningProgressCompletion(Id learningProgId, Boolean completed){
        try{
            Learning_progress__c learningProgRecord = [SELECT Id, Completed__c FROM Learning_progress__c 
            WHERE Id=:learningProgId];

            learningProgRecord.Completed__c = completed;

            update learningProgRecord;
            return true;
        }catch(Exception e){
            throw e;
        }
    }

}