common/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Course_article__c/Course_article__c.object-meta.xml
<CustomObject>
    <description>Serves as a junction object to fulfil the many-many relationship between course and knowledge article.</description>
    <label>Course article</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Course_article__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course articles</relationshipLabel>
    <relationshipName>Course_articles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Course_article__c/fields/Knowledge__c.field-meta.xml
<CustomField>
    <fullName>Knowledge__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Knowledge</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Course articles</relationshipLabel>
    <relationshipName>Course_articles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Learning__c/Learning__c.object-meta.xml
<CustomObject>
    <label>Learning</label>
    <nameField>
        <label>Learning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Learning_course__c/Learning_course__c.object-meta.xml
<CustomObject>
    <description>Serves as a junction object to fulfil the many-many relationship between Learning and Course.</description>
    <label>Learning course</label>
    <nameField>
        <label>Learning course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Learning_course__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Learning courses</relationshipLabel>
    <relationshipName>Learning_courses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Learning_course__c/fields/Learning__c.field-meta.xml
<CustomField>
    <fullName>Learning__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Learning</label>
    <referenceTo>Learning__c</referenceTo>
    <relationshipLabel>Learning courses</relationshipLabel>
    <relationshipName>Learning_courses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Learning_progress__c/Learning_progress__c.object-meta.xml
<CustomObject>
    <label>Learning progress</label>
    <nameField>
        <label>Learning progress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning progress</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Learning_progress__c/fields/Knowledge__c.field-meta.xml
<CustomField>
    <fullName>Knowledge__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Knowledge</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Learning progress</relationshipLabel>
    <relationshipName>Learning_progress</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Learning_progress__c/fields/Learning__c.field-meta.xml
<CustomField>
    <fullName>Learning__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Learning</label>
    <referenceTo>Learning__c</referenceTo>
    <relationshipLabel>Learning progress</relationshipLabel>
    <relationshipName>Learning_progress</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/classes/LearningFactory.cls
public class LearningFactory implements ILearningFactory {

    public Map<String,Object> createLearning(String companyName, List<String> courseNames){
        Map<String,Object> returnData = new Map<String,Object>();
        // create the learning object
        Learning__c learningRecord = new Learning__c();

        learningRecord.put('Name', companyName + ' Learning');

        insert learningRecord;

        returnData.put('learning', learningRecord);

        // assign the course with the Learning_course__c
        Id learningRecordId = learningRecord.Id;
        String learningRecordName = learningRecord.Name;

        List<Learning_course__c> linkedCourses = createLearningCourses(learningRecordId, learningRecordName, courseNames);

        returnData.put('learningCourses', linkedCourses);

        // using the Learning_courses__c create the  Learning_progress__c objects based on the course_articles__c records
        // this can be a list of learning courses
        for(Learning_course__c learningCourse : linkedCourses){
            Id course = learningCourse.Course__c;

            List<Course_article__c> courseArticles = [SELECT Id, Name, Knowledge__c, Course__c FROM Course_article__c WHERE Course__c=:course ORDER BY Name ASC];

            List<Learning_progress__c> linkedProgress = createLearningProgress(learningRecordId,learningRecordName,courseArticles);

            returnData.put('learningProgress'+course, linkedProgress);

        }
        

        return returnData;
    }

    public List<Learning_course__c> createLearningCourses(Id learningId, String learningName, List<String> courseNames){
        List<Learning_course__c> returnData = new List<Learning_course__c>();
        
        for(String courseName : courseNames){
            Course__c courseToAssign = [SELECT Id, Name FROM Course__c WHERE Name=:courseName];
            System.debug(courseName);
            System.debug(courseToAssign);
            // create new learning course link
            Learning_course__c newLearningCourseLink = new Learning_course__c();

            newLearningCourseLink.put('Name', learningName + ' X ' + courseName);
            newLearningCourseLink.put('Learning__c', learningId);
            newLearningCourseLink.put('Course__c', courseToAssign.Id);

            returnData.add(newLearningCourseLink);
        }

        insert returnData;

        return returnData;
    }


    public List<Learning_progress__c> createLearningProgress(Id learningId, String learningName, List<Course_article__c> courseArticles){
        //for each course article, get the knowledge article ID, and learning Id, then create the learning progress object
        List<Learning_progress__c> returnProgressRecords = new List<Learning_progress__c> ();

        for(Course_article__c courseArticle :courseArticles){
            Learning_progress__c newLearningProgress = new Learning_progress__c();

            String learningProgressName = learningName + ' X ' + courseArticle.Name;
            newLearningProgress.put('Name',learningProgressName);
            newLearningProgress.put('Knowledge__c',courseArticle.Knowledge__c);
            newLearningProgress.put('Learning__c', learningId);

            returnProgressRecords.add(newLearningProgress);
        }

        if(returnProgressRecords.size() > 0){
            insert returnProgressRecords;
        }

        return returnProgressRecords;
    }
}