common/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Knowledge__kav/fields/Course_length__c.field-meta.xml
<CustomField>
    <fullName>Course_length__c</fullName>
    <description>Course length in hours</description>
    <inlineHelpText>Course length in hours</inlineHelpText>
    <label>Course length</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/Knowledge__kav/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the knowledge article</description>
    <inlineHelpText>Please enter a description of the knowledge article</inlineHelpText>
    <label>Description</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Knowledge__kav/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <description>Objective of the knowledge article</description>
    <inlineHelpText>Please enter the objective of the knowledge article</inlineHelpText>
    <label>Objective</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

common/force-app/main/default/objects/Learning__c/Learning__c.object-meta.xml
<CustomObject>
    <label>Learning</label>
    <nameField>
        <label>Learning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Learning__c/fields/Completed_date__c.field-meta.xml
<CustomField>
    <fullName>Completed_date__c</fullName>
    <label>Completed date</label>
    <type>DateTime</type>
</CustomField>

common/force-app/main/default/objects/Learning_progress__c/Learning_progress__c.object-meta.xml
<CustomObject>
    <label>Learning progress</label>
    <nameField>
        <label>Learning progress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning progress</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Learning_progress__c/fields/Knowledge__c.field-meta.xml
<CustomField>
    <fullName>Knowledge__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Knowledge</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Learning progress</relationshipLabel>
    <relationshipName>Learning_progress</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Learning_progress__c/fields/Learning__c.field-meta.xml
<CustomField>
    <fullName>Learning__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Learning</label>
    <referenceTo>Learning__c</referenceTo>
    <relationshipLabel>Learning progress</relationshipLabel>
    <relationshipName>Learning_progress</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/Raise__c.object-meta.xml
<CustomObject>
    <description>The raise object accountable for keeping track of a Founder&apos;s raise process.</description>
    <label>Raise</label>
    <nameField>
        <label>Raise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Raise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Raise__c/fields/Learning__c.field-meta.xml
<CustomField>
    <fullName>Learning__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The learning record associated to this raise</description>
    <inlineHelpText>Please link an existing learning record</inlineHelpText>
    <label>Learning</label>
    <referenceTo>Learning__c</referenceTo>
    <relationshipLabel>Raise</relationshipLabel>
    <relationshipName>Raise</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Learning_completed__c.field-meta.xml
<CustomField>
    <fullName>Learning_completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates whether the learning has been completed.</description>
    <inlineHelpText>Check this box if the learning has been completed.</inlineHelpText>
    <label>Learning completed</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/classes/KnowledgeService.cls
public class KnowledgeService {
    private KnowledgeFactory factory = new KnowledgeFactory();
    
    public List<Map<String,Object>> getArticleDetailsFromCourse(Id courseId){
        try{
            // setup return structure
            List<Map<String,Object>> returnList = new  List<Map<String,Object>>();
            
            // get articles from factory
            List<Knowledge__kav> articles = factory.getArticlesFromCourse(courseId);
            
            //loop thru return result and create the article structure
            for(Knowledge__kav article : articles){
                Map<String,Object> articleReturn = new Map<String,Object>();
                
                articleReturn.put('id', article.Id);
                articleReturn.put('title', article.Title);
                articleReturn.put('description', article.Description__c);
                articleReturn.put('estimatedCompletionTime' , article.Course_length__c);
                articleReturn.put('urlName', article.UrlName);
                returnList.add(articleReturn);
            }
            
            return returnList;
        }catch(Exception e){
            throw e;
        }
    }
    
    public Map<String,Object> getArticleContent(Id articleId){
        try{
            // setup return structure
           	Map<String,Object> articleReturn = new Map<String,Object>();
            // get articles from factory
            Knowledge__kav article = factory.getArticle(articleId);
                        
            articleReturn.put('id', article.Id);
            articleReturn.put('title', article.Title);
            articleReturn.put('description', article.Description__c);
            articleReturn.put('objective', article.Objective__c);
            articleReturn.put('createdDate', article.CreatedDate);
            articleReturn.put('lastPublishedDate', article.LastPublishedDate);
            articleReturn.put('question', article.Question__c);
            articleReturn.put('answer', article.Answer__c);
           	articleReturn.put('estimatedCompletionTime' , article.Course_length__c);
            return articleReturn;
        }catch(Exception e){
            throw e;
        }
    }
    
    public List<Map<String,Object>> getCoursesFromLearning(Id learningId){
        try{
             // setup return structure
            List<Map<String,Object>> returnList = new  List<Map<String,Object>>();
            
            // get courses from learningId
            List<Course__c> courses = factory.getCoursesFromLearning(learningId);
        	
             for(Course__c course : courses){
                Map<String,Object> courseReturn = new Map<String,Object>();
                
                courseReturn.put('id', course.Id);
                courseReturn.put('title', course.Name);
                courseReturn.put('description', course.Description__c);
                
                
                returnList.add(courseReturn);
            }
            
            return returnList;
			            
        }catch(Exception e){
            throw e;
        }
    }

    public List<Map<String,Object>> getLearningProgressFromLearning(Id learningId){
        try{
             // setup return structure
            List<Map<String,Object>> returnList = new  List<Map<String,Object>>();
            
            // get courses from learningId
            List<Learning_progress__c> learningProgressItems = factory.getLearningProgressFromLearning(learningId);
        	
             for(Learning_progress__c learningProgress : learningProgressItems){

                Map<String,Object> learningProgressReturn = new Map<String,Object>();
                
                learningProgressReturn.put('id', learningProgress.Id);
                learningProgressReturn.put('name', learningProgress.Name);
                learningProgressReturn.put('completed', learningProgress.Completed__c);
                learningProgressReturn.put('articleId', learningProgress.Knowledge__c);
                learningProgressReturn.put('learningId', learningProgress.Learning__c);
                
                
                returnList.add(learningProgressReturn);
            }
            
            return returnList;
			            
        }catch(Exception e){
            throw e;
        }
    }


    public Boolean updateLearningProgressCompletion(Id learningProgId, Boolean completed){
        try{
            factory.updateLearningProgressCompletion(learningProgId,completed);
            return true;
        }catch(Exception e){
            throw e;
        }
    }

    public Map<String,Object> completeLearningProgress(Id learningId, Id raiseId){
        try{
            Learning__c learningRecord =  factory.completeLearningCourse(learningId);
            Raise__c raiseRecord = factory.completeLearningRaise(raiseId);

            Map<String,Object> retData = new Map<String,Object>();
            retData.put('raiseId', raiseRecord.Id);
            retData.put('raiseLearningStatus',raiseRecord.Learning_completed__c);
            retData.put('learningId' , learningRecord.Id);
            retData.put('completed' ,learningRecord.Completed__c);
            retData.put('completedDate',learningRecord.Completed_date__c);

            return retData;
        }catch(Exception e){
            throw e;
        }
    }
}