common/force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <label>Investment</label>
    <nameField>
        <displayFormat>IN-{00000000}</displayFormat>
        <label>Investment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Investment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investments</relationshipLabel>
    <relationshipName>Investments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>This Funds Management object is used to track the transaction of funds to/from investments, VC Entities, and Vehicles</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>What account does this Transaction relate to?</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Transaction__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>What Investment does this Transaction relate to?</inlineHelpText>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Authorised</fullName>
            </value>
            <value>
                <fullName>Awaiting Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>SUBMITTED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Transaction__c/fields/Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Amount__c</fullName>
    <label>Total Transaction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Transaction__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>This field determines if it is an Invoice or a Bill transaction</description>
    <inlineHelpText>Invoice is something that has been paid to.
Bill is something that needs to be paid</inlineHelpText>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Bill</fullName>
            </value>
            <value>
                <fullName>Bank Transaction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Transaction__c/fields/XI_Line_Items_Description__c.field-meta.xml
<CustomField>
    <fullName>XI_Line_Items_Description__c</fullName>
    <label>XI Line Items Description</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/classes/TransactionsFactory.cls
/**
 * @description
 * Factory class responsible for retrieving `Transaction__c` records associated with a given investment ID.
 * This class implements the `ITransactionsFactory` interface to adhere to the Transaction App's 
 * defined contract for transaction data retrieval.
 * 
 * The retrieved records include details such as Account, Created Date, Transaction Type, 
 * Amount, Status, Name, and Line Item Descriptions.
 * 
 * @date
 * 18-11-2024
 */

public inherited sharing class TransactionsFactory implements ITransactionsFactory  {

    /**
     * @description
     * Retrieves a list of `Transaction__c` records for a given investment ID. 
     * The records are filtered to include only those with a `Transaction_Type__c` of "Bill," 
     * and are ordered by the `CreatedDate` in descending order.
     * 
     * @param investmentId The ID of the Investment record for which transactions are being retrieved.
     * @return A list of `Transaction__c` records matching the specified criteria, or an empty list if none are found.
     */
    public List<Transaction__c> getInterestTransactions (Id investmentId) {
        // Fetch Transactions
        List<Transaction__c> transactionRecord = [SELECT Account__c, CreatedDate, Transaction_Type__c, Transaction_Amount__c, Status__c, Name, XI_Line_Items_Description__c
        FROM Transaction__c WHERE Investment__c = :investmentId AND Transaction_Type__c = 'Bill' AND (Status__c = 'Paid' OR Status__c = 'Draft') ORDER BY CreatedDate DESC];
        return transactionRecord;
    }
}