common/force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <label>Investment</label>
    <nameField>
        <displayFormat>IN-{00000000}</displayFormat>
        <label>Investment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Investment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investments</relationshipLabel>
    <relationshipName>Investments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/classes/MyPortfolio_InvestmentsTest.cls
@isTest
public class MyPortfolio_InvestmentsTest {
    @isTest
    public static void testGetInvestments(){
        Test.startTest();
        String investAmnt = MyPortfolio_Investments.getInvestments();
        system.assertEquals(True, investAmnt != null);
        Test.stopTest();
    }
    
    @isTest
    public static void testGetCurrentUser(){
        Test.startTest();
        List<user> curUser = MyPortfolio_Investments.getCurrentUser();
        system.assertEquals(True, curUser != null);
        Test.stopTest();
    }
    
    @isTest
    public static void testGetInvestmentFromInvestmentObject(){
        Account a = new Account();
        a.LastName = 'test';
        a.FirstName = 'test';
        a.PersonEmail = 'tugg@tyugg.com';
        Database.insert(a);
        
        Investment__c invst = new Investment__c();
        invst.Account__c = a.id;
        invst.Investment_Amount__c = Decimal.valueOf('123');
        Database.insert(invst);
        
        Test.startTest();
        MyPortfolio_Investments.getInvestmentFromInvestmentObject();
        Test.stopTest();
    }

}