common/force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <label>Investment</label>
    <nameField>
        <displayFormat>IN-{00000000}</displayFormat>
        <label>Investment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Investment__c/fields/Investment_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Investment_Product_Name__c</fullName>
    <label>Investment Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Investment_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Investment_Product_Type__c</fullName>
    <label>Investment Product Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Investments1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Purchased_Shares__c.field-meta.xml
<CustomField>
    <fullName>Purchased_Shares__c</fullName>
    <label>Investment Holding</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/CRC_Assigned__c.field-meta.xml
<CustomField>
    <fullName>CRC_Assigned__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRC Assigned</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>CRC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Invested_Product_ADMIN_FIELD__c.field-meta.xml
<CustomField>
    <fullName>Invested_Product_ADMIN_FIELD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please disregard this field. Admin field Only!</inlineHelpText>
    <label>Invested Product_ADMIN FIELD</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Number_Of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Units__c</fullName>
    <formula>Unit_Certificate_Amount__c  /  Invested_Opp_Prod_ADMIN__r.UnitPrice</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Original Holdings</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Unit_Certificate_Amount__c.field-meta.xml
<CustomField>
    <fullName>Unit_Certificate_Amount__c</fullName>
    <inlineHelpText>The amount issued on the unit certificate. This is the amount invested less any contribution fees.</inlineHelpText>
    <label>Original Unit Certificate Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/recordTypes/VC.recordType-meta.xml
<RecordType>
    <fullName>VC</fullName>
    <active>true</active>
    <businessProcess>VC</businessProcess>
    <label>VC</label>
</RecordType>

common/force-app/main/default/objects/Product2/fields/Investment_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Investment_Product_Type__c</fullName>
    <inlineHelpText>This is the structure in which the investment will be made.</inlineHelpText>
    <label>Investment Product Type</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Tile_Banner__c.field-meta.xml
<CustomField>
    <fullName>Tile_Banner__c</fullName>
    <label>Tile Banner</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/classes/ProcessInvestmentRecordQueueableTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class ProcessInvestmentRecordQueueableTest {

     @isTest
    static void testProcessInvestmentRecordQueueable_Insert() {
        User owner = [SELECT Id FROM USER WHERE Name = 'The VentureCrowd Team'];

        Id recordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('VC Person Account').getRecordTypeId();

        // Create test Account
        Account testAccount = new Account(FirstName = 'TestPersonAccountFirst',
            LastName = 'TestPersonAccountLast',
            PersonEmail = 'test@user.com',
            RecordTypeId = recordTypeId,
            // Name = 'Test Account',
            OwnerId = owner.Id);
        insert testAccount;

        // Create test Product2
        Product2 testProduct = new Product2(
            Name = 'Test Product',
            Tile_Banner__c = 'http://example.com/product'
        );
        
        Profile testProfile = [SELECT Id, Name FROM Profile WHERE Name = 'VC Investor Community Plus Login' LIMIT 1];
    
        Contact getContact = [SELECT Id, Name FROM Contact WHERE FirstName = 'TestPersonAccountFirst'];

        User testUser = new User(
        FirstName = 'TestingUserN2',
        Username = 'testUser_n2@test.com',
        LastName = 'TestAds',
        // ContactId = testContact.Id,
        Email = 'testUser_n2@test.com',
        Alias = 'tuser',
        TimeZoneSidKey = 'America/Los_Angeles',
        LocaleSidKey = 'en_US',
        EmailEncodingKey = 'UTF-8',
        LanguageLocaleKey = 'en_US',
        ProfileId = testProfile.Id,
        ContactId = getContact.Id
        );
        insert testUser;
        
        insert testProduct;
        // Create test Opportunity associated with Account and Product
        Opportunity testOpportunity = new Opportunity(
            Name = 'Test Opportunity',
            AccountId = testAccount.Id,
            StageName = 'Expression of Interest',
            CloseDate = Date.today(),
            Invested_Product_ADMIN_FIELD__c = testProduct.Id,
            Unit_Certificate_Amount__c = 1000.00,
            OwnerId = UserInfo.getUserId(),
            CRC_Assigned__c = testUser.id
        );
        insert testOpportunity;

        // Prepare newOppMap
        Map<Id, Opportunity> newOppMap = new Map<Id, Opportunity>{ testOpportunity.Id => testOpportunity };

        // For insert, oldOppMap is null
        Map<Id, Opportunity> oldOppMap = null;
        Boolean isInsert = true;

        // Instantiate the Queueable class
        ProcessInvestmentRecordQueueable queueable = new ProcessInvestmentRecordQueueable(oldOppMap, newOppMap, isInsert);

        // Execute the Queueable class
        Test.startTest();
        System.enqueueJob(queueable);
        Test.stopTest();

        // Verify that the Investment__c record was created
        //List<Investment__c> investments = [
        //   SELECT Id, Opportunity__c, Investment_Product_Name__c, Investment_Product_Type__c
        //    FROM Investment__c
        //    WHERE Opportunity__c = :testOpportunity.Id
        //];
        //System.assertEquals(1, investments.size(), 'Investment__c record should have been created.');
        //Investment__c inv = investments[0];
        //System.assertEquals(testOpportunity.Id, inv.Opportunity__c, 'Opportunity__c should match the Opportunity Id.');
        //System.assertEquals(testProduct.Name, inv.Investment_Product_Name__c, 'Investment_Product_Name__c should match the Product Name.');
        //System.assertEquals(testProduct.Investment_Product_Type__c, inv.Investment_Product_Type__c, 'Investment_Product_Type__c should match.');
    }

    @isTest
    static void testProcessInvestmentRecordQueueable_Update() {
        User owner = [SELECT Id FROM USER WHERE Name = 'The VentureCrowd Team'];

        Id recordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('VC Person Account').getRecordTypeId();

        // Create test Account
        Account testAccount = new Account(FirstName = 'TestPersonAccountFirst',
            LastName = 'TestPersonAccountLast',
            PersonEmail = 'test@user.com',
            RecordTypeId = recordTypeId,
            // Name = 'Test Account',
            OwnerId = owner.Id);
        insert testAccount;

        // Create test Product2
        Product2 testProduct = new Product2(
            Name = 'Test Product',
            Tile_Banner__c = 'http://example.com/product'
        );
        insert testProduct;
        
        Profile testProfile = [SELECT Id, Name FROM Profile WHERE Name = 'VC Investor Community Plus Login' LIMIT 1];
    
        Contact getContact = [SELECT Id, Name FROM Contact WHERE FirstName = 'TestPersonAccountFirst'];

        User testUser = new User(
        FirstName = 'TestingUserN2',
        Username = 'testUser_n2@test.com',
        LastName = 'TestAds',
        // ContactId = testContact.Id,
        Email = 'testUser_n2@test.com',
        Alias = 'tuser',
        TimeZoneSidKey = 'America/Los_Angeles',
        LocaleSidKey = 'en_US',
        EmailEncodingKey = 'UTF-8',
        LanguageLocaleKey = 'en_US',
        ProfileId = testProfile.Id,
        ContactId = getContact.Id
        );
        insert testUser;

        // Create test Opportunity
        Opportunity testOpportunity = new Opportunity(
           Name = 'Test Opportunity',
            AccountId = testAccount.Id,
            StageName = 'Expression of Interest',
            CloseDate = Date.today(),
            Invested_Product_ADMIN_FIELD__c = testProduct.Id,
            Unit_Certificate_Amount__c = 1000.00,
            OwnerId = UserInfo.getUserId(),
            CRC_Assigned__c = testUser.id
        );
        insert testOpportunity;

        // Clone the old Opportunity for oldMap
        Opportunity oppOld = testOpportunity.clone(false, true, true, true);
        Map<Id, Opportunity> oldOppMap = new Map<Id, Opportunity>{ testOpportunity.Id => oppOld };

        // Update the Opportunity to new stage
        testOpportunity.StageName = 'EOI';
        update testOpportunity;

        // Get the updated Opportunity
        Opportunity oppNew = [
            SELECT Id, StageName, Number_Of_Units__c, Invested_Product_ADMIN_FIELD__c
            FROM Opportunity
            WHERE Id = :testOpportunity.Id
        ];
        Map<Id, Opportunity> newOppMap = new Map<Id, Opportunity>{ oppNew.Id => oppNew };
        Boolean isInsert = false;

        // Instantiate the Queueable class
        ProcessInvestmentRecordQueueable queueable = new ProcessInvestmentRecordQueueable(oldOppMap, newOppMap, isInsert);

        // Execute the Queueable class
        Test.startTest();
        System.enqueueJob(queueable);
        Test.stopTest();

        // Verify that the Investment__c record was created or updated
        //List<Investment__c> investments = [
        //    SELECT Id, Opportunity__c, Purchased_Shares__c
        //    FROM Investment__c
        //    WHERE Opportunity__c = :testOpportunity.Id
        //];
        //System.assertEquals(1, investments.size(), 'Investment__c record should have been created or updated.');
        //Investment__c inv = investments[0];
        //System.assertEquals(testOpportunity.Id, inv.Opportunity__c, 'Opportunity__c should match the Opportunity Id.');
        //System.assertEquals(oppNew.Number_Of_Units__c, inv.Purchased_Shares__c, 'Purchased_Shares__c should match Opportunity Number_Of_Units__c.');
    }
}