common/force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <label>Investment</label>
    <nameField>
        <displayFormat>IN-{00000000}</displayFormat>
        <label>Investment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Investment__c/fields/Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Investments</relationshipLabel>
    <relationshipName>Investments</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <inlineHelpText>The sector that this product operates in</inlineHelpText>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture and Farming</fullName>
            </value>
            <value>
                <fullName>Art and Design</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Banking and Finance</fullName>
            </value>
            <value>
                <fullName>Construction and Real Estate</fullName>
            </value>
            <value>
                <fullName>Defense and Aerospace</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Energy and Utilities</fullName>
            </value>
            <value>
                <fullName>Entertainment and Media</fullName>
            </value>
            <value>
                <fullName>Environmental and Waste Management</fullName>
            </value>
            <value>
                <fullName>Food and Beverage</fullName>
            </value>
            <value>
                <fullName>Healthcare and Pharmaceuticals</fullName>
            </value>
            <value>
                <fullName>Hospitality and Tourism</fullName>
            </value>
            <value>
                <fullName>Human Resources</fullName>
            </value>
            <value>
                <fullName>Information Technology (IT)</fullName>
            </value>
            <value>
                <fullName>Legal Services</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Marketing and Advertising</fullName>
            </value>
            <value>
                <fullName>Nonprofit</fullName>
            </value>
            <value>
                <fullName>Retail and E-commerce</fullName>
            </value>
            <value>
                <fullName>Retail Banking</fullName>
            </value>
            <value>
                <fullName>Security Services</fullName>
            </value>
            <value>
                <fullName>Social Services</fullName>
            </value>
            <value>
                <fullName>Sport and Fitness</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
            <value>
                <fullName>Transportation, Logistics and Mobility</fullName>
            </value>
            <value>
                <fullName>WealthTech</fullName>
                <isActive>false</isActive>
                <label>WealthTech</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/classes/InvestmentIconDesignClass.cls
public without sharing  class  InvestmentIconDesignClass {
  @auraEnabled
    public static String retrivePdtCategory(String recordId){
        Id productId = [select Id,Opportunity_Product__r.Product2Id from Investment__c where Id=:recordId].Opportunity_Product__r.Product2Id;  
        String sector = [select Id,Name,Sector__c from Product2 where Id =: productId ].Sector__c;
         return sector;
     }
   
}