common/force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <label>Investment</label>
    <nameField>
        <displayFormat>IN-{00000000}</displayFormat>
        <label>Investment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Investment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Investments1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Contribution Fee Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Approval Required</fullName>
                <default>true</default>
                <label>No Approval Required</label>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Associated_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Associated_Product_Type__c</fullName>
    <label>Associated Product Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Bpay_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Bpay_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>check this to send the bpay creds email to investor</inlineHelpText>
    <label>Bpay Email Sent</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Delete_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Delete_Opportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this is checked then we will delete this opp by trigger</description>
    <label>Delete Opportunity</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Donation__c.field-meta.xml
<CustomField>
    <fullName>Donation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Donation</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Donation_Related_Investment_Opp__c.field-meta.xml
<CustomField>
    <fullName>Donation_Related_Investment_Opp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>when an investor submits an application from portal and selects a donation amount, this field will be linked to either donation opp or related invested opp.</inlineHelpText>
    <label>Donation / Related Investment Opp</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities (Donation / Related Investment Opp)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Invested_Opp_Prod_ADMIN__c.field-meta.xml
<CustomField>
    <fullName>Invested_Opp_Prod_ADMIN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invested_Opp Prod_ADMIN</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Invested_Product_ADMIN_FIELD__c.field-meta.xml
<CustomField>
    <fullName>Invested_Product_ADMIN_FIELD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please disregard this field. Admin field Only!</inlineHelpText>
    <label>Invested Product_ADMIN FIELD</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Loss_Reasons__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reasons__c</fullName>
    <label>Loss Reasons</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wasp lost tags</fullName>
            </value>
            <value>
                <fullName>CM-wasp-Timing not quite right -but still interested.</fullName>
            </value>
            <value>
                <fullName>CM-wasp-Location based</fullName>
            </value>
            <value>
                <fullName>CM-Wasp-No Trust - does not understand the model</fullName>
            </value>
            <value>
                <fullName>CM-wasp-time waster</fullName>
            </value>
            <value>
                <fullName>Dasp Lost tags</fullName>
            </value>
            <value>
                <fullName>CM- Dasp-Didn’t like the project</fullName>
            </value>
            <value>
                <fullName>CM-Dasp-No Trust - does not understand the model</fullName>
            </value>
            <value>
                <fullName>CM-Dasp-Personal reasons.</fullName>
            </value>
            <value>
                <fullName>CM-Dasp-Advisor</fullName>
            </value>
            <value>
                <fullName>CM-Dasp-Other</fullName>
            </value>
            <value>
                <fullName>Claims they never clicked</fullName>
            </value>
            <value>
                <fullName>Awaiting other Development Results</fullName>
            </value>
            <value>
                <fullName>Does Not Qualify</fullName>
            </value>
            <value>
                <fullName>No Phone Number</fullName>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
            </value>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>Project not suitable</fullName>
            </value>
            <value>
                <fullName>Set up SMSF</fullName>
            </value>
            <value>
                <fullName>Can&apos;t decide</fullName>
            </value>
            <value>
                <fullName>No funds</fullName>
            </value>
            <value>
                <fullName>Timing not right</fullName>
            </value>
            <value>
                <fullName>No Trust</fullName>
            </value>
            <value>
                <fullName>Too risky</fullName>
            </value>
            <value>
                <fullName>Bought another property</fullName>
            </value>
            <value>
                <fullName>Invested Elsewhere</fullName>
            </value>
            <value>
                <fullName>Couldn&apos;t get finance</fullName>
            </value>
            <value>
                <fullName>Don&apos;t have enough in SMSF</fullName>
            </value>
            <value>
                <fullName>No Deposit</fullName>
            </value>
            <value>
                <fullName>Not Ready</fullName>
            </value>
            <value>
                <fullName>Sold to other party</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Original_invested_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Original_invested_Quantity__c</fullName>
    <label>Original invested Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Primary_Contact_email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_email__c</fullName>
    <formula>Primary_Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Contact email</label>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Related_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Related_Product_Code__c</fullName>
    <label>Related Product Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Sent_Verify_ID_Email__c.field-meta.xml
<CustomField>
    <fullName>Sent_Verify_ID_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>this is auto checked when the un verified invertor submits the invest application.</inlineHelpText>
    <label>Sent Verify ID Email</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <label>Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offer Doc sent</fullName>
            </value>
            <value>
                <fullName>Offer Received</fullName>
            </value>
            <value>
                <fullName>Offer Approved</fullName>
            </value>
            <value>
                <fullName>EOI Sent</fullName>
            </value>
            <value>
                <fullName>EOI Received</fullName>
            </value>
            <value>
                <fullName>Contract Issued</fullName>
            </value>
            <value>
                <fullName>Contract signed by Buyer</fullName>
            </value>
            <value>
                <fullName>Contract Executed</fullName>
                <label>Contract Executed (Conditional)</label>
            </value>
            <value>
                <fullName>Contract Unconditional</fullName>
                <label>Contract Executed (Unconditional)</label>
            </value>
            <value>
                <fullName>Awaiting Settlement</fullName>
                <isActive>false</isActive>
                <label>Awaiting Settlement</label>
            </value>
            <value>
                <fullName>Contract Pending</fullName>
                <isActive>false</isActive>
                <label>Contract Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/TSF_Donation_email_sent__c.field-meta.xml
<CustomField>
    <fullName>TSF_Donation_email_sent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check box is used to trigger TSF first email and second email. Please review TSF AR process for details.</description>
    <inlineHelpText>Check box is used to trigger TSF first email and second email. Please review TSF AR process for details.</inlineHelpText>
    <label>TSF Email Trigger ADMIN ONLY</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/TSF_Receipt_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>TSF_Receipt_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TSF Receipt Email Sent</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/recordTypes/Founders.recordType-meta.xml
<RecordType>
    <fullName>Founders</fullName>
    <active>true</active>
    <businessProcess>Founders</businessProcess>
    <label>Founders</label>
</RecordType>

common/force-app/main/default/objects/Opportunity/recordTypes/VC.recordType-meta.xml
<RecordType>
    <fullName>VC</fullName>
    <active>true</active>
    <businessProcess>VC</businessProcess>
    <label>VC</label>
</RecordType>

common/force-app/main/default/objects/Opportunity/recordTypes/VCPP.recordType-meta.xml
<RecordType>
    <fullName>VCPP</fullName>
    <active>true</active>
    <businessProcess>VCPP</businessProcess>
    <label>VCPP</label>
</RecordType>

common/force-app/main/default/objects/OpportunityLineItem/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Approval Required</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/OpportunityLineItem/fields/Original_Invested_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Original_Invested_Quantity__c</fullName>
    <label>Current Holdings</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/OpportunityLineItem/fields/Original_Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Original_Sales_Price__c</fullName>
    <label>Current Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Expression Of Interest</fullName>
            </value>
            <value>
                <fullName>Sold Out</fullName>
            </value>
            <value>
                <fullName>Reserved for Display Home</fullName>
            </value>
            <value>
                <fullName>Reserved for Put and Call</fullName>
            </value>
            <value>
                <fullName>Reserved for builder house and land package</fullName>
            </value>
            <value>
                <fullName>Contract Executed</fullName>
                <isActive>false</isActive>
                <label>Contract Executed</label>
            </value>
            <value>
                <fullName>Contract Pending</fullName>
                <isActive>false</isActive>
                <label>Contract Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Product2/recordTypes/Founders.recordType-meta.xml
<RecordType>
    <fullName>Founders</fullName>
    <active>true</active>
    <description>Founder Products</description>
    <label>Founders</label>
</RecordType>

common/force-app/main/default/objects/Product2/recordTypes/VCPP.recordType-meta.xml
<RecordType>
    <fullName>VCPP</fullName>
    <active>true</active>
    <description>VentureCrowd Property Projects</description>
    <label>VCPP</label>
</RecordType>

common/force-app/main/default/classes/OpportunityProcessor.cls
public with sharing class OpportunityProcessor implements Queueable, Database.AllowsCallouts {
    private List<Opportunity> opportunities;
    private Map<Id, Opportunity> opportunitiesOldMap;
    private Map<Id, Opportunity> opportunitiesNewMap;
    private String updateType;
    
    // Existing constants and variables…
    public static final String LINEITEM_STAGENAME_EOI = 'EOI';
    public static final String LINEITEM_STAGENAME_CONTRACT = 'Contract';
    public static final String LINEITEM_SUBSTAGE_CONTRACT_EXECUTED = 'Contract Executed';
    public static final String PRODUCT_STATUS_EXPRESSION_OF_INTREST = 'Expression Of Interest';
    public static final String PRODUCT_STATUS_SOLD_OUT = 'Sold Out';
    public static final String OPPORTUNITY_STAGE_CLOSED_LOST = 'Closed Lost';
    public static final String OPPORTUNITY_LOST_REASON_SOLD_TO_OTHER_PARTY = 'Sold to other party';
    public static final String OPPORTUNITY_STAGE_SETTLEMENT_BOOKED = 'Settlement Booked';	
    public static final String PRODUCT_STATUS_AVAILABLE = 'Available';	
    public static Boolean emailsent = false;
    public static Id vcpprecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('VCPP').getRecordTypeId();
    public static Boolean isProcessInvestmentRecordRunning = false;
    
    // **Static flag to prevent recursive email processing**
    public static Boolean emailsProcessed = false;
    
    public OpportunityProcessor(List<Opportunity> opportunities, Map<Id, Opportunity> opportunitiesOldMap, 
                                Map<Id, Opportunity> opportunitiesNewMap, String updateType) {
        this.opportunities = opportunities;
        this.updateType = updateType;
        this.opportunitiesOldMap = opportunitiesOldMap;
        this.opportunitiesNewMap = opportunitiesNewMap;
    }
    
    public void execute(QueueableContext context) {
        if(this.updateType == 'AFTER_UPDATE'){
            updateProductStatusOnOpportunityClosure(opportunitiesNewMap, opportunitiesOldMap);
            oppfilesshare();
            oliCurrentValuesIpdate();
            updateChildOLIstatus();
            sendEmails();
        }
        if(this.updateType == 'AFTER_INSERT'){
            sendEmails();
        }
    }
    
    public void sendEmails(){
        // Prevent recursion: if emails have already been processed, exit.
        //if(emailsProcessed){
        //    return;
        //}
        //emailsProcessed = true;
        
        // Re-query the opportunities to ensure you have the latest data.
        Set<Id> oppIds = new Set<Id>();
        for(Opportunity opp : this.opportunities){
            oppIds.add(opp.Id);
        }
        List<Opportunity> currentOpps = [SELECT Id, StageName, RecordTypeId, Related_Product_Code__c, Invested_opp_prod_admin__c, Invested_Product_ADMIN_FIELD__c,
                                  Primary_Contact_email__c, Primary_Contact__c, Bpay_Email_sent__c, TSF_receipt_email_sent__c,
                                  Sent_verify_id_email__c, TSF_Donation_EMail_Sent__c,
                                  Amount, Donation_related_investment_opp__c, Donation__c, Associated_Product_Type__c
                                  FROM Opportunity
                                  WHERE Id IN :oppIds];
        
        System.debug('Opps found:' + JSON.serializePretty(currentOpps));
                                        
        // Cache the VC record type Id.
        Id vcRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('VC').getRecordTypeId();
        List<Opportunity> qualifiedList = new List<Opportunity>();
        List<Opportunity> tsfList = new List<Opportunity>();
        
        // Evaluate each Opportunity against email criteria.
        for(Opportunity opp : currentOpps){
            if(opp.StageName == 'Application Received' &&
               opp.RecordTypeId == vcRecordTypeId &&
               opp.Related_Product_Code__c != 'TSF' &&
               opp.Invested_opp_prod_admin__c != null &&
               opp.Primary_Contact_email__c != null &&
               opp.Primary_Contact__c != null &&
               !opp.Bpay_Email_sent__c &&
               opp.Amount != null &&
               ((opp.Donation_related_investment_opp__c == null && !opp.Donation__c) ||
                (opp.Donation_related_investment_opp__c != null && opp.Donation__c))){
                qualifiedList.add(opp);
            }
            if(opp.StageName == 'Receipt Issued' &&
               opp.RecordTypeId == vcRecordTypeId &&
               opp.Related_Product_Code__c == 'TSF' &&
               opp.Primary_Contact_email__c != null &&
               !opp.TSF_receipt_email_sent__c){
                tsfList.add(opp);
            }
        }
        
        System.debug('Opportunities found 2: ' + JSON.serializePretty(qualifiedList));
        
        // Only enqueue the email job if there is at least one matching record.
        if(!qualifiedList.isEmpty() || !tsfList.isEmpty()){
            Map<Id, Opportunity> oppUpdates = new Map<Id, Opportunity>();
            for(Opportunity opp : currentOpps){
                if(qualifiedList.contains(opp) || tsfList.contains(opp)){
                    Opportunity updatedOpp = new Opportunity(Id = opp.Id);
                    if(qualifiedList.contains(opp)){
                        updatedOpp.Bpay_Email_sent__c = true;
                    }
                    if(tsfList.contains(opp)){
                        updatedOpp.TSF_receipt_email_sent__c = true;
                    }
                    oppUpdates.put(opp.Id, updatedOpp);
                }
            }
            if(!oppUpdates.isEmpty()){
                update oppUpdates.values();
            }
            
            System.debug('Opportunities found 3: ' + JSON.serializePretty(currentOpps));
           
            System.enqueueJob(new QUE_oppEmail(currentOpps));
        }
    }
    
    
    

    public void oppfilesshare(){
        List<Id> oppidlst = new List<Id>();
        for(Opportunity o : this.opportunities){
            if(o.StageName == 'Closed Won')
                oppidlst.add(o.Id);
        }
        if(!oppidlst.isEmpty()){
            sharefiles(oppidlst);
        }
    } 

    public static void sharefiles(List<Id> oppidlst){
        // Bulk query Investments associated with these opportunities.
        Map<Id, Set<Id>> oppVSinv = new Map<Id, Set<Id>>();
        List<Id> invidlst = new List<Id>();
        for(Investment__c i : [SELECT Id, Opportunity__c FROM Investment__c WHERE Opportunity__c IN :oppidlst]){
            if(!oppVSinv.containsKey(i.Opportunity__c)){
                oppVSinv.put(i.Opportunity__c, new Set<Id>());
            }
            oppVSinv.get(i.Opportunity__c).add(i.Id);
            invidlst.add(i.Id);
        }
        List<ContentDocumentLink> cdlst = new List<ContentDocumentLink>();
        if(!oppVSinv.keySet().isEmpty()){
            cdlst = [SELECT Id, LinkedEntityId, ContentDocumentId, ContentDocument.Title 
                     FROM ContentDocumentLink WHERE LinkedEntityId IN :oppVSinv.keySet()];
        }
        List<ContentDocumentLink> childidlst = new List<ContentDocumentLink>();
        if(!invidlst.isEmpty()){
            childidlst = [SELECT Id, LinkedEntityId, ContentDocumentId, ContentDocument.Title 
                          FROM ContentDocumentLink WHERE LinkedEntityId IN :invidlst];
        }
        // Build a map for existing child links.
        Map<Id, Set<Id>> childmap = new Map<Id, Set<Id>>();
        for(ContentDocumentLink c : childidlst){
            if(!childmap.containsKey(c.LinkedEntityId)){
                childmap.put(c.LinkedEntityId, new Set<Id>());
            }
            childmap.get(c.LinkedEntityId).add(c.ContentDocumentId);
        }
        // Create new ContentDocumentLink records as needed.
        List<ContentDocumentLink> cdlinsert = new List<ContentDocumentLink>();
        for(ContentDocumentLink cd : cdlst){
            if(!cd.ContentDocument.Title.containsIgnoreCase('INTERNAL-')){
                for(Id i : oppVSinv.get(cd.LinkedEntityId)){
                    if(childmap.get(i) == null || !childmap.get(i).contains(cd.ContentDocumentId)){
                        ContentDocumentLink c = new ContentDocumentLink();
                        c.ContentDocumentId = cd.ContentDocumentId;
                        c.LinkedEntityId = i;
                        c.ShareType = 'V';
                        c.Visibility = 'AllUsers';
                        cdlinsert.add(c);
                    }
                }
            }
        }
        if(!cdlinsert.isEmpty()){
            insert cdlinsert;
        }
    }

    public void oliCurrentValuesIpdate(){
        if(this.opportunities == null || this.opportunitiesOldMap == null) {
            return;
        }
        List<Id> oppidlst = new List<Id>();
        for(Opportunity o : this.opportunities){
            // Compare current StageName with the old value.
            if(o.StageName == 'Closed Won' && o.StageName != this.opportunitiesOldMap.get(o.Id).get('StageName')){
                oppidlst.add(o.Id);
            }
        }
        if(!oppidlst.isEmpty()){
            List<OpportunityLineItem> olilst = new List<OpportunityLineItem>();
            for(OpportunityLineItem oli : [SELECT Id, Quantity, UnitPrice 
                                            FROM OpportunityLineItem 
                                            WHERE OpportunityId IN :oppidlst]){
                oli.Original_Invested_Quantity__c = oli.Quantity;
                oli.Original_Sales_Price__c = oli.UnitPrice * oli.Quantity;
                olilst.add(oli);
            }
            if(!olilst.isEmpty()){
                update olilst;
            }
        }
    }

    public void updateChildOLIstatus(){
        // Check if maps are provided to avoid NullPointerException
        if(this.opportunitiesOldMap == null || this.opportunitiesNewMap == null) {
            return;
        }
        Set<Id> oppIdset = new Set<Id>();
        for(Opportunity opp : this.opportunities){
            // Ensure we have an old version for comparison
            Opportunity oldOpp = this.opportunitiesOldMap.get(opp.Id);
            if(oldOpp != null &&
               (opp.Approval_Status__c == 'Completed' || opp.Approval_Status__c == 'Rejected') &&
               oldOpp.get('Approval_Status__c') != opp.Approval_Status__c) {
                oppIdset.add(opp.Id);
            }
        }
        if(!oppIdset.isEmpty()){
            List<OpportunityLineItem> oliList = new List<OpportunityLineItem>();
            for(OpportunityLineItem oli : [
                SELECT Id, OpportunityId 
                FROM OpportunityLineItem 
                WHERE OpportunityId IN :oppIdset
            ]){
                // Get the new version of the Opportunity for this OLI
                Opportunity newOpp = this.opportunitiesNewMap.get(oli.OpportunityId);
                // Update the Approval_Status__c based on the new Opportunity's status if available
                if(newOpp != null && newOpp.get('Approval_Status__c') == 'Completed'){
                    oli.Approval_Status__c = 'Completed';
                } else {
                    oli.Approval_Status__c = 'Rejected';
                }
                oliList.add(oli);
            }
            if(!oliList.isEmpty()){
                update oliList;
            }
        }
    }
    

    // ----------------------- UPDATED METHOD WITH FOUNDER FILTERING -----------------------
    public void updateProductStatusOnOpportunityClosure(Map<Id, Opportunity> mapNewOpportunity, Map<Id, Opportunity> mapOldOpportunity) {
        // Safely retrieve the 'Founders' record type Id.
        Map<String, Schema.RecordTypeInfo> rtMap = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName();
        Id foundersRecordTypeId = rtMap.containsKey('Founders') ? rtMap.get('Founders').getRecordTypeId() : null;
        Set<Id> foundersRecordTypeIds = new Set<Id>();
        if (foundersRecordTypeId != null) {
            foundersRecordTypeIds.add(foundersRecordTypeId);
        }
        
        // If mapNewOpportunity is null, exit early.
        if (mapNewOpportunity == null) {
            return;
        }
        
        Map<Id, Opportunity> updatedOpportunities = new Map<Id, Opportunity>();
        Set<Id> soldOutOppSet = new Set<Id>();
    
        for (Id oppId : mapNewOpportunity.keySet()) {
            Opportunity newOpp = mapNewOpportunity.get(oppId);
            // Make sure we have an old version before comparing.
            Opportunity oldOpp = (mapOldOpportunity != null) ? mapOldOpportunity.get(oppId) : null;
            if (oldOpp == null) {
                continue;
            }
            // Process if StageName has changed (and either no 'Founders' record type exists or the opportunity is not a Founder)
            // OR if the Sub_Stage__c has changed.
            if (((newOpp.StageName != oldOpp.StageName && (foundersRecordTypeIds.isEmpty() || !foundersRecordTypeIds.contains(newOpp.RecordTypeId)))
                 || newOpp.Sub_Stage__c != oldOpp.Sub_Stage__c)
                && (newOpp.StageName == LINEITEM_STAGENAME_EOI || newOpp.StageName == LINEITEM_STAGENAME_CONTRACT)) {
                updatedOpportunities.put(oppId, newOpp);
                if (newOpp.StageName == LINEITEM_STAGENAME_CONTRACT) {
                    soldOutOppSet.add(oppId);
                }
            }
        }
        if (!soldOutOppSet.isEmpty()) {
            createTaskOnSoldOutProduct(soldOutOppSet);
        }
        if (!updatedOpportunities.isEmpty()) {
            List<OpportunityLineItem> oppLineItemList = [SELECT Id, Product2Id, OpportunityId, Opportunity.StageName, Opportunity.Sub_Stage__c 
                                                          FROM OpportunityLineItem 
                                                          WHERE OpportunityId IN :updatedOpportunities.keySet()];
            try {
                if (!oppLineItemList.isEmpty()) {
                    // Use a map to track products to update.
                    Map<Id, Product2> toBeUpdatedProductMap = new Map<Id, Product2>();
                    for (OpportunityLineItem oli : oppLineItemList) {
                        String oppStage = oli.Opportunity.StageName;
                        if (oppStage == LINEITEM_STAGENAME_EOI) {
                            if (!toBeUpdatedProductMap.containsKey(oli.Product2Id)) {
                                toBeUpdatedProductMap.put(oli.Product2Id, new Product2(
                                    Id = oli.Product2Id,
                                    Status__c = PRODUCT_STATUS_EXPRESSION_OF_INTREST
                                ));
                            }
                        }
                        if (oppStage == LINEITEM_STAGENAME_CONTRACT) {
                            if (!toBeUpdatedProductMap.containsKey(oli.Product2Id)) {
                                toBeUpdatedProductMap.put(oli.Product2Id, new Product2(
                                    Id = oli.Product2Id,
                                    Status__c = PRODUCT_STATUS_SOLD_OUT
                                ));
                            }
                            if (toBeUpdatedProductMap.containsKey(oli.Product2Id) &&
                                toBeUpdatedProductMap.get(oli.Product2Id).Status__c != PRODUCT_STATUS_SOLD_OUT) {
                                toBeUpdatedProductMap.get(oli.Product2Id).Status__c = PRODUCT_STATUS_SOLD_OUT;
                            }
                        }
                    }
                    if (!toBeUpdatedProductMap.isEmpty()) {
                        Database.SaveResult[] updateResult = Database.update(toBeUpdatedProductMap.values(), false);
                        Set<Id> updatedProductIdSet = new Set<Id>();
                        for (Database.SaveResult sr : updateResult) {
                            if (sr.isSuccess() && toBeUpdatedProductMap.get(sr.getId()).Status__c == PRODUCT_STATUS_SOLD_OUT) {
                                updatedProductIdSet.add(sr.getId());
                            }
                        }
                        if (!updatedProductIdSet.isEmpty()) {
                            List<OpportunityLineItem> finalOppLineItemList = [SELECT Id, Product2Id, OpportunityId 
                                                                               FROM OpportunityLineItem 
                                                                               WHERE Product2Id IN :updatedProductIdSet 
                                                                               AND Opportunity.StageName <> 'Closed Lost'];
                            Set<Id> oppIdToUpdate = new Set<Id>();
                            for (OpportunityLineItem oli : finalOppLineItemList) {
                                if (!mapNewOpportunity.containsKey(oli.OpportunityId)) {
                                    oppIdToUpdate.add(oli.OpportunityId);
                                }
                            }
                            if (!oppIdToUpdate.isEmpty()) {
                                List<Opportunity> tobeUpdatedOpps = new List<Opportunity>();
                                for (Id oppId : oppIdToUpdate) {
                                    tobeUpdatedOpps.add(new Opportunity(
                                        Id = oppId,
                                        StageName = OPPORTUNITY_STAGE_CLOSED_LOST,
                                        Loss_Reasons__c = OPPORTUNITY_LOST_REASON_SOLD_TO_OTHER_PARTY
                                    ));
                                }
                                if (!tobeUpdatedOpps.isEmpty()) {
                                    Database.SaveResult[] updateOppResults = Database.update(tobeUpdatedOpps, false);
                                    for (Database.SaveResult sr : updateOppResults) {
                                        if (!sr.isSuccess()) {
                                            System.debug('failure>>>' + sr.getErrors());
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            } catch (Exception e) {
                System.debug('Something went wrong: ' + e.getMessage());
            }
        }
    }
    
    // ---------------------------------------------------------------------------------------

    // ----------------------- NEW METHOD: createTaskOnSoldOutProduct -----------------------
    public void createTaskOnSoldOutProduct(Set<Id> oppsId) {
        // Query OpportunityLineItems for given opportunities.
        Set<Id> prodIdSet = new Set<Id>();
        for(OpportunityLineItem oli : [SELECT Id, Product2Id FROM OpportunityLineItem WHERE OpportunityId IN :oppsId]){
            prodIdSet.add(oli.Product2Id);
        }
        
        // Build tasks for opportunities (excluding those in oppsId) that share these products.
        List<Task> newTaskList = new List<Task>();
        Set<Id> opportunityIdSet = new Set<Id>();
        if(!prodIdSet.isEmpty()){
            for(OpportunityLineItem oli : [SELECT Id, OpportunityId, Opportunity.OwnerId 
                                           FROM OpportunityLineItem 
                                           WHERE Product2Id IN :prodIdSet 
                                           AND OpportunityId NOT IN :oppsId 
                                           AND Opportunity.RecordTypeId = :vcpprecordTypeId 
                                           AND Opportunity.delete_opportunity__c = false]){
                Task tasObj = new Task();
                tasObj.OwnerId = oli.Opportunity.OwnerId;
                tasObj.ActivityDate = System.today() + 1;
                tasObj.Subject = 'This Lot is currently unavailable';
                tasObj.Description = 'This opportunity has been moved to Closed Lost because another opportunity associated with this product is marked as Sold Out. Please try to sell this client another product if available.';
                tasObj.WhatId = oli.OpportunityId;
                newTaskList.add(tasObj);
                opportunityIdSet.add(oli.OpportunityId);
            }
        }
        if(!newTaskList.isEmpty()){
            insert newTaskList;
        }
        if(!opportunityIdSet.isEmpty()){
            updateOpportunities(opportunityIdSet);
        }
    }
    // ---------------------------------------------------------------------------------------

    // ----------------------- UPDATED FUTURE METHOD WITH FOUNDER FILTERING -----------------------
    @future 
    public static void updateOpportunities(Set<Id> oppSet) {
        // Safely retrieve the 'Founders' record type Id.
        Map<String, Schema.RecordTypeInfo> rtMap = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName();
        Id foundersRecordTypeId = rtMap.containsKey('Founders') ? rtMap.get('Founders').getRecordTypeId() : null;
        
        List<Opportunity> oppList = [SELECT Id, RecordTypeId FROM Opportunity WHERE Id IN :oppSet];
        List<Opportunity> updateOppList = new List<Opportunity>();
        for (Opportunity opp : oppList) {
            if (foundersRecordTypeId == null || opp.RecordTypeId != foundersRecordTypeId) {
                opp.StageName = 'Closed Lost';
                opp.Loss_Reasons__c = 'Product Unavailable';
                updateOppList.add(opp);
            }
        }
        if (!updateOppList.isEmpty()) {
            update updateOppList;
        }
    }

    // ---------------------------------------------------------------------------------------
}