common/force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <label>Investment</label>
    <nameField>
        <displayFormat>IN-{00000000}</displayFormat>
        <label>Investment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Investment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investments</relationshipLabel>
    <relationshipName>Investments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Investments1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Process_Fund_Disbursement__c.field-meta.xml
<CustomField>
    <fullName>Process_Fund_Disbursement__c</fullName>
    <defaultValue>false</defaultValue>
    <description>this field will be utilised when the partial/full fund is disbursed.</description>
    <inlineHelpText>checking the box will effect the portfolio summary on investor portal</inlineHelpText>
    <label>Process Fund Disbursement</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Delete_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Delete_Opportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this is checked then we will delete this opp by trigger</description>
    <label>Delete Opportunity</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Invested_Product_ADMIN_FIELD__c.field-meta.xml
<CustomField>
    <fullName>Invested_Product_ADMIN_FIELD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please disregard this field. Admin field Only!</inlineHelpText>
    <label>Invested Product_ADMIN FIELD</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Offer_Launch_Date__c.field-meta.xml
<CustomField>
    <fullName>Offer_Launch_Date__c</fullName>
    <description>The date that Capital Raising launched the offer to market</description>
    <label>Offer Launch Date</label>
    <type>DateTime</type>
</CustomField>

common/force-app/main/default/classes/investmentHelperTest.cls
@istest
class investmentHelperTest {
    @isTest
    static void testmethod1(){
        Test.startTest();
        Account acc = new Account();
        acc.name = 'Test Acount';
        insert acc;
        Id pricebookId = Test.getStandardPricebookId();               

        //Create Product
        Product2 oProduct = new Product2(name='Test');
        oProduct.Offer_Launch_Date__c = System.today().addDays(-4);
        insert oProduct;

        Opportunity oppObj = new Opportunity();
        oppObj.name = 'Test1lname';
        oppObj.stageName = 'Why Appt Set Pending';
        oppObj.Pricebook2Id = pricebookId;
        date dt = System.today();
        dt = dt.addDays(5);
        oppObj.delete_opportunity__c = true;
        oppObj.closedate = dt;
        oppObj.Amount = 50000;
        oppObj.Invested_Product_ADMIN_FIELD__c = oProduct.Id;
        insert oppObj;
        Investment__c inv = new Investment__c();
        inv.Account__c = acc.Id;
        inv.Opportunity__c = oppObj.Id;
        inv.Process_Fund_Disbursement__c  =  TRUE;
        insert inv;
        investmentHelper.getInvestments();
    }
}