common/force-app/main/default/objects/Contact/fields/EIC_Property__c.field-meta.xml
<CustomField>
    <fullName>EIC_Property__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EIC Property</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Charity</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Conveyancer</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Development Manager</fullName>
            </value>
            <value>
                <fullName>Financial Adviser</fullName>
            </value>
            <value>
                <fullName>Fund Manager</fullName>
            </value>
            <value>
                <fullName>Integrator</fullName>
            </value>
            <value>
                <fullName>Investor</fullName>
            </value>
            <value>
                <fullName>Mortgage Broker</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Press</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Real Estate Agent</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Special Purpose Vehicle</fullName>
            </value>
            <value>
                <fullName>Trustee Company</fullName>
            </value>
            <value>
                <fullName>Venture Capital Business</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <displayFormat>MN-{0000000}</displayFormat>
        <label>Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Membership__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/Membership__c/fields/Eligible_from__c.field-meta.xml
<CustomField>
    <fullName>Eligible_from__c</fullName>
    <label>Eligible from</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Membership__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wholesale</fullName>
            </value>
            <value>
                <fullName>EIC - Property</fullName>
            </value>
            <value>
                <fullName>EIC - Start up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/classes/BAT_membershipCheckTest.cls
@istest
class BAT_membershipCheckTest {
    @istest
    static void testmethod1(){
        Id personaccId  = [SELECT Id,recordtype.Name,SobjectType FROM recordtype WHERE Name ='VC Person Account'].Id;
        Id platinumpartner  = [SELECT Id,recordtype.Name,SobjectType FROM recordtype WHERE Name ='Platinum Partner'].Id;
        Account acc = new Account();
        acc.LastName = 'Test Acount';
        acc.RecordTypeId = personaccId;
        insert acc;
        contact con = [SELECT ID FROM CONTACT WHERE AccountId = :acc.Id];
        con.EIC_Property__c = true;
        update con;
        Membership__c m = new Membership__c();
        m.Account__c = acc.Id;
        m.RecordTypeId = platinumpartner;
        m.Type__c = 'Platinum Partner';
        m.End_Date__c = system.Today().addDays(-1);
        m.Start_Date__c = system.Today().addDays(-2);
        m.Eligible_from__c = system.Today().addDays(-2);
        insert m;
        system.debug([SELECT Id,Account__c,Account__r.EIC_Property__pc, Account__r.Wholesale__pc, Account__r.EIC_Startup__pc FROM Membership__c]);
        Database.executeBatch(new BAT_membershipCheck());
        System.schedule('test', '0 00 05 ? * 2', new BAT_membershipCheck());
    }
}