common/force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Charity</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Conveyancer</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Development Manager</fullName>
            </value>
            <value>
                <fullName>Financial Adviser</fullName>
            </value>
            <value>
                <fullName>Fund Manager</fullName>
            </value>
            <value>
                <fullName>Integrator</fullName>
            </value>
            <value>
                <fullName>Investor</fullName>
            </value>
            <value>
                <fullName>Mortgage Broker</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Press</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Real Estate Agent</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Special Purpose Vehicle</fullName>
            </value>
            <value>
                <fullName>Trustee Company</fullName>
            </value>
            <value>
                <fullName>Venture Capital Business</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Image_Info__c/Image_Info__c.object-meta.xml
<CustomObject>
    <label>Image Info</label>
    <nameField>
        <displayFormat>IMG-{0000}</displayFormat>
        <label>Image Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Image infos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Image_Info__c/fields/Image_Public_URL__c.field-meta.xml
<CustomField>
    <fullName>Image_Public_URL__c</fullName>
    <label>Image Public URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Image_Info__c/fields/Image_Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Image_Unique_Name__c</fullName>
    <label>Image Unique Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

common/force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <label>Investment</label>
    <nameField>
        <displayFormat>IN-{00000000}</displayFormat>
        <label>Investment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Investment__c/fields/Current_Value__c.field-meta.xml
<CustomField>
    <fullName>Current_Value__c</fullName>
    <formula>&quot;$&quot;
+
IF(LEN(TEXT(MFLOOR(Opportunity_Product__r.ListPrice)))&gt;3,
    IF(LEN(TEXT(MFLOOR(Opportunity_Product__r.ListPrice)))&gt;6,
        LEFT(TEXT(MFLOOR(Opportunity_Product__r.ListPrice)),LEN(TEXT(MFLOOR(Opportunity_Product__r.ListPrice)))-6)+&quot;,&quot;+LEFT(RIGHT(TEXT(MFLOOR(Opportunity_Product__r.ListPrice)),6),3)+&quot;,&quot;+RIGHT(TEXT(MFLOOR(Opportunity_Product__r.ListPrice)),3),
        LEFT(TEXT(MFLOOR(Opportunity_Product__r.ListPrice)),LEN(TEXT(MFLOOR(Opportunity_Product__r.ListPrice)))-3)+&quot;,&quot;+RIGHT(TEXT(MFLOOR(Opportunity_Product__r.ListPrice)),3)),
TEXT(MFLOOR(Opportunity_Product__r.ListPrice)))
+
IF(MOD(Opportunity_Product__r.ListPrice , 1) = 0,&apos;.00&apos;,TEXT(MOD(Opportunity_Product__r.ListPrice , 1)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Value</label>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Purchased_Shares__c.field-meta.xml
<CustomField>
    <fullName>Purchased_Shares__c</fullName>
    <label>Investment Holding</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/News_List_Page__c.object-meta.xml
<CustomObject>
    <label>News List Page</label>
    <nameField>
        <displayFormat>LP-{00000}</displayFormat>
        <label>ListPage Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>News List Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/News_List_Page__c/fields/CategoryBanner_Img_Url__c.field-meta.xml
<CustomField>
    <fullName>CategoryBanner_Img_Url__c</fullName>
    <description>Category Image Banner image URL</description>
    <label>CategoryBanner_Img_Url</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Likes_Number__c.field-meta.xml
<CustomField>
    <fullName>Likes_Number__c</fullName>
    <label>Likes Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Navigation_url__c.field-meta.xml
<CustomField>
    <fullName>Navigation_url__c</fullName>
    <label>Navigation url</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/News_Category__c.field-meta.xml
<CustomField>
    <fullName>News_Category__c</fullName>
    <label>News Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/News_Descriptions__c.field-meta.xml
<CustomField>
    <fullName>News_Descriptions__c</fullName>
    <label>News Descriptions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/News_Label__c.field-meta.xml
<CustomField>
    <fullName>News_Label__c</fullName>
    <label>News Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Newsbg_Url__c.field-meta.xml
<CustomField>
    <fullName>Newsbg_Url__c</fullName>
    <label>Newsbg Url</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Publish_On_Community_Site__c.field-meta.xml
<CustomField>
    <fullName>Publish_On_Community_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean flag to decide if this blog should be visible or not.</description>
    <inlineHelpText>Boolean flag to decide if this blog should be visible or not.</inlineHelpText>
    <label>Publish On Community Site</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/src_url__c.field-meta.xml
<CustomField>
    <fullName>src_url__c</fullName>
    <description>Source URL</description>
    <label>src url</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Tagged_category__c.field-meta.xml
<CustomField>
    <fullName>Tagged_category__c</fullName>
    <description>This is the URL for tagged category on the top corner</description>
    <inlineHelpText>This is the URL for tagged category on the top corner</inlineHelpText>
    <label>Tagged category</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VC Product</fullName>
                <label>VC Product - Wholesale</label>
            </value>
            <value>
                <fullName>Property Product</fullName>
            </value>
            <value>
                <fullName>CSF Product</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>PSP Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/OpportunityLineItem/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Button_Text__c.field-meta.xml
<CustomField>
    <fullName>Button_Text__c</fullName>
    <label>Button Text</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Deal_Description__c.field-meta.xml
<CustomField>
    <fullName>Deal_Description__c</fullName>
    <label>Deal Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Deal_Page_Link__c.field-meta.xml
<CustomField>
    <fullName>Deal_Page_Link__c</fullName>
    <label>Deal Page Link</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/FAQ_s__c.field-meta.xml
<CustomField>
    <fullName>FAQ_s__c</fullName>
    <label>FAQ&apos;s</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Fully_Funded__c.field-meta.xml
<CustomField>
    <fullName>Fully_Funded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fully Funded</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Private_Deal__c.field-meta.xml
<CustomField>
    <fullName>Private_Deal__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box for private deals that are not to be publicly published on the community site but are visible by invite to the URL.</inlineHelpText>
    <label>Private Deal</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Publish_on_Community_Site__c.field-meta.xml
<CustomField>
    <fullName>Publish_on_Community_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publish on Community Site</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Return_Type__c.field-meta.xml
<CustomField>
    <fullName>Return_Type__c</fullName>
    <label>Return Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Per Annum</fullName>
            </value>
            <value>
                <fullName>Fixed Return</fullName>
            </value>
            <value>
                <fullName>Variable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Sector_Personas__c.field-meta.xml
<CustomField>
    <fullName>Sector_Personas__c</fullName>
    <description>The personas that this product is suitable for</description>
    <label>Sector/Personas</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Just Launchers</fullName>
            </value>
            <value>
                <fullName>Sharp Shooters</fullName>
            </value>
            <value>
                <fullName>Prosperity Builders</fullName>
            </value>
            <value>
                <fullName>Grand Designers</fullName>
            </value>
            <value>
                <fullName>Wholesale/Sophisticated Investors</fullName>
            </value>
            <value>
                <fullName>Retail Investors</fullName>
            </value>
            <value>
                <fullName>Property Investors</fullName>
            </value>
            <value>
                <fullName>ARE Auckland Real Estate Management - property and Asset managers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Tile_Banner__c.field-meta.xml
<CustomField>
    <fullName>Tile_Banner__c</fullName>
    <label>Tile Banner</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Tile_Heading__c.field-meta.xml
<CustomField>
    <fullName>Tile_Heading__c</fullName>
    <label>Tile Heading</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Tile_Offer_Type__c.field-meta.xml
<CustomField>
    <fullName>Tile_Offer_Type__c</fullName>
    <label>Tile Offer Type</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Tile_Ordering__c.field-meta.xml
<CustomField>
    <fullName>Tile_Ordering__c</fullName>
    <label>Tile Ordering</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Trust_Deed_Link__c.field-meta.xml
<CustomField>
    <fullName>Trust_Deed_Link__c</fullName>
    <label>Trust Deed Link</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VC Product</fullName>
            </value>
            <value>
                <fullName>Property Product</fullName>
            </value>
            <value>
                <fullName>CSF Product</fullName>
            </value>
            <value>
                <fullName>CSF Nominee</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>PSP Product</fullName>
            </value>
            <value>
                <fullName>Retail IPO</fullName>
            </value>
            <value>
                <fullName>Retail MIS</fullName>
            </value>
            <value>
                <fullName>Vest</fullName>
            </value>
            <value>
                <fullName>CIF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/classes/ProductController.cls
global without sharing  class ProductController{
  public List<product2> prodList{get; set;}
  public List<product2> prodListHome{get; set;}
  public List<product2> prodListProperty{get; set;}
  public List<product2> successfulDealList{get; set;}
  public List<News_List_Page__c> newsBlogList{get; set;}
  Map<Id,News_List_Page__c> newsMap;
  public String baseUrl{get; set;}
  public Id currentblogrecId{get; set;}
  public Boolean showall{get;set;}
  public Boolean showacategory{get;set;}
   public Map<String,String> imageNameURLMap{get;set;}
  
   //public List<News_List_Page__c> currentnewsList{get;set;}
  // public String currentcategory {get;set;}
  //public List<prodWrapper> productWrapLst{get; set;}
  
  global ProductController(){ 
      
     // For adding Image in the VF page 
       imageNameURLMap=new  Map<String,String>();
      for(Image_Info__c img:[Select Image_Unique_Name__c,Image_Public_URL__C from Image_Info__c]){
        this.imageNameURLMap.put(img.Image_Unique_Name__c,img.Image_Public_URL__C);  
      }
      
      
      this.showall=true;
      this.showacategory=false;
      // Method to check of environement is Production ORG or not
      baseUrl = URL.getSalesforceBaseUrl().toExternalForm();
      
      //################## Property Page Product #######################

      prodListProperty = [select id,Name,Family,DisplayUrl,Deal_Page_Link__c,Trust_Deed_Link__c,Sector_Personas__c,
                 ProductCode,FAQ_s__c,Fully_Funded__c,Return_Type__c,Deal_Description__c, Tile_Banner__c, Tile_Heading__c, Tile_Offer_Type__c, Button_Text__c 
                 from  product2 where Publish_on_Community_Site__c = TRUE  AND  IsActive = TRUE AND Private_Deal__c = FALSE AND Fully_Funded__c = FALSE AND Type__c in ('Property Product') order by Tile_Ordering__c LIMIT 199];
      
      // ########## Product list Home #############
      prodListHome =[select id,Name,Family,DisplayUrl,Deal_Page_Link__c,Trust_Deed_Link__c,Sector_Personas__c,
                     ProductCode,FAQ_s__c,Fully_Funded__c,Return_Type__c,Deal_Description__c,  Tile_Banner__c, Tile_Heading__c, Tile_Offer_Type__c, Button_Text__c 
                     from  product2 where Publish_on_Community_Site__c = TRUE  AND  IsActive = TRUE AND Private_Deal__c = FALSE AND Fully_Funded__c = FALSE order by Tile_Ordering__c LIMIT 3];
      
      
      
      // ########## Product list query #############
      prodList =[select id,Name,Family,DisplayUrl,Deal_Page_Link__c,Trust_Deed_Link__c,Sector_Personas__c,
                 ProductCode,FAQ_s__c,Fully_Funded__c,Return_Type__c,Deal_Description__c, Tile_Banner__c, Tile_Heading__c, Tile_Offer_Type__c, Button_Text__c 
                 from  product2 where Publish_on_Community_Site__c = TRUE  AND  IsActive = TRUE AND Private_Deal__c = FALSE AND Fully_Funded__c = FALSE order by Tile_Ordering__c LIMIT 199];
      
      
      // ########## Successful Deal list query #############
      successfulDealList =[select id,Name,Family,DisplayUrl,Deal_Page_Link__c,Trust_Deed_Link__c,Sector_Personas__c,Deal_Description__c,
                           ProductCode,FAQ_s__c,Fully_Funded__c,Return_Type__c, Tile_Banner__c, Tile_Heading__c, Tile_Offer_Type__c, Button_Text__c from  product2 where IsActive = TRUE AND Fully_Funded__c = TRUE AND Private_Deal__c = FALSE order by Tile_Ordering__c LIMIT 199];
      
      
      // ########## News blog tile information query #############
      
      newsBlogList = [SELECT Id, News_Label__c, Tagged_category__c, Date__c, News_Category__c, News_Descriptions__c, Likes_Number__c, Newsbg_Url__c,  src_url__c, Navigation_url__c FROM News_List_Page__c ORDER BY Date__c DESC LIMIT 199];
      newsMap=new Map<Id,News_List_Page__c>(newsBlogList);
      // for(News_List_Page__c nlp:newsBlogList){
      //     prodWrapper pw = new prodWrapper();
      
      //     Date d = nlp.Date__c;
      //     String dt = DateTime.newInstance(d.year(),d.month(),d.day()).format('MMMM d YYYY');
      
      
      //     pw.nlabel = nlp.News_Label__c;
      //     pw.ndate = dt;
      //     pw.ncateg = nlp.News_Category__c;
      //     pw.ndes = nlp.News_Descriptions__c;
      //     pw.lnum = nlp.Likes_Number__c;
      //     pw.nimgUrl = nlp.Newsbg_Url__c;
      //     productWrapLst.add(pw);
      //   }
  }
  public void likeblog(){
      System.debug('liking news Id='+this.currentblogrecId);
      System.debug('liking news ='+newsMap.get(this.currentblogrecId));
      News_List_Page__c currentNews=newsMap.get(this.currentblogrecId);
      currentNews.Likes_Number__c=currentNews.Likes_Number__c!=null?currentNews.Likes_Number__c+1:1;
      update currentNews;
      newsBlogList = [SELECT Id, News_Label__c,CategoryBanner_Img_Url__c, Tagged_category__c, Date__c, News_Category__c, News_Descriptions__c, Likes_Number__c, Newsbg_Url__c,  src_url__c, Navigation_url__c FROM News_List_Page__c ORDER BY Id LIMIT 199];
      newsMap=new Map<Id,News_List_Page__c>(newsBlogList);
      system.debug('after update newsBlogList='+newsBlogList);
      
     // return null;
  }
  
/*  public void categorychange(){
      
      String category=this.currentcategory;
      system.debug(' categorychange category=>>'+category);
      this.showall=false;
      this.showacategory=true;
      this.currentnewsList=[SELECT Id, News_Label__c,CategoryBanner_Img_Url__c, Tagged_category__c, Date__c, News_Category__c, News_Descriptions__c, Likes_Number__c, Newsbg_Url__c,  src_url__c, Navigation_url__c FROM News_List_Page__c where News_Category__c=:category ORDER BY Date__c DESC LIMIT 199];

  }*/
  
  // public class prodWrapper{
  //   public string nlabel{get;set;}
  //   public string ndate{get;set;}
  //   public string ncateg{get;set;}
  //   public string ndes{get;set;}
  //   public decimal lnum{get;set;}
  //   public String nimgUrl{get;set;}
  // }
  @AuraEnabled(Cacheable=true)
  public static List<Product2> getProducts(Boolean isSucessfull, String productType){
    if(productType=='' || productType==null){
    
    if(isSucessfull){
                 return [select id,Name,Family,DisplayUrl,Deal_Page_Link__c,Trust_Deed_Link__c,Sector_Personas__c,Tile_Ordering__c,
                           ProductCode,FAQ_s__c,Fully_Funded__c,Return_Type__c,Deal_Description__c, Tile_Banner__c, Tile_Heading__c, Tile_Offer_Type__c, Button_Text__c from  product2 where IsActive = TRUE AND Fully_Funded__c = TRUE AND Private_Deal__c = FALSE order by Tile_Ordering__c LIMIT 199];
      
      
      }
       return  [select id,Name,Family,DisplayUrl,Deal_Page_Link__c,Trust_Deed_Link__c,Sector_Personas__c,Tile_Ordering__c,
                 ProductCode,FAQ_s__c,Fully_Funded__c,Return_Type__c,Deal_Description__c, Tile_Banner__c, Tile_Heading__c, Tile_Offer_Type__c, Button_Text__c 
                 from  product2 where Publish_on_Community_Site__c = TRUE  AND IsActive = TRUE AND Private_Deal__c = FALSE AND Fully_Funded__c = FALSE order by Tile_Ordering__c LIMIT 199];
      
  } else {
    List<string> prodlst = productType.split(',');
    if(isSucessfull){
      return [select id,Name,Family,DisplayUrl,Deal_Page_Link__c,Trust_Deed_Link__c,Sector_Personas__c,Tile_Ordering__c,
                ProductCode,FAQ_s__c,Fully_Funded__c,Return_Type__c,Deal_Description__c, Tile_Banner__c, Tile_Heading__c, Tile_Offer_Type__c, Button_Text__c from  product2 where IsActive = TRUE AND Fully_Funded__c = TRUE AND Private_Deal__c = FALSE AND Type__c in :prodlst order by Tile_Ordering__c LIMIT 199];
}
return  [select id,Name,Family,DisplayUrl,Deal_Page_Link__c,Trust_Deed_Link__c,Sector_Personas__c,Tile_Ordering__c,
      ProductCode,FAQ_s__c,Fully_Funded__c,Return_Type__c,Deal_Description__c, Tile_Banner__c, Tile_Heading__c, Tile_Offer_Type__c, Button_Text__c 
      from  product2 where Publish_on_Community_Site__c = TRUE  AND IsActive = TRUE AND Private_Deal__c = FALSE AND Fully_Funded__c = FALSE AND Type__c in :prodlst order by Tile_Ordering__c LIMIT 199];


  }
}
  
   @AuraEnabled(Cacheable=true)
  public static List<News_List_Page__c> getNewsBlogs(){
     return  [SELECT Id, News_Label__c,CategoryBanner_Img_Url__c, Tagged_category__c, Date__c, News_Category__c, News_Descriptions__c, Likes_Number__c, Newsbg_Url__c,  src_url__c, Navigation_url__c FROM News_List_Page__c ORDER BY Id LIMIT 199];   
  }

  @AuraEnabled(Cacheable=true)
  public static List<News_List_Page__c> getNewsBlogsForNewsContainer(Integer limitSize, Integer offset){
    return  [SELECT Id, News_Label__c,CategoryBanner_Img_Url__c, Tagged_category__c, Date__c, 
                    News_Category__c, News_Descriptions__c, Likes_Number__c, Newsbg_Url__c,  
                    src_url__c, Navigation_url__c 
            FROM News_List_Page__c 
            ORDER BY Id 
            LIMIT :limitSize
            OFFSET :offset];   
  }

  
  @AuraEnabled(Cacheable=true)
  public static List<News_List_Page__c> getNewsBlogsByCategory(String category){
     return  [SELECT Id, News_Label__c,CategoryBanner_Img_Url__c, Tagged_category__c, Date__c, News_Category__c, News_Descriptions__c, Likes_Number__c, Newsbg_Url__c,  src_url__c, Navigation_url__c FROM News_List_Page__c Where Tagged_category__c=:category ORDER BY Id LIMIT 199];   
  }

  @AuraEnabled(Cacheable=true)
  public static List<News_List_Page__c> getNewsBlogsForNewsContainerByCategory(Integer limitSize, Integer offset, String categoryName){
    return  [SELECT Id, News_Label__c,CategoryBanner_Img_Url__c, Tagged_category__c, Date__c, 
                    News_Category__c, News_Descriptions__c, Likes_Number__c, Newsbg_Url__c,  
                    src_url__c, Navigation_url__c 
            FROM News_List_Page__c 
            WHERE News_Category__c = :categoryName 
            ORDER BY Id 
            LIMIT :limitSize
            OFFSET :offset];   
  }
  
  @AuraEnabled(Cacheable=true)
  public static List<List<Product2>> getInvestProds(){
    List<List<Product2>> retlst = new List<List<Product2>>();
    retlst.add([SELECT id,Name,Family,DisplayUrl,Deal_Page_Link__c,Trust_Deed_Link__c,Sector_Personas__c,ProductCode,FAQ_s__c,Fully_Funded__c,Return_Type__c,Deal_Description__c, Tile_Banner__c, Tile_Heading__c, Tile_Offer_Type__c, Button_Text__c FROM product2 WHERE Publish_on_Community_Site__c = TRUE  AND  IsActive = TRUE AND Private_Deal__c = FALSE AND Fully_Funded__c = FALSE order by Tile_Ordering__c  LIMIT 50000]);
    retlst.add([SELECT id,Name,Family,DisplayUrl,Deal_Page_Link__c,Trust_Deed_Link__c,Sector_Personas__c,ProductCode,FAQ_s__c,Fully_Funded__c,Return_Type__c,Deal_Description__c, Tile_Banner__c, Tile_Heading__c, Tile_Offer_Type__c, Button_Text__c FROM product2 WHERE IsActive = TRUE AND Fully_Funded__c = TRUE AND Private_Deal__c = FALSE order by Tile_Ordering__c  LIMIT 50000]);
    return retlst;
  }
  @AuraEnabled(Cacheable=true)
  public static List<Product2> getRelProds(List<Id> prodIdlst){
    List<Product2> myList = [SELECT id,Name,Family,DisplayUrl,Deal_Page_Link__c,Trust_Deed_Link__c,Sector_Personas__c,ProductCode,FAQ_s__c,Fully_Funded__c,Return_Type__c,Deal_Description__c, Tile_Banner__c, Tile_Heading__c, Tile_Offer_Type__c, Button_Text__c FROM product2 WHERE Id IN :prodIdlst  LIMIT 50000];
    return myList;
  }
@AuraEnabled
  public static List<invRecordWrapper> investmentsRecords(string filter,string investmentTile){   
    List<Id> accidlst = new List<Id>();
    User usr = [SELECT Id,contact.AccountId,contactId  FROM USER WHERE ID =:UserInfo.getuserId()];
    Id loggedinaccId = usr.contact.AccountId;

    if(investmentTile <> 'Current Investments - Entities'){
      accidlst.add(loggedinaccId);
    }
    if(investmentTile <> 'Current Investments - Personal'){
      List<AccountContactRelation> acrlst = [SELECT Id, Account.Name,AccountId FROM AccountContactRelation WHERE ContactId = :usr.contactId];
      for(AccountContactRelation acr:acrlst){
        accidlst.add(acr.AccountId);
      }
    }
    string query = 'SELECT Id,Current_Value__c,Purchased_Shares__c,Account__r.Name,Opportunity_Product__r.ListPrice,Opportunity_Product__r.Current_Investment_Value__c,Account__r.BPAY_CRN__c,Account__r.BPAY_Biller_Code__c,Investment_Product_Image_FORMULA__c,Opportunity_Product__r.TotalPrice,Opportunity_Product__r.Investment_Contribution_Fee__c,Opportunity_Product__r.Product2.Portal_Display_Name__c,Opportunity_Product__r.Product2.Portal_Short_Description__c,Opportunity_Product__r.Product2.Type__c,Opportunity_Product__r.Product2.Sector__c,Opportunity_Product__r.Product2.stage__c,Investment_Product_Type__c,Investment_Date__c,Investment_Amount__c,Investment_Opp_ID__c,Funds_Received__c FROM Investment__c';  
    filter += ' AND Account__c = :accidlst';
    filter +=  ' AND Opportunity__r.StageName <> \'Closed Lost\'';

    String finalQuery = query + filter;

    List<Investment__c> invlst = Database.Query(query+filter);
    List<invRecordWrapper> wraplst = new List<invRecordWrapper>();
    try{
      for(Investment__c inv : invlst){
          wraplst.add(new invRecordWrapper(inv,investmentTile));
      }
      return wraplst;
    }catch(Exception e){
      Logger.logMessage('Product','ProductController','Err', 'Id ' + String.valueof(loggedinaccId) + 'Query ' + finalQuery + 'accIdLst ' + JSON.serialize(accidlst) + 'invlst ' + JSON.serialize(invlst) + 'err ' + e.getStackTraceString());
      throw e;
    }
    
  }
  public class invRecordWrapper{
      @AuraEnabled public string prodimgformula;
      @AuraEnabled public string prodDisplayName;
      @AuraEnabled public string portalshortdescription;
      @AuraEnabled public List<fields> fieldDataSet;
      @AuraEnabled public string invId;
      @AuraEnabled public string redirectType;
      @AuraEnabled public boolean showviewmore;
      public invRecordWrapper(Investment__c inv,string investmentTile){
        fieldDataSet = new List<fields>();
        prodimgformula = inv.Investment_Product_Image_FORMULA__c;
        prodDisplayName = inv.Opportunity_Product__r.Product2.Portal_Display_Name__c;
        if(investmentTile == 'Pending Investments'){
          Decimal inamout = inv.Opportunity_Product__r.TotalPrice+inv.Opportunity_Product__r.Investment_Contribution_Fee__c;
          fieldDataSet.add(new fields('Investment Amount','$'+inamout?.format()));
          if(inv.Funds_Received__c){
            fieldDataSet.add(new fields('Status', 'Funds Received'));   
            portalshortdescription = 'Thanks! We have received your payment, and your investment will be confirmed once the certificate of ownership is issued.';         
          }else{
            fieldDataSet.add(new fields('Status','Funds Pending'));
            fieldDataSet.add(new fields('BPAY Biller Code',inv.Account__r.BPAY_Biller_Code__c)); 
            fieldDataSet.add(new fields('BPAY CRN',inv.Account__r.BPAY_CRN__c)); 
            portalshortdescription = 'Please complete the transfer of funds with the below BPAY details. It may take two business days for this payment to be reflected in this investor portal.';
          }   
          invId = inv.Id;         
          showviewmore = true;
          redirectType = 'filesRelatedlist';
        }else if(investmentTile == 'Current Investments - Personal' || investmentTile == 'Current Investments - Entities'){
          fieldDataSet.add(new fields('Current Holding Value','$'+inv.Opportunity_Product__r.Current_Investment_Value__c.format(),'This reflects the number of Securities Held multiplied by the Current Security Price. For more information about how we price your holding, please revert to our Pricing policies on our website')); 
          portalshortdescription = inv.Opportunity_Product__r.Product2.Portal_Short_Description__c;
          fieldDataSet.add(new fields('Purchase Price','$'+inv.Investment_Amount__c?.format())); 
          fieldDataSet.add(new fields('Current Security Price',inv.Current_Value__c,'If you own units in a trust, the Current Security Price reflects the unit\'s current value. If you own direct shares in a company, the "Current Security Price" reflects the share\'s current value. For more information about how we price, please revert to our Pricing policies on our website '));   
          fieldDataSet.add(new fields('Securities Held',inv.Purchased_Shares__c?.format(),'If you own units in a trust, the number of Securities Held reflects the number of units you hold. If you own direct shares in a company, the number of Securities Held reflects the number of shares you hold. Please refer to your Holding Certificate, which states your ownership.')); 
          if(investmentTile == 'Current Investments - Personal'){
            fieldDataSet.add(new fields('Investor',inv.Account__r.Name,true,UserInfo.getUserId()));
          }else{
            fieldDataSet.add(new fields('Investor',inv.Account__r.Name,true,inv.Account__c));
          }          
          fieldDataSet.add(new fields('Investment ID',inv.Investment_Opp_ID__c));
          if(inv.Opportunity_Product__r.Product2.Sector__c <> NULL)
            fieldDataSet.add(new fields('Sector',inv.Opportunity_Product__r.Product2.Sector__c));           
          if(inv.Opportunity_Product__r.Product2.stage__c <> NULL)
            fieldDataSet.add(new fields('Stage',inv.Opportunity_Product__r.Product2.stage__c)); 
          showviewmore = true;    
          redirectType = 'detail';    
          invId = inv.Id;     
        }else{
          portalshortdescription = inv.Opportunity_Product__r.Product2.Portal_Short_Description__c;
          fieldDataSet.add(new fields('Investment Amount','$'+inv.Investment_Amount__c?.format()));
          if(inv.Opportunity_Product__r.Product2.Sector__c <> NULL)
            fieldDataSet.add(new fields('Sector',inv.Opportunity_Product__r.Product2.Sector__c));
          if(inv.Opportunity_Product__r.Product2.stage__c <> NULL)
            fieldDataSet.add(new fields('Stage',inv.Opportunity_Product__r.Product2.stage__c));            
          fieldDataSet.add(new fields('Investment ID',inv.Investment_Opp_ID__c));   
          showviewmore = true;    
          redirectType = 'detail';    
          invId = inv.Id;     
        }
      }
  }
  public class fields{
      @AuraEnabled public string label;
      @AuraEnabled public string value;
      @AuraEnabled public boolean isHyperLink = false;
      @AuraEnabled public string hyperlinknavigation;
      @AuraEnabled public string helpText;
      public fields(string label,string value){
          this.label = label;
          this.value = value;
      }
      public fields(string label,string value, boolean isHyperLink, string hyperlinknavigation){
          this.label = label;
          this.value = value;
          this.isHyperLink = isHyperLink;
          this.hyperlinknavigation = hyperlinknavigation;
      }
      public fields(string label,string value, string helpText){
        this.label = label;
        this.value = value;
        this.isHyperLink = isHyperLink;
        this.hyperlinknavigation = hyperlinknavigation;
        this.helpText = helpText;
    }
  }
  @AuraEnabled
  public static Product2 isRetailProd(Id prodId){
    return [SELECT Id,Type__c,Footer_Text__c,AFSL_Licence__c FROM Product2 WHERE Id = :prodId];
  }
  @AuraEnabled
  public static Map<String,List<FileDetails>> fetchFiles(Id recordId){
    List<String> investmentDocuments = new List<String>{'Investment Contract',
    'Unit Certificate',
    'Receipt',
    'Receipt of transfer',
    'Share Certificate',
    'Con Note',
    'Loan Agreement',
    'SAFE Note',
    'Interest Certificate',
    'Promissory Note',
    'PDS Part 1',
    'PDS Part 2',
    'Information Memorandum',
    'Target Market Determination',
    'CSF Offer Document',
    'Trust Deed',
    'Off Market Transfer',
    'Buy Back Agreement',
    'Investment Variation',
    'Redemption Request form',
    'Limited Partnership',
    'Agreement to Reinvest Distributions',
    'Application for Product',
    'Terms of Issue',
    'Investment_Contract',
    'Unit_Certificate',
    'Receipt_of_transfer',
    'Share_Certificate',
    'Con_Note',
    'Loan_Agreement',
    'SAFE_Note',
    'Interest_Certificate',
    'Promissory_Note',
    'Fund_Document',
    'Prospectus',
    'Information_Memorandum',
    'Target_Market_Determination',
    'CSF_Offer_Document',
    'Trust_Deed',
    'Off_Market_Transfer',
    'Buy_Back_Agreement',
    'Investment_Variation',
    'Redemption_Request_form',
    'Limited_Partnership',
    'Agreement_to_Reinvest_Distributions',
    'Application_for_Product',
    'Terms_of_Issue'};
      
    
      List<ContentDocumentLink> files = [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :recordId];
      List<Id> fileIds = new List<Id>();
      for (ContentDocumentLink docLink : files) {
          fileIds.add(docLink.ContentDocumentId);
      }
      Map<String,List<String>> matchCriteria = new Map<String,List<String>>();
      matchCriteria.put('Investment Documents', investmentDocuments);
      matchCriteria.put('Investment Updates and Actions', new List<String>{'Corporate_Action','Investor Update','Fund Update','Corporate Action','Investor_Update','Fund_Update'});
      matchCriteria.put('Financial Statements and Distributions', new List<String>{'.*FY\\d{2} Tax Statement.*','.*FY\\d{2} Tax Statement_Amended.*','Distribution Statement','Remittance Advice','ESIC Offset Determination','Redemption Confirmation','Confirmation of Redemption and Re-investment','.*FY\\d{2}_Tax_Statement.*','.*FY\\d{2}_Tax_Statement_Amended.*','Distribution_Statement','Remittance_Advice','ESIC_Offset_Determination','Redemption_Confirmation','Confirmation_of_Redemption_and Re-investment','FY Tax Statement','FY_Tax_Statement'});
      Map<String,List<FileDetails>> retMap = new Map<String,List<FileDetails>>();
      retMap.put('Investment Documents', new List<FileDetails>());
      retMap.put('Investment Updates and Actions', new List<FileDetails>());
      retMap.put('Financial Statements and Distributions', new List<FileDetails>());
      // Filter PDF files 
      List<ContentVersion> docs = [SELECT ContentDocumentId, FileExtension, Title,CreatedDate  FROM ContentVersion WHERE ContentDocumentId IN : fileIds ORDER BY CreatedDate DESC];
      for (ContentVersion docLink : docs) {
          if(fileNameCheck(docLink.Title,matchCriteria.get('Investment Updates and Actions'))){
              retMap.get('Investment Updates and Actions').add(new FileDetails(docLink.ContentDocumentId, docLink.Title,docLink.CreatedDate.format()));
          }else if(fileNameCheck(docLink.Title,matchCriteria.get('Financial Statements and Distributions'))){
            system.debug(docLink.Title+'Financial Statements and Distributions');
              retMap.get('Financial Statements and Distributions').add(new FileDetails(docLink.ContentDocumentId, docLink.Title,docLink.CreatedDate.format()));
          }else{
              retMap.get('Investment Documents').add(new FileDetails(docLink.ContentDocumentId, docLink.Title,docLink.CreatedDate.format()));
          }
      }
      return retMap;
  }
  public static Boolean fileNameCheck(string fileName, List<String> matchList){
      Boolean isFileMatch = false;
      for(String s : matchList){
        system.debug(fileName +'-------' +s+'---------'+fileName.contains(s));
        if(s.contains('\\d{2}')){
          Pattern stringPattern = Pattern.compile(s);
          Matcher stringMatcher = stringPattern.matcher(fileName);
          isFileMatch = stringMatcher.matches();
          if(isFileMatch)
          break;
        }else if(fileName.contains(s)){
          system.debug(fileName +'-------' +s);
          isFileMatch = true;
          break;
        }
      }
      return isFileMatch;
  }
  public class FileDetails{
      @AuraEnabled public string fileId;
      @AuraEnabled public string fileName;
      @AuraEnabled public string fileUrl;
      @AuraEnabled public string createdDate;
      public FileDetails(string fileId,string fileName, string createdDate){
          this.fileId = fileId;
          this.fileName = fileName;
          this.createdDate = createdDate;
          this.fileUrl = '/sfc/servlet.shepherd/document/download/'+fileId;
      }
  }
}