common/force-app/main/default/objects/Lead_Investor__c/Lead_Investor__c.object-meta.xml
<CustomObject>
    <label>Lead Investor</label>
    <nameField>
        <displayFormat>LI-{0000}</displayFormat>
        <label>Lead Investor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Investors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Lead_Investor__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lead Investors</relationshipLabel>
    <relationshipName>Lead_Investors</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/classes/InvestmentDetailsController.cls
/**

**/
public without sharing class InvestmentDetailsController {

    public static final string OPPORTUNITY_STAGENAME_APPLICATION_RECEIVED = 'Application Received';
    public static final string OPPORTUNITY_STAGENAME_RECEIPT_ISSUED = 'Receipt Issued';
    public static final string OPPORTUNITY_STAGENAME_CLOSED_WON= 'Closed Won';
    @AuraEnabled(cacheable=true)
    public static string retrieveRaisedAmount(Id productId){
        String raisedAmount = '0';
        try {
            OpportunityLineItem[] lstOpportunity = [SELECT Id,Opportunity.Amount FROM OpportunityLineItem WHERE Product2Id = :productId AND 
                        (Opportunity.StageName = : OPPORTUNITY_STAGENAME_APPLICATION_RECEIVED OR Opportunity.StageName = : OPPORTUNITY_STAGENAME_RECEIPT_ISSUED
                        OR Opportunity.StageName = : OPPORTUNITY_STAGENAME_CLOSED_WON)];

            Lead_Investor__c[] lstInvestor = [SELECT Id,Amount__c FROM Lead_Investor__c WHERE Product__c = :productId];

            if (!lstOpportunity.isEmpty()) {
                Decimal counter = 0;
                for (OpportunityLineItem opp : lstOpportunity) {
                    if (opp.Opportunity.Amount != null) {
                        counter += opp.Opportunity.Amount;
                    }
                }

                if (!lstInvestor.isEmpty()) {
                    for (Lead_Investor__c oLead : lstInvestor) {
                        if (oLead.Amount__c != null) {
                            counter += oLead.Amount__c;
                        }
                    }
                }
                raisedAmount = String.valueOf(counter);
            }            
            return  raisedAmount;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}