common/force-app/main/default/objects/OpportunityLineItem/fields/Original_Invested_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Original_Invested_Quantity__c</fullName>
    <label>Current Holdings</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/OpportunityLineItem/fields/Original_Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Original_Sales_Price__c</fullName>
    <label>Current Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/classes/OpportunityLineItemTriggerHandler.cls
public class OpportunityLineItemTriggerHandler {
    public static void beforeInsert(List<OpportunityLineItem> TriggerNew) {
        prepopulateDefaultValues(TriggerNew);
    }
    public static void prepopulateDefaultValues(List<OpportunityLineItem> TriggerNew){
        for(OpportunityLineItem oli : TriggerNew){
            if(oli.Quantity <> null && oli.UnitPrice<> null){
                oli.Original_Invested_Quantity__c = oli.Quantity;
                oli.Original_Sales_Price__c = oli.UnitPrice * oli.Quantity;
            }
        }
    }
}