common/force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Log_Message__c/Log_Message__c.object-meta.xml
<CustomObject>
    <label>Log Message</label>
    <nameField>
        <displayFormat>LM-{0000}</displayFormat>
        <label>Log Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Message</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Log_Message__c/fields/DML_info__c.field-meta.xml
<CustomField>
    <fullName>DML_info__c</fullName>
    <label>DML info</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Log_Message__c/fields/log_message__c.field-meta.xml
<CustomField>
    <fullName>log_message__c</fullName>
    <label>log message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Log_Message__c/fields/Record_details__c.field-meta.xml
<CustomField>
    <fullName>Record_details__c</fullName>
    <label>Record details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

common/force-app/main/default/objects/Log_Message__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Log_Message__c/fields/Source_Function__c.field-meta.xml
<CustomField>
    <fullName>Source_Function__c</fullName>
    <label>Source Function</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Log_Message__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <label>Status Code</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/classes/logMsgUtility.cls
public without sharing class logMsgUtility {
    public static void logMessage(Exception e, string ClassName, String appName, string methodname, Map<String,Object> inParamsMap ){   
        List<Log_Message__c> logmsglst = new List<Log_Message__c>();
        Log_Message__c msg = new Log_Message__c();
        string message = '';
        message += 'Exception Type: ' + e.getTypeName() + '\nException Line Nr: ' + e.getLineNumber(); 
        msg.Record_details__c = '';
        msg.Application__c = appName;
        if(inParamsMap != null){
            for(String ipKey : inParamsMap.keyset()){
                msg.Record_details__c += '<p>'+ ipKey + ': ' + inparamsMap.get(ipKey) + '</p>';
            }
        }
        
        if (e instanceof DmlException){
           DmlException dmlExc = (DmlException) e;
           String dmlMessage ;
           for (integer i= 0; i<dmlExc.getNumDml(); i++){
               dmlMessage += '  \nException Message:' + dmlExc.getDmlMessage(i);
               dmlMessage +=  ' Batch Row #:' + dmlExc.getDmlIndex(i);
               String fieldsInError = '';               
               for (String fieldName : dmlExc.getDmlFieldNames(i))
               {
                   if (fieldsInError == '')
                       fieldsInError = fieldName;
                   else
                       fieldsInError += ', ' + fieldName;
               }
               dmlMessage += fieldsInError;             
               msg.Stack_Trace__c = e.getStackTraceString();
               msg.Source_Function__c = methodname;
               msg.Source__c = ClassName;
               msg.log_message__c = message;
               msg.Status_Code__c = dmlExc.getDmlStatusCode(i);
               msg.DML_info__c = dmlMessage;
               logmsglst.add(msg);
           }        
       }else{
            message += '\nException Message: ' + e.getMessage();
            msg.Stack_Trace__c = e.getStackTraceString();
            msg.Source_Function__c = methodname;
            msg.Source__c = ClassName;
            msg.log_message__c = message;
            logmsglst.add(msg);
        }
        insert logmsglst;
    }
}