common/force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Application__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Application__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EOI</fullName>
            </value>
            <value>
                <fullName>Wholesale</fullName>
            </value>
            <value>
                <fullName>Experienced Investor - Property</fullName>
            </value>
            <value>
                <fullName>Experienced Investor - Startups</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <label>Investment</label>
    <nameField>
        <displayFormat>IN-{00000000}</displayFormat>
        <label>Investment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Investment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investments</relationshipLabel>
    <relationshipName>Investments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Investments1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Log_Message__c/Log_Message__c.object-meta.xml
<CustomObject>
    <label>Log Message</label>
    <nameField>
        <displayFormat>LM-{0000}</displayFormat>
        <label>Log Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Message</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Log_Message__c/fields/log_message__c.field-meta.xml
<CustomField>
    <fullName>log_message__c</fullName>
    <label>log message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Log_Message__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Log_Message__c/fields/Source_Function__c.field-meta.xml
<CustomField>
    <fullName>Source_Function__c</fullName>
    <label>Source Function</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Log_Message__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VC Product</fullName>
                <label>VC Product - Wholesale</label>
            </value>
            <value>
                <fullName>Property Product</fullName>
            </value>
            <value>
                <fullName>CSF Product</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>PSP Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/classes/ContentDocumentLinkTriggerHandlerTest.cls
@isTest
public class ContentDocumentLinkTriggerHandlerTest {
    @isTest
    static void testAfterInsert() {
        // Create test data
        Account acc = new Account(Name = 'Test Account');
        insert acc;

        Opportunity opp = new Opportunity(Name = 'Test Opportunity', AccountId = acc.Id, CloseDate = Date.today(), StageName = 'Prospecting');
        insert opp;

        // Insert Investment__c linked to Opportunity
        Investment__c investment = new Investment__c(Opportunity__c = opp.Id, Account__c =acc.Id );
        insert investment;

        // Insert ContentVersion to implicitly create ContentDocument
        ContentVersion contentVer = new ContentVersion(
            Title = 'Test Document',
            PathOnClient = 'TestPath',
            VersionData = Blob.valueOf('Test Data')
        );
        insert contentVer;

        // Retrieve the ContentDocumentId from the inserted ContentVersion
        ContentVersion insertedContentVer = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :contentVer.Id LIMIT 1];

        ContentDocumentLink cdl = new ContentDocumentLink(
            LinkedEntityId = opp.Id,
            ContentDocumentId = insertedContentVer.ContentDocumentId,
            ShareType = 'V',
            Visibility = 'AllUsers'
        );

        Test.startTest();
        insert cdl;
        Test.stopTest();

        // Verify that the ContentDocumentLink was created for the Investment__c record
        List<ContentDocumentLink> contentDocumentLinks = [SELECT Id, LinkedEntityId, ContentDocumentId FROM ContentDocumentLink WHERE ContentDocumentId = :insertedContentVer.ContentDocumentId];

        // Verify the log message
        Log_Message__c logEntry = [SELECT Id, Application__c, Source__c, Source_Function__c, log_message__c, Type__c FROM Log_Message__c WHERE Source_Function__c = 'afterInsert' LIMIT 1];
        System.assertEquals('RaiseApp', logEntry.Application__c, 'Application should match');
        System.assertEquals('ContentDocumentLinkTriggerHandler', logEntry.Source__c, 'Source should match');
        System.assertEquals('afterInsert', logEntry.Source_Function__c, 'Source function should match');
        System.assertEquals('Info', logEntry.Type__c, 'Type should be Info');
    }
}