common/force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Application__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EOI</fullName>
            </value>
            <value>
                <fullName>Wholesale</fullName>
            </value>
            <value>
                <fullName>Experienced Investor - Property</fullName>
            </value>
            <value>
                <fullName>Experienced Investor - Startups</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Log_Message__c/Log_Message__c.object-meta.xml
<CustomObject>
    <label>Log Message</label>
    <nameField>
        <displayFormat>LM-{0000}</displayFormat>
        <label>Log Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Message</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Log_Message__c/fields/DML_info__c.field-meta.xml
<CustomField>
    <fullName>DML_info__c</fullName>
    <label>DML info</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Log_Message__c/fields/log_message__c.field-meta.xml
<CustomField>
    <fullName>log_message__c</fullName>
    <label>log message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Log_Message__c/fields/Record_details__c.field-meta.xml
<CustomField>
    <fullName>Record_details__c</fullName>
    <label>Record details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

common/force-app/main/default/objects/Log_Message__c/fields/refrence_Id__c.field-meta.xml
<CustomField>
    <fullName>refrence_Id__c</fullName>
    <label>refrence Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Log_Message__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Log_Message__c/fields/Source_Function__c.field-meta.xml
<CustomField>
    <fullName>Source_Function__c</fullName>
    <label>Source Function</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Log_Message__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <label>Status Code</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Log_Message__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/classes/Logger.cls
public class Logger {
    public static void logError(String application, String source, String sourceFunction, String referenceId, String recordDetails, String dmlInfo, String statusCode, Exception e, String logMessage) {
        Log_Message__c logEntry = new Log_Message__c();
        logEntry.Application__c = application;
        logEntry.Source__c = source;
        logEntry.Source_Function__c = sourceFunction;
        logEntry.refrence_Id__c = referenceId;
        logEntry.Record_details__c = recordDetails;
        logEntry.DML_info__c = dmlInfo;
        logEntry.Status_Code__c = statusCode;
        logEntry.log_message__c = logMessage + ': ' + e.getMessage();
        logEntry.Stack_Trace__c = e.getStackTraceString();
        logEntry.Type__c = 'Error';
        
        try {
            insert logEntry;
        } catch (Exception logException) {
            System.debug('Error logging exception: ' + logException.getMessage());
            System.debug('Original exception: ' + e.getMessage());
            System.debug('Original stack trace: ' + e.getStackTraceString());
        }
    }

    public static void logMessage(String application, String source, String sourceFunction, String logMessage) {
        Log_Message__c logEntry = new Log_Message__c();
        logEntry.Application__c = application;
        logEntry.Source__c = source;
        logEntry.Source_Function__c = sourceFunction;
        logEntry.log_message__c = logMessage;
        logEntry.Type__c = 'Info';

        try {
            insert logEntry;
        } catch (Exception logException) {
            System.debug('Error logging message: ' + logException.getMessage());
            System.debug('Log message: ' + logMessage);
        }
    }
}