common/force-app/main/default/objects/Account/fields/Account_Type_Dynamic__c.field-meta.xml
<CustomField>
    <fullName>Account_Type_Dynamic__c</fullName>
    <formula>IF(Total_Closed_Won_Opps__c &gt; 0, &apos;Existing Business&apos;, 

 IF(
     AND(Total_Closed_Won_Opps__c = 0, TODAY() - DATEVALUE(CreatedDate) &gt; 56), &apos;New Business&apos;, 

   IF(
       AND(Total_Closed_Won_Opps__c = 0, TODAY() - DATEVALUE(CreatedDate) &lt; 56), &apos;New New Business&apos;,null)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Type - Dynamic</label>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Application__c/fields/Buyer_1_Email__c.field-meta.xml
<CustomField>
    <fullName>Buyer_1_Email__c</fullName>
    <label>Buyer 1 Email</label>
    <type>Email</type>
</CustomField>

common/force-app/main/default/objects/Application__c/fields/Buyer_1_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Buyer_1_First_Name__c</fullName>
    <label>Buyer 1 First Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Application__c/fields/Buyer_1_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Buyer_1_Last_Name__c</fullName>
    <label>Buyer 1 Last Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Application__c/fields/Buyer_1_Phone__c.field-meta.xml
<CustomField>
    <fullName>Buyer_1_Phone__c</fullName>
    <label>Buyer 1 Phone</label>
    <type>Phone</type>
</CustomField>

common/force-app/main/default/objects/Application__c/fields/Buyer_1_Postal_City__c.field-meta.xml
<CustomField>
    <fullName>Buyer_1_Postal_City__c</fullName>
    <label>Buyer 1 Postal City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Application__c/fields/Buyer_1_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Buyer_1_Postal_Code__c</fullName>
    <label>Buyer 1 Postal Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Application__c/fields/Buyer_1_Postal_State__c.field-meta.xml
<CustomField>
    <fullName>Buyer_1_Postal_State__c</fullName>
    <label>Buyer 1 Postal State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Province</valueSetName>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Application__c/fields/Buyer_1_Postal_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Buyer_1_Postal_Street_Address__c</fullName>
    <label>Buyer 1 Postal Street Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications (Contact)</relationshipLabel>
    <relationshipName>Applications4</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Application__c/fields/Land_Size_in_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Land_Size_in_Sqm__c</fullName>
    <label>Land Size in Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/Application__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Application__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Application__c/fields/Property_City__c.field-meta.xml
<CustomField>
    <fullName>Property_City__c</fullName>
    <label>Property City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Application__c/fields/Property_Lot_Unit_No__c.field-meta.xml
<CustomField>
    <fullName>Property_Lot_Unit_No__c</fullName>
    <label>Property Lot/Unit No.</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Application__c/fields/Property_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Property_Postal_Code__c</fullName>
    <label>Property Postal Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Application__c/fields/Property_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Property_Street_Address__c</fullName>
    <label>Property Street Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Application__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/Province</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Application__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EOI</fullName>
            </value>
            <value>
                <fullName>Wholesale</fullName>
            </value>
            <value>
                <fullName>Experienced Investor - Property</fullName>
            </value>
            <value>
                <fullName>Experienced Investor - Startups</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Charity</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Conveyancer</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Development Manager</fullName>
            </value>
            <value>
                <fullName>Financial Adviser</fullName>
            </value>
            <value>
                <fullName>Fund Manager</fullName>
            </value>
            <value>
                <fullName>Integrator</fullName>
            </value>
            <value>
                <fullName>Investor</fullName>
            </value>
            <value>
                <fullName>Mortgage Broker</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Press</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Real Estate Agent</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Special Purpose Vehicle</fullName>
            </value>
            <value>
                <fullName>Trustee Company</fullName>
            </value>
            <value>
                <fullName>Venture Capital Business</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/CM_Assigned__c.field-meta.xml
<CustomField>
    <fullName>CM_Assigned__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CM Assigned</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>CM</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Create_EOI_Application__c.field-meta.xml
<CustomField>
    <fullName>Create_EOI_Application__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create EOI Application</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Initial_Term_Expiry__c.field-meta.xml
<CustomField>
    <fullName>Initial_Term_Expiry__c</fullName>
    <label>Initial Term/Expiry</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Invested_Product_ADMIN_FIELD__c.field-meta.xml
<CustomField>
    <fullName>Invested_Product_ADMIN_FIELD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please disregard this field. Admin field Only!</inlineHelpText>
    <label>Invested Product_ADMIN FIELD</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Maturation_Date__c.field-meta.xml
<CustomField>
    <fullName>Maturation_Date__c</fullName>
    <inlineHelpText>If this investment has a defined term, ensure that you indicate the correct date of maturation here and that you have also checked &quot;Defined Term&quot; check box.
To update this field, please go to related tab -&gt; Click on NEW button at Investment Maturities Section</inlineHelpText>
    <label>Maturation Date</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VC Product</fullName>
                <label>VC Product - Wholesale</label>
            </value>
            <value>
                <fullName>Property Product</fullName>
            </value>
            <value>
                <fullName>CSF Product</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>PSP Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Unit_Cert_Issued__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cert_Issued__c</fullName>
    <label>Unit Cert Issued</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/recordTypes/VC.recordType-meta.xml
<RecordType>
    <fullName>VC</fullName>
    <active>true</active>
    <businessProcess>VC</businessProcess>
    <label>VC</label>
</RecordType>

common/force-app/main/default/objects/Opportunity/recordTypes/VCPP.recordType-meta.xml
<RecordType>
    <fullName>VCPP</fullName>
    <active>true</active>
    <businessProcess>VCPP</businessProcess>
    <label>VCPP</label>
</RecordType>

common/force-app/main/default/objects/Product2/fields/Land_Size__c.field-meta.xml
<CustomField>
    <fullName>Land_Size__c</fullName>
    <label>Land Size</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <label>Postcode</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Product_Number__c.field-meta.xml
<CustomField>
    <fullName>Product_Number__c</fullName>
    <label>Lot/Unit No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>Qld</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>Vic</fullName>
            </value>
            <value>
                <fullName>Tas</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_Address__c</fullName>
    <label>Street Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Suburb__c.field-meta.xml
<CustomField>
    <fullName>Suburb__c</fullName>
    <label>Suburb</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/recordTypes/VCPP.recordType-meta.xml
<RecordType>
    <fullName>VCPP</fullName>
    <active>true</active>
    <description>VentureCrowd Property Projects</description>
    <label>VCPP</label>
</RecordType>

common/force-app/main/default/globalValueSets/State_Province.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ACT</fullName>
    </customValue>
    <customValue>
        <fullName>NSW</fullName>
    </customValue>
    <customValue>
        <fullName>NT</fullName>
    </customValue>
    <customValue>
        <fullName>QLD</fullName>
    </customValue>
    <customValue>
        <fullName>SA</fullName>
    </customValue>
    <customValue>
        <fullName>TAS</fullName>
    </customValue>
    <customValue>
        <fullName>VIC</fullName>
    </customValue>
    <customValue>
        <fullName>WA</fullName>
    </customValue>
    <masterLabel>State/Province</masterLabel>
</GlobalValueSet>

common/force-app/main/default/classes/OpportunityTriggerHandler.cls
/**
**/
public class OpportunityTriggerHandler
{
    public static final string  LINEITEM_STAGENAME_EOI = 'EOI';
    public static final string  LINEITEM_STAGENAME_CONTRACT = 'Contract';
    public static final string  LINEITEM_SUBSTAGE_CONTRACT_EXECUTED = 'Contract Executed';
    public static final string  PRODUCT_STATUS_EXPRESSION_OF_INTREST = 'Expression Of Interest';
    public static final string  PRODUCT_STATUS_SOLD_OUT = 'Sold Out';
    public static final string  OPPORTUNITY_STAGE_CLOSED_LOST = 'Closed Lost';
    public static final string  OPPORTUNITY_LOST_REASON_SOLD_TO_OTHER_PARTY = 'Sold to other party';
    public static final string  OPPORTUNITY_STAGE_SETTLEMENT_BOOKED = 'Settlement Booked';	
    public static final string  PRODUCT_STATUS_AVAILABLE = 'Available';	
    public static boolean emailsent = false;
    public static Id vcpprecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('VCPP').getRecordTypeId();
    public static Boolean isProcessInvestmentRecordRunning = false;

   
    public static void updateContact(){
        Set<Id> accIdset = new Set<Id>();
        // Only add non-null AccountIds.
        for(Opportunity opp : (List<Opportunity>) Trigger.New){
            if(opp.AccountId != null) {
                accIdset.add(opp.AccountId);
            }
        }
        // Query Accounts with their RecordType info and related Contacts.
        Map<Id,Account> accMap = new Map<Id,Account>(
            [SELECT Id, RecordType.Name, Account_Type_Dynamic__c, 
                    (SELECT Id, Name FROM Contacts)
             FROM Account WHERE Id IN : accIdset]
        );
        // Query AccountContactRelation records.
        Map<Id,List<AccountContactRelation>> accIdVSconlstmap = new Map<Id,List<AccountContactRelation>>();
        for(AccountContactRelation acr : [SELECT Id, Roles, Account.RecordType.Name, IsDirect, AccountId, ContactId 
                                          FROM AccountContactRelation 
                                          WHERE AccountId IN : accIdset]){
            if(!accIdVSconlstmap.containsKey(acr.AccountId))
                accIdVSconlstmap.put(acr.AccountId, new List<AccountContactRelation>());
            accIdVSconlstmap.get(acr.AccountId).add(acr);
        }
        // Loop through the Opportunities in trigger context.
        for(Opportunity opp : (List<Opportunity>) Trigger.New){
            // Check that the Account exists in our query.
            if(opp.AccountId != null && accMap.containsKey(opp.AccountId)){
                Account a = accMap.get(opp.AccountId);
                // If Opportunity.Type is null and the Account's dynamic type field is not null, then assign it.
                if(opp.Type == null && a.Account_Type_Dynamic__c != null){
                    opp.Type = a.Account_Type_Dynamic__c;
                }
                // Set Primary_Contact__c if not already set.
                if(opp.Primary_Contact__c == null){
                    // If the Account's record type name indicates a 'person' and it has at least one contact, use that.
                    if(a.RecordType != null && a.RecordType.Name != null && a.RecordType.Name.containsIgnoreCase('person') && !a.Contacts.isEmpty()){
                        opp.Primary_Contact__c = a.Contacts[0].Id;
                    } else {
                        AccountContactRelation accr1;
                        AccountContactRelation accr2;
                        AccountContactRelation accr3;
                        if(accIdVSconlstmap.containsKey(opp.AccountId)){
                            for(AccountContactRelation acr : accIdVSconlstmap.get(opp.AccountId)){
                                accr1 = acr;
                                if(acr.Roles != null && acr.Roles.containsIgnoreCase('Decision Maker'))
                                    accr2 = acr;
                                if(acr.IsDirect)
                                    accr3 = acr;
                            }
                            if(accr3 != null) {
                                opp.Primary_Contact__c = accr3.ContactId;
                            } else if(accr2 != null) {
                                opp.Primary_Contact__c = accr2.ContactId;
                            } else if(accr1 != null) {
                                opp.Primary_Contact__c = accr1.ContactId;
                            }
                        } else if(!a.Contacts.isEmpty()){
                            opp.Primary_Contact__c = a.Contacts[0].Id;
                        }                    
                    }
                }
            }
        }
    }
    

    // Process builder logic to trigger
    public static void commonLogic(){
        // before update
        if(Trigger.isBefore){   
            List<Id> accountIdlst = new List<Id>();         
            for(Opportunity opp : (List<Opportunity>) Trigger.new){
                if(Trigger.isInsert){
                    if(opp.stagename == 'Application Received' && opp.LeadSource == 'VC Website Organic'){
                        // opp.CM_Assigned__c = opp.ownerId;
                        opp.Web_Source__c = 'Invest Now Form';
                    }
                }
                if(Trigger.isUpdate){
                    Map<Id,Opportunity> oppMap = new Map<Id,Opportunity>([SELECT Id, Account.PersonContactId, Account.Account_Type_Dynamic__c, Recordtype.Name, Primary_Contact__r.Email, Primary_Contact__r.FirstName, Primary_Contact__r.LastName, Primary_Contact__r.MobilePhone, Primary_Contact__r.MailingCity, Primary_Contact__r.MailingPostalCode, Primary_Contact__r.MailingState, Primary_Contact__r.MailingStreet, Invested_Product_ADMIN_FIELD__c, Invested_Product_ADMIN_FIELD__r.Land_Size__c, Invested_Product_ADMIN_FIELD__r.Suburb__c, Invested_Product_ADMIN_FIELD__r.Product_Number__c, Invested_Product_ADMIN_FIELD__r.Postcode__c, Invested_Product_ADMIN_FIELD__r.Street_Address__c, Invested_Product_ADMIN_FIELD__r.State__c FROM Opportunity WHERE Id IN :Trigger.newMap.keyset()]);
                    if(opp.Unit_Cert_Issued__c <> NULL && Trigger.oldMap.get(opp.Id).get('Unit_Cert_Issued__c') == NULL && opp.Initial_Term_Expiry__c <> null){
                        opp.Maturation_Date__c = opp.Unit_Cert_Issued__c.addMonths(Integer.valueOf(opp.Initial_Term_Expiry__c));
                    }
                    system.debug(opp.stagename+'GSAC');
                    system.debug(oppMap.get(opp.Id).Recordtype.Name+'GSAC'); system.debug(!opp.Create_EOI_Application__c+'GSAC');
                    if(opp.stagename == 'EOI' && oppMap.get(opp.Id).Recordtype.Name == 'VCPP' && !opp.Create_EOI_Application__c){
                        Application__c app = new Application__c();
                        app.Account__c = opp.AccountId;
                        app.Buyer_1_Email__c = oppMap.get(opp.Id).Primary_Contact__r.Email;
                        app.Buyer_1_First_Name__c = oppMap.get(opp.Id).Primary_Contact__r.FirstName;
                        app.Buyer_1_Last_Name__c = oppMap.get(opp.Id).Primary_Contact__r.LastName;
                        app.Buyer_1_Phone__c = oppMap.get(opp.Id).Primary_Contact__r.MobilePhone;
                        app.Buyer_1_Postal_City__c = oppMap.get(opp.Id).Primary_Contact__r.MailingCity;
                        app.Buyer_1_Postal_Code__c = oppMap.get(opp.Id).Primary_Contact__r.MailingPostalCode;
                        app.Buyer_1_Postal_State__c = oppMap.get(opp.Id).Primary_Contact__r.MailingState;
                        app.Buyer_1_Postal_Street_Address__c = oppMap.get(opp.Id).Primary_Contact__r.MailingStreet;
                        app.Land_Size_in_Sqm__c = oppMap.get(opp.Id).Invested_Product_ADMIN_FIELD__r.Land_Size__c;
                        app.Opportunity__c = opp.Id;
                        app.Product__c = oppMap.get(opp.Id).Invested_Product_ADMIN_FIELD__c;
                        app.Property_City__c = oppMap.get(opp.Id).Invested_Product_ADMIN_FIELD__r.Suburb__c;
                        app.Property_Lot_Unit_No__c = oppMap.get(opp.Id).Invested_Product_ADMIN_FIELD__r.Product_Number__c;
                        app.Property_Postal_Code__c = oppMap.get(opp.Id).Invested_Product_ADMIN_FIELD__r.Postcode__c;
                        app.Property_Street_Address__c = oppMap.get(opp.Id).Invested_Product_ADMIN_FIELD__r.Street_Address__c;
                        app.State_Province__c = oppMap.get(opp.Id).Invested_Product_ADMIN_FIELD__r.State__c;
                        app.Type__c = 'EOI';
                        // Correct assignment: use the Contact Id from the Opportunity lookup field or relationship.
                        app.Contact__c = oppMap.get(opp.Id).Primary_Contact__c;
                        insert app;
                        opp.Create_EOI_Application__c = true;
                    }
                    
                }
                accountIdlst.add(opp.AccountId);
            }
            Map<Id,Account> accMap = new Map<Id,Account>([SELECT Id, Account_Type_Dynamic__c FROM Account WHERE Id IN :accountIdlst]);
            // for both insert and update
            for(Opportunity opp : (List<Opportunity>) Trigger.new){
                if(opp.Type == NULL && accMap.get(opp.AccountId).Account_Type_Dynamic__c <> NULL){
                    opp.Type = accMap.get(opp.AccountId).Account_Type_Dynamic__c;
                }
            }
        }
        if(Trigger.isAfter){
            system.debug('Afetr Updat');
            // set<Id> oppIsdet = 
            Map<Id,Opportunity> oppMap = new Map<Id,Opportunity>([SELECT Id, Account.PersonContactId, Account.Account_Type_Dynamic__c FROM Opportunity WHERE Id IN :Trigger.newMap.keyset()]);
            for(Opportunity opp : (List<Opportunity>) Trigger.new){
                if(Trigger.isInsert){
                    // Removed as part of INFSD-369 KENDRICK KAM 12-09-2024
                    // if(opp.stagename == 'Application Received' && opp.LeadSource == 'VC Website Organic'){
                    //     List<Task> tasklst = new List<Task>();
                    //     tasklst.add(new Task(ActivityDate= Date.Valueof(opp.createddate),Description = 'Received a new request to invest submission. Please review if ID has been verified',OwnerId = opp.CM_Assigned__c,Priority='Normal',Status='Open',Subject='Request to Invest Submission - ID Verified?',WhatId=opp.Id,WhoId=oppMap.get(opp.Id).Account.PersonContactId));
                    //     tasklst.add(new Task(ActivityDate= Date.Valueof(opp.createddate),Description = 'Received a new request to invest submission. If investment product is wholesale, verify if the account is verified for Wholesale',OwnerId = opp.CM_Assigned__c,Priority='Normal',Status='Open',Subject='Request to Invest Submission - If Wholesale Product?',WhatId=opp.Id,WhoId=oppMap.get(opp.Id).Account.PersonContactId));
                    //     tasklst.add(new Task(ActivityDate= Date.Valueof(opp.createddate),Description = 'Received a new request to invest submission. Review if ‘Req to Invest Under Different Account’ field is checked.',OwnerId = opp.CM_Assigned__c,Priority='Normal',Status='Open',Subject='Request to Invest Submission - Different Account',WhatId=opp.Id,WhoId=oppMap.get(opp.Id).Account.PersonContactId));
                    //     tasklst.add(new Task(ActivityDate= Date.Valueof(opp.createddate),Description = 'Please update the closed date to a new date to refelect the changes in opportunity status',OwnerId = opp.CM_Assigned__c,Priority='High',Status='Open',Subject='Update closed date on opportuntity',WhatId=opp.Id,WhoId=oppMap.get(opp.Id).Account.PersonContactId));
                    //     insert tasklst;
                    // }
                }
            }
        }
    }
}