common/force-app/main/default/objects/Account/fields/ACN__c.field-meta.xml
<CustomField>
    <fullName>ACN__c</fullName>
    <inlineHelpText>Australian Company Number (ACN)  or Australian Business Number (ABN)</inlineHelpText>
    <label>ACN/ABN</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>20</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/BSB_Number__c.field-meta.xml
<CustomField>
    <fullName>BSB_Number__c</fullName>
    <label>BSB Number</label>
    <length>6</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/Create_Company_Account__c.field-meta.xml
<CustomField>
    <fullName>Create_Company_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Company Account</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <description>Venture Capital sector</description>
    <inlineHelpText>The sector that the VC business is working in</inlineHelpText>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FINTECH</fullName>
            </value>
            <value>
                <fullName>AGTECH</fullName>
            </value>
            <value>
                <fullName>FOODTECH</fullName>
            </value>
            <value>
                <fullName>PROPTECH</fullName>
            </value>
            <value>
                <fullName>EDTECH</fullName>
            </value>
            <value>
                <fullName>ARTS &amp; ENTERTAINMENT</fullName>
            </value>
            <value>
                <fullName>MEDTECH</fullName>
            </value>
            <value>
                <fullName>IMPACT</fullName>
            </value>
            <value>
                <fullName>PROPERTY DEVELOPMENT</fullName>
            </value>
            <value>
                <fullName>BioTech</fullName>
            </value>
            <value>
                <fullName>MarTech</fullName>
            </value>
            <value>
                <fullName>SpaceTech</fullName>
            </value>
            <value>
                <fullName>HealthTech</fullName>
            </value>
            <value>
                <fullName>EnergyTech</fullName>
            </value>
            <value>
                <fullName>Robotics</fullName>
            </value>
            <value>
                <fullName>Blockchain</fullName>
            </value>
            <value>
                <fullName>Supply Chain</fullName>
            </value>
            <value>
                <fullName>E-Commerce</fullName>
            </value>
            <value>
                <fullName>Gaming</fullName>
            </value>
            <value>
                <fullName>Cosmetics</fullName>
            </value>
            <value>
                <fullName>Social Network</fullName>
            </value>
            <value>
                <fullName>TravelTech</fullName>
            </value>
            <value>
                <fullName>SecurityTech</fullName>
            </value>
            <value>
                <fullName>ClimateTech</fullName>
            </value>
            <value>
                <fullName>DeathTech</fullName>
            </value>
            <value>
                <fullName>Digital Health</fullName>
            </value>
            <value>
                <fullName>ESGs</fullName>
            </value>
            <value>
                <fullName>Web3</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
            <value>
                <fullName>DeepTech</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Account/fields/utm_campaign__c.field-meta.xml
<CustomField>
    <fullName>utm_campaign__c</fullName>
    <label>utm_campaign</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/utm_content__c.field-meta.xml
<CustomField>
    <fullName>utm_content__c</fullName>
    <label>utm content</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/utm_keyword__c.field-meta.xml
<CustomField>
    <fullName>utm_keyword__c</fullName>
    <label>utm keyword</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/utm_medium__c.field-meta.xml
<CustomField>
    <fullName>utm_medium__c</fullName>
    <label>utm medium</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/utm_source__c.field-meta.xml
<CustomField>
    <fullName>utm_source__c</fullName>
    <label>utm source</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/utm_term__c.field-meta.xml
<CustomField>
    <fullName>utm_term__c</fullName>
    <label>utm_term</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/Ventures_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Ventures_Company_Name__c</fullName>
    <inlineHelpText>Please complete this field to proceed with creating a company account.</inlineHelpText>
    <label>Ventures Company Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Contact/fields/Email_Opt_In__c.field-meta.xml
<CustomField>
    <fullName>Email_Opt_In__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Marketing Email Opt-in</inlineHelpText>
    <label>Email Opt In</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Contact/fields/Self_Identification__c.field-meta.xml
<CustomField>
    <fullName>Self_Identification__c</fullName>
    <label>Self Identification</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Contact/fields/Ts_Cs__c.field-meta.xml
<CustomField>
    <fullName>Ts_Cs__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in VC Investor Portal</description>
    <inlineHelpText>Form Submitted Agrress to the Tc &amp; Cs.</inlineHelpText>
    <label>Ts &amp; Cs</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/EOI__c.object-meta.xml
<CustomObject>
    <description>This object will be used by Founders, this was part of the MVP project.</description>
    <label>EOI</label>
    <nameField>
        <label>EOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOI&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/EOI__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>This will link to the Ventures Company Account that is related to the EOI</description>
    <inlineHelpText>This field links to the Ventures Company Account that is related to this EOI</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EOI&apos;s</relationshipLabel>
    <relationshipName>EOI_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PropTech</fullName>
            </value>
            <value>
                <fullName>HealthTech</fullName>
            </value>
            <value>
                <fullName>BioTech</fullName>
            </value>
            <value>
                <fullName>Digital Health</fullName>
            </value>
            <value>
                <fullName>MedTech</fullName>
            </value>
            <value>
                <fullName>FoodTech</fullName>
            </value>
            <value>
                <fullName>FinTech</fullName>
            </value>
            <value>
                <fullName>EdTech</fullName>
            </value>
            <value>
                <fullName>ClimateTech</fullName>
            </value>
            <value>
                <fullName>ESG&apos;s</fullName>
            </value>
            <value>
                <fullName>E-Commerce</fullName>
            </value>
            <value>
                <fullName>Web3</fullName>
            </value>
            <value>
                <fullName>MarTech</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
            <value>
                <fullName>SpaceTech</fullName>
            </value>
            <value>
                <fullName>DeepTech</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/classes/ReCaptchaAuraController.cls
public without sharing class ReCaptchaAuraController {    
    @AuraEnabled
    public static String getRegisterSubmit(Map<String,Object> registerComponentInfo){
        return NULL;
    }
    // New registratopn form
    @AuraEnabled
    public static Boolean verifyrecaptchaToken(string token){
        Http http = new Http();
        HttpRequest request = new HttpRequest();   
        request.setEndpoint('https://www.google.com/recaptcha/api/siteverify');
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/x-www-form-urlencoded');
        string body = 'secret=6Lcxu8QaAAAAAOKqVKlcpePIkcx3Yzmbygc-LhR4&response='+token;
        request.setBody(body);
        HttpResponse response = http.send(request);
        Map<string,Object> retobj = (Map<string,Object>) JSON.deserializeUntyped(response.getBody());
        return (boolean) retobj.get('success') && (decimal)retobj.get('score') > 0.5;
    }
    // Create or find person Account
    @AuraEnabled
    public static Map<string,Object> upsertPersonAccount(Map<string,Object> userdatamap){
        Map<string,Object> retMap = new Map<string,Object>();
        try{
            string email = (string) userdatamap.get('email');
            // Id personAccrecordId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Ventures Person Account').getRecordTypeId();
            Id personAccrecordId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('VC Person Account').getRecordTypeId();
            List<Account> a = [SELECT Id,(SELECT Id FROM Users),(SELECT Id FROM Contacts),(SELECT Id FROM Opportunities WHERE StageName = 'Closed Won') FROM ACCOUNT WHERE PersonEmail = :email AND RecordTypeId = :personAccrecordId];
            Map<string,string> profileMap = new Map<string,string>();
            for(Profile p : [SELECT Id,Name FROM PROFILE WHERE Name IN ('VC Customer Community Login','VC Investor Community Plus Login')]){
                profileMap.put(p.Name,p.Id);
            }
            List<user> adminuserlst;
            String communityNickname = String.valueOf(System.now().getTime()/1000)+(string) userdatamap.get('email');
            if(communityNickname.length() > 40)
            communityNickname = communityNickname.substring(0,35);
            if(a.Isempty()){
                User owner = [SELECT Id FROM USER WHERE Name = 'The VentureCrowd Team'];
                if(owner == NULL ){
                    owner = [SELECT ID,Name FROM User WHERE Id IN (SELECT UserOrGroupId FROM GroupMember WHERE Group.name='CM') AND IsActive = TRUE LIMIT 1];
                }
                Account act = new Account();
                act.FirstName = (string) userdatamap.get('firstName');
                act.LastName = (string) userdatamap.get('lastName');
                act.OwnerId = owner.Id;
                act.RecordTypeId = personAccrecordId;
                act.PersonEmail = (string) userdatamap.get('email');
                act.PersonMobilePhone = (string) userdatamap.get('mobile');
                act.Ts_Cs__pc = true;
                act.Email_Opt_In__pc = (boolean) userdatamap.get('Email_Opt_In__pc');
                act.utm_source__c = (string) userdatamap.get('utm_source__c');               
                act.utm_medium__c = (string) userdatamap.get('utm_medium__c');               
                act.utm_campaign__c = (string) userdatamap.get('utm_campaign__c');               
                act.utm_content__c = (string) userdatamap.get('utm_content__c');               
                act.utm_term__c = (string) userdatamap.get('utm_term__c');
                act.utm_keyword__c = (string) userdatamap.get('utm_keyword__c');               
                insert act;

                User u = new User();
                u.Username = (string) userdatamap.get('email');
                u.Email = (string) userdatamap.get('email');
                u.FirstName =  (string) userdatamap.get('firstName');
                u.LastName = (string) userdatamap.get('lastName');
                u.MobilePhone = (string) userdatamap.get('mobile');
                u.ProfileId =  profileMap.get('VC Customer Community Login');
                u.EmailEncodingKey = 'UTF-8';
                u.CommunityNickname = communityNickname;
                u.Alias = 'ComUser';
                u.TimeZoneSidKey = 'Australia/Brisbane';
                u.LocaleSidKey = 'en_US';
                u.LanguageLocaleKey = 'en_US';
                Id userId = Site.createExternalUser(u, act.Id, (string) userdatamap.get('password'));
                // ApexPages.PageReference lgn = Site.login(u.Email, (string) userdatamap.get('password'),'/s/portal/portfolio');                
                retMap.put('IsValidtransaction',true);
                retMap.put('IsAccountCreated',true);
                retMap.put('accId',act.Id);
                retMap.put('userId',userId);
                // retMap.put('retURL',lgn.getURL());
            }else if(!a.Isempty() && a[0].Users.isempty()){
                Contact c= new Contact();
                c.Id = a[0].Contacts[0].Id;
                c.Email = (string) userdatamap.get('email');
                c.FirstName = (string) userdatamap.get('firstName');
                c.LastName = (string) userdatamap.get('lastName');
                c.Ts_Cs__c = true;
                c.MobilePhone = (string) userdatamap.get('mobile');
                c.Email_Opt_In__c = true;
                // c.Self_Identification__c = investorDetail;
                update c;

                User u = new User();
                u.Username = (string) userdatamap.get('email');
                u.Email = (string) userdatamap.get('email');
                u.FirstName =  (string) userdatamap.get('firstName');
                u.LastName = (string) userdatamap.get('lastName');
                u.MobilePhone = (string) userdatamap.get('mobile');
                u.CommunityNickname = communityNickname;
                u.EmailEncodingKey = 'UTF-8';
                u.Alias = 'ComUser';
                u.TimeZoneSidKey = 'Australia/Brisbane';
                u.LocaleSidKey = 'en_US';
                u.LanguageLocaleKey = 'en_US';
                
                u.ProfileId = profileMap.get('VC Customer Community Login');
                                
                Id userId = Site.createExternalUser(u, a[0].Id, (string) userdatamap.get('password'));
                ApexPages.PageReference lgn = Site.login(u.Email, (string) userdatamap.get('password'),'/s/portal/my-companies');  
                retMap.put('IsValidtransaction',true);              
                retMap.put('IsAccountCreated',false);
                retMap.put('accId',a[0].Id);
                retMap.put('userId',userId);
                // retMap.put('retURL',lgn.getURL());                
            }else{
                retMap.put('IsValidtransaction',false);                 
            }
            return retMap;
        }catch(Exception e){
            logMsgUtility.logMessage(e, 'ReCaptchaAuraController', 'User Registration', 'upsertPersonAccount',userdatamap );
            return NULL;
        }
    }
    // @AuraEnabled
    // public static string updateAccount(Map<string,object> datmap){
    //     try{
    //         Account a = new Account();
    //         for(string s : datmap.keyset()){
    //             a.put(s,datmap.get(s));
    //         }
    //         update a;
    //         return 'success';
    //     }catch(Exception e){
    //         logMsgUtility.logMessage(e, 'ReCaptchaAuraController', 'User Registration', 'updateAccount',datmap );
    //         return 'failure';
    //     }
    // }
    @AuraEnabled
    public static String updateAccount(Map<String, Object> datmap) {
        try {
            Account a = new Account();
            for (String s : datmap.keySet()) {
                a.put(s, datmap.get(s));
            }
            update a;
            return 'success';
        } catch (Exception e) {
            logMsgUtility.logMessage(e, 'ReCaptchaAuraController', 'User Registration', 'updateAccount', datmap);
            return 'failure';
        }
    }

    @AuraEnabled
    public static string communityLogin(string email,string pwd, string landingurl){
        return Site.login(email, pwd,landingurl).getUrl();
    }
    
    //? Get the ACN of 
    @AuraEnabled(cacheable=true)
    public static String getEOICompanyId(String acn) {
        EOI__c eoi = [SELECT Id FROM EOI__c WHERE Account__r.ACN__c = :acn ORDER BY CreatedDate DESC LIMIT 1];
        return eoi.Id;
    }



    @AuraEnabled
public static Map<String, Object> createAccountAndUser(Map<String, Object> userdata) {
    Map<String, Object> retMap = new Map<String, Object>();
    try {
        // Initialize GenericObjectFactory
        GenericObjectFactory factory = new GenericObjectFactory();

        // Prepare field mappings
        Map<String, String> accountFieldMapInitializer = new Map<String, String>{
            'firstName' => 'FirstName',
            'lastName' => 'LastName',
            'email' => 'PersonEmail',
            'mobile' => 'PersonMobilePhone',
            'Ventures_Company_Name__c' => 'Ventures_Company_Name__c',
            'Website' => 'Website',
            'Sector__c' => 'Sector__c',
            'ACN__c' => 'ACN__c',
            'Create_Company_Account__c'=>'Create_Company_Account__c',
            'Email_Opt_In__pc' => 'Email_Opt_In__pc',
            'Ts_Cs__pc' => 'Ts_Cs__pc',
            'utm_source__c' => 'utm_source__c',
            'utm_medium__c' => 'utm_medium__c',
            'utm_campaign__c' => 'utm_campaign__c',
            'utm_content__c' => 'utm_content__c',
            'utm_term__c' => 'utm_term__c',
            'utm_keyword__c' => 'utm_keyword__c',
            'Self_Identification__pc' => 'Self_Identification__pc',
            'OwnerId'=>'OwnerId',
            'BillingStreet' => 'BillingStreet',
            'BillingCity' => 'BillingCity',
            'BillingState' => 'BillingState',
            'BillingPostalCode' => 'BillingPostalCode',
            'BillingCountry' => 'BillingCountry',
            'Bank_Account_Name__c' => 'Bank_Account_Name__c',
            'Bank_Account_Number__c' => 'Bank_Account_Number__c',
            'BSB_Number__c'=> 'BSB_Number__c',
            'RecordTypeId' => 'RecordTypeId',
            'source'=>'PersonLeadSource',
            'webSource' => 'Web_Source__pc'
        };
        BidiMap accountFieldMap = new BidiMap(accountFieldMapInitializer);

        // Determine Record Type
        String selectedValue = (String) userdata.get('Self_Identification__pc');
        String recordTypeName = 'VC Person Account';
        if (selectedValue == 'Founder') {
            recordTypeName = 'Ventures Person Account';
        }
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
        userdata.put('RecordTypeId', recordTypeId);

        // Set default values
        userdata.put('Ts_Cs__pc', true);

        // Get Owner
        User owner = [SELECT Id FROM USER WHERE Name = 'The VentureCrowd Team'];
        if(owner == NULL ){
            owner = [SELECT ID,Name FROM User WHERE Id IN (SELECT UserOrGroupId FROM GroupMember WHERE Group.name='CM') AND IsActive = TRUE LIMIT 1];
        }
        userdata.put('OwnerId',owner.Id);

        // Check if Account already exists
        String email = (String) userdata.get('email');
        List<Account> existingAccounts = [
            SELECT Id, PersonEmail
            FROM Account
            WHERE PersonEmail = :email
        ];
        if (!existingAccounts.isEmpty()) {
            retMap.put('IsValidtransaction', false);
            retMap.put('error', 'Account already exists with this email.');
            return retMap;
        }

        // Create Account
        Map<String, Object> accountResult = factory.createRecord('Account', userdata, accountFieldMap);
        if (accountResult.containsKey('Id')) {
            Id accountId = (Id) accountResult.get('Id');

            //setup community nickname
            String communityNickname  =String.valueOf(System.now().getTime() / 1000) + (String) userdata.get('email');
            if(communityNickname.length() > 40)
            communityNickname = communityNickname.substring(0,35);

            // Create User
            User u = new User();
            u.Username = (String) userdata.get('email');
            u.Email = (String) userdata.get('email');
            u.FirstName = (String) userdata.get('firstName');
            u.LastName = (String) userdata.get('lastName');
            u.MobilePhone = (String) userdata.get('mobile');
            u.CommunityNickname = communityNickname;
            u.EmailEncodingKey = 'UTF-8';
            u.Alias = 'ComUser';
            u.TimeZoneSidKey = 'Australia/Brisbane';
            u.LocaleSidKey = 'en_US';
            u.LanguageLocaleKey = 'en_US';

            // Determine Profile
            Map<String, String> profileMap = new Map<String, String>();
            for (Profile p : [SELECT Id, Name FROM Profile WHERE Name IN ('VC Customer Community Login', 'VC Investor Community Plus Login')]) {
                profileMap.put(p.Name, p.Id);
            }
            u.ProfileId = profileMap.get('VC Customer Community Login');

            // Create External User
            Id userId = Site.createExternalUser(u, accountId, (String) userdata.get('password'));

            retMap.put('IsValidtransaction', true);
            retMap.put('IsAccountCreated', true);
            retMap.put('accId', accountId);
            retMap.put('userId', userId);
        } else {
            retMap.put('IsValidtransaction', false);
            retMap.put('error', accountResult.get('error'));
        }
        return retMap;
    } catch (Exception e) {
        logMsgUtility.logMessage(e, 'ReCaptchaAuraController', 'User Registration', 'createAccountAndUser', userdata);
        retMap.put('IsValidtransaction', false);
        retMap.put('error', e.getMessage());
        return retMap;
    }
}
}