common/force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Before checking this box you must run this entity through SKYC and upload the &quot;Main Report&quot; to the related tab within this record. 
By checking this box you&apos;re confirming that you have completed the above and that the entity is verified and is able to complete an investment.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>20</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/BSB_Number__c.field-meta.xml
<CustomField>
    <fullName>BSB_Number__c</fullName>
    <label>BSB Number</label>
    <length>6</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

common/force-app/main/default/classes/EntitiesFactory.cls
public inherited sharing class EntitiesFactory implements IEntitiesFactory{
 
    public List<Account> getRelatedBusinessAccounts(Id contactId){
        // get business account RT ID
        Id bussAccountRecType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('VC Business Account').getRecordTypeId();

        List<Account> accContactRel = [SELECT Id, Name ,BSB_Number__c,Bank_Account_Number__c
        FROM Account 
        WHERE Id In (SELECT AccountId FROM AccountContactRelation WHERE ContactId=:contactId) 
        AND RecordTypeId=:bussAccountRecType
        AND Active__c=True];

        return accContactRel;
    }

    public Id getContactFromLoggedInUser(){
        Id loggedInUser = UserInfo.getUserId();

       // Query the User object to get the ContactId
        User currentUser = [
            SELECT ContactId 
            FROM User 
            WHERE Id = :loggedInUser
            LIMIT 1
        ];
        
        // Return the ContactId
        return currentUser.ContactId;
    }
}