common/force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Before checking this box you must run this entity through SKYC and upload the &quot;Main Report&quot; to the related tab within this record. 
By checking this box you&apos;re confirming that you have completed the above and that the entity is verified and is able to complete an investment.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/BPAY__c.field-meta.xml
<CustomField>
    <fullName>BPAY__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BPAY</label>
    <referenceTo>BPAY__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/BPAY__c/BPAY__c.object-meta.xml
<CustomObject>
    <label>BPAY</label>
    <nameField>
        <displayFormat>BP-{000000}</displayFormat>
        <label>BPAY Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BPAY</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/BPAY__c/fields/Biller_Code__c.field-meta.xml
<CustomField>
    <fullName>Biller_Code__c</fullName>
    <defaultValue>&apos;201913&apos;</defaultValue>
    <label>Biller Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/BPAY__c/fields/CRN__c.field-meta.xml
<CustomField>
    <fullName>CRN__c</fullName>
    <label>CRN</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/CM_Assigned__c.field-meta.xml
<CustomField>
    <fullName>CM_Assigned__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CM Assigned</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>CM</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/CRC_Assigned__c.field-meta.xml
<CustomField>
    <fullName>CRC_Assigned__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRC Assigned</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>CRC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Delete_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Delete_Opportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this is checked then we will delete this opp by trigger</description>
    <label>Delete Opportunity</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Invested_Opp_Prod_ADMIN__c.field-meta.xml
<CustomField>
    <fullName>Invested_Opp_Prod_ADMIN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invested_Opp Prod_ADMIN</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Invested_Product_ADMIN_FIELD__c.field-meta.xml
<CustomField>
    <fullName>Invested_Product_ADMIN_FIELD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please disregard this field. Admin field Only!</inlineHelpText>
    <label>Invested Product_ADMIN FIELD</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Related_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Related_Product_Code__c</fullName>
    <label>Related Product Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/recordTypes/VC.recordType-meta.xml
<RecordType>
    <fullName>VC</fullName>
    <active>true</active>
    <businessProcess>VC</businessProcess>
    <label>VC</label>
</RecordType>

common/force-app/main/default/objects/Product2/fields/Offer_Launch_Date__c.field-meta.xml
<CustomField>
    <fullName>Offer_Launch_Date__c</fullName>
    <description>The date that Capital Raising launched the offer to market</description>
    <label>Offer Launch Date</label>
    <type>DateTime</type>
</CustomField>

common/force-app/main/default/classes/QUE_oppEmailTest.cls
@istest
public class QUE_oppEmailTest {
    @istest
    static void testMethod1(){
        BPAY__c bpay = new BPAY__c();
        bpay.Active__c = false;
        bpay.Biller_Code__c = '201913';
        bpay.CRN__c = '201913';
        insert bpay;
        Account acc = new Account();
        acc.name = 'Test Acount';
        acc.recordtypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('VC Business Account').getRecordTypeId();
        insert acc;        
        Contact con = new Contact();
        con.lastName = 'lastname';
        con.email = 'test@test.com';
        con.AccountId = acc.Id;
        insert con;        
        Id opprectypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('VC').getRecordTypeId();
        List<Opportunity> oppList = new List<Opportunity>();
        Opportunity oppObj = new Opportunity();
        oppObj.name = 'Test1lname';
        oppObj.stageName = 'Application Received';
        oppObj.CRC_Assigned__c = UserInfo.getuserId();
        oppObj.CM_Assigned__c =  UserInfo.getuserId();
        date dt = System.today();
        dt = dt.addDays(5);
        oppObj.delete_opportunity__c = true;
        oppObj.closedate = dt;
        oppObj.Amount = 50000;
        oppObj.recordtypeId = opprectypeId;
        oppObj.Related_Product_Code__c = 'opprectypeId';
        oppObj.AccountId = acc.Id;
            
        Product2 oProduct = new Product2(name='Test');
        oProduct.Offer_Launch_Date__c = System.today().addDays(-4);
        insert oProduct;
        oppObj.Invested_Product_ADMIN_FIELD__c = oProduct.Id;
        oppList.add(oppObj); 
        insert oppList;
        Id pricebookId = Test.getStandardPricebookId();
        //Price Book entry creation
        PricebookEntry customPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = oProduct.Id,
            UnitPrice = 12000, IsActive = true);
        insert customPrice;
        
        //Create Opportunity Line item 1
        OpportunityLineItem oppLineItem = new OpportunityLineItem();
        oppLineItem.Product2Id = oProduct.Id;
        oppLineItem.OpportunityId = oppList[0].Id;
        oppLineItem.Quantity = 1;
        oppLineItem.TotalPrice = 10;
        oppLineItem.PricebookEntryId = customPrice.Id;
        insert oppLineItem;  
        oppList[0].Invested_opp_prod_admin__c = oppLineItem.Id;
        oppList[0].Primary_Contact__c = con.Id;
        update oppList;  
        try{   
            test.starttest();
            System.enqueueJob(new QUE_oppEmail(oppList));  
            test.stoptest(); 
        }catch(exception e){}   
    }
}