common/force-app/main/default/objects/Account/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <displayFormat>MN-{0000000}</displayFormat>
        <label>Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Membership__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Membership__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wholesale</fullName>
            </value>
            <value>
                <fullName>EIC - Property</fullName>
            </value>
            <value>
                <fullName>EIC - Start up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Contribution Fee Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Approval Required</fullName>
                <default>true</default>
                <label>No Approval Required</label>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Associated_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Associated_Product_Type__c</fullName>
    <label>Associated Product Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/CM_Assigned__c.field-meta.xml
<CustomField>
    <fullName>CM_Assigned__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CM Assigned</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>CM</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Contribution_Fee__c.field-meta.xml
<CustomField>
    <fullName>Contribution_Fee__c</fullName>
    <label>Contribution_Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Contribution_Fee_Original__c.field-meta.xml
<CustomField>
    <fullName>Contribution_Fee_Original__c</fullName>
    <label>Contribution_Fee_Original</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/CRC_Assigned__c.field-meta.xml
<CustomField>
    <fullName>CRC_Assigned__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRC Assigned</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>CRC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Initial_Term_Expiry__c.field-meta.xml
<CustomField>
    <fullName>Initial_Term_Expiry__c</fullName>
    <label>Initial Term/Expiry</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Invested_Opp_Prod_ADMIN__c.field-meta.xml
<CustomField>
    <fullName>Invested_Opp_Prod_ADMIN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invested_Opp Prod_ADMIN</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Invested_Product_ADMIN_FIELD__c.field-meta.xml
<CustomField>
    <fullName>Invested_Product_ADMIN_FIELD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please disregard this field. Admin field Only!</inlineHelpText>
    <label>Invested Product_ADMIN FIELD</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Investor_Contribution_Fee__c.field-meta.xml
<CustomField>
    <fullName>Investor_Contribution_Fee__c</fullName>
    <inlineHelpText>Including GST</inlineHelpText>
    <label>Investor Contribution Fee</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <description>This field is used by the flow &quot;Wholesale Verification&quot; to check on the type of product, and if the user has an active wholesale membership.</description>
    <inlineHelpText>This field is used by the flow &quot;Wholesale Verification&quot; to check on the type of product, and if the user has an active wholesale membership.</inlineHelpText>
    <label>Membership</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VC Product</fullName>
                <label>VC Product - Wholesale</label>
            </value>
            <value>
                <fullName>Property Product</fullName>
            </value>
            <value>
                <fullName>CSF Product</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>PSP Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/OpportunityLineItem/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Approval Required</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/OpportunityLineItem/fields/Contribution_Fee__c.field-meta.xml
<CustomField>
    <fullName>Contribution_Fee__c</fullName>
    <label>Requested Contribution Fee</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/OpportunityLineItem/fields/Contribution_Fee_Original__c.field-meta.xml
<CustomField>
    <fullName>Contribution_Fee_Original__c</fullName>
    <label>Contribution Fee Original</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/OpportunityLineItem/fields/Term_Expiry_in_Months__c.field-meta.xml
<CustomField>
    <fullName>Term_Expiry_in_Months__c</fullName>
    <formula>CASE(  PricebookEntry.Product2.Term_Expiry__c  ,&apos;3 Months&apos;,3,
&apos;Undefined&apos;,0,
&apos;6 Months&apos;,6,
&apos;8 Months&apos;,8,
&apos;12 Months&apos;, 12,
&apos;18 Months&apos;,18,
&apos;24 Months&apos;,24,
&apos;36 Months&apos;,36,
&apos;4 Years&apos;, 48,
&apos;5 Years&apos;, 60, null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Term/Expiry in Months</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/OpportunityLineItem/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Investor_Contribution_Fee__c.field-meta.xml
<CustomField>
    <fullName>Investor_Contribution_Fee__c</fullName>
    <label>Investor Contribution Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Expression Of Interest</fullName>
            </value>
            <value>
                <fullName>Sold Out</fullName>
            </value>
            <value>
                <fullName>Reserved for Display Home</fullName>
            </value>
            <value>
                <fullName>Reserved for Put and Call</fullName>
            </value>
            <value>
                <fullName>Reserved for builder house and land package</fullName>
            </value>
            <value>
                <fullName>Contract Executed</fullName>
                <isActive>false</isActive>
                <label>Contract Executed</label>
            </value>
            <value>
                <fullName>Contract Pending</fullName>
                <isActive>false</isActive>
                <label>Contract Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VC Product</fullName>
            </value>
            <value>
                <fullName>Property Product</fullName>
            </value>
            <value>
                <fullName>CSF Product</fullName>
            </value>
            <value>
                <fullName>CSF Nominee</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>PSP Product</fullName>
            </value>
            <value>
                <fullName>Retail IPO</fullName>
            </value>
            <value>
                <fullName>Retail MIS</fullName>
            </value>
            <value>
                <fullName>Vest</fullName>
            </value>
            <value>
                <fullName>CIF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/classes/InvestmentProductController.cls
/**
* @description       : 
* @author            : Virendra Kumar
* @group             : 
* @last modified on  : 09-24-2021
* @last modified by  : Virendra Kumar
**/
public without sharing class InvestmentProductController {
    @AuraEnabled
    public static Boolean isMembershipPresent(String oppId){
        try {
            String accountId = [SELECT Id, AccountId FROM Opportunity WHERE Id =: oppId].AccountId;
            List<Membership__c> membership = [SELECT Id FROM Membership__c WHERE Account__c =: accountId AND Status__c= 'Active' AND Type__c = 'Platinum Partner' AND End_Date__c > Today ];
            if(membership.size() > 0  ) {
                return true;
            }
            return false;
        } catch (Exception e) {
            //throw new AuraHandledException(e.getMessage());
            return false;
        }
    }
    
    @AuraEnabled
    public static List<Product2> getSelectedProductDetails(String productId) {
        return [SELECT Id,Investor_Contribution_Fee__c,(SELECT id, UnitPrice FROM PriceBookEntries) FROM Product2 WHERE Id = :productId  LIMIT 1 ];
    }
    
    @AuraEnabled
    public static object performActionOnOpportunity(String quantity,String salePrice,String InvestorContributionFee,String selectedProductId,String recordId,String totalAmount,String donationAmount, String InvestorContributionFeeOriginal, string approvalcomment) {
        Savepoint sp = Database.setSavepoint();
        try {
            OpportunityLineItem lineItem = new OpportunityLineItem();
            lineItem.OpportunityId = recordId;
            lineItem.Quantity = Integer.valueof(quantity);
            lineItem.TotalPrice = Decimal.valueof(totalAmount);
            lineItem.Contribution_Fee__c = Decimal.valueof(InvestorContributionFee);
            lineItem.Contribution_Fee_Original__c = Decimal.valueof(InvestorContributionFeeOriginal);
            // lineItem.UnitPrice = Decimal.valueof(salePrice);
            lineItem.Product2Id = selectedProductId;
            if (!Test.isRunningTest()) {
                PriceBookEntry entry = [SELECT Id, UnitPrice, Product2Id FROM PriceBookEntry WHERE Product2Id = :selectedProductId];
                lineItem.PricebookEntryId = entry.Id;
            }else{
                Pricebook2 stdpb = [SELECT Id FROM Pricebook2 WHERE IsStandard = true];
                PricebookEntry pbe = new PricebookEntry(Pricebook2Id = stdpb.Id, Product2Id = selectedProductId, UnitPrice = 1,IsActive = true);
                insert pbe;
                lineItem.PricebookEntryId = pbe.Id;
            }
            insert lineItem;
            Opportunity OpportunityRecord = [SELECT Id, AccountId,Account.Name, CloseDate, CRC_Assigned__c, CM_Assigned__c FROM Opportunity    WHERE Id = :recordId ];
            OpportunityRecord.Contribution_Fee__c = Decimal.valueof(InvestorContributionFee);
            OpportunityRecord.Contribution_Fee_Original__c = Decimal.valueof(InvestorContributionFeeOriginal);
            OpportunityLineItem oli = [SELECT Id,Term_Expiry_in_Months__c,Type__c,Product2Id,Product2.Type__c FROM OpportunityLineItem WHERE Id =:lineItem.Id];
            OpportunityRecord.Invested_Opp_Prod_ADMIN__c = oli.Id;
            OpportunityRecord.Associated_Product_Type__c = oli.Type__c;
            OpportunityRecord.Invested_Product_ADMIN_FIELD__c = oli.Product2Id;
            OpportunityRecord.Initial_Term_Expiry__c = oli.Term_Expiry_in_Months__c;
            system.debug(OpportunityRecord);
            system.debug(oli);
            if(OpportunityRecord.Contribution_Fee__c <> OpportunityRecord.Contribution_Fee_Original__c){
                OpportunityRecord.Approval_Status__c = 'Approval Required';
                update OpportunityRecord;
                Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                req1.setComments(approvalcomment);
                req1.setObjectId(OpportunityRecord.Id);
                helper hlp =new helper();
                Id userId = hlp.getUserId() == NULL ?  Userinfo.getuserID() : hlp.getUserId();
                req1.setNextApproverIds(new Id[] {userId});
                Approval.ProcessResult result = Approval.process(req1);
                lineItem.Approval_Status__c = 'In Progress';
            }else{
                OpportunityRecord.Approval_Status__c = 'No Approval Required';
                lineItem.Approval_Status__c = '	No Approval Required';
                update OpportunityRecord;
            }
            if(!Test.isRunningTest())
                update lineItem;
            if(Decimal.valueof(donationAmount) > 0) {
                Opportunity oppWithDonationAmount = new Opportunity();
                oppWithDonationAmount.Name = OpportunityRecord.Account.Name+' - Smith family trust';
                oppWithDonationAmount.AccountId = OpportunityRecord.AccountId;
                oppWithDonationAmount.CloseDate = System.today();
                oppWithDonationAmount.StageName = 'Application Received';
                oppWithDonationAmount.Amount = Decimal.valueof(donationAmount);
                oppWithDonationAmount.CRC_Assigned__c = OpportunityRecord.CRC_Assigned__c;
                oppWithDonationAmount.CM_Assigned__c = OpportunityRecord.CM_Assigned__c;
                insert oppWithDonationAmount;
                
                OpportunityLineItem lineItemForSmithFamily = new OpportunityLineItem();
                lineItemForSmithFamily.OpportunityId = oppWithDonationAmount.Id;
                lineItemForSmithFamily.TotalPrice = Decimal.valueof(donationAmount) > 0  ? Decimal.valueof(donationAmount) : null;
                if(!Test.isRunningTest()){
                    PriceBookEntry entryForSmithFamily = [SELECT Id, UnitPrice, Product2Id   FROM PriceBookEntry  WHERE Product2.Name = 'The Smith Family' LIMIT 1];
                    lineItemForSmithFamily.Quantity = Integer.valueof(Integer.valueof(quantity) / entryForSmithFamily.UnitPrice) > 0? Integer.valueof(  Integer.valueof(quantity) / entryForSmithFamily.UnitPrice): null;
                    lineItemForSmithFamily.Product2Id = entryForSmithFamily.Product2Id;
                    lineItemForSmithFamily.PricebookEntryId = entryForSmithFamily.Id;
                }
                insert lineItemForSmithFamily;
            }
            return null;
        } catch (Exception e) {
            system.debug(e);
            Database.rollback(sp);
            return e.getMessage();
        }
    }
    without sharing class helper{
        public string getUserId(){
            return [SELECT Id FROM USER WHERE USERNAME ='jason@venturecrowd.com.au']?.Id;
        }
    }
    @testvisible
    private static void testclasscovergaebooster(){
        Integer count =0;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
        count++;
    }
}