common/force-app/main/default/objects/Account/fields/Approval_Requested_For__c.field-meta.xml
<CustomField>
    <fullName>Approval_Requested_For__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Requested For</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Account/fields/Has_Made_1_Investment__c.field-meta.xml
<CustomField>
    <fullName>Has_Made_1_Investment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Box will be ticked if account has 1 Won Opportunity.</description>
    <label>Has Made 1 Investment</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/Total_Investment__c.field-meta.xml
<CustomField>
    <fullName>Total_Investment__c</fullName>
    <description>To Calculate Total Investment</description>
    <label>Total Investment</label>
    <summarizedField>Investment__c.Investment_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Investment__c.Process_Fund_Disbursement__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Investment__c.Stage__c</field>
        <operation>equals</operation>
        <value>Closed Won</value>
    </summaryFilterItems>
    <summaryForeignKey>Investment__c.Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

common/force-app/main/default/classes/accTriggerHandler.cls
public without sharing class accTriggerHandler {
    public static void beforeinsert(){
        for(Account a : (List<Account>) Trigger.new){
            // Only set investment flag synchronously.
            a.Has_Made_1_Investment__c = a.Total_Investment__c >= 1;         
        }
    }
 
    public static void beforeupdate(){
        // Minimal synchronous logic here.
        for(Account a : (List<Account>) Trigger.new){
            // If Approval_Status changed to Approved, update owner
            if(a.Approval_Status__c == 'Approved' && Trigger.oldMap.get(a.Id).get('Approval_Status__c') <> a.get('Approval_Status__c')){
                a.OwnerId = a.Approval_Requested_For__c;
            }
            // Set the investment flag
            a.Has_Made_1_Investment__c = a.Total_Investment__c >= 1;
        }
    }
}