common/force-app/main/default/objects/Account/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>20</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/BSB_Number__c.field-meta.xml
<CustomField>
    <fullName>BSB_Number__c</fullName>
    <label>BSB Number</label>
    <length>6</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

common/force-app/main/default/classes/acctriggerHandlerTest.cls
/**
Test method for accTriggerHandler
 */
@istest
class acctriggerHandlerTest {
    @IsTest
    static void methodName(){        
        createCaseCntrl.getUserDEtails();
        Account acc = new Account();
        acc.name = 'Test Acount';
        insert acc;
        acc.Bank_Account_Number__c = 'test';
        acc.BSB_Number__c = 'test';
        acc.Bank_Account_Name__c = 'test';
        update acc;
    }
}