common/force-app/main/default/objects/Account/fields/BPAY__c.field-meta.xml
<CustomField>
    <fullName>BPAY__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BPAY</label>
    <referenceTo>BPAY__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/ID_Checked__c.field-meta.xml
<CustomField>
    <fullName>ID_Checked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OUT OF USE - ID Checked</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/BPAY__c/BPAY__c.object-meta.xml
<CustomObject>
    <label>BPAY</label>
    <nameField>
        <displayFormat>BP-{000000}</displayFormat>
        <label>BPAY Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BPAY</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Contact/fields/ID_Checked__c.field-meta.xml
<CustomField>
    <fullName>ID_Checked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ID Checked</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Charity</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Conveyancer</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Development Manager</fullName>
            </value>
            <value>
                <fullName>Financial Adviser</fullName>
            </value>
            <value>
                <fullName>Fund Manager</fullName>
            </value>
            <value>
                <fullName>Integrator</fullName>
            </value>
            <value>
                <fullName>Investor</fullName>
            </value>
            <value>
                <fullName>Mortgage Broker</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Press</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Real Estate Agent</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Special Purpose Vehicle</fullName>
            </value>
            <value>
                <fullName>Trustee Company</fullName>
            </value>
            <value>
                <fullName>Venture Capital Business</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Associated_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Associated_Product_Type__c</fullName>
    <label>Associated Product Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Bpay_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Bpay_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>check this to send the bpay creds email to investor</inlineHelpText>
    <label>Bpay Email Sent</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Donation__c.field-meta.xml
<CustomField>
    <fullName>Donation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Donation</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Donation_Related_Investment_Opp__c.field-meta.xml
<CustomField>
    <fullName>Donation_Related_Investment_Opp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>when an investor submits an application from portal and selects a donation amount, this field will be linked to either donation opp or related invested opp.</inlineHelpText>
    <label>Donation / Related Investment Opp</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities (Donation / Related Investment Opp)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Invested_Opp_Prod_ADMIN__c.field-meta.xml
<CustomField>
    <fullName>Invested_Opp_Prod_ADMIN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invested_Opp Prod_ADMIN</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Invested_Product_ADMIN_FIELD__c.field-meta.xml
<CustomField>
    <fullName>Invested_Product_ADMIN_FIELD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please disregard this field. Admin field Only!</inlineHelpText>
    <label>Invested Product_ADMIN FIELD</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Primary_Contact_email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_email__c</fullName>
    <formula>Primary_Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Contact email</label>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Related_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Related_Product_Code__c</fullName>
    <label>Related Product Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Sent_Verify_ID_Email__c.field-meta.xml
<CustomField>
    <fullName>Sent_Verify_ID_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>this is auto checked when the un verified invertor submits the invest application.</inlineHelpText>
    <label>Sent Verify ID Email</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/TSF_Donation_email_sent__c.field-meta.xml
<CustomField>
    <fullName>TSF_Donation_email_sent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check box is used to trigger TSF first email and second email. Please review TSF AR process for details.</description>
    <inlineHelpText>Check box is used to trigger TSF first email and second email. Please review TSF AR process for details.</inlineHelpText>
    <label>TSF Email Trigger ADMIN ONLY</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/TSF_Receipt_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>TSF_Receipt_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TSF Receipt Email Sent</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VC Product</fullName>
                <label>VC Product - Wholesale</label>
            </value>
            <value>
                <fullName>Property Product</fullName>
            </value>
            <value>
                <fullName>CSF Product</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>PSP Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Opportunity/recordTypes/VC.recordType-meta.xml
<RecordType>
    <fullName>VC</fullName>
    <active>true</active>
    <businessProcess>VC</businessProcess>
    <label>VC</label>
</RecordType>

common/force-app/main/default/objects/Product2/fields/AFSL_Licence__c.field-meta.xml
<CustomField>
    <fullName>AFSL_Licence__c</fullName>
    <label>AFSL Licence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VC</fullName>
            </value>
            <value>
                <fullName>GSL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VC Product</fullName>
            </value>
            <value>
                <fullName>Property Product</fullName>
            </value>
            <value>
                <fullName>CSF Product</fullName>
            </value>
            <value>
                <fullName>CSF Nominee</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>PSP Product</fullName>
            </value>
            <value>
                <fullName>Retail IPO</fullName>
            </value>
            <value>
                <fullName>Retail MIS</fullName>
            </value>
            <value>
                <fullName>Vest</fullName>
            </value>
            <value>
                <fullName>CIF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/classes/QUE_oppEmail.cls
public without sharing class QUE_oppEmail implements Queueable {
    public List<opportunity> opplist;
    public QUE_oppEmail(List<opportunity> opplist) {
        this.opplist=opplist;
    }
    public void execute(QueueableContext context) {
        try{
            Opportunity opp1;
            List<opportunity> qualifiedopplst = new List<opportunity>();
            List<Id> conIdlst = new List<Id>();
            List<Id> prodIdlst = new List<Id>();
            List<opportunity> verifyIdopplst = new List<opportunity>();
            List<opportunity> verifyIdwithDonationlst = new List<opportunity>();
            List<opportunity> IdwithDonation = new List<opportunity>();
            List<opportunity> IdwithoutDonation = new List<opportunity>();
            List<opportunity> tsfdonation = new List<opportunity>();
            List<opportunity> oppToUpdate = new List<opportunity>();
            Id opprectypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('VC').getRecordTypeId();
            List<Messaging.SingleEmailMessage> messages = new List<Messaging.SingleEmailMessage>();
            List<string> emailtemplatelst = new List<string>{'CSF_Nominee_New_ID_Verified_Investor_without_Donation','CSF_Nominee_NEW_ID_NOT_Verified_Investor_without_Donation','GSL_New_ID_Verified_Investor_without_Donation','GSL_NEW_ID_NOT_Verified_Investor_without_Donation','NEW_ID_NOT_Verified_Investor_without_Donation','NEW_ID_NOT_Verified_Investor_with_Donation','New_ID_Verified_Investor_without_Donation','New_ID_Verified_Investor_with_Donation','TSF_Recipt_Email','New_ID_Verified_Investor_with_Donation_OURCOW','New_ID_Verified_Investor_without_Donation_OURCOW'};
            Map<string,EmailTemplate> etmap = new Map<string,EmailTemplate>();
            Map<String,List<Opportunity>> oppmap = new Map<String,List<Opportunity>>();
            for(string s : emailtemplatelst){
                oppmap.put(s,new List<opportunity>());
            }
            //OUR COW and With Dontation are depracted
            for(EmailTemplate et : [SELECT Id,DeveloperName FROM EmailTemplate WHERE DeveloperName IN :emailtemplatelst]){
                etmap.put(et.DeveloperName,et);
            }
            OrgWideEmailAddress orgwideemail = [SELECT Id,Address,DisplayName FROM OrgWideEmailAddress WHERE Address = 'investor@venturecrowd.com.au'];
            //This for loop was modified to include PSP Products.
            for(Opportunity opp : opplist){
                if(opp.StageName == 'Application Received' && opp.RecordTypeId == opprectypeId 
                                                        && opp.Related_Product_Code__c != 'TSF' && opp.Invested_opp_prod_admin__c != NULL 
                                                        && opp.Primary_Contact_email__c != NULL && opp.Primary_Contact__c != NULL  && !opp.Bpay_Email_sent__c && opp.Amount <> NULL 
                                                        && (opp.Associated_Product_Type__c <> 'PSP Product' || opp.Associated_Product_Type__c == 'PSP Product')){
                    qualifiedopplst.add(opp);
                    conIdlst.add(opp.Primary_Contact__c);
                }
                if(opp.StageName == 'Receipt Issued' && opp.RecordTypeId == opprectypeId && opp.Related_Product_Code__c == 'TSF' 
                                                        && opp.Primary_Contact_email__c != NULL && !opp.TSF_receipt_email_sent__c 
                                                        && (opp.Associated_Product_Type__c <> 'PSP Product' || opp.Associated_Product_Type__c == 'PSP Product')){
                    // oppmap.get('TSF_Recipt_Email').add(opp);
                    // opp1 = new Opportunity(Id=opp.Id);
                    // opp1.TSF_receipt_email_sent__c = true;
                    // oppToUpdate.add(opp1);
                }
                prodIdlst.add(opp.Invested_Product_ADMIN_FIELD__c);
            }
            Map<Id,contact> conMap = new Map<Id,contact>([SELECT Id,ID_Checked__c,Account.BPAY__c FROM Contact WHERE Id In :conIdlst]); 
            Map<Id,Product2> prodMap = new Map<Id,Product2>([SELECT Id,Type__c,AFSL_Licence__c FROM Product2 WHERE Id In :prodIdlst]); 
            for(Opportunity opp : qualifiedopplst){
                product2 prod = prodMap.get(opp.Invested_Product_ADMIN_FIELD__c);
                if(!opp.Sent_verify_id_email__c && !opp.TSF_Donation_EMail_Sent__c && !conMap.get(opp.Primary_Contact__c).ID_Checked__c){
                    if(opp.Donation_related_investment_opp__c == NULL){
                        if(prod.Type__c == 'Retail IPO' && prod.AFSL_Licence__c == 'GSL'){
                            oppmap.get('GSL_NEW_ID_NOT_Verified_Investor_without_Donation').add(opp);
                        }else if(prod.Type__c == 'CSF Nominee'){
                            oppmap.get('CSF_Nominee_NEW_ID_NOT_Verified_Investor_without_Donation').add(opp);
                        }else{
                            oppmap.get('NEW_ID_NOT_Verified_Investor_without_Donation').add(opp);
                        }
                    }else{
                        oppmap.get('NEW_ID_NOT_Verified_Investor_with_Donation').add(opp);
                    }
                    opp1 = new Opportunity(Id=opp.Id);
                    opp1.Sent_verify_id_email__c = true;
                    oppToUpdate.add(opp1);
                }
                if(!opp.TSF_Donation_EMail_Sent__c && opp.Donation_related_investment_opp__c == NULL && conMap.get(opp.Primary_Contact__c).ID_Checked__c && conMap.get(opp.Primary_Contact__c).Account.BPAY__c !=NULL && !opp.Donation__c){
                    if(opp.Related_Product_Code__c != 'OURCOW'){
                        if(prod.Type__c == 'Retail IPO' && prod.AFSL_Licence__c == 'GSL'){
                            oppmap.get('GSL_New_ID_Verified_Investor_without_Donation').add(opp);
                        }else if(prod.Type__c == 'CSF Nominee'){
                            oppmap.get('CSF_Nominee_New_ID_Verified_Investor_without_Donation').add(opp);
                        }else{
                            oppmap.get('New_ID_Verified_Investor_with_Donation').add(opp);
                        } 
                    }else{
                        oppmap.get('New_ID_Verified_Investor_without_Donation_OURCOW').add(opp);
                    }                                        
                    opp1 = new Opportunity(Id=opp.Id);
                    opp1.Bpay_email_sent__c = true;
                    oppToUpdate.add(opp1);
                }
                if(!opp.TSF_Donation_EMail_Sent__c && opp.Donation_related_investment_opp__c <> NULL && conMap.get(opp.Primary_Contact__c).ID_Checked__c && conMap.get(opp.Primary_Contact__c).Account.BPAY__c !=NULL){
                    // if(opp.Related_Product_Code__c != 'OURCOW'){
                    //     if(prod.Type__c == 'Retail IPO' && prod.AFSL_Licence__c == 'GSL'){
                    //         oppmap.get('GSL_New_ID_Verified_Investor_without_Donation').add(opp);
                    //     }else{
                    //         oppmap.get('New_ID_Verified_Investor_without_Donation').add(opp);
                    //     }                        
                    // }
                    // else{
                    //     oppmap.get('New_ID_Verified_Investor_with_Donation_OURCOW').add(opp);
                    // }                    
                    // opp1 = new Opportunity(Id=opp.Id);
                    // opp1.TSF_Donation_EMail_Sent__c = true;
                    // oppToUpdate.add(opp1);
                }
            }
            for(string s : oppmap.keyset()){
                for(Opportunity opp : oppmap.get(s)){
                    Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                    message.setTemplateId(etmap.get(s).Id);
                    message.setTargetObjectId(opp.Primary_Contact__c);
                    message.setWhatId(opp.Id);
                    message.setOrgWideEmailAddressId(orgwideemail.Id);
                    messages.add(message);
                }
            }        
            Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
            for(Messaging.SendEmailResult r : results){
                if(!r.success){
                    System.debug('The email failed to send: ' + r.errors);
                }
            }
            update oppToUpdate;  
        }catch(Exception e){
            system.debug(e);
        }
    }
}