common/force-app/main/default/objects/Account/fields/GID_Address_Country__c.field-meta.xml
<CustomField>
    <fullName>GID_Address_Country__c</fullName>
    <label>GID_Address_Country</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/GID_Address_Flat_Number__c.field-meta.xml
<CustomField>
    <fullName>GID_Address_Flat_Number__c</fullName>
    <label>GID_Address Flat Number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/GID_Address_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>GID_Address_Postal_Code__c</fullName>
    <label>GID_Address Postal Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/GID_Address_State__c.field-meta.xml
<CustomField>
    <fullName>GID_Address_State__c</fullName>
    <label>GID_Address State</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/GID_Address_Street__c.field-meta.xml
<CustomField>
    <fullName>GID_Address_Street__c</fullName>
    <label>GID_Address Street</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/GID_Address_street_Number__c.field-meta.xml
<CustomField>
    <fullName>GID_Address_street_Number__c</fullName>
    <label>GID_Address street Number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/GID_Address_Street_Type__c.field-meta.xml
<CustomField>
    <fullName>GID_Address_Street_Type__c</fullName>
    <label>GID_Address Street Type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/GID_Address_Suburb__c.field-meta.xml
<CustomField>
    <fullName>GID_Address_Suburb__c</fullName>
    <label>GID_Address Suburb</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/GID_Changed_Address_Flat_Number__c.field-meta.xml
<CustomField>
    <fullName>GID_Changed_Address_Flat_Number__c</fullName>
    <label>GID_Changed Address Flat Number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/GID_Changed_Address_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>GID_Changed_Address_Postal_Code__c</fullName>
    <label>GID_Changed Address Postal Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/GID_Changed_Address_State__c.field-meta.xml
<CustomField>
    <fullName>GID_Changed_Address_State__c</fullName>
    <label>GID_Changed Address State</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/GID_Changed_Address_Street__c.field-meta.xml
<CustomField>
    <fullName>GID_Changed_Address_Street__c</fullName>
    <label>GID_Changed Address Street</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/GID_Changed_Address_Street_Type__c.field-meta.xml
<CustomField>
    <fullName>GID_Changed_Address_Street_Type__c</fullName>
    <label>GID_Changed Address Street Type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/GID_Changed_Address_Suburb__c.field-meta.xml
<CustomField>
    <fullName>GID_Changed_Address_Suburb__c</fullName>
    <label>GID_Changed Address Suburb</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/GID_Changed_First_Name__c.field-meta.xml
<CustomField>
    <fullName>GID_Changed_First_Name__c</fullName>
    <label>GID_Changed First Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/GID_Changed_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>GID_Changed_Last_Name__c</fullName>
    <label>GID_Changed Last Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/GID_Changed_Street_Number__c.field-meta.xml
<CustomField>
    <fullName>GID_Changed_Street_Number__c</fullName>
    <label>GID_Changed Street Number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/GID_Chnaged_DOB__c.field-meta.xml
<CustomField>
    <fullName>GID_Chnaged_DOB__c</fullName>
    <label>GID_Chnaged DOB</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/GreenID_DOB__c.field-meta.xml
<CustomField>
    <fullName>GreenID_DOB__c</fullName>
    <label>GreenID DOB</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/GreenID_First_Name__c.field-meta.xml
<CustomField>
    <fullName>GreenID_First_Name__c</fullName>
    <label>GreenID First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/GreenID_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>GreenID_Last_Name__c</fullName>
    <label>GreenID Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/GreenID_Middle_Name__c.field-meta.xml
<CustomField>
    <fullName>GreenID_Middle_Name__c</fullName>
    <label>GreenID Middle Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/GreenId_Status__c.field-meta.xml
<CustomField>
    <fullName>GreenId_Status__c</fullName>
    <label>GreenId Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IN_PROGRESS</fullName>
            </value>
            <value>
                <fullName>VERIFIED</fullName>
            </value>
            <value>
                <fullName>VERIFIED_ADMIN</fullName>
            </value>
            <value>
                <fullName>VERIFIED_WITH_CHANGES</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
            </value>
            <value>
                <fullName>null</fullName>
            </value>
            <value>
                <fullName>LOCKED_OUT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Account/fields/GreenID_TransID__c.field-meta.xml
<CustomField>
    <fullName>GreenID_TransID__c</fullName>
    <label>GreenID TransID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/GreenID_USerID__c.field-meta.xml
<CustomField>
    <fullName>GreenID_USerID__c</fullName>
    <label>GreenID USerID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/classes/VerificationController.cls
/**

**/
public without sharing class VerificationController {
    @AuraEnabled
    public static Account checkVerificationNeeded(){
        try {
            User user = [SELECT Id, Contact.AccountId FROM User WHERE Id =: Userinfo.getUserId()];
            return [SELECT Id, ID_Checked__pc,GreenId_Status__c FROM Account WHERE Id =: user.Contact.AccountId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static String updateAccountVerificationDetails(String dataToBeUpdated){
        try {
            List<DataToBeUpdatedWrapper> result = (List<DataToBeUpdatedWrapper>) System.JSON.deserialize(dataToBeUpdated, List<DataToBeUpdatedWrapper>.class);
            User user = [SELECT Id, contactId, contact.AccountId,Account.ispersonaccount FROM User WHERE Id =: Userinfo.getUserId()];
        if(user.contact.AccountId != null) {
            Account acc = new Account();
            acc.Id = user.contact.AccountId;
            for(DataToBeUpdatedWrapper data : result) { 
                if(data.label == 'verificationId') {
                    acc.GreenID_USerID__c = data.value;
                }else if(data.label == 'verificationToken') {
                    acc.GreenID_TransID__c = data.value;
                }else if(data.label == 'verificationResult') {
                    acc.GreenId_Status__c  = data.value;
                }else if(data.label == 'givenName') {
                    acc.GreenID_First_Name__c  = data.value;
                }else if(data.label == 'middleNames') {
                    acc.GreenID_Middle_Name__c  = data.value;
                }else if(data.label == 'surname') {
                    acc.GreenID_Last_Name__c  = data.value;
                }else if(data.label == 'dob') {
                    acc.GreenID_DOB__c  = date.valueOf(data.value);
                }
            }
            if((acc.GreenId_Status__c == 'VERIFIED' || acc.GreenId_Status__c == 'VERIFIED_ADMINS'
               || acc.GreenId_Status__c == 'VERIFIED_WITH_CHANGES') && !test.isRunningTest()){
                  acc.ID_Checked__pc = true; 
            }
            update acc;
            return 'Success';
        }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return '';
    }

    public class DataToBeUpdatedWrapper{
        public String label;
        public String value;
    }
    @AuraEnabled
    public static string getverificationresult(string accountId,string webServicePassword,string verificationToken){
        dynamicformServicesRegistrationsEdent.DynamicFormsServiceV3Port parentclass1 = new dynamicformServicesRegistrationsEdent.DynamicFormsServiceV3Port();
        dynamicformServicesRegistrationsEdent.currentStatusV3 response = parentclass1.getVerificationResult(accountId,webServicePassword,null,verificationToken,null);
        system.debug(response);
        dynamicformServicesRegistrationsEdent.registrationDetailsV3 registrationDetails = response.registrationDetails;
        dynamicformServicesRegistrationsEdent.address currentResidentialAddress = registrationDetails.currentResidentialAddress;
        dynamicformServicesRegistrationsEdent.dateOfBirth dob = registrationDetails.dob;
        dynamicformServicesRegistrationsEdent.name name = registrationDetails.name;
        dynamicformServicesRegistrationsEdent.sourceFieldsV3 sourceFields = response.sourceFields;
        dynamicformServicesRegistrationsEdent.sourceListV3 sourceList = response.sourceList;
        dynamicformServicesRegistrationsEdent.verificationResultV3 verificationResult = response.verificationResult;
        dynamicformServicesRegistrationsEdent.checkResultV3[] individualResult = verificationResult.individualResult;
        string overallVerificationStatus = verificationResult.overallVerificationStatus;
        string verificationId = verificationResult.verificationId;
        User user = [SELECT Id, contactId, contact.AccountId,Account.ispersonaccount FROM User WHERE Id =: Userinfo.getUserId()];
        if(user.contact.AccountId != null) {
            Account acc = new Account();
            acc.Id = user.contact.AccountId;
            acc.GreenID_USerID__c = verificationId;
            acc.GreenID_TransID__c = verificationToken;
            acc.GreenId_Status__c  = overallVerificationStatus;
            acc.GreenID_First_Name__c  = name.givenName;
            acc.GreenID_Middle_Name__c  = name.middleNames;
            acc.GreenID_Last_Name__c  = name.surname;
            acc.GreenID_DOB__c  = date.newinstance(Integer.valueOf(dob.year),Integer.valueOf(dob.month),Integer.valueOf(dob.day));
            if((acc.GreenId_Status__c == 'VERIFIED' || acc.GreenId_Status__c == 'VERIFIED_ADMINS'|| acc.GreenId_Status__c == 'VERIFIED_WITH_CHANGES') && !test.isRunningTest()){
                acc.ID_Checked__pc = true; 
            }
            acc.GID_Address_Country__c = currentResidentialAddress.country;
            acc.GID_Address_Flat_Number__c = currentResidentialAddress.flatNumber;
            acc.GID_Address_Postal_Code__c = currentResidentialAddress.postcode;
            acc.GID_Address_State__c = currentResidentialAddress.state;
            acc.GID_Address_Street__c = currentResidentialAddress.streetName;
            acc.GID_Address_street_Number__c = currentResidentialAddress.streetNumber;
            acc.GID_Address_Street_Type__c = currentResidentialAddress.streetType;
            acc.GID_Address_Suburb__c = currentResidentialAddress.suburb;
            for(dynamicformServicesRegistrationsEdent.checkResultV3 inv : individualResult){
                if(inv.fieldResult <> null)
                for(dynamicformServicesRegistrationsEdent.fieldResultV3 flr : inv.fieldResult){
                    if(flr.status == 'CHANGED' && inv.state == 'VERIFIED_WITH_CHANGES'){
                        if(flr.name == 'state'){
                            acc.GID_Changed_Address_State__c = flr.changedValue;
                        }else if(flr.name == 'postcode'){
                            acc.GID_Changed_Address_Postal_Code__c = flr.changedValue;
                        }else if(flr.name == 'suburb'){
                            acc.GID_Changed_Address_Suburb__c = flr.changedValue;
                        }else if(flr.name == 'streetType'){
                            acc.GID_Changed_Address_Street_Type__c = flr.changedValue;
                        }else if(flr.name == 'street'){
                            acc.GID_Changed_Address_Street__c = flr.changedValue;
                        }else if(flr.name == 'streetNumber'){
                            acc.GID_Changed_Street_Number__c = flr.changedValue;
                        }else if(flr.name == 'flatNumber'){
                            acc.GID_Changed_Address_Flat_Number__c = flr.changedValue;
                        }else if(flr.name == 'surname'){
                            acc.GID_Changed_Last_Name__c = flr.changedValue;
                        }else if(flr.name == 'givenName'){
                            acc.GID_Changed_First_Name__c = flr.changedValue;
                        }else if(flr.name == 'dob'){
                            acc.GID_Chnaged_DOB__c = Date.valueof(flr.changedValue);
                        }
                    }
                }
            }
            update acc;
        }
        return overallVerificationStatus;
    }
}