common/force-app/main/default/objects/Account/fields/ID_Checked__c.field-meta.xml
<CustomField>
    <fullName>ID_Checked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OUT OF USE - ID Checked</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/Total_Investment__c.field-meta.xml
<CustomField>
    <fullName>Total_Investment__c</fullName>
    <description>To Calculate Total Investment</description>
    <label>Total Investment</label>
    <summarizedField>Investment__c.Investment_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Investment__c.Process_Fund_Disbursement__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Investment__c.Stage__c</field>
        <operation>equals</operation>
        <value>Closed Won</value>
    </summaryFilterItems>
    <summaryForeignKey>Investment__c.Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/Total_Personal_Investments__c.field-meta.xml
<CustomField>
    <fullName>Total_Personal_Investments__c</fullName>
    <label>Total Personal Investments</label>
    <summaryFilterItems>
        <field>Investment__c.Process_Fund_Disbursement__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Investment__c.Stage__c</field>
        <operation>equals</operation>
        <value>Closed Won</value>
    </summaryFilterItems>
    <summaryForeignKey>Investment__c.Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

common/force-app/main/default/objects/Contact/fields/ID_Checked__c.field-meta.xml
<CustomField>
    <fullName>ID_Checked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ID Checked</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <label>Investment</label>
    <nameField>
        <displayFormat>IN-{00000000}</displayFormat>
        <label>Investment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Investment__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Investment_Stages</valueSetName>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Total_Investment__c.field-meta.xml
<CustomField>
    <fullName>Total_Investment__c</fullName>
    <inlineHelpText>Sum of &quot;Amount&quot; for opportinities in &quot;Closed Won&quot; state</inlineHelpText>
    <label>Total Investment</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/globalValueSets/Investment_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Why Appt Set Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Decision Appt Set Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Closing Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Application Received</fullName>
    </customValue>
    <customValue>
        <fullName>Receipt Issued</fullName>
    </customValue>
    <customValue>
        <fullName>Closed Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Closed Won</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
        <isActive>false</isActive>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>Closing</fullName>
        <isActive>false</isActive>
        <label>Closing</label>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
        <isActive>false</isActive>
        <label>Active</label>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
        <isActive>false</isActive>
        <label>Pending</label>
    </customValue>
    <description>Stages of an Investment</description>
    <masterLabel>Investment Stages</masterLabel>
</GlobalValueSet>

common/force-app/main/default/classes/MyPortfolio_Investments.cls
public with sharing class MyPortfolio_Investments {
    @AuraEnabled
    public static String getInvestments(){

        //get logged in accId
        List<Id> accidlst = new List<Id>();
        User usr = [SELECT Id,contact.AccountId,contactId  FROM USER WHERE ID =:UserInfo.getuserId()];
        Id loggedinaccId = usr.contact.AccountId;

        // add to acc id list
        accidlst.add(loggedinaccId);

        // get other accounts related to the logged in acc Id & add them to the acc id list
        List<AccountContactRelation> acrlst = [SELECT Id, Account.Name,AccountId FROM AccountContactRelation WHERE ContactId = :usr.contactId];
        for(AccountContactRelation acr:acrlst){
            accidlst.add(acr.AccountId);
        }

        if(accidlst.size() > 0){
            return JSON.serialize([select SUM(Total_Investment__c) Investments,RecordTypeId,RecordType.Name,sum(Total_Personal_Investments__c) NumberOfInvestments  from Account WHERE Id=:accIdLst group by RecordTypeId ,RecordType.Name]);

        }else{
            return JSON.serialize([select SUM(Total_Investment__c) Investments,RecordTypeId,RecordType.Name,sum(Total_Personal_Investments__c) NumberOfInvestments  from Account group by RecordTypeId ,RecordType.Name]);
        }
    }
    

    
    @AuraEnabled
	public static List<User> getCurrentUser(){
	return  [SELECT Id, Name,Contact.ID_Checked__c , AccountId FROM User WHERE Id =: Userinfo.getUserId()];
   }
    
    @AuraEnabled
    public static Integer getInvestmentFromInvestmentObject(){
        return [SELECT COUNT() FROM  Investment__c WHERE Stage__c = 'Receipt Issued' OR Stage__c = 'Application Received' OR Stage__c = 'Closed Won'];        
    }
    
}