common/force-app/main/default/objects/Account/fields/Investor_Updates_OptIn__c.field-meta.xml
<CustomField>
    <fullName>Investor_Updates_OptIn__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to hold optin data for preference category Investor Updates on the preference centre page</description>
    <label>Investor_Updates_OptIn</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Account/fields/Marketing_Updates_About_Product_OptIn__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Updates_About_Product_OptIn__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to hold optin data for preference category Marketing Updates about products on the preference centre page</description>
    <label>Marketing_Updates_About_Product_OptIn</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Marketing_Preference__c/Marketing_Preference__c.object-meta.xml
<CustomObject>
    <label>Marketing Preference</label>
    <nameField>
        <displayFormat>MP-{000000}</displayFormat>
        <label>Marketing Preference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Marketing_Preference__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Marketing Preferences</relationshipLabel>
    <relationshipName>Marketing_Preferences</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Marketing_Preference__c/fields/Investor_Updates_OptIn__c.field-meta.xml
<CustomField>
    <fullName>Investor_Updates_OptIn__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Investor_Updates_OptIn</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Marketing_Preference__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Marketing Preferences</relationshipLabel>
    <relationshipName>Marketing_Preferences</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Marketing_Preference__c/fields/Marketing_Updates_About_Product_OptIn__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Updates_About_Product_OptIn__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Marketing_Updates_About_Product_OptIn</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Marketing_Preference__c/fields/Marketing_Updates_About_Product_Optout__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Updates_About_Product_Optout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Marketing_Updates_About_Product_Optout</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Marketing_Preference__c/fields/Regular_Marketing_Communications_Optin_c__c.field-meta.xml
<CustomField>
    <fullName>Regular_Marketing_Communications_Optin_c__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Regular_Marketing_Communications_Optin</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Marketing_Preference__c/fields/Regular_Marketing_Communications_Optout__c.field-meta.xml
<CustomField>
    <fullName>Regular_Marketing_Communications_Optout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Regular_Marketing_Communications_Optout</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/classes/MarketingPrerenceTriggerHandler.cls
public class MarketingPrerenceTriggerHandler {
    public static Boolean performSyncFromMarketingPreference = true;
    public static void afterinsert(){
        if(performSyncFromMarketingPreference){
            syncMarketPreferences();
        }        
    }
    public static void afterupdate(){
        system.debug(performSyncFromMarketingPreference);
        if(performSyncFromMarketingPreference){
            syncMarketPreferences();
        }
    }
    public static void syncMarketPreferences(){
        List<Id> accIdlst = new List<Id>();
        List<Id> leadIdlst = new List<Id>();
        for(Marketing_Preference__c mp : (List<Marketing_Preference__c>) Trigger.new){
            if(string.isNotEmpty(mp.Account__c))accIdlst.add(mp.Account__c);
            if(string.isNotEmpty(mp.Lead__c))leadIdlst.add(mp.Lead__c);
        }
        Map<Id,Account> accMap = new Map<Id,Account>([SELECT Id,Investor_Updates_OptIn__c,PersonHasOptedOutOfEmail,Email_Opt_In__pc FROM Account WHERE Id IN :accIdlst]);
        Map<Id,Lead> leadMap = new Map<Id,Lead>([SELECT Id,Email_Opt_In__c,HasOptedOutOfEmail FROM Lead WHERE Id IN :leadIdlst]);
        List<Account> accLst = new List<Account>();
        List<Lead> leadLst = new List<Lead>();
        for(Marketing_Preference__c mp : (List<Marketing_Preference__c>) Trigger.new){
            if(string.isNotEmpty(mp.Account__c) && accMap.containsKey(mp.Account__c)){
                Account acc = accMap.get(mp.Account__c);
                if(acc.Investor_Updates_OptIn__c <> mp.Investor_Updates_OptIn__c || acc.PersonHasOptedOutOfEmail <> mp.Regular_Marketing_Communications_Optout__c || acc.Email_Opt_In__pc <> mp.Regular_Marketing_Communications_Optin_c__c){
                    acc.Investor_Updates_OptIn__c = mp.Investor_Updates_OptIn__c;
                    acc.PersonHasOptedOutOfEmail = mp.Regular_Marketing_Communications_Optout__c;
                    acc.Email_Opt_In__pc = mp.Regular_Marketing_Communications_Optin_c__c;
                    accLst.add(acc);
                }
            }
            if(string.isNotEmpty(mp.Lead__c) && leadMap.containsKey(mp.Lead__c)){
                Lead ld = leadMap.get(mp.Lead__c);
                if(ld.Email_Opt_In__c <> mp.Marketing_Updates_About_Product_OptIn__c || ld.HasOptedOutOfEmail <> mp.Marketing_Updates_About_Product_Optout__c ){
                    ld.Email_Opt_In__c = mp.Marketing_Updates_About_Product_OptIn__c;
                    ld.HasOptedOutOfEmail = mp.Marketing_Updates_About_Product_Optout__c;
                    leadLst.add(ld);
                }
            }
        }
        update accLst;
        update leadLst;
    }
}