common/force-app/main/default/objects/Account/fields/Investor_Updates_OptIn__c.field-meta.xml
<CustomField>
    <fullName>Investor_Updates_OptIn__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to hold optin data for preference category Investor Updates on the preference centre page</description>
    <label>Investor_Updates_OptIn</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Marketing_Preference__c/Marketing_Preference__c.object-meta.xml
<CustomObject>
    <label>Marketing Preference</label>
    <nameField>
        <displayFormat>MP-{000000}</displayFormat>
        <label>Marketing Preference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Marketing_Preference__c/fields/Investor_Updates_OptIn__c.field-meta.xml
<CustomField>
    <fullName>Investor_Updates_OptIn__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Investor_Updates_OptIn</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/classes/MarketingPrerenceTriggerHandlerTest.cls
@isTest
public class MarketingPrerenceTriggerHandlerTest {
    @isTest
    static void testmethod1(){
        Account acc = new Account();
        acc.lastname = 'Test1lname';
        acc.Phone = '6786789876';
        acc.RecordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('VC Person Account').getRecordTypeId();
        insert acc;

        MarketingPrerenceTriggerHandler.performSyncFromMarketingPreference = true;
        Marketing_Preference__c mp = [SELECT Id FROM Marketing_Preference__c];
        mp.Investor_Updates_OptIn__c = false;
        update mp;
        MarketingPrerenceTriggerHandler.performSyncFromMarketingPreference = true;
        mp.Investor_Updates_OptIn__c = true;
        update mp;
    }
}