common/force-app/main/default/objects/Account/fields/Related_Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Related Person Account)</relationshipLabel>
    <relationshipName>Accounts6</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/EOI__c.object-meta.xml
<CustomObject>
    <description>This object will be used by Founders, this was part of the MVP project.</description>
    <label>EOI</label>
    <nameField>
        <label>EOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOI&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/EOI__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>This will link to the Ventures Company Account that is related to the EOI</description>
    <inlineHelpText>This field links to the Ventures Company Account that is related to this EOI</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EOI&apos;s</relationshipLabel>
    <relationshipName>EOI_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Internal_Owner__c.field-meta.xml
<CustomField>
    <fullName>Internal_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Internal Owner in charge of the EOI and the Account</description>
    <inlineHelpText>Internal Owner in charge of the EOI and the Account</inlineHelpText>
    <label>Internal Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EOI_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Related_Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EOI&apos;s (Related Person Account)</relationshipLabel>
    <relationshipName>EOI_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/Raise__c.object-meta.xml
<CustomObject>
    <description>The raise object accountable for keeping track of a Founder&apos;s raise process.</description>
    <label>Raise</label>
    <nameField>
        <label>Raise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Raise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Raise__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field represents an account lookup relationship.</description>
    <inlineHelpText>Select an account to associate with this record.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Raise</relationshipLabel>
    <relationshipName>Raise</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field represents a master-detail relationship with the Company object.</description>
    <inlineHelpText>Select the company to which this record belongs.</inlineHelpText>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Raise (Company)</relationshipLabel>
    <relationshipName>Company</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Content_approved__c.field-meta.xml
<CustomField>
    <fullName>Content_approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox indicates whether the content has been approved.</description>
    <inlineHelpText>Check this box if the content has been reviewed and approved.
A task to the record owner to instruct the Funds Management Team to send the Establishment Fee to the founder will also be created when this field is checked.</inlineHelpText>
    <label>Content approved</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Course_unlocked__c.field-meta.xml
<CustomField>
    <fullName>Course_unlocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox indicates whether the course has been unlocked for the user.</description>
    <inlineHelpText>Check this box if the user has unlocked access to the course.</inlineHelpText>
    <label>Course unlocked</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/EOI__c.field-meta.xml
<CustomField>
    <fullName>EOI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field represents a lookup relationship with the EOI object.</description>
    <inlineHelpText>Select an Expression of Interest (EOI) associated with this record.</inlineHelpText>
    <label>EOI</label>
    <referenceTo>EOI__c</referenceTo>
    <relationshipLabel>Raise</relationshipLabel>
    <relationshipName>Raise</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Company_one_liner__c.field-meta.xml
<CustomField>
    <fullName>Form_Company_one_liner__c</fullName>
    <description>This field contains a brief one-liner description of the company.</description>
    <inlineHelpText>Provide a concise, one-sentence description of your company.</inlineHelpText>
    <label>Company one liner</label>
    <type>TextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Differentiation__c.field-meta.xml
<CustomField>
    <fullName>Form_Differentiation__c</fullName>
    <description>This field highlights the differentiation points of the company.</description>
    <inlineHelpText>Highlight what sets your company apart from competitors.</inlineHelpText>
    <label>Differentiation</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Growth_plan__c.field-meta.xml
<CustomField>
    <fullName>Form_Growth_plan__c</fullName>
    <description>This field outlines the company&apos;s growth plan and strategies for future expansion.</description>
    <inlineHelpText>Describe your company&apos;s growth plan and strategies for achieving future expansion.</inlineHelpText>
    <label>Growth plan</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Intellectual_Property__c.field-meta.xml
<CustomField>
    <fullName>Form_Intellectual_Property__c</fullName>
    <description>This field provides details about the company&apos;s intellectual property.</description>
    <inlineHelpText>Include information about patents, trademarks, copyrights, or any other intellectual property your company holds.</inlineHelpText>
    <label>Intellectual Property</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Offer_close_date__c.field-meta.xml
<CustomField>
    <fullName>Form_Offer_close_date__c</fullName>
    <description>This field specifies the closing date for the current offer.</description>
    <inlineHelpText>Provide the closing date for the current offer.</inlineHelpText>
    <label>Offer close date</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Problem_or_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Form_Problem_or_Opportunity__c</fullName>
    <description>This field identifies the problem or opportunity that the company is addressing.</description>
    <inlineHelpText>Describe the problem or opportunity your company is addressing.</inlineHelpText>
    <label>Problem or Opportunity</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Progress__c.field-meta.xml
<CustomField>
    <fullName>Form_Progress__c</fullName>
    <description>This field provides an update on the company&apos;s progress.</description>
    <inlineHelpText>Provide an update on your company&apos;s progress.</inlineHelpText>
    <label>Progress</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Solution__c.field-meta.xml
<CustomField>
    <fullName>Form_Solution__c</fullName>
    <description>This field describes the solution the company provides.</description>
    <inlineHelpText>Detail the solution your company offers to address the identified problem or opportunity.</inlineHelpText>
    <label>Solution</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Total_addressable_market__c.field-meta.xml
<CustomField>
    <fullName>Form_Total_addressable_market__c</fullName>
    <description>This field indicates the total addressable market for the company’s product or service.</description>
    <inlineHelpText>Specify the total addressable market for your product or service.</inlineHelpText>
    <label>Total addressable market</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Valuation__c.field-meta.xml
<CustomField>
    <fullName>Form_Valuation__c</fullName>
    <description>This field indicates the company’s valuation.</description>
    <inlineHelpText>Specify the current valuation of your company.</inlineHelpText>
    <label>Valuation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Learning_completed__c.field-meta.xml
<CustomField>
    <fullName>Learning_completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates whether the learning has been completed.</description>
    <inlineHelpText>Check this box if the learning has been completed.</inlineHelpText>
    <label>Learning completed</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field specifies the owner of the record.</description>
    <inlineHelpText>Select the owner of this record.</inlineHelpText>
    <label>Internal Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Raise1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Payment_received__c.field-meta.xml
<CustomField>
    <fullName>Payment_received__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates whether the payment has been received.</description>
    <inlineHelpText>Check this box if the payment has been received.</inlineHelpText>
    <label>Payment received</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field indicates the status of the record.</description>
    <inlineHelpText>Select the current status of this record.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for review</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Waiting for payment</fullName>
            </value>
            <value>
                <fullName>Waiting to complete learning course</fullName>
            </value>
            <value>
                <fullName>Pending final approval</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live on VC Website</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/classes/SecurityControllerTest.cls
@isTest
public with sharing class SecurityControllerTest {

    @TestSetup
    static void setupTestData() {
        Id recordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('VC Person Account').getRecordTypeId();

        // Create a test Account
        Account testAccount = new Account(
            FirstName = 'TestPersonAccountFirst',
            LastName = 'Account',
            RecordTypeId = recordTypeId
        );
        insert testAccount;

        Contact getContact = [SELECT Id, Name FROM Contact WHERE FirstName = 'TestPersonAccountFirst' LIMIT 1];

        // Create a test User associated with the Account
        Profile p = [SELECT Id FROM Profile WHERE Name = 'VC Customer Community Login' LIMIT 1];

        User testUser = new User(
            Alias = 'testuser',
            Email = 'testuserTEST@example.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'testuserTEST@example.com',
            ContactId = getContact.Id
        );
        insert testUser;

        Account businessAccount = new Account(Name='Test Business', Related_Person_Account__c=testAccount.Id);
        insert businessAccount;
        
        Id ownerId = 'a3XXX000000cXXXAAI';

        List<User> benQuery = [SELECT Id FROM User WHERE Name='Ben Crow' LIMIT 1];
        if(benQuery.size() > 0){
            ownerId = benQuery[0].Id;
        }

        EOI__c testEOI = new EOI__c(Name = 'Test EOI', Account__c = businessAccount.Id, Internal_Owner__c = ownerId, Related_Person_Account__c = testAccount.Id);
        insert testEOI;

        // Create a test Raise__c record associated with the Account
        Raise__c testRaise = new Raise__c(
            Name = 'Test Raise',
            Account__c = testAccount.Id,
            Owner__c = ownerId,
            Company__c = businessAccount.Id,
            EOI__c = testEOI.Id,
            Status__c = 'In Progress',
            Payment_received__c = true,
            Content_approved__c = true,
            Course_unlocked__c = false,
            Learning_completed__c = false,
            Form_Problem_or_Opportunity__c = 'Test Problem',
            Form_Solution__c = 'Test Solution',
            Form_Differentiation__c = 'Test Differentiation',
            Form_Intellectual_Property__c = 'Test Intellectual Property',
            Form_Total_addressable_market__c = 'Test Market',
            Form_Progress__c = 'Test Progress',
            Form_Growth_plan__c = 'Test Growth Plan',
            Form_Valuation__c = 1000000,
            Form_Company_one_liner__c = 'Test Company Overview',
            Form_Offer_close_date__c = Date.today()
        );
        insert testRaise;
    }

    @isTest
    static void testGetLoggedInAccountId() {
        // Get the test User
        User testUser = [SELECT Id, AccountId FROM User WHERE UserName = 'testuserTEST@example.com' LIMIT 1];

        // Run as the test User
        System.runAs(testUser) {
            // Call the method to test
            String accountId = SecurityController.getLoggedInAccountId();

            // Assert that the returned AccountId matches the test User's AccountId
            System.assertEquals(testUser.AccountId, accountId, 'The returned AccountId should match the test User\'s AccountId');
        }
    }

    @isTest
    static void testCheckRaiseAccess_ValidAccess() {
        // Get the test User and Raise__c record
        User testUser = [SELECT Id, AccountId FROM User WHERE UserName = 'testuserTEST@example.com' LIMIT 1];
        Raise__c testRaise = [SELECT Id FROM Raise__c WHERE Name = 'Test Raise' LIMIT 1];

        // Run as the test User
        System.runAs(testUser) {
            // Call the method to test
            Boolean hasAccess = SecurityController.checkRaiseAccess(testRaise.Id);

            // Assert that the user has access to the Raise__c record
            System.assertEquals(true, hasAccess, 'The user should have access to the Raise__c record');
        }
    }

    @isTest
    static void testCheckRaiseAccess_Exception() {
        // Get the test User
        User testUser = [SELECT Id, AccountId FROM User WHERE UserName = 'testuserTEST@example.com' LIMIT 1];

        // Run as the test User
        System.runAs(testUser) {
            try {
                // Call the method with an invalid Raise Id to trigger an exception
                SecurityController.checkRaiseAccess('0058s00000DPo1nXXX');
                System.assert(false, 'Expected an exception to be thrown');
            } catch (AuraHandledException e) {
                // Assert that the exception was thrown as expected
                System.assert(true, 'An AuraHandledException was thrown as expected');
            }
        }
    }

    @isTest
    static void testCheckEOIAccess_ValidAccess() {
        // Get the test User and Raise__c record
        User testUser = [SELECT Id, AccountId FROM User WHERE UserName = 'testuserTEST@example.com' LIMIT 1];
        EOI__c testEOI = [SELECT Id FROM EOI__c WHERE Name = 'Test EOI' LIMIT 1];

        // Run as the test User
        System.runAs(testUser) {
            // Call the method to test
            Boolean hasAccess = SecurityController.checkEoiAccess(testEOI.Id);

            // Assert that the user has access to the Raise__c record
            System.assertEquals(true, hasAccess, 'The user should have access to the EOI record');
        }
    }

    @isTest
    static void testCheckEOIAccess_Exception() {
        // Get the test User
        User testUser = [SELECT Id, AccountId FROM User WHERE UserName = 'testuserTEST@example.com' LIMIT 1];

        // Run as the test User
        System.runAs(testUser) {
            try {
                // Call the method with an invalid Raise Id to trigger an exception
                SecurityController.checkEoiAccess('0058s00000DPo1nXXX');
                System.assert(false, 'Expected an exception to be thrown');
            } catch (AuraHandledException e) {
                // Assert that the exception was thrown as expected
                System.assert(true, 'An AuraHandledException was thrown as expected');
            }
        }
    }
}