common/force-app/main/default/objects/Account/fields/Related_Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Related Person Account)</relationshipLabel>
    <relationshipName>Accounts6</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/EOI__c.object-meta.xml
<CustomObject>
    <description>This object will be used by Founders, this was part of the MVP project.</description>
    <label>EOI</label>
    <nameField>
        <label>EOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOI&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/EOI__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>This will link to the Ventures Company Account that is related to the EOI</description>
    <inlineHelpText>This field links to the Ventures Company Account that is related to this EOI</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EOI&apos;s</relationshipLabel>
    <relationshipName>EOI_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/EOI_Status__c.field-meta.xml
<CustomField>
    <fullName>EOI_Status__c</fullName>
    <description>This is the Status (Progress) for the EOI record.</description>
    <label>EOI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Published</fullName>
                <default>true</default>
                <label>Not Published</label>
            </value>
            <value>
                <fullName>Submitted to be Published</fullName>
            </value>
            <value>
                <fullName>Publishing</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/EOI_Title__c.field-meta.xml
<CustomField>
    <fullName>EOI_Title__c</fullName>
    <description>EOI Title</description>
    <label>EOI Title</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Internal_Owner__c.field-meta.xml
<CustomField>
    <fullName>Internal_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Internal Owner in charge of the EOI and the Account</description>
    <inlineHelpText>Internal Owner in charge of the EOI and the Account</inlineHelpText>
    <label>Internal Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EOI_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/One_liner_about_business__c.field-meta.xml
<CustomField>
    <fullName>One_liner_about_business__c</fullName>
    <label>One liner about business</label>
    <type>TextArea</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Publish_on_Community_Site__c.field-meta.xml
<CustomField>
    <fullName>Publish_on_Community_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox will render the card to show it on the VC website</description>
    <label>Publish on Community Site</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Published_EOI_URL__c.field-meta.xml
<CustomField>
    <fullName>Published_EOI_URL__c</fullName>
    <label>Published EOI URL</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Related_Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EOI&apos;s (Related Person Account)</relationshipLabel>
    <relationshipName>EOI_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/SXSW_Finalist__c.field-meta.xml
<CustomField>
    <fullName>SXSW_Finalist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this if the EOI is an SXSW Finalist. This will enable it to be displayed on the SXSW Finalist EOI landing page</description>
    <inlineHelpText>Check this if the EOI is an SXSW Finalist. This will enable it to be displayed on the SXSW Finalist EOI landing page</inlineHelpText>
    <label>SXSW Finalist</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/URL_Files_Img__c.field-meta.xml
<CustomField>
    <fullName>URL_Files_Img__c</fullName>
    <description>This field stores a JSON file after a user click save on edit EOI. The Apex controller updating this is ContentDownloadURL</description>
    <inlineHelpText>This field stores a JSON file after a user click save on edit EOI. The Apex controller updating this is ContentDownloadURL</inlineHelpText>
    <label>URL_Files_Img</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>VC Person Account</label>
</RecordType>

common/force-app/main/default/classes/EOI_Service_Test.cls
@isTest
private class EOI_Service_Test {
    // test class for EOI service
    @TestSetup
    static void setup() {
        User owner = [SELECT Id FROM USER WHERE Name = 'The VentureCrowd Team'];
        Id recordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('VC Person Account').getRecordTypeId();

        // Create a test Business Account and related Person Account
        Account personAccount = new Account(
            FirstName = 'TestPersonAccountFirst',
            LastName = 'TestPersonAccountLast',
            PersonEmail = 'test@user.com',
            RecordTypeId = recordTypeId,
            // Name = 'Test Account',
            OwnerId = owner.Id
        );
        insert personAccount;

        Account businessAccount = new Account(Name = 'Test Business', Related_Person_Account__c = personAccount.Id);
        insert businessAccount;

        Profile testProfile = [SELECT Id, Name FROM Profile WHERE Name = 'VC Investor Community Plus Login' LIMIT 1];
    
        Contact getContact = [SELECT Id, Name FROM Contact WHERE FirstName = 'TestPersonAccountFirst'];

        User testUser = new User(
        FirstName = 'TestingUserN3',
        Username = 'testUser_n3@test.com',
        LastName = 'TestAd11s',
        // ContactId = testContact.Id,
        Email = 'testUser_n3@test.com',
        Alias = 't3user',
        TimeZoneSidKey = 'America/Los_Angeles',
        LocaleSidKey = 'en_US',
        EmailEncodingKey = 'UTF-8',
        LanguageLocaleKey = 'en_US',
        ProfileId = testProfile.Id,
        ContactId = getContact.Id
        );
        insert testUser;

         // Create a test EOI
        EOI__c eoi = new EOI__c(
            Name = 'Test EOI',
            Account__c = businessAccount.Id,
            EOI_Status__c = 'Published',
            Publish_on_Community_Site__c = true,
            URL_Files_Img__c = 'http://example.com/image.png',
            Published_EOI_URL__c = 'http://example.com/eoi',
            One_liner_about_business__c = 'Innovative business idea',
            SXSW_Finalist__c = true,
            EOI_Title__c = 'Exciting EOI Title',
            Internal_Owner__c=owner.Id
        );
        insert eoi;

        EOI__c eoi2 = new EOI__c(
            Name = 'EOI new',
            Account__c = businessAccount.Id,
            EOI_Status__c = 'Published',
            Publish_on_Community_Site__c = true,
            URL_Files_Img__c = 'http://example.com/image.png',
            Published_EOI_URL__c = 'http://example.com/eoi',
            One_liner_about_business__c = 'Innovative business idea',
            SXSW_Finalist__c = true,
            EOI_Title__c = 'Exciting EOI Title',
            Internal_Owner__c=owner.Id
        );
        insert eoi2;
    }

    @isTest
    static void testGetEoiOfferInformation_Success() {
        // Instantiate the service class
        EOI_Service service = new EOI_Service();

        Test.startTest();
        // Call the method to retrieve and process EOI information
        String jsonResult = service.getEoiOfferInformation();
        Test.stopTest();

        // Deserialize the JSON result to a list of EOI_Service.EoiOfferData
        List<EOI_Service.EoiOfferData> eoiDataList = (List<EOI_Service.EoiOfferData>) JSON.deserialize(jsonResult, List<EOI_Service.EoiOfferData>.class);

        // Validate the results
        System.assertNotEquals(null, eoiDataList, 'EOI data list should not be null');
        System.assertEquals(2, eoiDataList.size(), 'There should be one EOI record returned');
        System.assertEquals('Exciting EOI Title', eoiDataList[0].tileHeading, 'The EOI title should match the expected value');
        System.assertEquals('http://example.com/eoi', eoiDataList[0].dealPageLink, 'The EOI deal page link should match the expected value');
    }

    @isTest
    static void testGetSXSWEoiOfferInformation_Success() {
        // Instantiate the service class
        EOI_Service service = new EOI_Service();

        Test.startTest();
        // Call the method to retrieve and process EOI information
        String jsonResult = service.getSXSWEoiOfferInformation('');
        Test.stopTest();

        // Deserialize the JSON result to a list of EOI_Service.EoiOfferData
        List<EOI_Service.EoiOfferData> eoiDataList = (List<EOI_Service.EoiOfferData>) JSON.deserialize(jsonResult, List<EOI_Service.EoiOfferData>.class);

        // Validate the results
        System.assertNotEquals(null, eoiDataList, 'EOI data list should not be null');
        System.assertEquals(2, eoiDataList.size(), 'There should be one EOI record returned');
        System.assertEquals('Exciting EOI Title', eoiDataList[0].tileHeading, 'The EOI title should match the expected value');
        System.assertEquals('http://example.com/eoi', eoiDataList[0].dealPageLink, 'The EOI deal page link should match the expected value');
    }

    @isTest
    static void testGetSXSWEoiOfferInformation_SuccessSearch() {
        // Instantiate the service class
        EOI_Service service = new EOI_Service();

        Test.startTest();
        // Call the method to retrieve and process EOI information
        String jsonResult = service.getSXSWEoiOfferInformation('Test');
        Test.stopTest();

        // Deserialize the JSON result to a list of EOI_Service.EoiOfferData
        List<EOI_Service.EoiOfferData> eoiDataList = (List<EOI_Service.EoiOfferData>) JSON.deserialize(jsonResult, List<EOI_Service.EoiOfferData>.class);

        // Validate the results
        System.assertNotEquals(null, eoiDataList, 'EOI data list should not be null');
        System.assertEquals(1, eoiDataList.size(), 'There should be one EOI record returned');
        System.assertEquals('Exciting EOI Title', eoiDataList[0].tileHeading, 'The EOI title should match the expected value');
        System.assertEquals('http://example.com/eoi', eoiDataList[0].dealPageLink, 'The EOI deal page link should match the expected value');
    }


    @isTest
    static void testGetEoiOfferInformation_NoEOIs() {
        // Delete all EOIs to simulate the scenario where no records exist
        delete [SELECT Id FROM EOI__c];

        // Instantiate the service class
        EOI_Service service = new EOI_Service();

        Test.startTest();
        try {
            // Call the method to retrieve and process EOI information
            service.getEoiOfferInformation();
            System.assert(false, 'An exception should have been thrown because no EOIs are available');
        } catch (Exception e) {
            // Validate that the exception is thrown with the correct message
            System.assertNotEquals(null, e.getMessage(), 'Expected exception message not received');
        }
        Test.stopTest();
    }

    @isTest
    static void testGetSXSWEoiOfferInformation_NoEOIs() {
        // Delete all EOIs to simulate the scenario where no records exist
        delete [SELECT Id FROM EOI__c];

        // Instantiate the service class
        EOI_Service service = new EOI_Service();

        Test.startTest();
        try {
            // Call the method to retrieve and process EOI information
            service.getSXSWEoiOfferInformation('');
            System.assert(false, 'An exception should have been thrown because no EOIs are available');
        } catch (Exception e) {
            // Validate that the exception is thrown with the correct message
            System.assertNotEquals(null, e.getMessage(), 'Expected exception message not received');
        }
        Test.stopTest();
    }
}