common/force-app/main/default/objects/Account/fields/Related_Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Related Person Account)</relationshipLabel>
    <relationshipName>Accounts6</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/EOI__c.object-meta.xml
<CustomObject>
    <description>This object will be used by Founders, this was part of the MVP project.</description>
    <label>EOI</label>
    <nameField>
        <label>EOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOI&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/EOI__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>This will link to the Ventures Company Account that is related to the EOI</description>
    <inlineHelpText>This field links to the Ventures Company Account that is related to this EOI</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EOI&apos;s</relationshipLabel>
    <relationshipName>EOI_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/EOI_Status__c.field-meta.xml
<CustomField>
    <fullName>EOI_Status__c</fullName>
    <description>This is the Status (Progress) for the EOI record.</description>
    <label>EOI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Published</fullName>
                <default>true</default>
                <label>Not Published</label>
            </value>
            <value>
                <fullName>Submitted to be Published</fullName>
            </value>
            <value>
                <fullName>Publishing</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/EOI_Title__c.field-meta.xml
<CustomField>
    <fullName>EOI_Title__c</fullName>
    <description>EOI Title</description>
    <label>EOI Title</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Internal_Owner__c.field-meta.xml
<CustomField>
    <fullName>Internal_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Internal Owner in charge of the EOI and the Account</description>
    <inlineHelpText>Internal Owner in charge of the EOI and the Account</inlineHelpText>
    <label>Internal Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EOI_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/One_liner_about_business__c.field-meta.xml
<CustomField>
    <fullName>One_liner_about_business__c</fullName>
    <label>One liner about business</label>
    <type>TextArea</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Publish_on_Community_Site__c.field-meta.xml
<CustomField>
    <fullName>Publish_on_Community_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox will render the card to show it on the VC website</description>
    <label>Publish on Community Site</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Published_EOI_URL__c.field-meta.xml
<CustomField>
    <fullName>Published_EOI_URL__c</fullName>
    <label>Published EOI URL</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Related_Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EOI&apos;s (Related Person Account)</relationshipLabel>
    <relationshipName>EOI_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/SXSW_Finalist__c.field-meta.xml
<CustomField>
    <fullName>SXSW_Finalist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this if the EOI is an SXSW Finalist. This will enable it to be displayed on the SXSW Finalist EOI landing page</description>
    <inlineHelpText>Check this if the EOI is an SXSW Finalist. This will enable it to be displayed on the SXSW Finalist EOI landing page</inlineHelpText>
    <label>SXSW Finalist</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/URL_Files_Img__c.field-meta.xml
<CustomField>
    <fullName>URL_Files_Img__c</fullName>
    <description>This field stores a JSON file after a user click save on edit EOI. The Apex controller updating this is ContentDownloadURL</description>
    <inlineHelpText>This field stores a JSON file after a user click save on edit EOI. The Apex controller updating this is ContentDownloadURL</inlineHelpText>
    <label>URL_Files_Img</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>VC Person Account</label>
</RecordType>

common/force-app/main/default/objects/Raise__c/Raise__c.object-meta.xml
<CustomObject>
    <description>The raise object accountable for keeping track of a Founder&apos;s raise process.</description>
    <label>Raise</label>
    <nameField>
        <label>Raise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Raise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Raise__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field represents an account lookup relationship.</description>
    <inlineHelpText>Select an account to associate with this record.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Raise</relationshipLabel>
    <relationshipName>Raise</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field represents a master-detail relationship with the Company object.</description>
    <inlineHelpText>Select the company to which this record belongs.</inlineHelpText>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Raise (Company)</relationshipLabel>
    <relationshipName>Company</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/EOI__c.field-meta.xml
<CustomField>
    <fullName>EOI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field represents a lookup relationship with the EOI object.</description>
    <inlineHelpText>Select an Expression of Interest (EOI) associated with this record.</inlineHelpText>
    <label>EOI</label>
    <referenceTo>EOI__c</referenceTo>
    <relationshipLabel>Raise</relationshipLabel>
    <relationshipName>Raise</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Form_Company_Name__c</fullName>
    <description>This is a brand name or the name customers know the company by.</description>
    <inlineHelpText>This is a brand name or the name customers know the company by.</inlineHelpText>
    <label>Company&apos;s Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field specifies the owner of the record.</description>
    <inlineHelpText>Select the owner of this record.</inlineHelpText>
    <label>Internal Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Raise1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Publish_on_Community_Site__c.field-meta.xml
<CustomField>
    <fullName>Publish_on_Community_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will be automatically checked once the Tile Banner field is populated and the Status is set to &quot;Live in VC Website&quot;</description>
    <inlineHelpText>This field will be automatically checked once the Tile Banner field is populated and the Status is set to &quot;Live in VC Website&quot;</inlineHelpText>
    <label>Publish on Community Site</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field indicates the status of the record.</description>
    <inlineHelpText>Select the current status of this record.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for review</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Waiting for payment</fullName>
            </value>
            <value>
                <fullName>Waiting to complete learning course</fullName>
            </value>
            <value>
                <fullName>Pending final approval</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live on VC Website</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/classes/EOI_Controller_Test.cls
@isTest
private class EOI_Controller_Test {

    @TestSetup
    static void setup() {
        User owner = [SELECT Id FROM USER WHERE Name = 'The VentureCrowd Team'];
        Id recordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('VC Person Account').getRecordTypeId();

        // Create a test Business Account and related Person Account
        Account personAccount = new Account(
            FirstName = 'TestPersonAccountFirst',
            LastName = 'TestPersonAccountLast',
            PersonEmail = 'test@user.com',
            RecordTypeId = recordTypeId,
            // Name = 'Test Account',
            OwnerId = owner.Id
        );
        insert personAccount;

        Account businessAccount = new Account(Name = 'Test Business', Related_Person_Account__c = personAccount.Id);
        insert businessAccount;

        Profile testProfile = [SELECT Id, Name FROM Profile WHERE Name = 'VC Investor Community Plus Login' LIMIT 1];
    
        Contact getContact = [SELECT Id, Name FROM Contact WHERE FirstName = 'TestPersonAccountFirst'];

        User testUser = new User(
        FirstName = 'TestingUserN2',
        Username = 'testUser_n2@test.com',
        LastName = 'TestAds',
        // ContactId = testContact.Id,
        Email = 'testUser_n2@test.com',
        Alias = 'tuser',
        TimeZoneSidKey = 'America/Los_Angeles',
        LocaleSidKey = 'en_US',
        EmailEncodingKey = 'UTF-8',
        LanguageLocaleKey = 'en_US',
        ProfileId = testProfile.Id,
        ContactId = getContact.Id
        );
        insert testUser;

         // Create a test EOI
        EOI__c eoi = new EOI__c(
            Name = 'Test EOI',
            Account__c = businessAccount.Id,
            EOI_Status__c = 'Published',
            Publish_on_Community_Site__c = true,
            URL_Files_Img__c = 'http://example.com/image.png',
            Published_EOI_URL__c = 'http://example.com/eoi',
            One_liner_about_business__c = 'Innovative business idea',
            SXSW_Finalist__c = true,
            EOI_Title__c = 'Exciting EOI Title',
            Internal_Owner__c=owner.Id
        );
        insert eoi;

        EOI__c eoi2 = new EOI__c(
            Name = 'EOI new',
            Account__c = businessAccount.Id,
            EOI_Status__c = 'Published',
            Publish_on_Community_Site__c = true,
            URL_Files_Img__c = 'http://example.com/image.png',
            Published_EOI_URL__c = 'http://example.com/eoi',
            One_liner_about_business__c = 'Innovative business idea',
            SXSW_Finalist__c = true,
            EOI_Title__c = 'Exciting EOI Title',
            Internal_Owner__c=owner.Id
        );
        insert eoi2;

         // Create a test Raise (unrelated to this test but provided in the setup)
        Raise__c testRaise = new Raise__c(
            Name = 'Existing Raise',
            Company__c = businessAccount.Id,
            EOI__c = eoi.Id,
            Account__c = personAccount.Id,
            Owner__c = owner.Id
        );
        insert testRaise;

         // Create a test Raise (unrelated to this test but provided in the setup)
        Raise__c testRaise2 = new Raise__c(
            Name = 'Existing Raise 2',
            Company__c = businessAccount.Id,
            EOI__c = eoi2.Id,
            Account__c = personAccount.Id,
            Form_Company_Name__c = 'TEST NAME',
            Owner__c = owner.Id,
            Status__c = 'Live'
        );
        insert testRaise2;
    }

    @isTest
    static void testGetEoiOfferInformation_Success() {
        // Call the controller method to get EOI offer information
        Test.startTest();
        String jsonResult = EOI_Controller.getEoiOfferInformation();
        Test.stopTest();

        // Deserialize the JSON result to a list of EOI_Service.EoiOfferData
        List<EOI_Service.EoiOfferData> eoiDataList = (List<EOI_Service.EoiOfferData>) JSON.deserialize(jsonResult, List<EOI_Service.EoiOfferData>.class);

        // Validate the results
        System.assertNotEquals(null, eoiDataList, 'EOI data list should not be null');
        System.assertEquals(1, eoiDataList.size(), 'There should be 2 EOI records returned');
        System.assertEquals('Exciting EOI Title', eoiDataList[0].tileHeading, 'The EOI title should match the expected value');
        System.assertEquals('http://example.com/eoi', eoiDataList[0].dealPageLink, 'The EOI deal page link should match the expected value');
    }

    @isTest
    static void testGetSXSWEoiOfferInformation_Success() {
        // Call the controller method to get EOI offer information
        Test.startTest();
        String jsonResult = EOI_Controller.getEoiSXSWOfferInformation('');
        Test.stopTest();

        // Deserialize the JSON result to a list of EOI_Service.EoiOfferData
        List<EOI_Service.EoiOfferData> eoiDataList = (List<EOI_Service.EoiOfferData>) JSON.deserialize(jsonResult, List<EOI_Service.EoiOfferData>.class);

        // Validate the results
        System.assertNotEquals(null, eoiDataList, 'EOI data list should not be null');
        System.assertEquals(1, eoiDataList.size(), 'There should be one EOI record returned');
        System.assertEquals('Exciting EOI Title', eoiDataList[0].tileHeading, 'The EOI title should match the expected value');
        System.assertEquals('http://example.com/eoi', eoiDataList[0].dealPageLink, 'The EOI deal page link should match the expected value');
    }

    @isTest
    static void testGetSXSWEoiOfferInformation_SuccessSearch() {
        // Call the controller method to get EOI offer information
        Test.startTest();
        String jsonResult = EOI_Controller.getEoiSXSWOfferInformation('Test');
        Test.stopTest();

        // Deserialize the JSON result to a list of EOI_Service.EoiOfferData
        List<EOI_Service.EoiOfferData> eoiDataList = (List<EOI_Service.EoiOfferData>) JSON.deserialize(jsonResult, List<EOI_Service.EoiOfferData>.class);

        // Validate the results
        System.assertNotEquals(null, eoiDataList, 'EOI data list should not be null');
        System.assertEquals(1, eoiDataList.size(), 'There should be one EOI record returned');
        System.assertEquals('Exciting EOI Title', eoiDataList[0].tileHeading, 'The EOI title should match the expected value');
        System.assertEquals('http://example.com/eoi', eoiDataList[0].dealPageLink, 'The EOI deal page link should match the expected value');
    }

    @isTest
    static void testGetLiveRaises() {
        EOI__c eoi = [SELECT Id, Name FROM EOI__c WHERE Name='EOI new'];
        // Call the controller method to get EOI offer information
        
        Test.startTest();
        
        Map<String,Object> raises = EOI_Controller.getLiveRaiseFromEOI(eoi.Id);


        Test.stopTest();

        System.assertNotEquals(null, raises, 'Raise data list should not be null');
    }

    @isTest
    static void testGetLiveRaisesNone() {
        EOI__c eoi = [SELECT Id, Name FROM EOI__c WHERE Name='Test EOI'];
        // Call the controller method to get EOI offer information
        Test.startTest();
        try {
            Map<String,Object> raises = EOI_Controller.getLiveRaiseFromEOI(eoi.Id);
            System.assert(false, 'An exception should have been thrown because no Raises are available');
        } catch (Exception e) {
            System.assertNotEquals(null, e.getMessage(), 'Expected exception message not received');
        }
        Test.stopTest();
    }

    @isTest
    static void testGetEoiOfferInformation_NoEOIs() {
        // Delete all EOIs to simulate the scenario where no records exist

        // Call the controller method to get EOI offer information
        Test.startTest();
        delete [SELECT Id FROM EOI__c];

        try {
            EOI_Controller.getEoiOfferInformation();
            System.assert(false, 'An exception should have been thrown because no EOIs are available');
        } catch (Exception e) {
            System.assertNotEquals(null, e.getMessage(), 'Expected exception message not received');
        }
        Test.stopTest();
    }

    @isTest
    static void testGetSXSWEoiOfferInformation_NoEOIs() {
        // Delete all EOIs to simulate the scenario where no records exist

        // Call the controller method to get EOI offer information
        Test.startTest();
        delete [SELECT Id FROM EOI__c];

        try {
            EOI_Controller.getEoiSXSWOfferInformation('');
            System.assert(false, 'An exception should have been thrown because no EOIs are available');
        } catch (Exception e) {
            System.assertNotEquals(null, e.getMessage(), 'Expected exception message not received');
        }
        Test.stopTest();
    }

    // Test case to check that the EOI is correctly returned when an ID is provided
    @isTest
    static void testGetEoiInformation_Success() {
        // Get the test EOI record's ID
        EOI__c testEoi = [SELECT Id FROM EOI__c WHERE Name = 'Test EOI' LIMIT 1];
        
        // Call the controller method to get EOI information
        Test.startTest();
        List<EOI__c> result = EOI_Controller.getEoiInformation(testEoi.Id);
        Test.stopTest();

        // Validate the results
        System.assertNotEquals(null, result, 'Result should not be null');
        System.assertEquals(1, result.size(), 'There should be one EOI record returned');
    }

    // Test case to check the behavior when an invalid or non-existing EOI ID is provided
    // @isTest
    // static void testGetEoiInformation_InvalidId() {
    //     Test.startTest();
    //     try {
    //         // Pass a non-existent EOI Id
    //         Id eoiID = '005000000000001';
    //         EOI_Controller.getEoiInformation(eoiID);
    //         System.assert(false, 'An exception should have been thrown for an invalid EOI ID');
    //     } catch (Exception e) {
    //         System.assert(true, 'Exception should have been thrown for wrong user ID');
    //     }
    //     Test.stopTest();
    // }

    @isTest
    static void testGetEOIbyID(){
        EOI__c testEOI = [SELECT Id, Name FROM EOI__c WHERE Name='Test EOI'];

        Test.startTest();
        EOI_Controller.getEOIByID(testEOI.Id);

        Test.stopTest();
    }

    @isTest
    static void testGetEOIbyIDInvalidEOIID(){
        Id testEOIID = 'a2vIo00000009HsIAI';

        Test.startTest();
        try{
            EOI_Controller.getEOIByID(testEOIID);
            System.assert(false, 'An exception should have been thrown because no EOIs are available');
        }catch(Exception e){
            System.assertNotEquals(null, e.getMessage(), 'Expected exception message not received');
        }
       

        Test.stopTest();
    }
}