common/force-app/main/default/objects/Account/fields/Related_Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Related Person Account)</relationshipLabel>
    <relationshipName>Accounts6</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/ContentVersion/fields/Form_field__c.field-meta.xml
<CustomField>
    <fullName>Form_field__c</fullName>
    <description>Tracks the form field that this document is part of</description>
    <label>Form field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Deal_Description__c.field-meta.xml
<CustomField>
    <fullName>Deal_Description__c</fullName>
    <label>Deal Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Deal_Page_Link__c.field-meta.xml
<CustomField>
    <fullName>Deal_Page_Link__c</fullName>
    <label>Deal Page Link</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Offer_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Offer_Close_Date__c</fullName>
    <inlineHelpText>The target date for capital raise to be complete</inlineHelpText>
    <label>Offer Close Date</label>
    <type>DateTime</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Portal_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Portal_Display_Name__c</fullName>
    <label>Portal Display Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Publish_on_Community_Site__c.field-meta.xml
<CustomField>
    <fullName>Publish_on_Community_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publish on Community Site</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Raise__c.field-meta.xml
<CustomField>
    <fullName>Raise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Raise</label>
    <referenceTo>Raise__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Expression Of Interest</fullName>
            </value>
            <value>
                <fullName>Sold Out</fullName>
            </value>
            <value>
                <fullName>Reserved for Display Home</fullName>
            </value>
            <value>
                <fullName>Reserved for Put and Call</fullName>
            </value>
            <value>
                <fullName>Reserved for builder house and land package</fullName>
            </value>
            <value>
                <fullName>Contract Executed</fullName>
                <isActive>false</isActive>
                <label>Contract Executed</label>
            </value>
            <value>
                <fullName>Contract Pending</fullName>
                <isActive>false</isActive>
                <label>Contract Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Tile_Banner__c.field-meta.xml
<CustomField>
    <fullName>Tile_Banner__c</fullName>
    <label>Tile Banner</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Tile_Heading__c.field-meta.xml
<CustomField>
    <fullName>Tile_Heading__c</fullName>
    <label>Tile Heading</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Tile_Offer_Type__c.field-meta.xml
<CustomField>
    <fullName>Tile_Offer_Type__c</fullName>
    <label>Tile Offer Type</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/Raise__c.object-meta.xml
<CustomObject>
    <description>The raise object accountable for keeping track of a Founder&apos;s raise process.</description>
    <label>Raise</label>
    <nameField>
        <label>Raise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Raise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Raise__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field represents an account lookup relationship.</description>
    <inlineHelpText>Select an account to associate with this record.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Raise</relationshipLabel>
    <relationshipName>Raise</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field represents a master-detail relationship with the Company object.</description>
    <inlineHelpText>Select the company to which this record belongs.</inlineHelpText>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Raise (Company)</relationshipLabel>
    <relationshipName>Company</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Company_one_liner__c.field-meta.xml
<CustomField>
    <fullName>Form_Company_one_liner__c</fullName>
    <description>This field contains a brief one-liner description of the company.</description>
    <inlineHelpText>Provide a concise, one-sentence description of your company.</inlineHelpText>
    <label>Company one liner</label>
    <type>TextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Differentiation__c.field-meta.xml
<CustomField>
    <fullName>Form_Differentiation__c</fullName>
    <description>This field highlights the differentiation points of the company.</description>
    <inlineHelpText>Highlight what sets your company apart from competitors.</inlineHelpText>
    <label>Differentiation</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Growth_plan__c.field-meta.xml
<CustomField>
    <fullName>Form_Growth_plan__c</fullName>
    <description>This field outlines the company&apos;s growth plan and strategies for future expansion.</description>
    <inlineHelpText>Describe your company&apos;s growth plan and strategies for achieving future expansion.</inlineHelpText>
    <label>Growth plan</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Intellectual_Property__c.field-meta.xml
<CustomField>
    <fullName>Form_Intellectual_Property__c</fullName>
    <description>This field provides details about the company&apos;s intellectual property.</description>
    <inlineHelpText>Include information about patents, trademarks, copyrights, or any other intellectual property your company holds.</inlineHelpText>
    <label>Intellectual Property</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Offer_close_date__c.field-meta.xml
<CustomField>
    <fullName>Form_Offer_close_date__c</fullName>
    <description>This field specifies the closing date for the current offer.</description>
    <inlineHelpText>Provide the closing date for the current offer.</inlineHelpText>
    <label>Offer close date</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Offer_launch_date__c.field-meta.xml
<CustomField>
    <fullName>Form_Offer_launch_date__c</fullName>
    <description>This field specifies the launch date for the current offer.</description>
    <inlineHelpText>Provide the launch date for the current offer.</inlineHelpText>
    <label>Offer launch date</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Problem_or_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Form_Problem_or_Opportunity__c</fullName>
    <description>This field identifies the problem or opportunity that the company is addressing.</description>
    <inlineHelpText>Describe the problem or opportunity your company is addressing.</inlineHelpText>
    <label>Problem or Opportunity</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Progress__c.field-meta.xml
<CustomField>
    <fullName>Form_Progress__c</fullName>
    <description>This field provides an update on the company&apos;s progress.</description>
    <inlineHelpText>Provide an update on your company&apos;s progress.</inlineHelpText>
    <label>Progress</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Solution__c.field-meta.xml
<CustomField>
    <fullName>Form_Solution__c</fullName>
    <description>This field describes the solution the company provides.</description>
    <inlineHelpText>Detail the solution your company offers to address the identified problem or opportunity.</inlineHelpText>
    <label>Solution</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Total_addressable_market__c.field-meta.xml
<CustomField>
    <fullName>Form_Total_addressable_market__c</fullName>
    <description>This field indicates the total addressable market for the company’s product or service.</description>
    <inlineHelpText>Specify the total addressable market for your product or service.</inlineHelpText>
    <label>Total addressable market</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Valuation__c.field-meta.xml
<CustomField>
    <fullName>Form_Valuation__c</fullName>
    <description>This field indicates the company’s valuation.</description>
    <inlineHelpText>Specify the current valuation of your company.</inlineHelpText>
    <label>Valuation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field specifies the owner of the record.</description>
    <inlineHelpText>Select the owner of this record.</inlineHelpText>
    <label>Internal Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Raise1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Publish_on_Community_Site__c.field-meta.xml
<CustomField>
    <fullName>Publish_on_Community_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will be automatically checked once the Tile Banner field is populated and the Status is set to &quot;Live in VC Website&quot;</description>
    <inlineHelpText>This field will be automatically checked once the Tile Banner field is populated and the Status is set to &quot;Live in VC Website&quot;</inlineHelpText>
    <label>Publish on Community Site</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field indicates the status of the record.</description>
    <inlineHelpText>Select the current status of this record.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for review</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Waiting for payment</fullName>
            </value>
            <value>
                <fullName>Waiting to complete learning course</fullName>
            </value>
            <value>
                <fullName>Pending final approval</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live on VC Website</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Tile_Banner__c.field-meta.xml
<CustomField>
    <fullName>Tile_Banner__c</fullName>
    <description>This tile banner will be used to be displayed in the Website.
This tile banner URL will also be synched up with the Product Tile Banner Field.</description>
    <inlineHelpText>This tile banner will be used to be displayed in the Website, please create and update the URL in this field for the Tile Banner.</inlineHelpText>
    <label>Tile Banner</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/classes/Product_V2_Service_Test.cls
@isTest
private class Product_V2_Service_Test {

    @testSetup
    static void setup() {

        User owner = [SELECT Id FROM USER WHERE Name = 'The VentureCrowd Team'];
        Id recordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('VC Person Account').getRecordTypeId();
        Account testAccount = new Account(
            FirstName = 'TestPersonAccountFirst',
            LastName = 'TestPersonAccountLast',
            PersonEmail = 'test@user.com',
            RecordTypeId = recordTypeId,
            // Name = 'Test Account',
            OwnerId = owner.Id
        );
        insert testAccount;

        // Create a test company account related to the test account
        Account testCompany = new Account(
            Name = 'Test Company Account',
            
            Related_Person_Account__c = testAccount.Id);
        insert testCompany;

        // Create a sample ContentVersion
        ContentVersion contentVersion = new ContentVersion();
        contentVersion.Title = 'Test Document';
        contentVersion.PathOnClient = 'Test Document.pdf';
        contentVersion.VersionData = Blob.valueOf('Test Content');
        contentVersion.Form_Field__c = 'companyLogoId';
        insert contentVersion;


        // Create a sample ContentVersion
        ContentVersion contentVersion2 = new ContentVersion();
        contentVersion2.Title = 'Test Document';
        contentVersion2.PathOnClient = 'Test Document.pdf';
        contentVersion2.VersionData = Blob.valueOf('Test Content');
        contentVersion2.Form_Field__c = 'heroImageId';
        insert contentVersion2;

        

        
        Profile testProfile = [SELECT Id, Name FROM Profile WHERE Name = 'VC Investor Community Plus Login' LIMIT 1];
    
        Contact getContact = [SELECT Id, Name FROM Contact WHERE FirstName = 'TestPersonAccountFirst'];
        // Id contactId = getContact.Id;

        User testUser = new User(
            FirstName = 'TestingUserN2',
            Username = 'testUser_n2@test.com',
            LastName = 'TestAds',
            // ContactId = testContact.Id,
            Email = 'testUser_n2@test.com',
            Alias = 'tuser',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            ProfileId = testProfile.Id,
            ContactId = getContact.Id
        );
        insert testUser;


        // Create a test raise
        Raise__c testRaise = new Raise__c(
            Name = 'Test Raise',
            Account__c = testAccount.Id,
            Company__c = testCompany.Id,
            Status__c = 'New',
            Form_Problem_or_Opportunity__c = 'Problem statement',
            Form_Solution__c = 'Solution statement',
            Form_Differentiation__c = 'Differentiation statement',
            Form_Intellectual_Property__c = 'IP statement',
            Form_Total_addressable_market__c = 'Market size statement',
            Form_Progress__c = 'Progress statement',
            Form_Growth_plan__c = 'Growth plan statement',
            Form_Valuation__c = 1000000,
            Form_Company_one_liner__c = 'One liner',
            Form_Offer_close_date__c = Date.today().addDays(30),
            Form_Offer_launch_date__c = Date.today(),
            Owner__c = testUser.Id
        );
        insert testRaise;

        // Link the document to the account
        ContentDocumentLink docLink = new ContentDocumentLink();
        docLink.ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion.Id].ContentDocumentId;
        docLink.LinkedEntityId = testRaise.Id;
        docLink.ShareType = 'V';
        docLink.Visibility = 'AllUsers';
        insert docLink;


        ContentDocumentLink docLink2 = new ContentDocumentLink();
        docLink2.ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion2.Id].ContentDocumentId;
        docLink2.LinkedEntityId = testRaise.Id;
        docLink2.ShareType = 'V';
        docLink2.Visibility = 'AllUsers';
        insert docLink2;

        // Create a sample ContentDistribution
        ContentDistribution contentDistribution = new ContentDistribution();
        contentDistribution.ContentVersionId = contentVersion.Id;
        contentDistribution.Name = 'Test Distribution';
        insert contentDistribution;

        // Create a sample ContentDistribution
        ContentDistribution contentDistribution2 = new ContentDistribution();
        contentDistribution2.ContentVersionId = contentVersion2.Id;
        contentDistribution2.Name = 'Test Distribution';
        insert contentDistribution2;



        // Create test Product2 records that match the criteria
        Product2 product1 = new Product2(
            Name = 'Test Product 1',
            Portal_Display_Name__c = 'Product Display 1',
            Tile_Heading__c = 'Heading 1',
            Deal_Description__c = 'Deal Description 1',
            Tile_Offer_Type__c = 'Offer Type 1',
            Tile_Banner__c = 'Banner 1',
            Family = 'Test Family',
            Raise__c = testRaise.Id,

            Deal_Page_Link__c = 'http://example.com/product1',
            Publish_on_Community_Site__c = true,
            IsActive = true,
            Offer_Close_Date__c = Date.today().addDays(1)
        );
        Product2 product2 = new Product2(
            Name = 'Test Product 2',
            Portal_Display_Name__c = 'Product Display 2',
            Tile_Heading__c = 'Heading 2',
            Deal_Description__c = 'Deal Description 2',
            Tile_Offer_Type__c = 'Offer Type 2',
            Tile_Banner__c = 'Banner 2',
            Family = 'Test Family',
            Raise__c = testRaise.Id,

            Deal_Page_Link__c = 'http://example.com/product2',
            Publish_on_Community_Site__c = true,
            IsActive = true,
            Offer_Close_Date__c = Date.today().addDays(1)
        );
        insert new List<Product2> { product1, product2 };


    }

    @isTest
    static void testGetProductOfferInformationSuccess() {
        // Instantiate the service class
        Product_V2_Service service = new Product_V2_Service();

        Test.startTest();
        // Call the method to retrieve product information
        String jsonResult = service.getProductOfferInformation();
        Test.stopTest();

        // Deserialize the JSON result to a list of ProductsData
        List<Product_V2_Service.ProductsData> productsDataList = (List<Product_V2_Service.ProductsData>) JSON.deserialize(jsonResult, List<Product_V2_Service.ProductsData>.class);

        // Validate the results
        System.assertNotEquals(null, productsDataList, 'Product data list should not be null');
        System.assertEquals(2, productsDataList.size(), 'There should be two products returned');
    }

    @isTest
    static void testGetProductOfferInformationNoProducts() {
        // Delete all products to simulate the scenario where no products exist
        delete [SELECT Id FROM Product2];

        // Instantiate the service class
        Product_V2_Service service = new Product_V2_Service();

        Test.startTest();
        try {
            // Call the method to retrieve product information
            service.getProductOfferInformation();
            System.assert(false, 'An exception should have been thrown because no products are available');
        } catch (Exception e) {
            System.assertNotEquals(null, e.getMessage(), 'Expected exception message not received');
        }
        Test.stopTest();
    }


    @isTest
    static void testGetProductInformationSuccess() {
        // Instantiate the service class
        Product2 testProduct = [SELECT Id, Name FROM Product2 WHERE Name = 'Test Product 1' LIMIT 1];
        
        Test.startTest();
        Product_V2_Service service = new Product_V2_Service();
        Product2 result = service.getProductInformation(testProduct.Id);
        Test.stopTest();

        // Validate the results
        System.assertNotEquals(null, result, 'The product record should not be null.');
    }

    @isTest
    static void testGetProductInformationNoProducts() {
        // Delete all products to simulate the scenario where no products exist
        delete [SELECT Id FROM Product2];

        // Instantiate the service class
        Product_V2_Service service = new Product_V2_Service();

        Test.startTest();
        try {
            Id productId = '0x00000000000';
            service.getProductInformation(productId);
            System.assert(false, 'An exception should have been thrown because no products are available');
        } catch (Exception e) {
            System.assertNotEquals(null, e.getMessage(), 'Expected exception message not received');
        }
        Test.stopTest();
    }
}