common/force-app/main/default/objects/Account/fields/Related_Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Related Person Account)</relationshipLabel>
    <relationshipName>Accounts6</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/EOI__c.object-meta.xml
<CustomObject>
    <description>This object will be used by Founders, this was part of the MVP project.</description>
    <label>EOI</label>
    <nameField>
        <label>EOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOI&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/EOI__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>This will link to the Ventures Company Account that is related to the EOI</description>
    <inlineHelpText>This field links to the Ventures Company Account that is related to this EOI</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EOI&apos;s</relationshipLabel>
    <relationshipName>EOI_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/EOI_Published_Date__c.field-meta.xml
<CustomField>
    <fullName>EOI_Published_Date__c</fullName>
    <label>EOI Published Date</label>
    <type>DateTime</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/EOI_Status__c.field-meta.xml
<CustomField>
    <fullName>EOI_Status__c</fullName>
    <description>This is the Status (Progress) for the EOI record.</description>
    <label>EOI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Published</fullName>
                <default>true</default>
                <label>Not Published</label>
            </value>
            <value>
                <fullName>Submitted to be Published</fullName>
            </value>
            <value>
                <fullName>Publishing</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Internal_Owner__c.field-meta.xml
<CustomField>
    <fullName>Internal_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Internal Owner in charge of the EOI and the Account</description>
    <inlineHelpText>Internal Owner in charge of the EOI and the Account</inlineHelpText>
    <label>Internal Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EOI_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Related_Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EOI&apos;s (Related Person Account)</relationshipLabel>
    <relationshipName>EOI_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/URL_Files_Img__c.field-meta.xml
<CustomField>
    <fullName>URL_Files_Img__c</fullName>
    <description>This field stores a JSON file after a user click save on edit EOI. The Apex controller updating this is ContentDownloadURL</description>
    <inlineHelpText>This field stores a JSON file after a user click save on edit EOI. The Apex controller updating this is ContentDownloadURL</inlineHelpText>
    <label>URL_Files_Img</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/Raise__c.object-meta.xml
<CustomObject>
    <description>The raise object accountable for keeping track of a Founder&apos;s raise process.</description>
    <label>Raise</label>
    <nameField>
        <label>Raise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Raise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Raise__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field represents an account lookup relationship.</description>
    <inlineHelpText>Select an account to associate with this record.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Raise</relationshipLabel>
    <relationshipName>Raise</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field represents a master-detail relationship with the Company object.</description>
    <inlineHelpText>Select the company to which this record belongs.</inlineHelpText>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Raise (Company)</relationshipLabel>
    <relationshipName>Company</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/EOI__c.field-meta.xml
<CustomField>
    <fullName>EOI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field represents a lookup relationship with the EOI object.</description>
    <inlineHelpText>Select an Expression of Interest (EOI) associated with this record.</inlineHelpText>
    <label>EOI</label>
    <referenceTo>EOI__c</referenceTo>
    <relationshipLabel>Raise</relationshipLabel>
    <relationshipName>Raise</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Company_one_liner__c.field-meta.xml
<CustomField>
    <fullName>Form_Company_one_liner__c</fullName>
    <description>This field contains a brief one-liner description of the company.</description>
    <inlineHelpText>Provide a concise, one-sentence description of your company.</inlineHelpText>
    <label>Company one liner</label>
    <type>TextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Differentiation__c.field-meta.xml
<CustomField>
    <fullName>Form_Differentiation__c</fullName>
    <description>This field highlights the differentiation points of the company.</description>
    <inlineHelpText>Highlight what sets your company apart from competitors.</inlineHelpText>
    <label>Differentiation</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Growth_plan__c.field-meta.xml
<CustomField>
    <fullName>Form_Growth_plan__c</fullName>
    <description>This field outlines the company&apos;s growth plan and strategies for future expansion.</description>
    <inlineHelpText>Describe your company&apos;s growth plan and strategies for achieving future expansion.</inlineHelpText>
    <label>Growth plan</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Intellectual_Property__c.field-meta.xml
<CustomField>
    <fullName>Form_Intellectual_Property__c</fullName>
    <description>This field provides details about the company&apos;s intellectual property.</description>
    <inlineHelpText>Include information about patents, trademarks, copyrights, or any other intellectual property your company holds.</inlineHelpText>
    <label>Intellectual Property</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Offer_close_date__c.field-meta.xml
<CustomField>
    <fullName>Form_Offer_close_date__c</fullName>
    <description>This field specifies the closing date for the current offer.</description>
    <inlineHelpText>Provide the closing date for the current offer.</inlineHelpText>
    <label>Offer close date</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Offer_launch_date__c.field-meta.xml
<CustomField>
    <fullName>Form_Offer_launch_date__c</fullName>
    <description>This field specifies the launch date for the current offer.</description>
    <inlineHelpText>Provide the launch date for the current offer.</inlineHelpText>
    <label>Offer launch date</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Problem_or_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Form_Problem_or_Opportunity__c</fullName>
    <description>This field identifies the problem or opportunity that the company is addressing.</description>
    <inlineHelpText>Describe the problem or opportunity your company is addressing.</inlineHelpText>
    <label>Problem or Opportunity</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Progress__c.field-meta.xml
<CustomField>
    <fullName>Form_Progress__c</fullName>
    <description>This field provides an update on the company&apos;s progress.</description>
    <inlineHelpText>Provide an update on your company&apos;s progress.</inlineHelpText>
    <label>Progress</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Solution__c.field-meta.xml
<CustomField>
    <fullName>Form_Solution__c</fullName>
    <description>This field describes the solution the company provides.</description>
    <inlineHelpText>Detail the solution your company offers to address the identified problem or opportunity.</inlineHelpText>
    <label>Solution</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Total_addressable_market__c.field-meta.xml
<CustomField>
    <fullName>Form_Total_addressable_market__c</fullName>
    <description>This field indicates the total addressable market for the company’s product or service.</description>
    <inlineHelpText>Specify the total addressable market for your product or service.</inlineHelpText>
    <label>Total addressable market</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Valuation__c.field-meta.xml
<CustomField>
    <fullName>Form_Valuation__c</fullName>
    <description>This field indicates the company’s valuation.</description>
    <inlineHelpText>Specify the current valuation of your company.</inlineHelpText>
    <label>Valuation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field specifies the owner of the record.</description>
    <inlineHelpText>Select the owner of this record.</inlineHelpText>
    <label>Internal Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Raise1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field indicates the status of the record.</description>
    <inlineHelpText>Select the current status of this record.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for review</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Waiting for payment</fullName>
            </value>
            <value>
                <fullName>Waiting to complete learning course</fullName>
            </value>
            <value>
                <fullName>Pending final approval</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live on VC Website</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/classes/CompaniesServiceTest.cls
@isTest
private class CompaniesServiceTest {

    private static CompaniesService companiesService = new CompaniesService();

    @testSetup
    static void setupTestData() {
        // Create test data for Account, Company, Raise, EOI, and User

        User owner = [SELECT Id FROM USER WHERE Name = 'The VentureCrowd Team'];
        Id recordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('VC Person Account').getRecordTypeId();
        Account testAccount = new Account(
            FirstName = 'TestPersonAccountFirst',
            LastName = 'TestPersonAccountLast',
            PersonEmail = 'test@user.com',
            RecordTypeId = recordTypeId,
            // Name = 'Test Account',
            OwnerId = owner.Id
        );
        insert testAccount;

        // Create a test company account related to the test account
        Account testCompany = new Account(
            Name = 'Test Company Account',
            
            Related_Person_Account__c = testAccount.Id);
        insert testCompany;
        
        Profile testProfile = [SELECT Id, Name FROM Profile WHERE Name = 'VC Investor Community Plus Login' LIMIT 1];
    
        Contact getContact = [SELECT Id, Name FROM Contact WHERE FirstName = 'TestPersonAccountFirst'];
        // Id contactId = getContact.Id;

        User testUser = new User(
            FirstName = 'TestingUserN2',
            Username = 'testUser_n2@test.com',
            LastName = 'TestAds',
            // ContactId = testContact.Id,
            Email = 'testUser_n2@test.com',
            Alias = 'tuser',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            ProfileId = testProfile.Id,
            ContactId = getContact.Id
        );
        insert testUser;

        // Create a test raise
        Raise__c testRaise = new Raise__c(
            Name = 'Test Raise',
            Account__c = testAccount.Id,
            Company__c = testCompany.Id,
            Status__c = 'New',
            Owner__c= owner.Id,
            Form_Problem_or_Opportunity__c = 'Problem statement',
            Form_Solution__c = 'Solution statement',
            Form_Differentiation__c = 'Differentiation statement',
            Form_Intellectual_Property__c = 'IP statement',
            Form_Total_addressable_market__c = 'Market size statement',
            Form_Progress__c = 'Progress statement',
            Form_Growth_plan__c = 'Growth plan statement',
            Form_Valuation__c = 1000000,
            Form_Company_one_liner__c = 'One liner',
            Form_Offer_close_date__c = Date.today().addDays(30),
            Form_Offer_launch_date__c = Date.today()
        );
        insert testRaise;
    
        // Create a test EOI
        EOI__c testEOI = new EOI__c(
            Name = 'Testing EOI',
            Related_Person_Account__c = testAccount.Id,
            Internal_Owner__c = owner.Id,
            Account__c = testCompany.Id,
            EOI_Status__c = 'Closed',
            EOI_Published_Date__c = DateTime.now(),
            URL_Files_Img__c = '[{"title":"logo","contentDownloadURL":"https://example.com/logo.png"}]'
        );
        insert testEOI;
    }

    @IsTest
    static void testRaiseExists_True() {
        Account testCompany = [SELECT Id FROM Account WHERE Name='Test Company Account' LIMIT 1];

        Test.startTest();
        Boolean exists = companiesService.raiseExists(testCompany.Id);
        Test.stopTest();

        System.assertEquals(true, exists, 'Raise should exist for the given company ID');
    }

    @IsTest
    static void testRaiseExists_False() {

        Test.startTest();
        Boolean exists = companiesService.raiseExists('001XXXXXXXXXXXXXXX');
        Test.stopTest();

        System.assertEquals(false, exists, 'Raise should not exist for an invalid company ID');
    }


    @IsTest
    static void testEoiExists_True() {
        Account testCompany = [SELECT Id FROM Account WHERE Name='Test Company Account' LIMIT 1];
        Test.startTest();
        Boolean exists = companiesService.eoiExists(testCompany.Id);
        Test.stopTest();

        System.assertEquals(true, exists, 'EOI should exist for the given company ID');
    }

    @IsTest
    static void testEoiExists_False() {

        Test.startTest();
        Boolean exists = companiesService.eoiExists('001XXXXXXXXXXXXXXX');
        Test.stopTest();

        System.assertEquals(false, exists, 'EOI should not exist for an invalid company ID');
    }


    @IsTest
    static void testGetRaiseDetailsFromCompanyId_ExistingCompany() {
        Account testCompany = [SELECT Id FROM Account WHERE Name='Test Company Account' LIMIT 1];
        Test.startTest();
        String details = companiesService.getRaiseDetailsFromCompanyId(testCompany.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, details, 'Details should not be null');
        System.assert(details.contains('Test Raise'), 'Details should contain raise name');
    }

    @IsTest
    static void testGetRaiseDetailsFromCompanyId_NonExistingCompany() {
        String nonExistingCompanyId = '001xx000003XXXXAAO';
        
        Test.startTest();
        AuraHandledException expectedException = null;
        try {
            String details = companiesService.getRaiseDetailsFromCompanyId(nonExistingCompanyId);
        } catch (AuraHandledException e) {
            expectedException = e;
        }
        Test.stopTest();
        
        System.assertNotEquals(null, expectedException, 'An AuraHandledException should be thrown for non-existing ID');
    }

    @IsTest
    static void testGetEoiDetailsFromCompanyId_ExistingCompany() {
        Account testCompany = [SELECT Id FROM Account WHERE Name='Test Company Account' LIMIT 1];
        Test.startTest();
        String details = companiesService.getEoiDetailsFromCompanyId(testCompany.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, details, 'Details should not be null');
        System.assert(details.contains('Testing EOI'), 'Details should contain EOI name');
    }

    @IsTest
    static void testGetEoiDetailsFromCompanyId_NonExistingCompany() {
        String nonExistingCompanyId = '001xx000003XXXXAAO';
        
        Test.startTest();
        AuraHandledException expectedException = null;
        try {
            String details = companiesService.getEoiDetailsFromCompanyId(nonExistingCompanyId);
        } catch (AuraHandledException e) {
            expectedException = e;
        }
        Test.stopTest();
        
        System.assertNotEquals(null, expectedException, 'An AuraHandledException should be thrown for non-existing ID');
    }

    @IsTest
    static void testGetCompaniesCardDetails() {
        // User testUser = [SELECT AccountId, ContactId, Id FROM User WHERE Email='testUser_n2@test.com' LIMIT 1];

        // System.debug('Test User: ' + getContact.Id + 'This is the contact' + getContact.Name);

        
        User testUser = [SELECT AccountId, Id, ContactId, Name FROM User WHERE Email = 'testUser_n2@test.com'];
        System.debug(testUser);

        Contact userContact = [SELECT AccountId , Id, Name FROM Contact WHERE FirstName = 'TestPersonAccountFirst'];
        System.debug('This is the contact Details' + userContact);
        // Account testAccount = [SELECT AccountId, Id, Name FROM Contact WHERE UserId=:testUser.Id];
        // System.debug('Test User: ' + testAccount.Id);


        EOI__c testEOI = [SELECT Account__c, Id, Name FROM EOI__c];
        System.debug('Test EOI' + testEOI);

        Raise__c testRaise = [SELECT Account__c, Id, Name FROM Raise__c];
        System.debug('Test Raise' + testRaise);

        Test.startTest();
        List<Map<String, Object>> companiesCardDetails = companiesService.getCompaniesCardDetails(testUser.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, companiesCardDetails, 'Companies card details should be retrieved for the given user ID');
        System.assertNotEquals(0, companiesCardDetails.size(), 'Companies card details list should not be empty');
        Map<String, Object> firstCompanyCardDetails = companiesCardDetails[0];
        System.assertEquals('Test Company Account', firstCompanyCardDetails.get('companyName'), 'Company name should match');
        System.assertEquals(true, firstCompanyCardDetails.get('eoiExist'), 'EOI should exist');
        System.assertEquals(true, firstCompanyCardDetails.get('raiseExist'), 'Raise should exist');
    }

    @IsTest
    static void testGetCompaniesCardDetails_Exception() {
        CompaniesService service = new CompaniesService();

        Test.startTest();
        try {
            service.getCompaniesCardDetails(null);
        } catch (AuraHandledException e) {
            System.assert(true, 'Exception should have been thrown for null user ID');
        }
        Test.stopTest();
    }

}