common/force-app/main/default/objects/Account/fields/Related_Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Related Person Account)</relationshipLabel>
    <relationshipName>Accounts6</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Account/recordTypes/Ventures_Company_Account.recordType-meta.xml
<RecordType>
    <fullName>Ventures_Company_Account</fullName>
    <active>true</active>
    <label>Ventures Company Account</label>
</RecordType>

common/force-app/main/default/objects/EOI__c/EOI__c.object-meta.xml
<CustomObject>
    <description>This object will be used by Founders, this was part of the MVP project.</description>
    <label>EOI</label>
    <nameField>
        <label>EOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOI&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/EOI__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>This will link to the Ventures Company Account that is related to the EOI</description>
    <inlineHelpText>This field links to the Ventures Company Account that is related to this EOI</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EOI&apos;s</relationshipLabel>
    <relationshipName>EOI_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/EOI_Published_Date__c.field-meta.xml
<CustomField>
    <fullName>EOI_Published_Date__c</fullName>
    <label>EOI Published Date</label>
    <type>DateTime</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/EOI_Status__c.field-meta.xml
<CustomField>
    <fullName>EOI_Status__c</fullName>
    <description>This is the Status (Progress) for the EOI record.</description>
    <label>EOI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Published</fullName>
                <default>true</default>
                <label>Not Published</label>
            </value>
            <value>
                <fullName>Submitted to be Published</fullName>
            </value>
            <value>
                <fullName>Publishing</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Published_EOI_URL__c.field-meta.xml
<CustomField>
    <fullName>Published_EOI_URL__c</fullName>
    <label>Published EOI URL</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Related_Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EOI&apos;s (Related Person Account)</relationshipLabel>
    <relationshipName>EOI_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/URL_Files_Img__c.field-meta.xml
<CustomField>
    <fullName>URL_Files_Img__c</fullName>
    <description>This field stores a JSON file after a user click save on edit EOI. The Apex controller updating this is ContentDownloadURL</description>
    <inlineHelpText>This field stores a JSON file after a user click save on edit EOI. The Apex controller updating this is ContentDownloadURL</inlineHelpText>
    <label>URL_Files_Img</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/Raise__c.object-meta.xml
<CustomObject>
    <description>The raise object accountable for keeping track of a Founder&apos;s raise process.</description>
    <label>Raise</label>
    <nameField>
        <label>Raise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Raise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Raise__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field represents an account lookup relationship.</description>
    <inlineHelpText>Select an account to associate with this record.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Raise</relationshipLabel>
    <relationshipName>Raise</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field represents a master-detail relationship with the Company object.</description>
    <inlineHelpText>Select the company to which this record belongs.</inlineHelpText>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Raise (Company)</relationshipLabel>
    <relationshipName>Company</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Course_unlocked__c.field-meta.xml
<CustomField>
    <fullName>Course_unlocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox indicates whether the course has been unlocked for the user.</description>
    <inlineHelpText>Check this box if the user has unlocked access to the course.</inlineHelpText>
    <label>Course unlocked</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/EOI__c.field-meta.xml
<CustomField>
    <fullName>EOI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field represents a lookup relationship with the EOI object.</description>
    <inlineHelpText>Select an Expression of Interest (EOI) associated with this record.</inlineHelpText>
    <label>EOI</label>
    <referenceTo>EOI__c</referenceTo>
    <relationshipLabel>Raise</relationshipLabel>
    <relationshipName>Raise</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Investment_type__c.field-meta.xml
<CustomField>
    <fullName>Form_Investment_type__c</fullName>
    <description>This field indicates the type of investment being made.</description>
    <inlineHelpText>Indicate the type of investment: Retail or Wholesale.</inlineHelpText>
    <label>Investment type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Retail</fullName>
                <default>true</default>
                <label>Retail</label>
            </value>
            <value>
                <fullName>Wholesale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Offer_close_date__c.field-meta.xml
<CustomField>
    <fullName>Form_Offer_close_date__c</fullName>
    <description>This field specifies the closing date for the current offer.</description>
    <inlineHelpText>Provide the closing date for the current offer.</inlineHelpText>
    <label>Offer close date</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Offer_launch_date__c.field-meta.xml
<CustomField>
    <fullName>Form_Offer_launch_date__c</fullName>
    <description>This field specifies the launch date for the current offer.</description>
    <inlineHelpText>Provide the launch date for the current offer.</inlineHelpText>
    <label>Offer launch date</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Learning_completed__c.field-meta.xml
<CustomField>
    <fullName>Learning_completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates whether the learning has been completed.</description>
    <inlineHelpText>Check this box if the learning has been completed.</inlineHelpText>
    <label>Learning completed</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field indicates the status of the record.</description>
    <inlineHelpText>Select the current status of this record.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for review</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Waiting for payment</fullName>
            </value>
            <value>
                <fullName>Waiting to complete learning course</fullName>
            </value>
            <value>
                <fullName>Pending final approval</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live on VC Website</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/classes/CompaniesFactory.cls
/**
Companies factory class that is used to retrieve data to my companies
from the EOI__c and Raise__c objects without exposing the object creation logic to the client
*/
public class CompaniesFactory implements ICompaniesFactory{
    /**
    * Checks if there is a Raise already created for a Business Account.
    * @param companyId The Id of the Business Account to create the raise.
    * @return Boolean to indicate if a raise exists or not.
    */
    public Boolean checkRaiseExists(String companyId){
        try{
            List<Raise__c> raiseList = [SELECT Id FROM Raise__c WHERE Company__c=:companyId];
            if(raiseList.size()>0){
                Logger.logMessage('CompaniesApp', 'CompaniesFactory', 'checkRaiseExists', 'Raise exists for companyId: ' + companyId);
                return true;
            }else{
                Logger.logMessage('CompaniesApp', 'CompaniesFactory', 'checkRaiseExists', 'No raise exists for companyId: ' + companyId);
                return false;
            }
        }catch(Exception e){
            Logger.logError('CompaniesApp', 'CompaniesFactory', 'checkRaiseExists', companyId, null, null, null, e, 'Failed to check if raise exists for companyId: ' + companyId);
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
    * Checks if there is a EOI already created for a Business Account.
    * @param companyId The Id of the Business Account to create the raise.
    * @return Boolean to indicate if a EOI exists or not.
    */
    public Boolean checkEoiExists(String companyId) {
        try {
            List<EOI__c> eoiList = [SELECT Id FROM EOI__c WHERE Account__c = :companyId];
            if (eoiList.size() > 0) {
                Logger.logMessage('CompaniesApp', 'CompaniesFactory', 'checkEoiExists', 'EOI exists for companyId: ' + companyId);
                return true;
            } else {
                Logger.logMessage('CompaniesApp', 'CompaniesFactory', 'checkEoiExists', 'No EOI exists for companyId: ' + companyId);
                return false;
            }
        } catch (Exception e) {
            Logger.logError('CompaniesApp', 'CompaniesFactory', 'checkEoiExists', companyId, null, null, null, e, 'Failed to check if EOI exists for companyId: ' + companyId);
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
    * Gets the EOI__c details for a specific Business account ID.
    * @param companyId The Id of the Business Account to be queried.
    * @return EOI__c record.
    * MODIFIED FOR PREVUP-98
    */
    public EOI__c getEOIDetailsFromCompanyId(String companyId){
        try{
            List<EOI__c> eoi = [SELECT Name, Id, EOI_Status__c, EOI_Published_Date__c, Published_EOI_URL__c, URL_Files_Img__c FROM EOI__c WHERE Account__c=:companyId ORDER BY CreatedDate DESC];        
            if (eoi.size() > 0) {
                Logger.logMessage('CompaniesApp', 'CompaniesFactory', 'getEOIDetailsFromCompanyId', 'Successfully retrieved EOI details for companyId: ' + companyId);
                return eoi[0];
            } else {
                Logger.logMessage('CompaniesApp', 'CompaniesFactory', 'getEOIDetailsFromCompanyId', 'No EOI details found for companyId: ' + companyId);
                return null;
            }
        }catch(Exception e){
            Logger.logError('CompaniesApp', 'CompaniesFactory', 'getEOIDetailsFromCompanyId', companyId, null, null, null, e, 'Failed to get EOI details for companyId: ' + companyId);
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
    * Gets the Raise record given a company ID.
    * @param companyId The Id of the Business Account.
    * @return Raise__c record.
    */
    public Raise__c getRaiseRecordCompanyId(String companyId){
        try{
            List<Raise__c> raiseList = [SELECT Name,Account__c, Company__c, EOI__c, Status__c ,Form_Investment_type__c, Form_Offer_close_date__c,Form_Offer_launch_date__c ,Course_unlocked__c, Learning_completed__c FROM Raise__c WHERE Company__c=:companyId];
            if (raiseList.isEmpty()) {
                Logger.logMessage('CompaniesApp', 'CompaniesFactory', 'getRaiseRecordCompanyId', 'GetRaiseRecord Factory No raise record found for companyId: ' + companyId);
                throw new AuraHandledException('GetRaiseRecord Factory No raise record found for companyId: ' + companyId);
            } else {
                Logger.logMessage('CompaniesApp', 'CompaniesFactory', 'getRaiseRecordCompanyId', 'Successfully retrieved raise record for companyId: ' + companyId);
                return raiseList[0];
            }
        }catch(Exception e){
            Logger.logError('CompaniesApp', 'CompaniesFactory', 'getRaiseRecordCompanyId', companyId, null, null, null, e, 'Failed to get raise record for companyId: ' + companyId);
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
    * Gets the Business account details for a specific account ID.
    * @param companyId The Id of the Business Account.
    * @return Account record.
    */
    public Account getCompanyDetails(String companyId){
        try{
            List<Account> company = [SELECT Id, Name FROM Account WHERE Id = :companyId];
            if(company.size() > 0){
                Logger.logMessage('RaiseApp', 'CompaniesFactory', 'getCompanyDetails', 'Successfully retrieved company details for companyId: ' + companyId);
                return company[0];
            }else{
                Logger.logMessage('RaiseApp', 'CompaniesFactory', 'getCompanyDetails', 'No company details found for companyId: ' + companyId);
                return null;
            }
        }catch(Exception e){
            Logger.logError('RaiseApp', 'CompaniesFactory', 'getCompanyDetails', companyId, null, null, null, e, 'Failed to get company details for companyId: ' + companyId);
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
    * Gets the company Id for  a specific user ID.
    * @param userId The Id of the User.
    * @return companyId record.
    */
    public List<Account> getCompanyId(String userId){
        try {
            List<User> companyId = [SELECT AccountId FROM User WHERE Id = :userId];
            
            if (companyId.isEmpty()) {
                Logger.logMessage('CompaniesApp', 'CompaniesFactory', 'getRaiseRecordCompanyId', 'No raise record found for userId: ' + userId);
                throw new AuraHandledException('No raise record found for userId: ' + userId);
            } else {
                // List<Account> lstCompanies = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'Ventures_Company_Account' AND Related_Person_Account__c=:companyId[0].AccountId];
                List<Account> lstCompanies = [SELECT Id FROM Account WHERE Related_Person_Account__c=:companyId[0].AccountId];

                Logger.logMessage('CompaniesApp', 'CompaniesFactory', 'getRaiseRecordCompanyId', 'Successfully retrieved raise record for companyId: ' + userId);
                return lstCompanies;
            }
        } catch(Exception e){
            Logger.logError('CompaniesApp', 'CompaniesFactory', 'getRaiseRecordCompanyId', userId, null, null, null, e, 'Failed to get raise record for companyId: ' + userId);
            throw new AuraHandledException(e.getMessage());
        }
    }
}