common/force-app/main/default/objects/Account/fields/Related_Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Related Person Account)</relationshipLabel>
    <relationshipName>Accounts6</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/EOI__c.object-meta.xml
<CustomObject>
    <description>This object will be used by Founders, this was part of the MVP project.</description>
    <label>EOI</label>
    <nameField>
        <label>EOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOI&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/EOI__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>This will link to the Ventures Company Account that is related to the EOI</description>
    <inlineHelpText>This field links to the Ventures Company Account that is related to this EOI</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EOI&apos;s</relationshipLabel>
    <relationshipName>EOI_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Internal_Owner__c.field-meta.xml
<CustomField>
    <fullName>Internal_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Internal Owner in charge of the EOI and the Account</description>
    <inlineHelpText>Internal Owner in charge of the EOI and the Account</inlineHelpText>
    <label>Internal Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EOI_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Related_Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EOI&apos;s (Related Person Account)</relationshipLabel>
    <relationshipName>EOI_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/URL_Files_Img__c.field-meta.xml
<CustomField>
    <fullName>URL_Files_Img__c</fullName>
    <description>This field stores a JSON file after a user click save on edit EOI. The Apex controller updating this is ContentDownloadURL</description>
    <inlineHelpText>This field stores a JSON file after a user click save on edit EOI. The Apex controller updating this is ContentDownloadURL</inlineHelpText>
    <label>URL_Files_Img</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Lead/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>Founder comments for this lead</description>
    <inlineHelpText>Founder comments for this lead</inlineHelpText>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Lead/fields/Investment_Amount_Currency__c.field-meta.xml
<CustomField>
    <fullName>Investment_Amount_Currency__c</fullName>
    <label>Investment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Lead/fields/Related_EOI__c.field-meta.xml
<CustomField>
    <fullName>Related_EOI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related EOI</label>
    <referenceTo>EOI__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Lead/fields/Web_Source__c.field-meta.xml
<CustomField>
    <fullName>Web_Source__c</fullName>
    <label>Web Source</label>
    <type>TextArea</type>
</CustomField>

common/force-app/main/default/objects/Lead/fields/Wholesale_Status__c.field-meta.xml
<CustomField>
    <fullName>Wholesale_Status__c</fullName>
    <inlineHelpText>This field is used when a lead fills in their Facebook form and their interpretation of whether they are wholesale or not.</inlineHelpText>
    <label>Are you a wholesale investor?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not Sure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>VC Person Account</label>
</RecordType>

common/force-app/main/default/objects/Raise__c/Raise__c.object-meta.xml
<CustomObject>
    <description>The raise object accountable for keeping track of a Founder&apos;s raise process.</description>
    <label>Raise</label>
    <nameField>
        <label>Raise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Raise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Raise__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field represents an account lookup relationship.</description>
    <inlineHelpText>Select an account to associate with this record.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Raise</relationshipLabel>
    <relationshipName>Raise</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field represents a master-detail relationship with the Company object.</description>
    <inlineHelpText>Select the company to which this record belongs.</inlineHelpText>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Raise (Company)</relationshipLabel>
    <relationshipName>Company</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Content_approved__c.field-meta.xml
<CustomField>
    <fullName>Content_approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox indicates whether the content has been approved.</description>
    <inlineHelpText>Check this box if the content has been reviewed and approved.
A task to the record owner to instruct the Funds Management Team to send the Establishment Fee to the founder will also be created when this field is checked.</inlineHelpText>
    <label>Content approved</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Course_unlocked__c.field-meta.xml
<CustomField>
    <fullName>Course_unlocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox indicates whether the course has been unlocked for the user.</description>
    <inlineHelpText>Check this box if the user has unlocked access to the course.</inlineHelpText>
    <label>Course unlocked</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/EOI__c.field-meta.xml
<CustomField>
    <fullName>EOI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field represents a lookup relationship with the EOI object.</description>
    <inlineHelpText>Select an Expression of Interest (EOI) associated with this record.</inlineHelpText>
    <label>EOI</label>
    <referenceTo>EOI__c</referenceTo>
    <relationshipLabel>Raise</relationshipLabel>
    <relationshipName>Raise</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Company_one_liner__c.field-meta.xml
<CustomField>
    <fullName>Form_Company_one_liner__c</fullName>
    <description>This field contains a brief one-liner description of the company.</description>
    <inlineHelpText>Provide a concise, one-sentence description of your company.</inlineHelpText>
    <label>Company one liner</label>
    <type>TextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Differentiation__c.field-meta.xml
<CustomField>
    <fullName>Form_Differentiation__c</fullName>
    <description>This field highlights the differentiation points of the company.</description>
    <inlineHelpText>Highlight what sets your company apart from competitors.</inlineHelpText>
    <label>Differentiation</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Growth_plan__c.field-meta.xml
<CustomField>
    <fullName>Form_Growth_plan__c</fullName>
    <description>This field outlines the company&apos;s growth plan and strategies for future expansion.</description>
    <inlineHelpText>Describe your company&apos;s growth plan and strategies for achieving future expansion.</inlineHelpText>
    <label>Growth plan</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Intellectual_Property__c.field-meta.xml
<CustomField>
    <fullName>Form_Intellectual_Property__c</fullName>
    <description>This field provides details about the company&apos;s intellectual property.</description>
    <inlineHelpText>Include information about patents, trademarks, copyrights, or any other intellectual property your company holds.</inlineHelpText>
    <label>Intellectual Property</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Offer_close_date__c.field-meta.xml
<CustomField>
    <fullName>Form_Offer_close_date__c</fullName>
    <description>This field specifies the closing date for the current offer.</description>
    <inlineHelpText>Provide the closing date for the current offer.</inlineHelpText>
    <label>Offer close date</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Problem_or_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Form_Problem_or_Opportunity__c</fullName>
    <description>This field identifies the problem or opportunity that the company is addressing.</description>
    <inlineHelpText>Describe the problem or opportunity your company is addressing.</inlineHelpText>
    <label>Problem or Opportunity</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Progress__c.field-meta.xml
<CustomField>
    <fullName>Form_Progress__c</fullName>
    <description>This field provides an update on the company&apos;s progress.</description>
    <inlineHelpText>Provide an update on your company&apos;s progress.</inlineHelpText>
    <label>Progress</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Solution__c.field-meta.xml
<CustomField>
    <fullName>Form_Solution__c</fullName>
    <description>This field describes the solution the company provides.</description>
    <inlineHelpText>Detail the solution your company offers to address the identified problem or opportunity.</inlineHelpText>
    <label>Solution</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Total_addressable_market__c.field-meta.xml
<CustomField>
    <fullName>Form_Total_addressable_market__c</fullName>
    <description>This field indicates the total addressable market for the company’s product or service.</description>
    <inlineHelpText>Specify the total addressable market for your product or service.</inlineHelpText>
    <label>Total addressable market</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Valuation__c.field-meta.xml
<CustomField>
    <fullName>Form_Valuation__c</fullName>
    <description>This field indicates the company’s valuation.</description>
    <inlineHelpText>Specify the current valuation of your company.</inlineHelpText>
    <label>Valuation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Learning_completed__c.field-meta.xml
<CustomField>
    <fullName>Learning_completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates whether the learning has been completed.</description>
    <inlineHelpText>Check this box if the learning has been completed.</inlineHelpText>
    <label>Learning completed</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field specifies the owner of the record.</description>
    <inlineHelpText>Select the owner of this record.</inlineHelpText>
    <label>Internal Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Raise1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Payment_received__c.field-meta.xml
<CustomField>
    <fullName>Payment_received__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates whether the payment has been received.</description>
    <inlineHelpText>Check this box if the payment has been received.</inlineHelpText>
    <label>Payment received</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field indicates the status of the record.</description>
    <inlineHelpText>Select the current status of this record.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for review</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Waiting for payment</fullName>
            </value>
            <value>
                <fullName>Waiting to complete learning course</fullName>
            </value>
            <value>
                <fullName>Pending final approval</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live on VC Website</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/classes/LeadControllerNewTest.cls
@IsTest
public class LeadControllerNewTest {
    @testSetup
    static void setup() {
        Id ownerId = 'a3XXX000000cXXXAAI';
         List<User> benQuery = [SELECT Id FROM User WHERE Name='Ben Crow' LIMIT 1];
         if(benQuery.size() > 0){
             ownerId = benQuery[0].Id;
         }
 
         // Create and insert a test account
         Account personAccount = new Account(Name='Related Person');
         insert personAccount;
 
         Account businessAccount = new Account(Name='Test Business', Related_Person_Account__c=personAccount.Id);
         insert businessAccount;
 
         // Optional: Create and insert related records if needed (like EOI)
         EOI__c testEOI = new EOI__c(
            Name = 'Test EOI', 
            Account__c = businessAccount.Id, 
            Internal_Owner__c=ownerId,
            URL_Files_Img__c = '[{"title":"logo","contentDownloadURL":"https://venturecrowd.my.salesforce.com/sfc/dist/version/download/?oid=00D8s000009HSSb&ids=0685i00000I3URJ&d=%2Fa%2F5i000000r2WZ%2FeABm2CrRetLvTDmslOcg9ise2vGxhK5EgoOKLtLlW_Y&asPdf=false"}]'
            );
         insert testEOI;

         Lead testLead = new Lead(
            FirstName ='Test',
            LastName='Lead',
            Email='mail@mail.com',
            Related_EOI__c=testEOI.Id,
            Investment_Amount_Currency__c = 100000
        );
         insert testLead;
         
 
 
         // Creating a Raise__c record to test existing raise functionality
         Raise__c testRaise = new Raise__c(
             Name = 'Test Raise',
             Account__c = personAccount.Id,
             Owner__c = ownerId,
             Company__c = businessAccount.Id,
             EOI__c = testEOI.Id,
             Status__c = 'In Progress',
             Payment_received__c = true,
             Content_approved__c = true,
             Course_unlocked__c = false,
             Learning_completed__c = false,
             Form_Problem_or_Opportunity__c = 'Test Problem',
             Form_Solution__c = 'Test Solution',
             Form_Differentiation__c = 'Test Differentiation',
             Form_Intellectual_Property__c = 'Test Intellectual Property',
             Form_Total_addressable_market__c = 'Test Market',
             Form_Progress__c = 'Test Progress',
             Form_Growth_plan__c = 'Test Growth Plan',
             Form_Valuation__c = 1000000,
             Form_Company_one_liner__c = 'Test Company Overview',
             Form_Offer_close_date__c = Date.today()
         );
         insert testRaise;

    
    }

    @isTest
    static void getRecordById(){
        Lead leadRecord = [SELECT Id ,FirstName, LastName FROM Lead WHERE FirstName='Test'];

        Map<String,Object> result = LeadControllerNew.getLeadById(leadRecord.Id);

        System.assertEquals(leadRecord.FirstName, result.get('firstName'));
        System.assertEquals(leadRecord.LastName, result.get('lastName'));

    }


    @isTest
    static void testGetRecords() {
        // Retrieve the test data
        Raise__c testRaise = [SELECT Id FROM Raise__c WHERE EOI__c != NULL LIMIT 1];
        
        // Set parameters
        Id recordId = testRaise.Id;
        Integer pageSize = 10;
        Integer pageNumber = 1;
        String sortBy = 'LastName';
        String sortDirection = 'ASC';
        List<String> columnNames = new List<String>{'LastName', 'FirstName', 'Id'};

        // Call the method
        LeadService.RecordsWrapper result = LeadControllerNew.getRecords(recordId, pageSize, pageNumber, sortBy, sortDirection, columnNames);

        // Verify the result
        System.assertNotEquals(null, result);
        System.assertNotEquals(null, result.records);
        System.assert(result.records.size() > 0, 'Expected records to be returned');
    }

    @isTest
    static void testGetRecordsException() {
        // Retrieve the test data
        
        // Set parameters
        Id recordId = 'a3XXX000000cXXXAAI';
        Integer pageSize = 10;
        Integer pageNumber = 1;
        String sortBy = 'LastName';
        String sortDirection = 'ASC';
        List<String> columnNames = new List<String>{'LastName', 'FirstName', 'Id'};

        Exception expectedE;

        // Call the method
        try{
            LeadService.RecordsWrapper result = LeadControllerNew.getRecords(recordId, pageSize, pageNumber, sortBy, sortDirection, columnNames);
        }catch(Exception e){
            expectedE = e;
        }

        // Verify the result
        System.assertNotEquals(null, expectedE);
    }

    @isTest
    static void testUpdateLead() {
        // Retrieve the test data
        Lead testLead = [SELECT Id, Comments__c FROM Lead LIMIT 1];
        
        // Set parameters
        Id recordId = testLead.Id;
        String objectName = 'Lead';
        Map<String, Object> fieldsToUpdate = new Map<String, Object>{
            'comments' => 'new Comment'
        };

        // Call the method
        Map<String, Object> result = LeadControllerNew.updateLead(recordId, objectName, fieldsToUpdate);

        // Verify the result
        System.assertNotEquals(null, result);
        System.assertEquals(recordId, result.get('Id'));

        // Verify the update
        Lead updatedLead = [SELECT Comments__c FROM Lead WHERE Id = :recordId];
        System.assertEquals('new Comment', updatedLead.Comments__c);
    }

    @isTest
    static void testUpdateLeadException() {
        // Retrieve the test data
        
        // Set parameters
        Id recordId = 'a3XXX000000cXXXAAI';
        String objectName = 'Lead';
        Map<String, Object> fieldsToUpdate = new Map<String, Object>{
            'comments' => 'new Comment'
        };
        Exception expectedE;
        // Call the method
        try{
            Map<String, Object> result = LeadControllerNew.updateLead(recordId, objectName, fieldsToUpdate);
        }catch(Exception e){
            expectedE = e;
        }

        // Verify the result
        System.assertNotEquals(null, expectedE);
    }

    @isTest
    static void testUpdateLeadFieldUnmapped() {
        // Retrieve the test data
        Lead testLead = [SELECT Id, Comments__c FROM Lead LIMIT 1];
        
        // Set parameters
        Id recordId = testLead.Id;
        String objectName = 'Lead';
        Map<String, Object> fieldsToUpdate = new Map<String, Object>{
            'unmapped' => 'value'
        };

        // Call the method
        Map<String, Object> result = LeadControllerNew.updateLead(recordId, objectName, fieldsToUpdate);

        // Verify the result
        System.assertNotEquals(null, result);
        System.assertEquals(recordId, result.get('Id'));
        System.assertNotEquals(null, result.get('unmapped'));
    }

    @isTest
    static void testGetEOILeadsEmail() {
        // Call the method being tested and pass a valid email
        List<Map<String, Object>> results = LeadControllerNew.getEOILeadsEmail('mail@mail.com');
        // Assert that the correct lead is returned
        System.assertEquals(1, results.size(), 'Expected one lead to be returned');
    }

    @isTest
    static void testCreateLeadSXSW(){
            // Set parameters
        Map<String, String> test = new Map<String, String>{
            'firstName'=>'John',
            'middleNames' => 'Test Names',
            'lastName'=>'Smith',
            'webSource'=>'SXSW 2024',
            'email' => 'jSmith@mail.com',
            'mobileCodeFormatted' => '+61455659874',
            'isWholesale' => 'No',
            'comments' => 'Hello Lead Created',
            'source' => 'Website Form',
            'company' => 'no Company',
            'emailOptIn' => 'true',
            'utm_source' => 'Ebay',
            'utm_medium' => 'cpc',
            'utm_campaign' => '2020 Campaign',
            'utm_term' => 'None',
            'utm_content' => 'None',
            'utm_keyword' => 'Hello'
        };

        // Call the method

        Map<String, Object> result = LeadControllerNew.createLeadSXSW(test);
        System.debug(result);
        System.assert(result.containsKey('Id'), 'Result should contain an "Id" key for the created Account.');
        Id createdLead = (Id)result.get('Id');

        Lead leadRecord = [
            SELECT FirstName, 
            LastName, 
            MiddleName, 
            Web_Source__c, 
            MobilePhone, 
            Wholesale_Status__c,
            Comments__c,
            LeadSource,
            Company,
            Email_Opt_In__c  FROM Lead WHERE Id=:createdLead LIMIT 1];

        // Verify the result
        System.Assert.areEqual('John', leadRecord.FirstName);
        System.Assert.areEqual('Test Names', leadRecord.MiddleName);
        System.Assert.areEqual('Smith', leadRecord.LastName);
        System.Assert.areEqual('SXSW 2024', leadRecord.Web_Source__c);
        System.Assert.areEqual('+61455659874', leadRecord.MobilePhone);
        System.Assert.areEqual('No', leadRecord.Wholesale_Status__c);
        System.Assert.areEqual('Hello Lead Created', leadRecord.Comments__c);
        System.Assert.areEqual('Website Form', leadRecord.LeadSource);
        System.Assert.areEqual('no Company', leadRecord.Company);
        System.Assert.areEqual(true, leadRecord.Email_Opt_In__c);
    }


    @isTest
    static void testCreateLead(){
            // Set parameters
        Map<String, String> test = new Map<String, String>{
            'firstName'=>'John',
            'middleNames' => 'Test Names',
            'lastName'=>'Smith',
            'webSource'=>'SXSW 2024',
            'email' => 'jSmith@mail.com',
            'mobileCodeFormatted' => '+61455659874',
            'isWholesale' => 'No',
            'comments' => 'Hello Lead Created',
            'source' => 'Website Form',
            'company' => 'no Company',
            'emailOptIn' => 'true',
            'utm_source' => 'Ebay',
            'utm_medium' => 'cpc',
            'utm_campaign' => '2020 Campaign',
            'utm_term' => 'None',
            'utm_content' => 'None',
            'utm_keyword' => 'Hello'
        };

        // Call the method

        Map<String, Object> result = LeadControllerNew.createLead(test);
        System.debug(result);
        System.assert(result.containsKey('Id'), 'Result should contain an "Id" key for the created Account.');
        Id createdLead = (Id)result.get('Id');

        Lead leadRecord = [
            SELECT FirstName, 
            LastName, 
            MiddleName, 
            Web_Source__c, 
            MobilePhone, 
            Wholesale_Status__c,
            Comments__c,
            LeadSource,
            Company,
            Email_Opt_In__c  FROM Lead WHERE Id=:createdLead LIMIT 1];

        // Verify the result
        System.Assert.areEqual('John', leadRecord.FirstName);
        System.Assert.areEqual('Test Names', leadRecord.MiddleName);
        System.Assert.areEqual('Smith', leadRecord.LastName);
        System.Assert.areEqual('SXSW 2024', leadRecord.Web_Source__c);
        System.Assert.areEqual('+61455659874', leadRecord.MobilePhone);
        System.Assert.areEqual('No', leadRecord.Wholesale_Status__c);
        System.Assert.areEqual('Hello Lead Created', leadRecord.Comments__c);
        System.Assert.areEqual('Website Form', leadRecord.LeadSource);
        System.Assert.areEqual('no Company', leadRecord.Company);
        System.Assert.areEqual(true, leadRecord.Email_Opt_In__c);
    }

    @isTest
    static void testGetLeads() {
        // Setup test data
        Lead testLead = [SELECT Id, FirstName, LastName, Email FROM Lead WHERE Email = 'mail@mail.com' LIMIT 1];

        // Call the method being tested
        List<Map<String, Object>> results = LeadControllerNew.getLeads('mail@mail.com');

        // Assertions to verify the result
        System.assertNotEquals(null, results, 'Results should not be null');
        System.assertEquals(1, results.size(), 'Expected exactly one lead to be returned');
}


}