common/force-app/main/default/objects/Account/fields/Related_Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Related Person Account)</relationshipLabel>
    <relationshipName>Accounts6</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/EOI__c.object-meta.xml
<CustomObject>
    <description>This object will be used by Founders, this was part of the MVP project.</description>
    <label>EOI</label>
    <nameField>
        <label>EOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOI&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/EOI__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>This will link to the Ventures Company Account that is related to the EOI</description>
    <inlineHelpText>This field links to the Ventures Company Account that is related to this EOI</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EOI&apos;s</relationshipLabel>
    <relationshipName>EOI_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/EOI_Status__c.field-meta.xml
<CustomField>
    <fullName>EOI_Status__c</fullName>
    <description>This is the Status (Progress) for the EOI record.</description>
    <label>EOI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Published</fullName>
                <default>true</default>
                <label>Not Published</label>
            </value>
            <value>
                <fullName>Submitted to be Published</fullName>
            </value>
            <value>
                <fullName>Publishing</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/EOI_Title__c.field-meta.xml
<CustomField>
    <fullName>EOI_Title__c</fullName>
    <description>EOI Title</description>
    <label>EOI Title</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Internal_Owner__c.field-meta.xml
<CustomField>
    <fullName>Internal_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Internal Owner in charge of the EOI and the Account</description>
    <inlineHelpText>Internal Owner in charge of the EOI and the Account</inlineHelpText>
    <label>Internal Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EOI_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/One_liner_about_business__c.field-meta.xml
<CustomField>
    <fullName>One_liner_about_business__c</fullName>
    <label>One liner about business</label>
    <type>TextArea</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Publish_on_Community_Site__c.field-meta.xml
<CustomField>
    <fullName>Publish_on_Community_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox will render the card to show it on the VC website</description>
    <label>Publish on Community Site</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Published_EOI_URL__c.field-meta.xml
<CustomField>
    <fullName>Published_EOI_URL__c</fullName>
    <label>Published EOI URL</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Related_Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EOI&apos;s (Related Person Account)</relationshipLabel>
    <relationshipName>EOI_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/SXSW_Finalist__c.field-meta.xml
<CustomField>
    <fullName>SXSW_Finalist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this if the EOI is an SXSW Finalist. This will enable it to be displayed on the SXSW Finalist EOI landing page</description>
    <inlineHelpText>Check this if the EOI is an SXSW Finalist. This will enable it to be displayed on the SXSW Finalist EOI landing page</inlineHelpText>
    <label>SXSW Finalist</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/URL_Files_Img__c.field-meta.xml
<CustomField>
    <fullName>URL_Files_Img__c</fullName>
    <description>This field stores a JSON file after a user click save on edit EOI. The Apex controller updating this is ContentDownloadURL</description>
    <inlineHelpText>This field stores a JSON file after a user click save on edit EOI. The Apex controller updating this is ContentDownloadURL</inlineHelpText>
    <label>URL_Files_Img</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>VC Person Account</label>
</RecordType>

common/force-app/main/default/objects/Raise__c/Raise__c.object-meta.xml
<CustomObject>
    <description>The raise object accountable for keeping track of a Founder&apos;s raise process.</description>
    <label>Raise</label>
    <nameField>
        <label>Raise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Raise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Raise__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field represents an account lookup relationship.</description>
    <inlineHelpText>Select an account to associate with this record.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Raise</relationshipLabel>
    <relationshipName>Raise</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field represents a master-detail relationship with the Company object.</description>
    <inlineHelpText>Select the company to which this record belongs.</inlineHelpText>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Raise (Company)</relationshipLabel>
    <relationshipName>Company</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/EOI__c.field-meta.xml
<CustomField>
    <fullName>EOI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field represents a lookup relationship with the EOI object.</description>
    <inlineHelpText>Select an Expression of Interest (EOI) associated with this record.</inlineHelpText>
    <label>EOI</label>
    <referenceTo>EOI__c</referenceTo>
    <relationshipLabel>Raise</relationshipLabel>
    <relationshipName>Raise</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field specifies the owner of the record.</description>
    <inlineHelpText>Select the owner of this record.</inlineHelpText>
    <label>Internal Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Raise1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Publish_on_Community_Site__c.field-meta.xml
<CustomField>
    <fullName>Publish_on_Community_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will be automatically checked once the Tile Banner field is populated and the Status is set to &quot;Live in VC Website&quot;</description>
    <inlineHelpText>This field will be automatically checked once the Tile Banner field is populated and the Status is set to &quot;Live in VC Website&quot;</inlineHelpText>
    <label>Publish on Community Site</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/classes/EOI_Factory_Test.cls
@IsTest
public class EOI_Factory_Test {

    @TestSetup
    static void setup() {
        User owner = [SELECT Id FROM USER WHERE Name = 'The VentureCrowd Team'];
        Id recordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('VC Person Account').getRecordTypeId();

        // Create a test Business Account and related Person Account
        Account personAccount = new Account(
            FirstName = 'TestPersonAccountFirst',
            LastName = 'TestPersonAccountLast',
            PersonEmail = 'test@user.com',
            RecordTypeId = recordTypeId,
            // Name = 'Test Account',
            OwnerId = owner.Id
        );
        insert personAccount;

        Account businessAccount = new Account(Name = 'Test Business', Related_Person_Account__c = personAccount.Id);
        insert businessAccount;

        Profile testProfile = [SELECT Id, Name FROM Profile WHERE Name = 'VC Investor Community Plus Login' LIMIT 1];
    
        Contact getContact = [SELECT Id, Name FROM Contact WHERE FirstName = 'TestPersonAccountFirst'];

        User testUser = new User(
        FirstName = 'TestingUserN2111',
        Username = 'testUser_n211@test.com',
        LastName = 'TestA22ds',
        // ContactId = testContact.Id,
        Email = 'testUser_n211@test.com',
        Alias = 'tuser',
        TimeZoneSidKey = 'America/Los_Angeles',
        LocaleSidKey = 'en_US',
        EmailEncodingKey = 'UTF-8',
        LanguageLocaleKey = 'en_US',
        ProfileId = testProfile.Id,
        ContactId = getContact.Id
        );
        insert testUser;

         // Create a test EOI
        EOI__c eoi = new EOI__c(
            Name = 'Test EOI',
            Account__c = businessAccount.Id,
            EOI_Status__c = 'Published',
            Publish_on_Community_Site__c = true,
            URL_Files_Img__c = 'http://example.com/image.png',
            Published_EOI_URL__c = 'http://example.com/eoi',
            One_liner_about_business__c = 'Innovative business idea',
            SXSW_Finalist__c = true,
            EOI_Title__c = 'Exciting EOI Title',
            Internal_Owner__c=owner.Id
        );
        insert eoi;

        EOI__c eoi2 = new EOI__c(
            Name = 'EOI new',
            Account__c = businessAccount.Id,
            EOI_Status__c = 'Published',
            Publish_on_Community_Site__c = true,
            URL_Files_Img__c = 'http://example.com/image.png',
            Published_EOI_URL__c = 'http://example.com/eoi',
            One_liner_about_business__c = 'Innovative business idea',
            SXSW_Finalist__c = true,
            EOI_Title__c = 'Exciting EOI Title',
            Internal_Owner__c=owner.Id
        );
        insert eoi2;

        // Create a test Raise (unrelated to this test but provided in the setup)
        Raise__c testRaise = new Raise__c(
            Name = 'Existing Raise',
            Company__c = businessAccount.Id,
            Account__c = personAccount.Id,
            Owner__c = owner.Id
        );
        insert testRaise;
    }

    @isTest
    static void testGetEoiOfferInformation_Success() {
        // Instantiate the factory class
        EOI_Factory factory = new EOI_Factory();

        Test.startTest();
        // Call the method to retrieve EOI information
        List<EOI__c> eoiRecords = factory.getEoiOfferInformation();
        Test.stopTest();

        // Validate the results
        System.assertNotEquals(null, eoiRecords, 'EOI records list should not be null');
        System.assertEquals(2, eoiRecords.size(), 'There should be one EOI record returned');
        System.assertEquals('Exciting EOI Title', eoiRecords[0].EOI_Title__c, 'The EOI title should match the expected value');
    }


    @isTest
    static void testGetSXSWEoiOfferInformation_Success() {
        // Instantiate the factory class
        EOI_Factory factory = new EOI_Factory();

        Test.startTest();
        // Call the method to retrieve EOI information
        List<EOI__c> eoiRecords = factory.getEoiSXSWFinalist('');
        Test.stopTest();

        // Validate the results
        System.assertNotEquals(null, eoiRecords, 'EOI records list should not be null');
        System.assertEquals(2, eoiRecords.size(), 'There should be one EOI record returned');
        System.assertEquals('Exciting EOI Title', eoiRecords[0].EOI_Title__c, 'The EOI title should match the expected value');
    }

    @isTest
    static void testGetSXSWEoiOfferInformation_SuccessSearch() {
        // Instantiate the factory class
        EOI_Factory factory = new EOI_Factory();

        Test.startTest();
        // Call the method to retrieve EOI information
        List<EOI__c> eoiRecords = factory.getEoiSXSWFinalist('Test');
        Test.stopTest();

        // Validate the results
        System.assertNotEquals(null, eoiRecords, 'EOI records list should not be null');
        System.assertEquals(1, eoiRecords.size(), 'There should be one EOI record returned');
        System.assertEquals('Exciting EOI Title', eoiRecords[0].EOI_Title__c, 'The EOI title should match the expected value');
    }

    @isTest
    static void testGetSXSWEoiOfferInformation_NoEOIs() {
        // Delete all EOIs to simulate the scenario where no records exist
        delete [SELECT Id FROM EOI__c];

        // Instantiate the factory class
        EOI_Factory factory = new EOI_Factory();

        Test.startTest();
        try {
            // Call the method to retrieve EOI information
            factory.getEoiSXSWFinalist('');
            System.assert(false, 'An exception should have been thrown because no EOIs are available');
        } catch (DmlException e) {
            // Validate that the exception is thrown with the correct message
            System.assert(true);

        }
        Test.stopTest();
    }


    @isTest
    static void testGetEoiOfferInformation_NoEOIs() {
        // Delete all EOIs to simulate the scenario where no records exist
        delete [SELECT Id FROM EOI__c];

        // Instantiate the factory class
        EOI_Factory factory = new EOI_Factory();

        Test.startTest();
        try {
            // Call the method to retrieve EOI information
            factory.getEoiOfferInformation();
            System.assert(false, 'An exception should have been thrown because no EOIs are available');
        } catch (DmlException e) {
            // Validate that the exception is thrown with the correct message
            System.assert(true);
        }
        Test.stopTest();
    }
}