common/force-app/main/default/objects/Account/fields/Related_Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Related Person Account)</relationshipLabel>
    <relationshipName>Accounts6</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/EOI__c.object-meta.xml
<CustomObject>
    <description>This object will be used by Founders, this was part of the MVP project.</description>
    <label>EOI</label>
    <nameField>
        <label>EOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOI&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/EOI__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>This will link to the Ventures Company Account that is related to the EOI</description>
    <inlineHelpText>This field links to the Ventures Company Account that is related to this EOI</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EOI&apos;s</relationshipLabel>
    <relationshipName>EOI_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Internal_Owner__c.field-meta.xml
<CustomField>
    <fullName>Internal_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Internal Owner in charge of the EOI and the Account</description>
    <inlineHelpText>Internal Owner in charge of the EOI and the Account</inlineHelpText>
    <label>Internal Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EOI_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Related_Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EOI&apos;s (Related Person Account)</relationshipLabel>
    <relationshipName>EOI_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/Raise__c.object-meta.xml
<CustomObject>
    <description>The raise object accountable for keeping track of a Founder&apos;s raise process.</description>
    <label>Raise</label>
    <nameField>
        <label>Raise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Raise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Raise__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field represents an account lookup relationship.</description>
    <inlineHelpText>Select an account to associate with this record.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Raise</relationshipLabel>
    <relationshipName>Raise</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field represents a master-detail relationship with the Company object.</description>
    <inlineHelpText>Select the company to which this record belongs.</inlineHelpText>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Raise (Company)</relationshipLabel>
    <relationshipName>Company</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Content_approved__c.field-meta.xml
<CustomField>
    <fullName>Content_approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox indicates whether the content has been approved.</description>
    <inlineHelpText>Check this box if the content has been reviewed and approved.
A task to the record owner to instruct the Funds Management Team to send the Establishment Fee to the founder will also be created when this field is checked.</inlineHelpText>
    <label>Content approved</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Course_unlocked__c.field-meta.xml
<CustomField>
    <fullName>Course_unlocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox indicates whether the course has been unlocked for the user.</description>
    <inlineHelpText>Check this box if the user has unlocked access to the course.</inlineHelpText>
    <label>Course unlocked</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/EOI__c.field-meta.xml
<CustomField>
    <fullName>EOI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field represents a lookup relationship with the EOI object.</description>
    <inlineHelpText>Select an Expression of Interest (EOI) associated with this record.</inlineHelpText>
    <label>EOI</label>
    <referenceTo>EOI__c</referenceTo>
    <relationshipLabel>Raise</relationshipLabel>
    <relationshipName>Raise</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Company_one_liner__c.field-meta.xml
<CustomField>
    <fullName>Form_Company_one_liner__c</fullName>
    <description>This field contains a brief one-liner description of the company.</description>
    <inlineHelpText>Provide a concise, one-sentence description of your company.</inlineHelpText>
    <label>Company one liner</label>
    <type>TextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Differentiation__c.field-meta.xml
<CustomField>
    <fullName>Form_Differentiation__c</fullName>
    <description>This field highlights the differentiation points of the company.</description>
    <inlineHelpText>Highlight what sets your company apart from competitors.</inlineHelpText>
    <label>Differentiation</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Growth_plan__c.field-meta.xml
<CustomField>
    <fullName>Form_Growth_plan__c</fullName>
    <description>This field outlines the company&apos;s growth plan and strategies for future expansion.</description>
    <inlineHelpText>Describe your company&apos;s growth plan and strategies for achieving future expansion.</inlineHelpText>
    <label>Growth plan</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Intellectual_Property__c.field-meta.xml
<CustomField>
    <fullName>Form_Intellectual_Property__c</fullName>
    <description>This field provides details about the company&apos;s intellectual property.</description>
    <inlineHelpText>Include information about patents, trademarks, copyrights, or any other intellectual property your company holds.</inlineHelpText>
    <label>Intellectual Property</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Offer_close_date__c.field-meta.xml
<CustomField>
    <fullName>Form_Offer_close_date__c</fullName>
    <description>This field specifies the closing date for the current offer.</description>
    <inlineHelpText>Provide the closing date for the current offer.</inlineHelpText>
    <label>Offer close date</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Problem_or_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Form_Problem_or_Opportunity__c</fullName>
    <description>This field identifies the problem or opportunity that the company is addressing.</description>
    <inlineHelpText>Describe the problem or opportunity your company is addressing.</inlineHelpText>
    <label>Problem or Opportunity</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Progress__c.field-meta.xml
<CustomField>
    <fullName>Form_Progress__c</fullName>
    <description>This field provides an update on the company&apos;s progress.</description>
    <inlineHelpText>Provide an update on your company&apos;s progress.</inlineHelpText>
    <label>Progress</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Solution__c.field-meta.xml
<CustomField>
    <fullName>Form_Solution__c</fullName>
    <description>This field describes the solution the company provides.</description>
    <inlineHelpText>Detail the solution your company offers to address the identified problem or opportunity.</inlineHelpText>
    <label>Solution</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Total_addressable_market__c.field-meta.xml
<CustomField>
    <fullName>Form_Total_addressable_market__c</fullName>
    <description>This field indicates the total addressable market for the company’s product or service.</description>
    <inlineHelpText>Specify the total addressable market for your product or service.</inlineHelpText>
    <label>Total addressable market</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Form_Valuation__c.field-meta.xml
<CustomField>
    <fullName>Form_Valuation__c</fullName>
    <description>This field indicates the company’s valuation.</description>
    <inlineHelpText>Specify the current valuation of your company.</inlineHelpText>
    <label>Valuation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Learning_completed__c.field-meta.xml
<CustomField>
    <fullName>Learning_completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates whether the learning has been completed.</description>
    <inlineHelpText>Check this box if the learning has been completed.</inlineHelpText>
    <label>Learning completed</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field specifies the owner of the record.</description>
    <inlineHelpText>Select the owner of this record.</inlineHelpText>
    <label>Internal Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Raise1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Payment_received__c.field-meta.xml
<CustomField>
    <fullName>Payment_received__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates whether the payment has been received.</description>
    <inlineHelpText>Check this box if the payment has been received.</inlineHelpText>
    <label>Payment received</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Preraise_completed__c.field-meta.xml
<CustomField>
    <fullName>Preraise_completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates whether the pre-raise activities have been completed.</description>
    <inlineHelpText>Check this box if the pre-raise activities have been completed.</inlineHelpText>
    <label>Preraise completed</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Raise__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field indicates the status of the record.</description>
    <inlineHelpText>Select the current status of this record.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for review</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Waiting for payment</fullName>
            </value>
            <value>
                <fullName>Waiting to complete learning course</fullName>
            </value>
            <value>
                <fullName>Pending final approval</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Live on VC Website</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Raise__c/recordTypes/Primary_Raise.recordType-meta.xml
<RecordType>
    <fullName>Primary_Raise</fullName>
    <active>true</active>
    <description>Main raise record type</description>
    <label>Primary Raise</label>
</RecordType>

common/force-app/main/default/classes/RaiseControllerTest.cls
@IsTest
private class RaiseControllerTest {

    // Helper method to set up the necessary test data
    @TestSetup
    static void setupTestData() {
        // Create and insert a test account
        Account personAccount = new Account(Name='Related Person');
        insert personAccount;

        Account businessAccount = new Account(Name='Test Business', Related_Person_Account__c=personAccount.Id);
        insert businessAccount;
        
        Id ownerId = 'a3XXX000000cXXXAAI';

        List<User> benQuery = [SELECT Id FROM User WHERE Name='Ben Crow' LIMIT 1];
        if(benQuery.size() > 0){
            ownerId = benQuery[0].Id;
        }

        EOI__c testEOI = new EOI__c(Name = 'Test EOI', Account__c = businessAccount.Id, Internal_Owner__c = ownerId);
        insert testEOI;

        // Creating a Raise__c record to test existing raise functionality
        Raise__c testRaise = new Raise__c(
            Name = 'Test Raise',
            Account__c = personAccount.Id,
            Owner__c = ownerId,
            Company__c = businessAccount.Id,
            EOI__c = testEOI.Id,
            Status__c = 'In Progress',
            Payment_received__c = true,
            Content_approved__c = true,
            Course_unlocked__c = false,
            Learning_completed__c = false,
            Form_Problem_or_Opportunity__c = 'Test Problem',
            Form_Solution__c = 'Test Solution',
            Form_Differentiation__c = 'Test Differentiation',
            Form_Intellectual_Property__c = 'Test Intellectual Property',
            Form_Total_addressable_market__c = 'Test Market',
            Form_Progress__c = 'Test Progress',
            Form_Growth_plan__c = 'Test Growth Plan',
            Form_Valuation__c = 1000000,
            Form_Company_one_liner__c = 'Test Company Overview',
            Form_Offer_close_date__c = Date.today()
        );
        insert testRaise;
    }

    // Test the creation of a Raise__c record
    @IsTest
    static void testCreateRaiseRecord() {
        Account testAccount = [SELECT Id FROM Account WHERE Name='Test Business' LIMIT 1];
        Test.startTest();
        Raise__c result = RaiseController.createRaiseRecord(testAccount.Id, 'Retail');
        Test.stopTest();

        // Asserts to verify the correct record creation
        System.assertNotEquals(null, result, 'The raise record should not be null');
        System.assertEquals('In Progress', result.Status__c, 'Status should be "In Progress"');
        System.assertEquals(true, result.Preraise_completed__c, 'Preraise should be completed');
    }
    
    // Test the creation of a Raise__c record with an invalid account ID to simulate an error
    @IsTest
    static void testCreateRaiseRecordWithError() {
        Test.startTest();
        try {
            Raise__c result = RaiseController.createRaiseRecord('invalidId','Retail');
            System.assert(false, 'An exception should have been thrown for invalid ID');
        } catch (Exception e) {
            System.assertNotEquals(null, e.getMessage(), 'Exception message not received');
        }
        Test.stopTest();
    }

    // Test to check if the raise exists for an account
    @IsTest
    static void testRaiseExists() {
        Account testAccount = [SELECT Id FROM Account WHERE Name='Test Business' LIMIT 1];
        Test.startTest();
        Boolean exists = RaiseController.raiseExists(testAccount.Id);
        Test.stopTest();

        // Assert to confirm that the raise exists
        System.assert(exists, 'Raise should exist for the test account');
    }
    
    // Test to check if the raise exists for an invalid account ID to simulate an error
    @IsTest
    static void testRaiseDoesntExist() {
        Test.startTest();
        Boolean exists = RaiseController.raiseExists('invalidId');
        Test.stopTest();
        
        System.assertEquals(false,exists, 'An exception should have been thrown for invalid ID');

    }

    // Test the retrieval of raise details by Raise ID
    @IsTest
    static void testGetRaiseDetails() {
        Raise__c testRaise = [SELECT Id FROM Raise__c LIMIT 1];
        Test.startTest();
        String details = RaiseController.getRaiseDetails(testRaise.Id);
        Test.stopTest();

        // Assert to ensure that some details are returned
        System.assertNotEquals(null, details, 'Details should not be null');
        System.assert(details.contains('Test Raise'), 'Details should contain the raise name');
    }
    
    // Test the retrieval of raise details with an invalid raise ID to simulate an error
    @IsTest
    static void testGetRaiseDetailsWithError() {
        Test.startTest();
        try {
            String details = RaiseController.getRaiseDetails('invalidId');
            System.assert(false, 'An exception should have been thrown for invalid ID');
        } catch (Exception e) {
            System.assertNotEquals(null, e.getMessage(), 'Expected exception message not received');
        }
        Test.stopTest();
    }

    // Test the retrieval of raise details by Company ID
    @IsTest
    static void testGetRaiseDetailsFromCompanyId() {
        Account testAccount = [SELECT Id FROM Account WHERE Name='Test Business' LIMIT 1];
        Test.startTest();
        String details = RaiseController.getRaiseDetailsFromCompanyId(testAccount.Id);
        Test.stopTest();

        // Assert to ensure that details are returned
        System.assertNotEquals(null, details, 'Details should not be null');
        System.assert(details.contains('Test Raise'), 'Details should contain the raise name');
    }
    
    // Test the retrieval of raise details with an invalid company ID to simulate an error
    @IsTest
    static void testGetRaiseDetailsFromCompanyIdWithError() {
        Test.startTest();
        try {
            String details = RaiseController.getRaiseDetailsFromCompanyId('invalidId');
            System.assert(false, 'An exception should have been thrown for invalid ID');
        } catch (Exception e) {
            System.assertNotEquals(null, e.getMessage(), 'Expected exception message not received');
        }
        Test.stopTest();
    }

    @IsTest
    static void testGetgetRaiseDetailsForm() {
        Raise__c testRaise = [SELECT Id FROM Raise__c LIMIT 1];

        Test.startTest();
        Map<String,Object>  details = RaiseController.getRaiseDetailsForm(testRaise.Id);
        Test.stopTest();

        // Assert to ensure that details are returned
        System.assertNotEquals(null, details, 'Details should not be null');
    }

    @IsTest
    static void testGetgetRaiseDetailsFormError() {
        Id testRaiseId = 'a3XXX000000cXXXAAI';

        Exception expectedException = null;
        Test.startTest();
        
        try{
            Map<String,Object>  details = RaiseController.getRaiseDetailsForm(testRaiseId);
        }catch(Exception e){
            expectedException = e;
        }
        
        Test.stopTest();

        // Assert to ensure that details are returned
        System.assertNotEquals(null, expectedException, 'expectedException should not be null');
    }

    @IsTest
    static void testGetupdateRaiseDetails() {
        Raise__c testRaise = [SELECT Id FROM Raise__c LIMIT 1];

        Map<String,Object> fieldsToUpdate = new Map<String,Object>();

        fieldsToUpdate.put('companyFullName', 'NewName CompanyName');

        Test.startTest();
        Map<String,Object>  details = RaiseController.updateRaiseDetails(testRaise.Id, fieldsToUpdate);
        Test.stopTest();

        // Assert to ensure that details are returned
        System.assertNotEquals(null, details, 'Details should not be null');
    }

    @IsTest
    static void testGetupdateRaiseDetailsError() {
        Id testRaiseId = 'a3XXX000000cXXXAAI';

        Map<String,Object> fieldsToUpdate = new Map<String,Object>();

        fieldsToUpdate.put('companyFullName', 'NewName CompanyName');
        Exception expectedException = null;
        Test.startTest();

        try{
            Map<String,Object>  details = RaiseController.updateRaiseDetails(testRaiseId, fieldsToUpdate);
        }catch(Exception e){
            expectedException = e;
        }
        Test.stopTest();

        // Assert to ensure that details are returned
        System.assertNotEquals(null, expectedException, 'expectedException should not be null');
    }

    @IsTest
    static void testGetPicklistValues() {
        String objectName = 'Raise__c';
        String fieldName = 'Form_Stage__c';

        Test.startTest();

        List<Map<String, String>>  details = RaiseController.getPicklistValues(objectName, fieldName);

        Test.stopTest();

        // Assert to ensure that details are returned
        System.assertNotEquals(null, details, 'Should not be null');
    }

    @IsTest
    static void testGetPicklistValuesError() {
        String objectName = 'Raise__c';
        String fieldName = 'nonExistentField';

        Exception expectedException = null;
        Test.startTest();
        try{
            List<Map<String, String>>  details = RaiseController.getPicklistValues(objectName, fieldName);
        }catch(Exception e){
            expectedException = e;
        }

        Test.stopTest();

        // Assert to ensure that details are returned
        System.assertNotEquals(null, expectedException, 'Should not be null');
    }

    @isTest
    static void testUserLoggedIn() {
        Test.startTest();
        Boolean isLoggedIn = RaiseController.userLoggedIn();
        Test.stopTest();

        // Perform assertions
        System.assertEquals(true, isLoggedIn, 'User should be logged in');
    }

    @isTest
    static void testUpdateRaiseStatus() {
        Raise__c testRaise = [SELECT Id, Status__c FROM Raise__c LIMIT 1];

        Test.startTest();
        Raise__c updatedRaise = RaiseController.updateRaiseStatus(testRaise.Id, 'Waiting for payment');
        Test.stopTest();

        // Perform assertions
        System.assertNotEquals(null, updatedRaise, 'Updated Raise should not be null');
        System.assertEquals('Waiting for payment', updatedRaise.Status__c, 'Raise status should be updated to Waiting for payment');
    }

    @isTest
    static void testGetRaisePageDetailsRaiseId() {
        // Retrieve the test raise record
        Raise__c testRaise = [SELECT Id FROM Raise__c LIMIT 1];

        // Mock the raiseService.getRaisePageDetailsRaiseId method
        Test.startTest();
        String raiseDetails = RaiseController.getRaisePageDetailsRaiseId(testRaise.Id);
        Test.stopTest();

        // Perform assertions
        System.assertNotEquals(null, raiseDetails, 'Raise details should not be null');
        // Add more assertions based on the expected format and content of raiseDetails
    }

    @IsTest
    static void testGetRaisePageDetailsRaiseIdWithError() {
        Test.startTest();
        try {
            String raiseDetails = RaiseController.getRaisePageDetailsRaiseId('invalidId');
            System.assert(false, 'An exception should have been thrown for invalid ID');
        } catch (Exception e) {
            System.assertNotEquals(null, e.getMessage(), 'Expected exception message not received');
        }
        Test.stopTest();
    }


    public static void testGetRaiseStatuses() {
		Raise__c testRaise = [SELECT Id FROM Raise__c LIMIT 1];
        
        Test.startTest();
        Map<String, Object> result = RaiseController.getRaiseStatuses(testRaise.Id);
        Test.stopTest();

        System.assertEquals('Test Raise', result.get('name'));
        System.assertEquals(true, result.get('paymentReceived'));
        System.assertEquals(true, result.get('contentApproved'));
        System.assertEquals(false, result.get('courseUnlocked'));
        System.assertEquals(false, result.get('learningCompleted'));
    }

    @isTest
    public static void testUnlockRaiseCourse() {
        // Setup test data
        List<Knowledge__kav> knowledgeArticles = new List<Knowledge__kav>{
            new Knowledge__kav(Title = 'Knowledge Article 1', UrlName = 'ka-1'),
            new Knowledge__kav(Title = 'Knowledge Article 2', UrlName = 'ka-2')
        };
        insert knowledgeArticles;
        
        List<Course__c> courses = new List<Course__c>{
            new Course__c(Name = 'Capital Raising 101 Course'),
            new Course__c(Name = 'Course 2')
        };
        insert courses;

        List<Course_article__c> courseArticles = new List<Course_article__c>{
            new Course_article__c(Name = 'Article 1', Knowledge__c = knowledgeArticles[0].Id, Course__c = courses[0].Id),
            new Course_article__c(Name = 'Article 2', Knowledge__c = knowledgeArticles[1].Id, Course__c = courses[1].Id)
        };
        insert courseArticles;

        Raise__c testRaise = [SELECT Id FROM Raise__c LIMIT 1];


        Test.startTest();
        Map<String, Object> result = RaiseController.unlockRaiseCourse(testRaise.Id);
        Test.stopTest();

        System.assertEquals(testRaise.Id, result.get('id'));
        System.assertEquals(true, result.get('courseUnlocked'));
        System.assertEquals(true, result.get('paymentReceived'));
    }

    @isTest
    public static void testCreateLearningForRaise() {
        // Setup test data
        List<Knowledge__kav> knowledgeArticles = new List<Knowledge__kav>{
            new Knowledge__kav(Title = 'Knowledge Article 3', UrlName = 'ka-3'),
            new Knowledge__kav(Title = 'Knowledge Article 4', UrlName = 'ka-4')
        };
        insert knowledgeArticles;
        
        List<Course__c> courses = new List<Course__c>{
            new Course__c(Name = 'Capital Raising 101 Course')
        };
        insert courses;

        List<Course_article__c> courseArticles = new List<Course_article__c>{
            new Course_article__c(Name = 'Article 3', Knowledge__c = knowledgeArticles[0].Id, Course__c = courses[0].Id),
            new Course_article__c(Name = 'Article 4', Knowledge__c = knowledgeArticles[1].Id, Course__c = courses[0].Id)
        };
        insert courseArticles;

		Raise__c testRaise = [SELECT Id FROM Raise__c LIMIT 1];

        Test.startTest();
        Map<String, Object> result = RaiseController.createLearningForRaise(testRaise.Id);
        Test.stopTest();

        System.assertNotEquals(null, result.get('learningData'));
        System.assertNotEquals(null, result.get('raiseData'));
    }

    @isTest
    static void testgetSummaryStatistics() {
        Raise__c testRaise = [SELECT Id FROM Raise__c LIMIT 1];
        EOI__c testEOI = [SELECT Id FROM EOI__c LIMIT 1];

        Test.startTest();
        Map<String,Object> result = RaiseController.getSummaryStatistics(testRaise.Id, testEOI.Id);
        Test.stopTest();

        System.assertNotEquals(null, result, 'Raise record should not be null');
    }

    @isTest
    static void testGetRaiseRecordType() {
        // Query for the test Raise record created in the test setup.
        Raise__c raiseTest = [SELECT Id, RecordType.DeveloperName FROM Raise__c LIMIT 1];
        
        
        // Call the method in a test context.
        Test.startTest();
        String result = RaiseController.getRaiseRecordType(raiseTest.Id);
        Test.stopTest();
        
        // Assert that the returned Raise__c record is not null.
        System.assertNotEquals(null, result, 'Expected a non-null Raise__c record.');
        
        // Assert that the returned record's Id matches the one queried from test setup.
        System.assertEquals('Primary_Raise', result, 'RecordType DeveloperName did not match.');
    }
}