common/force-app/main/default/objects/Account/fields/Related_Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Related Person Account)</relationshipLabel>
    <relationshipName>Accounts6</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/EOI__c.object-meta.xml
<CustomObject>
    <description>This object will be used by Founders, this was part of the MVP project.</description>
    <label>EOI</label>
    <nameField>
        <label>EOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOI&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/EOI__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>This will link to the Ventures Company Account that is related to the EOI</description>
    <inlineHelpText>This field links to the Ventures Company Account that is related to this EOI</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EOI&apos;s</relationshipLabel>
    <relationshipName>EOI_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/EOI_Status__c.field-meta.xml
<CustomField>
    <fullName>EOI_Status__c</fullName>
    <description>This is the Status (Progress) for the EOI record.</description>
    <label>EOI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Published</fullName>
                <default>true</default>
                <label>Not Published</label>
            </value>
            <value>
                <fullName>Submitted to be Published</fullName>
            </value>
            <value>
                <fullName>Publishing</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/EOI__c/fields/Related_Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EOI&apos;s (Related Person Account)</relationshipLabel>
    <relationshipName>EOI_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/EOI_Team_and_Advisors__c/EOI_Team_and_Advisors__c.object-meta.xml
<CustomObject>
    <description>This object will be associated to the EOI Record.</description>
    <label>EOI Team and Advisors</label>
    <nameField>
        <label>Team member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EOI Team and Advisors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/EOI_Team_and_Advisors__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Founder</fullName>
            </value>
            <value>
                <fullName>Management Team</fullName>
            </value>
            <value>
                <fullName>Advisors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/EOI_Team_and_Advisors__c/fields/Member_Role__c.field-meta.xml
<CustomField>
    <fullName>Member_Role__c</fullName>
    <label>Team Role</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/EOI_Team_and_Advisors__c/fields/Team_Member_Description__c.field-meta.xml
<CustomField>
    <fullName>Team_Member_Description__c</fullName>
    <label>Team Member Description</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/EOI_Team_and_Advisors__c/fields/Team_member_Linkedin__c.field-meta.xml
<CustomField>
    <fullName>Team_member_Linkedin__c</fullName>
    <label>Team member Linkedin</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/EOI_Team_and_Advisors__c/fields/Team_Related_EOI__c.field-meta.xml
<CustomField>
    <fullName>Team_Related_EOI__c</fullName>
    <label>Team Related EOI</label>
    <referenceTo>EOI__c</referenceTo>
    <relationshipLabel>EOI Team and Advisors</relationshipLabel>
    <relationshipName>EOI_Team_and_Advisors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/classes/TestDataFactory.cls
@IsTest
public class TestDataFactory {

    public static void testData() {
	User owner = [SELECT Id FROM USER WHERE Name = 'The VentureCrowd Team'];
        
        Id recordIdByName = Schema.SObjectType.Account.getRecordTypeInfosByName().get('VC Business Account').getRecordTypeId();
        List<Account> lstOfAccountForInsert1 = new List<Account>();
        	Account accObj = new Account();
        		accObj.Name = 'Test Venture Person Account';
        		accObj.RecordTypeId = recordIdByName;
        		accObj.OwnerId = owner.Id;
        	lstOfAccountForInsert1.add(accObj);
        Database.SaveResult[] saveResults1 ;
        Test.startTest();
        System.runAs(owner){
           saveResults1 = Database.insert(lstOfAccountForInsert1,false);
        }
        List<EOI__c> lstOfEOIForInsert = new List<EOI__c>();
        EOI__c eoiObj = new EOI__c();
        	eoiObj.Name = 'Test updateEoi Method';
        	eoiObj.Account__c =  saveResults1[0].getId();
        	eoiObj.EOI_Status__c = 'Not Published';
        	eoiObj.Related_Person_Account__c = saveResults1[0].getId();
        lstOfEOIForInsert.add(eoiObj);
        
        Database.SaveResult[] saveResults2 ;
        System.runAs(owner){
           saveResults2 = Database.insert(lstOfEOIForInsert,false);
        }
        
        
        List<EOI_team_and_advisors__c> lstOfEoiTeamAndAdviser = new List<EOI_team_and_advisors__c>();
        	EOI_team_and_advisors__c eoiTeamAndAdviser = new EOI_team_and_advisors__c();
    			eoiTeamAndAdviser.put('Name','John Steven');
        		eoiTeamAndAdviser.put('Category__c','Founder');
        		eoiTeamAndAdviser.put('Member_Role__c','Founder & CEO');
        		eoiTeamAndAdviser.put('Team_Member_Description__c','john is an Accredited Practicing Dietitian');
        		eoiTeamAndAdviser.put('Team_member_Linkedin__c','https://www.linkedin.com/');
        		eoiTeamAndAdviser.put('Team_Related_EOI__c',saveResults2[0].getId());
        lstOfEoiTeamAndAdviser.add(eoiTeamAndAdviser);
        Database.SaveResult[] saveResults3 ;
       
        System.runAs(owner){
           saveResults3 = Database.insert(lstOfEoiTeamAndAdviser,false);
        }
        Test.stopTest();
    }
    
    public static void dataForContentDownloadURL(){
        User owner = [SELECT Id FROM USER WHERE Name = 'The VentureCrowd Team'];
        
        Id recordIdByName = Schema.SObjectType.Account.getRecordTypeInfosByName().get('VC Business Account').getRecordTypeId();
        List<Account> lstOfAccountForInsert1 = new List<Account>();
        	Account accObj = new Account();
        		accObj.Name = 'Test Venture Person Account';
        		accObj.RecordTypeId = recordIdByName;
        		accObj.OwnerId = owner.Id;
        	lstOfAccountForInsert1.add(accObj);
        Database.SaveResult[] saveResults1 ;
        System.runAs(owner){
           saveResults1 = Database.insert(lstOfAccountForInsert1,false);
        }
        
        
        List<EOI__c> lstOfEOIForInsert = new List<EOI__c>();
        EOI__c eoiObj = new EOI__c();
        	eoiObj.Name = 'Test Eoi record';
        	eoiObj.Account__c = saveResults1[0].getId();
        	eoiObj.EOI_Status__c = 'Not Published';
        	eoiObj.Related_Person_Account__c = saveResults1[0].getId();
        lstOfEOIForInsert.add(eoiObj);
        
        Database.SaveResult[] saveResults2 ;
        System.runAs(owner){
           saveResults2 = Database.insert(lstOfEOIForInsert,false);
        }
    }
}