common/force-app/main/default/objects/Account/fields/Related_Product__c.field-meta.xml
<CustomField>
    <fullName>Related_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <label>Investment</label>
    <nameField>
        <displayFormat>IN-{00000000}</displayFormat>
        <label>Investment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Investment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investments</relationshipLabel>
    <relationshipName>Investments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Current_Holding_Value__c.field-meta.xml
<CustomField>
    <fullName>Current_Holding_Value__c</fullName>
    <formula>&quot;$&quot;
+
IF(LEN(TEXT(MFLOOR(Opportunity_Product__r.Current_Investment_Value__c)))&gt;3,
    IF(LEN(TEXT(MFLOOR(Opportunity_Product__r.Current_Investment_Value__c)))&gt;6,
        LEFT(TEXT(MFLOOR(Opportunity_Product__r.Current_Investment_Value__c)),LEN(TEXT(MFLOOR(Opportunity_Product__r.Current_Investment_Value__c)))-6)+&quot;,&quot;+LEFT(RIGHT(TEXT(MFLOOR(Opportunity_Product__r.Current_Investment_Value__c)),6),3)+&quot;,&quot;+RIGHT(TEXT(MFLOOR(Opportunity_Product__r.Current_Investment_Value__c)),3),
        LEFT(TEXT(MFLOOR(Opportunity_Product__r.Current_Investment_Value__c)),LEN(TEXT(MFLOOR(Opportunity_Product__r.Current_Investment_Value__c)))-3)+&quot;,&quot;+RIGHT(TEXT(MFLOOR(Opportunity_Product__r.Current_Investment_Value__c)),3)),
TEXT(MFLOOR(Opportunity_Product__r.Current_Investment_Value__c)))
+
IF(MOD(Opportunity_Product__r.Current_Investment_Value__c , 1) = 0,&apos;.00&apos;,TEXT(MOD(Opportunity_Product__r.Current_Investment_Value__c , 1)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Holding Value</label>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Date_Refund_Requested__c.field-meta.xml
<CustomField>
    <fullName>Date_Refund_Requested__c</fullName>
    <description>This field is updated in the LWC pipoInvestmentSupport</description>
    <inlineHelpText>Date requested for the investor in the portal</inlineHelpText>
    <label>Date Refund Requested</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Funds_Received_in_Bank__c.field-meta.xml
<CustomField>
    <fullName>Funds_Received_in_Bank__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Funds Received in Bank</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Investment_Date__c.field-meta.xml
<CustomField>
    <fullName>Investment_Date__c</fullName>
    <description>&quot;Close Date&quot; of opportunity</description>
    <label>Investment Date</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Investment_Opp_ID__c.field-meta.xml
<CustomField>
    <fullName>Investment_Opp_ID__c</fullName>
    <description>The Opportunity ID</description>
    <label>Investment ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Investment_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Investment_Product_Name__c</fullName>
    <label>Investment Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Investment_Stages__c.field-meta.xml
<CustomField>
    <fullName>Investment_Stages__c</fullName>
    <label>Investment Stages</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closing</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Investment_Status__c.field-meta.xml
<CustomField>
    <fullName>Investment_Status__c</fullName>
    <formula>IF( Process_Fund_Disbursement__c = FALSE, &apos;Active&apos;, &apos;Pending&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Investment Status</label>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Investments1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Reason_Refund__c.field-meta.xml
<CustomField>
    <fullName>Reason_Refund__c</fullName>
    <description>This field is used to track the reason of the refund</description>
    <inlineHelpText>Please specify the customer reason for the refund</inlineHelpText>
    <label>Reason Refund</label>
    <type>TextArea</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Refund_Requested__c.field-meta.xml
<CustomField>
    <fullName>Refund_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Refund Requested</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Related_product__c.field-meta.xml
<CustomField>
    <fullName>Related_product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related product</description>
    <label>Related product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Investments</relationshipLabel>
    <relationshipName>Investments</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Securities_Held__c.field-meta.xml
<CustomField>
    <fullName>Securities_Held__c</fullName>
    <description>This is a FE fields created to remove decimal places when the values is 0000</description>
    <formula>IF(LEN(TEXT(MFLOOR(Purchased_Shares__c)))&gt;3,
    IF(LEN(TEXT(MFLOOR(Purchased_Shares__c)))&gt;6,
        LEFT(TEXT(MFLOOR(Purchased_Shares__c)),LEN(TEXT(MFLOOR(Purchased_Shares__c)))-6)+&quot;,&quot;+LEFT(RIGHT(TEXT(MFLOOR(Purchased_Shares__c)),6),3)+&quot;,&quot;+RIGHT(TEXT(MFLOOR(Purchased_Shares__c)),3),
        LEFT(TEXT(MFLOOR(Purchased_Shares__c)),LEN(TEXT(MFLOOR(Purchased_Shares__c)))-3)+&quot;,&quot;+RIGHT(TEXT(MFLOOR(Purchased_Shares__c)),3)),
TEXT(MFLOOR(Purchased_Shares__c)))
+
IF(MOD(Purchased_Shares__c , 1) = 0,&apos;.00&apos;,TEXT(MOD(Purchased_Shares__c , 1)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Securities Held</label>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Investment_Stages</valueSetName>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Term_Expiry__c.field-meta.xml
<CustomField>
    <fullName>Term_Expiry__c</fullName>
    <formula>TEXT(Opportunity__r.Invested_Product_ADMIN_FIELD__r.Term_Expiry__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Term Expiry from Product</inlineHelpText>
    <label>Term Expiry</label>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Funds_received_in_Bank__c.field-meta.xml
<CustomField>
    <fullName>Funds_received_in_Bank__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>To be updated by Finance Department</inlineHelpText>
    <label>Funds Received in Bank</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Refund_Requested__c.field-meta.xml
<CustomField>
    <fullName>Refund_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Refund Requested</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Opportunity/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VC Product</fullName>
                <label>VC Product - Wholesale</label>
            </value>
            <value>
                <fullName>Property Product</fullName>
            </value>
            <value>
                <fullName>CSF Product</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>PSP Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ventures - Pre-Seed</fullName>
            </value>
            <value>
                <fullName>Ventures - Seed</fullName>
            </value>
            <value>
                <fullName>Ventures - Series A</fullName>
            </value>
            <value>
                <fullName>Ventures - Series B</fullName>
            </value>
            <value>
                <fullName>Ventures - Series C</fullName>
            </value>
            <value>
                <fullName>Ventures - Bridging Round</fullName>
            </value>
            <value>
                <fullName>Ventures - Pre-IPO</fullName>
            </value>
            <value>
                <fullName>Ventures - IPO</fullName>
            </value>
            <value>
                <fullName>Property - Equity</fullName>
            </value>
            <value>
                <fullName>Property - Preference Equity</fullName>
            </value>
            <value>
                <fullName>Property - Debt</fullName>
            </value>
            <value>
                <fullName>Fund - Multi Stage as per IM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Term_Expiry__c.field-meta.xml
<CustomField>
    <fullName>Term_Expiry__c</fullName>
    <defaultValue>(&quot;Undefined&quot;)</defaultValue>
    <label>Term/Expiry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3 Months</fullName>
            </value>
            <value>
                <fullName>6 Months</fullName>
            </value>
            <value>
                <fullName>8 Months</fullName>
            </value>
            <value>
                <fullName>12 Months</fullName>
            </value>
            <value>
                <fullName>18 Months</fullName>
            </value>
            <value>
                <fullName>24 Months</fullName>
            </value>
            <value>
                <fullName>36 Months</fullName>
            </value>
            <value>
                <fullName>Undefined</fullName>
            </value>
            <value>
                <fullName>3 Years</fullName>
                <isActive>false</isActive>
                <label>3 Years</label>
            </value>
            <value>
                <fullName>4 Years</fullName>
                <isActive>false</isActive>
                <label>4 Years</label>
            </value>
            <value>
                <fullName>5 Years</fullName>
                <isActive>false</isActive>
                <label>5 Years</label>
            </value>
            <value>
                <fullName>9 Months</fullName>
                <isActive>false</isActive>
                <label>9 Months</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VC Product</fullName>
            </value>
            <value>
                <fullName>Property Product</fullName>
            </value>
            <value>
                <fullName>CSF Product</fullName>
            </value>
            <value>
                <fullName>CSF Nominee</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>PSP Product</fullName>
            </value>
            <value>
                <fullName>Retail IPO</fullName>
            </value>
            <value>
                <fullName>Retail MIS</fullName>
            </value>
            <value>
                <fullName>Vest</fullName>
            </value>
            <value>
                <fullName>CIF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/globalValueSets/Investment_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Why Appt Set Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Decision Appt Set Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Closing Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Application Received</fullName>
    </customValue>
    <customValue>
        <fullName>Receipt Issued</fullName>
    </customValue>
    <customValue>
        <fullName>Closed Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Closed Won</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
        <isActive>false</isActive>
        <label>Closed</label>
    </customValue>
    <customValue>
        <fullName>Closing</fullName>
        <isActive>false</isActive>
        <label>Closing</label>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
        <isActive>false</isActive>
        <label>Active</label>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
        <isActive>false</isActive>
        <label>Pending</label>
    </customValue>
    <description>Stages of an Investment</description>
    <masterLabel>Investment Stages</masterLabel>
</GlobalValueSet>

common/force-app/main/default/classes/InvestmentFactory.cls
public inherited sharing class InvestmentFactory implements IInvestmentFactory  {
    /**
     * Retrieves a list of Investment__c records for a given accountId.
     * The records contain information such as Stage, Opportunity, Amount, and Product Name.
     * 
     * @param accountId The Id of the account for which investments are being retrieved.
     * @return A List of Investment__c records, or null if no investments are found.
     */
    public List<Investment__c> getInvestments (List<Id> accountId, Integer limitSize, Integer offsetValue) {
            // Fetch Investments
            if (accountId.isEmpty()) {
                return new List<Investment__c>();
            }
            List<Investment__c> investment = [SELECT Id, Account__c, Related_Product__c, Stage__c, Opportunity__c, Investment_Amount__c, Amount__c, Investment_Product_Name__c, Investment_Status__c, Investment_Stages__c, Current_Holding_Value__c, Closed_Date__c,Investment_Date__c
                FROM Investment__c WHERE Account__c =:accountId AND (Stage__c = 'Closed Won') AND (Investment_Stages__c = 'Active' OR Investment_Stages__c = null OR Investment_Stages__c = 'Closing') ORDER BY Investment_Date__c DESC LIMIT :limitSize OFFSET :offsetValue];
            Logger.logMessage('InvestmentApp', 'InvestmentFactory', 'getInvestments', 'Successfully retrieved full investment record for accountId: ' + accountId);
            return investment;
    }

    /**
     * Retrieves a list of Investment Ids records for a given accountId.
     * 
         * @param accountId The Id of the account for which investments are being retrieved.
         * @return A List of Investment__c Ids
     */
    public List<Investment__c> getInvestmentsIds (Id accountId) {
        // Fetch Investments
        List<Investment__c> investment = [SELECT Id FROM Investment__c WHERE Account__c =:accountId];
        Logger.logMessage('InvestmentApp', 'InvestmentFactory', 'getInvestments', 'Successfully retrieved full investment record for accountId: ' + accountId);
        return investment;
    }

    /**
     * Retrieves a list of Investment__c records for a given investment Id.
     * 
     * @param investmentId The Id of the account for which investments are being retrieved.
     * @return A List of Investment__c records, or null if no investments are found.
     */
    public List<Investment__c> getInvestmentDetails (Id investmentId) {
        // Fetch Investments
        List<Investment__c> investment = [SELECT Amount__c, Investment_Amount__c, Investment_Opp_ID__c, Current_Holding_Value__c, Investment_Date__c, Term_Expiry__c, Securities_Held__c, Related_Product__c, Funds_Received_in_Bank__c, Reason_Refund__c, Refund_Requested__c, Date_Refund_Requested__c  FROM Investment__c WHERE Id =:investmentId];
        Logger.logMessage('InvestmentApp', 'InvestmentFactory', 'getInvestments', 'Successfully retrieved full investment record for investmentId: ' + investmentId);
        return investment;
    }

    /**
     * Retrieves investment records for a given account ID that are in the 
     * 'Closed Won' stage and either 'Active' or have no defined investment stage.
     * 
     * @param accountId The ID of the account for which investments are retrieved.
     * @return A list of Investment__c records matching the criteria.
     */
    public List<Investment__c> getInvestmentSpotlightData (Id accountId) {
        // Fetch Investments
        List<Investment__c> investment = [SELECT Amount__c, Investment_Amount__c, Investment_Status__c, Current_Holding_Value__c FROM Investment__c
        WHERE Account__c =:accountId AND Stage__c = 'Closed Won' AND (Investment_Stages__c = 'Active' OR Investment_Stages__c = null OR Investment_Stages__c = 'Closing')];
        Logger.logMessage('InvestmentApp', 'InvestmentFactory', 'getInvestmentSpotlightData', 'Successfully retrieved full investment record for accountId: ' + accountId);
        return investment;
    }

    /**
     * Retrieves pending and closed investment records for a given list of account IDs.
     * This method filters investments that are linked to an opportunity and have a positive amount.
     * 
     * @param accountId A list of account IDs for which investments are retrieved.
     * @return A list of Investment__c records that are either in 'Closed Won' (with stage 'Closed') 
     *         or in 'Application Received' stage.
     */
    public List<Investment__c> getPendingAndClosedInvestments (List<Id> accountId) {
        // Fetch Investments
        if (accountId.isEmpty()) {
            return new List<Investment__c>();
        }
        List<Investment__c> investment = [
            SELECT Id, Related_Product__c, Investment_Product_Name__c, Account__c, Amount__c, Investment_Amount__c, Investment_Stages__c, Stage__c 
            FROM Investment__c 
            WHERE Account__c = :accountId 
            AND Opportunity__c != null 
            AND Amount__c > 0 
            AND ( 
                (Stage__c = 'Closed Won' AND Investment_Stages__c = 'Closed') 
                OR Stage__c IN ('Application Received', 'Receipt Issued')
            )
        ];
        Logger.logMessage('InvestmentApp', 'InvestmentFactory', 'getInvestmentSpotlightData', 'Successfully retrieved full investment record for accountId: ' + accountId);
        return investment;
        }

    /**
     * Determines whether the CSF Product banner should be displayed for a given account.
     * The banner is displayed if there is at least one investment related to a CSF Product.
     * 
     * @param accountId The ID of the account for which the CSF banner check is performed.
     * @return Boolean value indicating whether the CSF banner should be shown.
     */
    public Boolean showCSFBanner (Id accountId) {
        Integer investments = [SELECT Count() FROM Investment__c WHERE Related_product__r.Type__c = 'CSF Product' AND Stage__c = 'Closed Won' AND Account__c =: accountId];
        return investments > 0;
    }   
}