common/force-app/main/default/objects/Account/fields/Third_Party_Authorised__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Authorised__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Third Party Authorised</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications (Contact)</relationshipLabel>
    <relationshipName>Applications4</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Application__c/fields/TPA_End_date__c.field-meta.xml
<CustomField>
    <fullName>TPA_End_date__c</fullName>
    <label>TPA End date</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/classes/BAT_thirdpartyAuthorizationCheck.cls
public without sharing class BAT_thirdpartyAuthorizationCheck implements Database.Batchable<Sobject>,Schedulable{
    public Database.QueryLocator start(Database.BatchableContext BC){
        Id apprecordtypeId = Schema.SObjectType.Application__c.getRecordTypeInfosByName().get('Third party Authority').getRecordTypeId();
        string query = 'SELECT Id,Contact__r.AccountId FROM Application__c WHERE TPA_End_date__c < Today AND Contact__r.Account.Third_Party_Authorised__c = TRUE AND recordtypeId =:apprecordtypeId';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<Application__c> scope){
        Map<Id,Account> accMap = new Map<Id,Account>();
        for(Application__c m : scope){
            Account acc = new Account();
            acc.Id = m.Contact__r.AccountId;
            acc.Third_Party_Authorised__c = false;
            accMap.put(acc.Id,acc);
        }
        update accMap.values();
    }
    public void finish(Database.BatchableContext BC){

    }
    public void execute(SchedulableContext sc){
        Database.executeBatch(this);
    }
}