common/force-app/main/default/objects/Account/fields/Third_Party_Authorised__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Authorised__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Third Party Authorised</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Application__c/fields/TPA_End_date__c.field-meta.xml
<CustomField>
    <fullName>TPA_End_date__c</fullName>
    <label>TPA End date</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Contact/fields/EIC_Property__c.field-meta.xml
<CustomField>
    <fullName>EIC_Property__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EIC Property</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/classes/BAT_thirdpartyAuthorizationCheckTest.cls
@istest
public with sharing class BAT_thirdpartyAuthorizationCheckTest {
    @istest
    static void testmethod1(){
        Id personaccId  = [SELECT Id,recordtype.Name,SobjectType FROM recordtype WHERE Name ='VC Person Account'].Id;
        Id platinumpartner  = [SELECT Id,recordtype.Name,SobjectType FROM recordtype WHERE Name ='Platinum Partner'].Id;
        Account acc = new Account();
        acc.LastName = 'Test Acount';
        acc.RecordTypeId = personaccId;
        acc.Third_Party_Authorised__c = TRUE;
        insert acc;
        contact con = [SELECT ID FROM CONTACT WHERE AccountId = :acc.Id];
        con.EIC_Property__c = true;
        update con;
        Id apprecordtypeId = Schema.SObjectType.Application__c.getRecordTypeInfosByName().get('Third party Authority').getRecordTypeId();
        Application__c a = new Application__c();
        a.RecordTypeId = apprecordtypeId;
        a.Account__c = acc.Id;
        a.TPA_End_date__c = system.Today().adddays(-1);
        insert a;
        Database.executeBatch(new BAT_thirdpartyAuthorizationCheck());
        System.schedule('test', '0 00 05 ? * 2', new BAT_thirdpartyAuthorizationCheck());
    }
}