common/force-app/main/default/objects/Account/fields/Total_Investment__c.field-meta.xml
<CustomField>
    <fullName>Total_Investment__c</fullName>
    <description>To Calculate Total Investment</description>
    <label>Total Investment</label>
    <summarizedField>Investment__c.Investment_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Investment__c.Process_Fund_Disbursement__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Investment__c.Stage__c</field>
        <operation>equals</operation>
        <value>Closed Won</value>
    </summaryFilterItems>
    <summaryForeignKey>Investment__c.Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <label>Investment</label>
    <nameField>
        <displayFormat>IN-{00000000}</displayFormat>
        <label>Investment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Investment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investments</relationshipLabel>
    <relationshipName>Investments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Funds_Received__c.field-meta.xml
<CustomField>
    <fullName>Funds_Received__c</fullName>
    <defaultValue>false</defaultValue>
    <description>&quot;Funds Received in Bank&quot; from opportunity</description>
    <label>Funds Received</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Investment_Date__c.field-meta.xml
<CustomField>
    <fullName>Investment_Date__c</fullName>
    <description>&quot;Close Date&quot; of opportunity</description>
    <label>Investment Date</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Investment__c/fields/Total_Investment__c.field-meta.xml
<CustomField>
    <fullName>Total_Investment__c</fullName>
    <inlineHelpText>Sum of &quot;Amount&quot; for opportinities in &quot;Closed Won&quot; state</inlineHelpText>
    <label>Total Investment</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

common/force-app/main/default/classes/PortFolioDetailController.cls
public class PortFolioDetailController {
	 @AuraEnabled
    public static MyPortfolio initlializeMyportfolio(){
       List<user> users= [SELECT Id, Name,AccountId, profile.Name,SmallPhotourl,FullPhotoUrl FROM User WHERE Id =: Userinfo.getUserId()];
        List<Account> accList=[Select Id,Name,Total_Investment__c,(Select Id,Total_Investment__c,Investment_Date__c,Investment_Amount__c,Funds_Received__c,Account__r.Name from Investments__r) from Account where Id=:users[0].AccountId];
        return new MyPortfolio(users.size()>0?users[0]:null,accList.size()>0?accList[0]:null);
    }
    
    public class MyPortfolio{
        @AuraEnabled
        public User currentUser;
         @AuraEnabled
        public Account currentAccount;
        
        public MyPortfolio( User currentUser,Account currentAccount){
         this.currentUser=currentUser;
         this.currentAccount=currentAccount;
        }
    }
}