common/force-app/main/default/objects/Raise_Team_and_Advisors__c/Raise_Team_and_Advisors__c.object-meta.xml
<CustomObject>
    <label>Raise Team and Advisors</label>
    <nameField>
        <label>Raise Team and Advisors Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Raise Team and Advisors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Raise_Team_and_Advisors__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Founder</fullName>
            </value>
            <value>
                <fullName>Management Team</fullName>
            </value>
            <value>
                <fullName>Advisors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

common/force-app/main/default/objects/Raise_Team_and_Advisors__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Raise_Team_and_Advisors__c/fields/Picture__c.field-meta.xml
<CustomField>
    <fullName>Picture__c</fullName>
    <label>Picture</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/Raise_Team_and_Advisors__c/fields/Related_Raise__c.field-meta.xml
<CustomField>
    <fullName>Related_Raise__c</fullName>
    <label>Related Raise</label>
    <referenceTo>Raise__c</referenceTo>
    <relationshipLabel>Raise Team and Advisors</relationshipLabel>
    <relationshipName>Raise_Team_and_Advisors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

common/force-app/main/default/objects/Raise_Team_and_Advisors__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/classes/RaiseTeamFactory.cls
public class RaiseTeamFactory implements IRaiseTeamFactory {
    public List<Raise_Team_and_Advisors__c> getTeamMembersByRaiseId(Id raiseId, String category) {
        try {
            List<Raise_Team_and_Advisors__c> teamMembers = [
                SELECT Id, Name, Category__c, Picture__c, Description__c, LinkedIn__c, Role__c, Related_Raise__c
                FROM Raise_Team_and_Advisors__c
                WHERE Related_Raise__c = :raiseId AND Category__c = :category
            ];
            Logger.logMessage('RaiseApp', 'RaiseTeamFactory', 'getTeamMembersByRaiseId', 'Successfully retrieved team members for raiseId: ' + raiseId);
            return teamMembers;
        } catch (Exception e) {
            Logger.logError('RaiseApp', 'RaiseTeamFactory', 'getTeamMembersByRaiseId', raiseId, null, null, null, e, 'Failed to retrieve team members for raiseId: ' + raiseId);
            throw new AuraHandledException(e.getMessage());
        }
    }

    public Raise_Team_and_Advisors__c createTeamMember(Id raiseId, String name, String category, String picture, String description, String linkedIn, String role) {
            Raise_Team_and_Advisors__c newTeamMember = new Raise_Team_and_Advisors__c();
            newTeamMember.Related_Raise__c = raiseId;
            newTeamMember.Name = name;
            newTeamMember.Category__c = category;
            newTeamMember.Picture__c = picture;
            newTeamMember.Description__c = description;
            newTeamMember.LinkedIn__c = linkedIn;
            newTeamMember.Role__c = role;

            insert newTeamMember;

            Logger.logMessage('RaiseApp', 'RaiseTeamFactory', 'createTeamMember', 'Successfully created team member for raiseId: ' + raiseId);
            return newTeamMember;

    }

    public void deleteTeamMember(Id teamMemberId) {
        try {
            Raise_Team_and_Advisors__c teamMember = [SELECT Id FROM Raise_Team_and_Advisors__c WHERE Id = :teamMemberId LIMIT 1];
            
            if(teamMember != null){
            	delete teamMember;    
                Logger.logMessage('RaiseApp', 'RaiseTeamFactory', 'deleteTeamMember', 'Successfully deleted team member with id: ' + teamMemberId);
            }else{
                Logger.logMessage('RaiseApp', 'RaiseTeamFactory', 'deleteTeamMember', 'Team member not found with id: ' + teamMemberId);
            }
        } catch (Exception e) {
            Logger.logError('RaiseApp', 'RaiseTeamFactory', 'deleteTeamMember', teamMemberId, null, null, null, e, 'Failed to delete team member with id: ' + teamMemberId);
            throw new AuraHandledException('Failed to delete team member with id: ' + teamMemberId);
        }
    }

    public Raise_Team_and_Advisors__c editTeamMember(Id teamMemberId, String name, String picture, String description, String linkedIn, String role) {
        try {
            Raise_Team_and_Advisors__c existingTeamMember = [SELECT Id, Name, Category__c, Picture__c, Description__c, LinkedIn__c, Role__c FROM Raise_Team_and_Advisors__c WHERE Id = :teamMemberId LIMIT 1];
            existingTeamMember.Name = name;
            existingTeamMember.Picture__c = picture;
            existingTeamMember.Description__c = description;
            existingTeamMember.LinkedIn__c = linkedIn;
            existingTeamMember.Role__c = role;

            update existingTeamMember;

            Logger.logMessage('RaiseApp', 'RaiseTeamFactory', 'editTeamMember', 'Successfully edited team member with id: ' + teamMemberId);
            return existingTeamMember;
        } catch (Exception e) {
            Logger.logError('RaiseApp', 'RaiseTeamFactory', 'editTeamMember', teamMemberId, null, null, null, e, 'Failed to edit team member with id: ' + teamMemberId);
            throw new AuraHandledException(e.getMessage());
        }
    }

    public Raise_Team_and_Advisors__c getTeamMemberById(Id teamMemberId) {
        try {
            Raise_Team_and_Advisors__c teamMember = [
                SELECT Id, Name, Category__c, Picture__c, Description__c, LinkedIn__c, Role__c
                FROM Raise_Team_and_Advisors__c
                WHERE Id = :teamMemberId
                LIMIT 1
            ];

            Logger.logMessage('RaiseApp', 'RaiseTeamFactory', 'getTeamMemberById', 'Successfully retrieved team member details for Id: ' + teamMemberId);
            return teamMember;
        } catch (Exception e) {
            Logger.logError('RaiseApp', 'RaiseTeamFactory', 'getTeamMemberById', teamMemberId, null, null, null, e, 'Failed to retrieve team member details for Id: ' + teamMemberId);
            throw new AuraHandledException(e.getMessage());
        }
    }
}