common/force-app/main/default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <label>Comment</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Product2/fields/Offer_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Offer_Close_Date__c</fullName>
    <inlineHelpText>The target date for capital raise to be complete</inlineHelpText>
    <label>Offer Close Date</label>
    <type>DateTime</type>
</CustomField>

common/force-app/main/default/objects/Product2/fields/Offer_Launch_Date__c.field-meta.xml
<CustomField>
    <fullName>Offer_Launch_Date__c</fullName>
    <description>The date that Capital Raising launched the offer to market</description>
    <label>Offer Launch Date</label>
    <type>DateTime</type>
</CustomField>

common/force-app/main/default/classes/CommentsTestClass.cls
@isTest 
private class CommentsTestClass { 
    @isTest
     static void testCommentCreation() {
        
         Product2 prdt = new Product2();
        prdt.Name = 'Test Prod';
        prdt.Offer_Launch_Date__c = system.now();
        prdt.Offer_Close_Date__c = system.now();
        insert prdt;
        Comment__c commentObj = Test_DataFactory.prepareComment(false, prdt.Id); 
        Test.startTest();
        commentsClass.createComment(commentObj, prdt.Id);
        commentObj.Approved__c = true;
         update commentObj;
         commentsClass.retriveComments(prdt.Id);
         commentsClass.retriveNextThreeComments(1, prdt.Id);
        Test.stopTest();       
    } 
}