common/force-app/main/default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <label>Comment</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/Comment__c/fields/Answer_comments__c.field-meta.xml
<CustomField>
    <fullName>Answer_comments__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Comment Responded By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Comments1</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Comment__c/fields/Commented_By_Name__c.field-meta.xml
<CustomField>
    <fullName>Commented_By_Name__c</fullName>
    <formula>Answer_comments__r.FirstName    + &apos; &apos; +  Answer_comments__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Commented Responded By Name</label>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Comment__c/fields/Commented_By_Name_Investor__c.field-meta.xml
<CustomField>
    <fullName>Commented_By_Name_Investor__c</fullName>
    <formula>Post_Comments__r.FirstName + &quot; &quot; + Post_Comments__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Commented By Name</label>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/Comment__c/fields/comments__c.field-meta.xml
<CustomField>
    <fullName>comments__c</fullName>
    <label>Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/Comment__c/fields/Post_Comments__c.field-meta.xml
<CustomField>
    <fullName>Post_Comments__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commented By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Comment__c/fields/Posted_Date__c.field-meta.xml
<CustomField>
    <fullName>Posted_Date__c</fullName>
    <label>Comment Posted Date</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/objects/Comment__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

common/force-app/main/default/objects/Comment__c/fields/Reponse_Date__c.field-meta.xml
<CustomField>
    <fullName>Reponse_Date__c</fullName>
    <label>Responded Date</label>
    <type>Date</type>
</CustomField>

common/force-app/main/default/classes/commentsClass.cls
/**

**/
public without sharing class commentsClass {
    @Auraenabled
     public static string createComment(Comment__c comObj,String productId)
     {
         if(productId != '' && productId != null) {
             comObj.Product__c = productId;
         }         
         upsert comObj;
         return comObj.Id;        
     }
 @auraenabled
     public static list<Comment__c> retriveComments(String productId){
         return [select id,Name,comments__c,Response__c,Approved__c,Commented_By_Name__c,Commented_By_Name_Investor__c,
         Post_Comments__r.Name,Post_Comments__r.UserRole.Name,Post_Comments__r.FullPhotoUrl,
         Answer_comments__r.Name,Answer_comments__r.UserRole.Name,Answer_comments__r.Title,Answer_comments__r.FullPhotoUrl,
         CreatedDate,Posted_Date__c,Reponse_Date__c FROM Comment__c where Approved__c=True AND Product__c=:productId Order By  createdDate DESC LIMIT 3];
     }
    
     @Auraenabled
     public static list<Comment__c> retriveNextThreeComments(Integer nextLimit,String productId){
         return [select id,Name,comments__c,Response__c,Approved__c,Commented_By_Name__c,Commented_By_Name_Investor__c,
         Post_Comments__r.Name,Post_Comments__r.UserRole.Name,Post_Comments__r.FullPhotoUrl,
         Answer_comments__r.Name,Answer_comments__r.UserRole.Name,Answer_comments__r.Title,Answer_comments__r.FullPhotoUrl,
         CreatedDate,Posted_Date__c,Reponse_Date__c FROM Comment__c where Approved__c=True AND Product__c=:productId Order By createdDate DESC LIMIT : nextLimit];
     }

 }