common/force-app/main/default/objects/News_List_Page__c/News_List_Page__c.object-meta.xml
<CustomObject>
    <label>News List Page</label>
    <nameField>
        <displayFormat>LP-{00000}</displayFormat>
        <label>ListPage Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>News List Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/News_List_Page__c/fields/Likes_Number__c.field-meta.xml
<CustomField>
    <fullName>Likes_Number__c</fullName>
    <label>Likes Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Navigation_url__c.field-meta.xml
<CustomField>
    <fullName>Navigation_url__c</fullName>
    <label>Navigation url</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/News_Category__c.field-meta.xml
<CustomField>
    <fullName>News_Category__c</fullName>
    <label>News Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/News_Descriptions__c.field-meta.xml
<CustomField>
    <fullName>News_Descriptions__c</fullName>
    <label>News Descriptions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/News_Label__c.field-meta.xml
<CustomField>
    <fullName>News_Label__c</fullName>
    <label>News Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Newsbg_Url__c.field-meta.xml
<CustomField>
    <fullName>Newsbg_Url__c</fullName>
    <label>Newsbg Url</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/src_url__c.field-meta.xml
<CustomField>
    <fullName>src_url__c</fullName>
    <description>Source URL</description>
    <label>src url</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Tagged_category__c.field-meta.xml
<CustomField>
    <fullName>Tagged_category__c</fullName>
    <description>This is the URL for tagged category on the top corner</description>
    <inlineHelpText>This is the URL for tagged category on the top corner</inlineHelpText>
    <label>Tagged category</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/classes/NewsCategoryControllerTest.cls
@isTest
public class NewsCategoryControllerTest {

    @isTest
    public static void newsBlogTestMethod(){
        News_List_Page__c nlp = new News_List_Page__c();
        nlp.News_Label__c = 'News Label1';
        nlp.Tagged_category__c = 'Tagged Catg1';
        nlp.Date__c = system.today();
        nlp.News_Category__c = 'News Catg1';
        nlp.News_Descriptions__c = 'test desc';
        nlp.Likes_Number__c = 2;
        nlp.Newsbg_Url__c = 'https://www.venturecrowd.com.au';
        nlp.src_url__c = 'https://www.venturecrowd.com.au';
        nlp.Navigation_url__c = 'https://www.venturecrowd.com.au'; 
        Database.SaveResult newsINs = database.insert(nlp,false);
        System.assertEquals(True, newsINs.isSuccess());   
		PageReference pageRef=Page.VC_CF_News_category;
       	Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('category','News Catg1');
        NewsCategoryController nc = new NewsCategoryController();
    }
}