common/force-app/main/default/objects/News_List_Page__c/News_List_Page__c.object-meta.xml
<CustomObject>
    <label>News List Page</label>
    <nameField>
        <displayFormat>LP-{00000}</displayFormat>
        <label>ListPage Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>News List Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/News_List_Page__c/fields/Archive__c.field-meta.xml
<CustomField>
    <fullName>Archive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean flag to identify if this blog will display under Archive or not.</description>
    <inlineHelpText>Boolean flag to identify if this blog will display under Archive or not.</inlineHelpText>
    <label>Archive</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Blog_Sequesnce__c.field-meta.xml
<CustomField>
    <fullName>Blog_Sequesnce__c</fullName>
    <description>This field is useful for sorting after date, for example, if more than one blog post on the same day,  this is the second filter that gives clients the ability to show blogs in the order they want. sorting should be in descending. This field also determines next blog post</description>
    <inlineHelpText>Blog  sequence number for sorting in descending</inlineHelpText>
    <label>Blog Sequesnce #</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Navigation_url__c.field-meta.xml
<CustomField>
    <fullName>Navigation_url__c</fullName>
    <label>Navigation url</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/News_Label__c.field-meta.xml
<CustomField>
    <fullName>News_Label__c</fullName>
    <label>News Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Publish_On_Community_Site__c.field-meta.xml
<CustomField>
    <fullName>Publish_On_Community_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean flag to decide if this blog should be visible or not.</description>
    <inlineHelpText>Boolean flag to decide if this blog should be visible or not.</inlineHelpText>
    <label>Publish On Community Site</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/classes/CustomBlogSideBarCntrl_Test.cls
@isTest
public with sharing class CustomBlogSideBarCntrl_Test {

    @TestSetup
    static void makeData(){
        List<News_List_Page__c> lstNewsListPages = new List<News_List_Page__c>();
        for(Integer i= 1; i< 10; i++ ) {
            lstNewsListPages.add(new News_List_Page__c(
                                        Date__c = Date.today().addMonths(i),
                                        News_Label__c = 'Test Label ' + i,
                                        Blog_Sequesnce__c = i,
                                        Navigation_url__c = 'https://cm-vc-internal.cs74.force.com/InvestorLogin/s/vc-cf-ecofriendlyinvestment',
                                        Archive__c = false,
                                        Publish_On_Community_Site__c = true));
        }
        for(Integer i= 10; i< 20; i++ ) {
            lstNewsListPages.add(new News_List_Page__c(
                                        Date__c = Date.today().addMonths(i),
                                        News_Label__c = 'Test Label ' + i,
                                        Blog_Sequesnce__c = i,
                                        Navigation_url__c = 'https://cm-vc-internal.cs74.force.com/InvestorLogin/s/vc-cf-ecofriendlyinvestment',
                                        Archive__c = true,
                                        Publish_On_Community_Site__c = true));
        }
        insert lstNewsListPages;
    }
    
    @isTest
    static void test_fetchNewsList() {
        Map<String, Object> mapNewsListResult = CustomBlogSideBarCntrl.fetchNewsList();
        System.assertEquals(true, mapNewsListResult.size() > 0);

        Map<String, Object> netBlogResult = CustomBlogSideBarCntrl.fetchBlogDetails(2);
        System.assertEquals(true, netBlogResult.size() > 0);
        
        Date todaysDate =Date.today();
        List<News_List_Page__c> lstMonthlyArchive = CustomBlogSideBarCntrl.fetchMonthlyArchives(todaysDate.month() + '' , todaysDate.year() + '');
    }
}