common/force-app/main/default/objects/News_List_Page__c/News_List_Page__c.object-meta.xml
<CustomObject>
    <label>News List Page</label>
    <nameField>
        <displayFormat>LP-{00000}</displayFormat>
        <label>ListPage Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>News List Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/News_List_Page__c/fields/CategoryBanner_Img_Url__c.field-meta.xml
<CustomField>
    <fullName>CategoryBanner_Img_Url__c</fullName>
    <description>Category Image Banner image URL</description>
    <label>CategoryBanner_Img_Url</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Likes_Number__c.field-meta.xml
<CustomField>
    <fullName>Likes_Number__c</fullName>
    <label>Likes Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Navigation_url__c.field-meta.xml
<CustomField>
    <fullName>Navigation_url__c</fullName>
    <label>Navigation url</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/News_Category__c.field-meta.xml
<CustomField>
    <fullName>News_Category__c</fullName>
    <label>News Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/News_Descriptions__c.field-meta.xml
<CustomField>
    <fullName>News_Descriptions__c</fullName>
    <label>News Descriptions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/News_Label__c.field-meta.xml
<CustomField>
    <fullName>News_Label__c</fullName>
    <label>News Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Newsbg_Url__c.field-meta.xml
<CustomField>
    <fullName>Newsbg_Url__c</fullName>
    <label>Newsbg Url</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/src_url__c.field-meta.xml
<CustomField>
    <fullName>src_url__c</fullName>
    <description>Source URL</description>
    <label>src url</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Tagged_category__c.field-meta.xml
<CustomField>
    <fullName>Tagged_category__c</fullName>
    <description>This is the URL for tagged category on the top corner</description>
    <inlineHelpText>This is the URL for tagged category on the top corner</inlineHelpText>
    <label>Tagged category</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/classes/NewsCategoryController.cls
global without sharing  class NewsCategoryController {
     public List<News_List_Page__c> newsList{get;set;}
     public String currentcategory {get;set;}
   	 public String catgoreyimagurl{get;set;}
    
    public NewsCategoryController(){
        String category=ApexPages.currentPage().getParameters().get('category');
        System.debug('category='+category);
        this.currentcategory=category;
        this.newsList=[SELECT Id, News_Label__c,CategoryBanner_Img_Url__c, Tagged_category__c, Date__c, News_Category__c, News_Descriptions__c, Likes_Number__c, Newsbg_Url__c,  src_url__c, Navigation_url__c FROM News_List_Page__c where News_Category__c=:category ORDER BY Date__c DESC LIMIT 199];
        if(this.newsList.size()>0){
          this.catgoreyimagurl= this.newsList[0].CategoryBanner_Img_Url__c;
        }
    }
}