common/force-app/main/default/objects/News_List_Page__c/News_List_Page__c.object-meta.xml
<CustomObject>
    <label>News List Page</label>
    <nameField>
        <displayFormat>LP-{00000}</displayFormat>
        <label>ListPage Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>News List Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

common/force-app/main/default/objects/News_List_Page__c/fields/Archive__c.field-meta.xml
<CustomField>
    <fullName>Archive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean flag to identify if this blog will display under Archive or not.</description>
    <inlineHelpText>Boolean flag to identify if this blog will display under Archive or not.</inlineHelpText>
    <label>Archive</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Blog_Sequesnce__c.field-meta.xml
<CustomField>
    <fullName>Blog_Sequesnce__c</fullName>
    <description>This field is useful for sorting after date, for example, if more than one blog post on the same day,  this is the second filter that gives clients the ability to show blogs in the order they want. sorting should be in descending. This field also determines next blog post</description>
    <inlineHelpText>Blog  sequence number for sorting in descending</inlineHelpText>
    <label>Blog Sequesnce #</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/CategoryBanner_Img_Url__c.field-meta.xml
<CustomField>
    <fullName>CategoryBanner_Img_Url__c</fullName>
    <description>Category Image Banner image URL</description>
    <label>CategoryBanner_Img_Url</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Navigation_url__c.field-meta.xml
<CustomField>
    <fullName>Navigation_url__c</fullName>
    <label>Navigation url</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/News_Category__c.field-meta.xml
<CustomField>
    <fullName>News_Category__c</fullName>
    <label>News Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/News_Descriptions__c.field-meta.xml
<CustomField>
    <fullName>News_Descriptions__c</fullName>
    <label>News Descriptions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/News_Label__c.field-meta.xml
<CustomField>
    <fullName>News_Label__c</fullName>
    <label>News Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Newsbg_Url__c.field-meta.xml
<CustomField>
    <fullName>Newsbg_Url__c</fullName>
    <label>Newsbg Url</label>
    <type>Url</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Page_Name__c.field-meta.xml
<CustomField>
    <fullName>Page_Name__c</fullName>
    <description>Contains the corresponding community Page Name.</description>
    <inlineHelpText>Contains the corresponding community Page Name.</inlineHelpText>
    <label>Page Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

common/force-app/main/default/objects/News_List_Page__c/fields/Publish_On_Community_Site__c.field-meta.xml
<CustomField>
    <fullName>Publish_On_Community_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean flag to decide if this blog should be visible or not.</description>
    <inlineHelpText>Boolean flag to decide if this blog should be visible or not.</inlineHelpText>
    <label>Publish On Community Site</label>
    <type>Checkbox</type>
</CustomField>

common/force-app/main/default/classes/CustomBlogSideBarCntrl.cls
public without sharing class CustomBlogSideBarCntrl {

    @AuraEnabled(cacheable=true)
    public static List<News_List_Page__c> fetchMonthlyArchives(String strMonth, String strYear){
        List<News_List_Page__c> lstArchivesPages = new List<News_List_Page__c>();
        if(String.isNotBlank(strMonth) && String.isNotBlank(strYear)) {
            Date monthStartDate = Date.newInstance(Integer.valueOf(strYear), Integer.valueOf(strMonth), 1);
            Date monthEndDate = monthStartDate.addMonths(+1);

            Map<String, Object> mapResult = new Map<String, Object>();
            lstArchivesPages = [SELECT Id, Date__c, News_Label__c, Navigation_url__c, News_Category__c, News_Descriptions__c, Newsbg_Url__c
                                                        FROM News_List_Page__c
                                                        WHERE Date__c >= :monthStartDate
                                                        AND Date__c < :monthEndDate
                                                        Order By Date__c ASC];
                                                        // WHERE Archive__c = true AND Publish_On_Community_Site__c = true
        }
        System.debug('===lstArchivesPages===>'+ JSON.serialize(lstArchivesPages));
        return lstArchivesPages;
    }

    @AuraEnabled(cacheable=true)
    public static Map<String, Object> fetchNewsList(){
        Map<String, Object> mapResult = new Map<String, Object>();
        List<News_List_Page__c> lstNewsListPages = [SELECT Id, Date__c, News_Label__c, Navigation_url__c, News_Category__c, News_Descriptions__c
                                                    FROM News_List_Page__c
                                                    WHERE Publish_On_Community_Site__c = true
                                                    Order By Date__c DESC
                                                    LIMIT 6];
        mapResult.put('lstNewsListPages', lstNewsListPages);

        List<News_List_Page__c> lstArchivesPages = [SELECT Id, Date__c, News_Label__c, Navigation_url__c, News_Category__c
                                                    FROM News_List_Page__c
                                                    Order By Date__c DESC];
                                                    // WHERE Archive__c = true AND Publish_On_Community_Site__c = true
        Map<String, String> mapKeyToMonth = new Map<String, String>();
        for(News_List_Page__c nlPage : lstArchivesPages) {
            Date myDate = nlPage.Date__c;
            DateTime myDateTime = datetime.newInstance(myDate.year(), myDate.month(), myDate.day());
            mapKeyToMonth.put(myDateTime.format('MMMM'), myDateTime.format('MMMM YYYY'));
        }
        mapResult.put('mapArchiveMonthly', mapKeyToMonth);
        return mapResult;
    }

    /**
     * Method used in Next Post Blog Component
     */
    @AuraEnabled
    public static Map<String, Object> fetchBlogDetails(Integer currentBlogSeqNum){
        Map<String, Object> mapResult = new Map<String, Object>();
        Map<Integer, News_List_Page__c> mapNewListOage = new Map<Integer, News_List_Page__c>();
        List<News_List_Page__c> lstBlogs = [SELECT Id, date__c , Name,Navigation_url__c, News_Label__c, Blog_Sequesnce__c, 
                                            Publish_On_Community_Site__c, Archive__c, Page_Name__c, CategoryBanner_Img_Url__c,
                                            News_Category__c, News_Descriptions__c
                                            FROM News_List_Page__c
                                            Order BY Blog_Sequesnce__c ASC];
        News_List_Page__c nextBlog = new News_List_Page__c();
        if(lstBlogs.size() == currentBlogSeqNum) {
            nextBlog = lstBlogs[0];
        }
        else {
            nextBlog = lstBlogs[currentBlogSeqNum];
        }
        mapResult.put('nextBlog', nextBlog);
        return mapResult;
    }
}